elastic/ml-cpp

lib/model/unittest/CCountingModelTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc
lib/model/unittest/CModelTestFixtureBase.h

Create a common base for the test fixture class used by a number of model test suites.
Refactor the test fixtures to move the resource monitor and common type definitions to the new base class.
Backports #1499

[7.x][ML] Refactor model lib unit tests (#1499)

---

lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
lib/model/unittest/CCountingModelTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc

With respect to
```
CCountingModelTest.cc
CEventRateModelTest.cc
CEventRatePopulationModelTest.cc
CMetricModelTest.cc
CMetricPopulationModelTest.cc
```
* Use initializer lists to populate containers where possible
* Remove unnecessarily included header files
Related to #1477

[ML] Modernize and tidy model test code where possible

---

lib/model/unittest/CCountingModelTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc
lib/model/unittest/CModelTestFixtureBase.h

Use modern C++ data structures, initialisation to remove the need for
boost::size.
Use uniform braced initialisation of variables consistently.

[ML] Replace boost::size in model unit tests

---

lib/model/unittest/CCountingModelTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc
lib/model/unittest/CModelTestFixtureBase.h

Use modern C++ data structures, initialisation to remove the need for
boost::size.
Use uniform braced initialisation of variables consistently.
Backports #1517

[7.x][ML] Replace boost::size in model unit tests (#1517)

---

include/api/CInferenceModelMetadata.h
lib/api/CInferenceModelMetadata.cc

We have an occasional failure in the total feature importance unit tests like this one. It happens while for some reason the mean value accumulator fails to produce correct results:
{
"feature_name": "c2",
"classes": [
{
"class_name": "foo",
"importance": {
"mean_magnitude": 0,
"min": -3.288343526748277,
"max": 3.288343526748277
}
},
{
"class_name": "bar",
"importance": {
"mean_magnitude": 0,
"min": -3.288343526748277,
"max": 3.288343526748277
}
}
]
}
In an attempt to fix this I changed the mean accumulator from using the eigen vector type to an explicit vector of doubles same as the min/max accumulator.
I keep the instrumentation of the unit tests for now so we have enough info if the tests continue to fail.
Backport of #1519.

[7.x][ML] Fix total feature importance unit tests 

---

include/api/CInferenceModelMetadata.h
include/maths/CTreeShapFeatureImportance.h
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
lib/api/CInferenceModelMetadata.cc
lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
lib/maths/CTreeShapFeatureImportance.cc

With this PR we will be able to store the feature importance baselines explicitly in the `model_metadata`. Being able baseline to retrieve the baselines will significantly simplify UI code related to the feature importance visualization.
**Classification**
```json
"feature_importance_baseline": {
"classes": [
{
"class_name": "foo",
"baseline": 0.123
},
{
"class_name": "bar",
"baseline": -0.123
}
]
}
```
**Regression**
```json
"feature_importance_baseline" : {
"baseline": 0.123
}
```
This is not a user-facing change, hence I mark it as a `non-issue`.

[ML] Store feature importance baselines in model metadata

---

lib/model/unittest/CCountingModelTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc
lib/model/unittest/CModelTestFixtureBase.cc
lib/model/unittest/CModelTestFixtureBase.h
lib/model/unittest/Makefile

Move existing model test helper functions to base class and share functionality where possible.
While this goes some way to reducing code duplication there may still be scope to
* generalise the existing helper functions further to reduce their number
* add further helper functions to encapsulate code duplicated in multiple suites 

[ML] Move model test helper functions to base class

---

lib/model/unittest/CCountingModelTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc
lib/model/unittest/CModelTestFixtureBase.cc
lib/model/unittest/CModelTestFixtureBase.h
lib/model/unittest/Makefile

Move existing model test helper functions to base class and share functionality where possible.
Backports #1523

[7.x][ML] Move model test helper functions to base class (#1523)

---

include/api/CDataFrameAnalysisConfigReader.h
include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
lib/api/CDataFrameAnalysisConfigReader.cc
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc

This PR makes the classification analysis accept `-1` as the value of `num_top_classes` parameter. When `num_top_classes` is set to `-1`, all the predicted classes will be emitted in the `top_classes` array in the results.
Relates https://github.com/elastic/elasticsearch/issues/63306

[ML] Allow unbounded num_top_classes in classification analysis 

---

include/api/CDataFrameAnalysisConfigReader.h
include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
lib/api/CDataFrameAnalysisConfigReader.cc
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc

- [ML] Allow unbounded num_top_classes in classification analysis   (#1526)

[7.x] [ML] Allow unbounded num_top_classes in classification analysis  (#1526)

---

include/api/CDataFrameAnalysisConfigReader.h
include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
lib/api/CDataFrameAnalysisConfigReader.cc
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc

Backports the following commits to 7.10:
- [ML] Allow unbounded num_top_classes in classification analysis   (#1526)

[7.10] [ML] Allow unbounded num_top_classes in classification analysis  (#1526)

---

lib/model/unittest/CCountingModelTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc
lib/model/unittest/CModelTestFixtureBase.h

Move boilerplate code for creating models to a base class method.
This goes some way to reducing duplicated code and standardising how models are created.

[ML] Provide factory setup for creating models

---

lib/model/unittest/CCountingModelTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc
lib/model/unittest/CModelTestFixtureBase.h

Move boilerplate code for creating models to a base class method.
This goes some way to reducing duplicated code and standardizing how models are created in the tests.
Backports #1527

[7.x][ML] Provide factory setup for creating models (#1527)

---

docs/CHANGELOG.asciidoc
include/maths/CBoostedTreeImpl.h
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc

For regression and classification, during hyperparameter optimization we prefer smaller models if the loss functions are otherwise comparable.
To this end, we add 0.01 * "forest number nodes" * E[GP] / "average forest number nodes" as an additional penalty.
Backport of #1516.

[7.x][ML] Prefer smaller models with similar performance 

---

dev-tools/docker/build_check_style_image.sh
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/prefetch_docker_image.sh
dev-tools/docker_build.sh
dev-tools/docker_check_style.sh
dev-tools/docker_test.sh
dev-tools/jenkins_ci.sh

Adds a function to retry pulling Docker images up to 5 times, and
calls it to pre-fetch every Docker image that's used as a "FROM"
image by our "docker build" commands.
"docker build" will pull the "FROM" image if it's not present on
the local machine, but will only try once, so is vulnerable to a
transient problem with the Docker registry failing the whole build.
By retrying "docker pull" several times before running "docker build"
we ensure that the image is present locally when "docker build" runs
and hence "docker build" never needs to pull it.

[ML] Retry pulling of Docker images to work around network issues

---

lib/model/unittest/CCountingModelTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc
lib/model/unittest/CModelTestFixtureBase.cc
lib/model/unittest/CModelTestFixtureBase.h

Provide a common interface to addArrival by extending the existing SMessage structure.
This reduces the amount of code duplicated between multiple addArrival methods at the expense of some added verbosity when specifying default arguments.

[ML] Amalgamate addArrival methods

---

lib/model/unittest/CCountingModelTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc
lib/model/unittest/CModelTestFixtureBase.cc
lib/model/unittest/CModelTestFixtureBase.h

Provide a common interface to addArrival by extending the existing SMessage structure.
Backports #1536

[7.x][ML] Amalgamate addArrival methods in model tests (#1536)

---

dev-tools/docker/build_check_style_image.sh
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/prefetch_docker_image.sh
dev-tools/docker_build.sh
dev-tools/docker_check_style.sh
dev-tools/docker_test.sh
dev-tools/jenkins_ci.sh

Adds a function to retry pulling Docker images up to 5 times, and
calls it to pre-fetch every Docker image that's used as a "FROM"
image by our "docker build" commands.
"docker build" will pull the "FROM" image if it's not present on
the local machine, but will only try once, so is vulnerable to a
transient problem with the Docker registry failing the whole build.
By retrying "docker pull" several times before running "docker build"
we ensure that the image is present locally when "docker build" runs
and hence "docker build" never needs to pull it.
Backport of #1535

[7.x][ML] Retry pulling of Docker images to work around network issues

---

bin/autodetect/CCmdLineParser.cc
bin/autodetect/CCmdLineParser.h
bin/autodetect/Main.cc

Add an argument to autodetect to enable specifying a config file.
Eventually this will be used to read an autodetect job config in JSON
format but in this initial step it is unused. 

[ML] Add argument for config file to autodetect

---

bin/autodetect/CCmdLineParser.cc
bin/autodetect/CCmdLineParser.h
bin/autodetect/Main.cc

Add an argument to autodetect to enable specifying a config file.
Eventually this will be used to read an autodetect job config in JSON
format but in this initial step it is unused.
Backports #1540

[7.x][ML] Add argument for config file to autodetect (#1540)

---

bin/autodetect/CCmdLineParser.cc
bin/controller/CCmdLineParser.cc
bin/controller/CCmdLineParser.h
bin/controller/CCommandProcessor.cc
bin/controller/CCommandProcessor.h
bin/controller/CResponseJsonWriter.cc
bin/controller/CResponseJsonWriter.h
bin/controller/Main.cc
bin/controller/Makefile
bin/controller/unittest/CCommandProcessorTest.cc
bin/controller/unittest/CResponseJsonWriterTest.cc
bin/controller/unittest/Makefile
docs/CHANGELOG.asciidoc

This change makes the controller process respond to each command
it receives with a document indicating whether that command was
successfully executed or not.
This response will be used by the Java side of the connection to
determine when it is appropriate to move on to the next phase of
the action that the controller command was part of.  For example,
when starting a process and connecting named pipes to it it is
best that the named pipe connections are not attempted until the
process is confirmed to be started.
Relates elastic/elasticsearch#62823
Relates elastic/elasticsearch#63542

[ML] Make controller send responses for each command received

---

bin/autodetect/CCmdLineParser.cc
bin/controller/CCmdLineParser.cc
bin/controller/CCmdLineParser.h
bin/controller/CCommandProcessor.cc
bin/controller/CCommandProcessor.h
bin/controller/CResponseJsonWriter.cc
bin/controller/CResponseJsonWriter.h
bin/controller/Main.cc
bin/controller/Makefile
bin/controller/unittest/CCommandProcessorTest.cc
bin/controller/unittest/CResponseJsonWriterTest.cc
bin/controller/unittest/Makefile
docs/CHANGELOG.asciidoc

This change makes the controller process respond to each command
it receives with a document indicating whether that command was
successfully executed or not.
This response will be used by the Java side of the connection to
determine when it is appropriate to move on to the next phase of
the action that the controller command was part of. For example,
when starting a process and connecting named pipes to it it is
best that the named pipe connections are not attempted until the
process is confirmed to be started.
Backport of #1520

[7.x][ML] Make controller send responses for each command received

---

dev-tools/docker/build_check_style_image.sh
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/prefetch_docker_image.sh
dev-tools/docker_build.sh
dev-tools/docker_check_style.sh
dev-tools/docker_test.sh
dev-tools/jenkins_ci.sh

Adds a function to retry pulling Docker images up to 5 times, and
calls it to pre-fetch every Docker image that's used as a "FROM"
image by our "docker build" commands.
"docker build" will pull the "FROM" image if it's not present on
the local machine, but will only try once, so is vulnerable to a
transient problem with the Docker registry failing the whole build.
By retrying "docker pull" several times before running "docker build"
we ensure that the image is present locally when "docker build" runs
and hence "docker build" never needs to pull it.
Backport of #1535

[7.10][ML] Retry pulling of Docker images to work around network issues

---

include/maths/CSignal.h
include/maths/CTimeSeriesSegmentation.h
include/maths/CTimeSeriesTestForSeasonality.h
lib/maths/CSignal.cc
lib/maths/CTimeSeriesChangeDetector.cc
lib/maths/CTimeSeriesDecompositionDetail.cc
lib/maths/CTimeSeriesModel.cc
lib/maths/CTimeSeriesSegmentation.cc
lib/maths/CTimeSeriesTestForSeasonality.cc
lib/maths/unittest/CForecastTest.cc
lib/maths/unittest/CSignalTest.cc
lib/maths/unittest/CTimeSeriesDecompositionTest.cc
lib/maths/unittest/CTimeSeriesModelTest.cc
lib/maths/unittest/CTimeSeriesSegmentationTest.cc
lib/maths/unittest/CTimeSeriesTestForSeasonalityTest.cc
lib/model/unittest/CMetricModelTest.cc

This follows on from #1530 and prepares the ground for using the code to segment time windows of values into piecewise linear trend and piecewise constant scaling for change detection.
Aside from some small improvements to methodology, the main changes were to support scaling an arbitrary seasonal function, which will be the current time series model when using for change point detection, and being able to limit the number of changes we fit. To do this it was useful to rewrite segmentation to use common functionality in `CSignal`.
I'll make the changes to actually use this in a follow up pull request. As before, this will not documented separately so marking as a non-issue.

[ML] Time series segmentation improvements

---

docs/CHANGELOG.asciidoc
lib/api/CAnomalyJob.cc

The model state min_version should indicate the minimum
node version required to restore the model state.  This
has not been updated since 6.4.0, meaning we have not had
the intended protection against model states being used on
nodes that are too old.  This change updates the
min_version to the correct version at present, which is
7.9.0 for latest state.
Relates #1545

[ML] Correcting model state min_version

---

docs/CHANGELOG.asciidoc
lib/api/CAnomalyJob.cc

The model state min_version should indicate the minimum
node version required to restore the model state.  This
has not been updated since 6.4.0, meaning we have not had
the intended protection against model states being used on
nodes that are too old.  This change updates the
min_version to the correct version at present, which is
7.9.0 for latest state.
Backport of #1546

[7.x][ML] Correcting model state min_version

---

docs/CHANGELOG.asciidoc
lib/api/CAnomalyJob.cc

The model state min_version should indicate the minimum
node version required to restore the model state.  This
has not been updated since 6.4.0, meaning we have not had
the intended protection against model states being used on
nodes that are too old.  This change updates the
min_version to the correct version at present, which is
7.9.0 for latest state.
Backport of #1546

[7.10][ML] Correcting model state min_version

---

include/maths/CTimeSeriesSegmentation.h
lib/maths/CTimeSeriesSegmentation.cc
lib/maths/unittest/CTimeSeriesSegmentationTest.cc

This implements segmentation of a window of times series values allowing for piecewise constant time shifts of the seasonality. This is needed to extend change detection to handle a wider range of possible time shifts. I also took the opportunity to finish up testing time series segmentation and make some improvements to documentation and variable naming.
This isn't used yet; I plan to wire it in the next change. This is marked as a non-issue because it will not be documented separately.

[ML] Time series time shift segmentation

---

lib/api/CAnomalyJob.cc

Ensure an error is logged when persistence fails.

[ML] Fix error logging for foreground persistence

---

lib/api/CAnomalyJob.cc

Ensure an error is logged when persistence fails
Backports #1555

[7.x][ML] Fix error logging for foreground persistence (#1555)

---

include/api/CForecastRunner.h
lib/api/CForecastRunner.cc
lib/api/unittest/CForecastRunnerTest.cc

This new parameter will allow the value of the
xpack.ml.min_disk_space_off_heap Elasticsearch setting
to be propagated to the autodetect process.  It will
prevent problems where xpack.ml.min_disk_space_off_heap
has been set to a low value but the previous hardcoded
C++ check still prevented forecasting from working.
Relates #1554

[ML] Adding a minimum disk space forecast parameter

---

include/api/CForecastRunner.h
lib/api/CForecastRunner.cc
lib/api/unittest/CForecastRunnerTest.cc

This new parameter will allow the value of the
xpack.ml.min_disk_space_off_heap Elasticsearch setting
to be propagated to the autodetect process.  It will
prevent problems where xpack.ml.min_disk_space_off_heap
has been set to a low value but the previous hardcoded
C++ check still prevented forecasting from working.
Backport of #1556

[7.x][ML] Adding a minimum disk space forecast parameter

---

bin/autodetect/CCmdLineParser.cc
bin/autodetect/CCmdLineParser.h
bin/autodetect/Main.cc
bin/data_frame_analyzer/Main.cc
include/api/CAnomalyJobConfig.h
include/api/CAnomalyJobConfigReader.h
include/api/CDetectionRulesJsonParser.h
include/core/CStringUtils.h
include/core/CTimeUtils.h
include/core/Constants.h
lib/api/CAnomalyJobConfig.cc
lib/api/CAnomalyJobConfigReader.cc
lib/api/CDetectionRulesJsonParser.cc
lib/api/Makefile.first
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/api/unittest/Makefile
lib/core/CStringUtils.cc
lib/core/CTimeUtils.cc
lib/core/unittest/CStringUtilsTest.cc
lib/core/unittest/CTimeUtilsTest.cc

Add a parser for the recently added anomaly job configuration file, which
is in JSON format.
As an initial step to the configuration file replacing a number of
command line arguments, modify autodetect to use the jobId extracted by
the parser.
Backports #1552

[7.x][ML] Parse anomaly job JSON config file (#1552)

---

include/api/CForecastRunner.h
lib/api/CForecastRunner.cc

The hand-crafted move constructor and move assignment operator
for CForecastRunner::SForecast were unnecessarily copying some
members instead of moving them.  The defaults will do the
correct thing and also avoid the need for future maintenance
when adding extra members.  (The hand-crafted versions were
created when we were using an old compiler that had a bug
related to default move assignment.)

[ML] Fixing move constructor/assignment for CForecastRunner::SForecast

---

dev-tools/docker/build_check_style_image.sh
dev-tools/docker/build_linux-musl_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/build_linux_test_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/prefetch_docker_image.sh
dev-tools/docker_build.sh
dev-tools/docker_check_style.sh
dev-tools/docker_test.sh
dev-tools/jenkins_ci.sh

Adds a function to retry pulling Docker images up to 5 times, and
calls it to pre-fetch every Docker image that's used as a "FROM"
image by our "docker build" commands.
"docker build" will pull the "FROM" image if it's not present on
the local machine, but will only try once, so is vulnerable to a
transient problem with the Docker registry failing the whole build.
By retrying "docker pull" several times before running "docker build"
we ensure that the image is present locally when "docker build" runs
and hence "docker build" never needs to pull it.
Backport of #1535

[6.8][ML] Retry pulling of Docker images to work around network issues

---

bin/autodetect/Main.cc
include/api/CAnomalyJobConfig.h
include/api/CAnomalyJobConfigReader.h
include/api/CDetectionRulesJsonParser.h
lib/api/CAnomalyJobConfig.cc
lib/api/CAnomalyJobConfigReader.cc
lib/api/CDetectionRulesJsonParser.cc
lib/api/unittest/CAnomalyJobConfigTest.cc

Detector rules may possibly refer to rule filters that are defined
separately, outside of the anomaly job configuration. As an interim
solution pass the rule filters parsed from the old-style field config to
the new-style JSON parser.

[ML] Initialize detectors parser with filters map

---

bin/autodetect/Main.cc
include/api/CAnomalyJobConfig.h
include/api/CAnomalyJobConfigReader.h
include/api/CDetectionRulesJsonParser.h
lib/api/CAnomalyJobConfig.cc
lib/api/CAnomalyJobConfigReader.cc
lib/api/CDetectionRulesJsonParser.cc
lib/api/unittest/CAnomalyJobConfigTest.cc

Detector rules may possibly refer to rule filters that are defined
separately, outside of the anomaly job configuration. As an interim
solution pass the rule filters parsed from the old-style field config to
the new-style JSON parser.
Backports #1562

[7.x][ML] Initialize detectors parser with filters map (#1562)

---

include/api/CForecastRunner.h
lib/api/CForecastRunner.cc
lib/api/unittest/CForecastRunnerTest.cc

This new parameter will allow the value of the
xpack.ml.min_disk_space_off_heap Elasticsearch setting
to be propagated to the autodetect process.  It will
prevent problems where xpack.ml.min_disk_space_off_heap
has been set to a low value but the previous hardcoded
C++ check still prevented forecasting from working.
Backport of #1556

[7.10][ML] Adding a minimum disk space forecast parameter

---

include/api/CForecastRunner.h
lib/api/CForecastRunner.cc

The hand-crafted move constructor and move assignment operator
for CForecastRunner::SForecast were unnecessarily copying some
members instead of moving them.  The defaults will do the
correct thing and also avoid the need for future maintenance
when adding extra members.  (The hand-crafted versions were
created when we were using an old compiler that had a bug
related to default move assignment.)
Backport of #1561

[7.x][ML] Fixing move constructor/assignment for CForecastRunner::SForecast

---

include/api/CForecastRunner.h
lib/api/CForecastRunner.cc

The hand-crafted move constructor and move assignment operator
for CForecastRunner::SForecast were unnecessarily copying some
members instead of moving them.  The defaults will do the
correct thing and also avoid the need for future maintenance
when adding extra members.  (The hand-crafted versions were
created when we were using an old compiler that had a bug
related to default move assignment.)
Backport of #1561

[7.10][ML] Fixing move constructor/assignment for CForecastRunner::SForecast

---

include/api/CAnomalyJob.h
include/api/CFieldDataCategorizer.h
include/api/CSingleStreamDataAdder.h
include/api/ElasticsearchStateIndex.h
include/core/CDataAdder.h
include/core/CDataSearcher.h
include/core/CStateCompressor.h
include/core/CStateDecompressor.h
include/test/CMultiFileDataAdder.h
lib/api/CAnomalyJob.cc
lib/api/CDataFrameAnalysisRunner.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/CFieldDataCategorizer.cc
lib/api/CSingleStreamDataAdder.cc
lib/api/ElasticsearchStateIndex.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/api/unittest/CFieldDataCategorizerTest.cc
lib/api/unittest/CMockDataAdder.cc
lib/api/unittest/CMockDataAdder.h
lib/api/unittest/CMockSearcher.cc
lib/api/unittest/CMockSearcher.h
lib/api/unittest/CMultiFileDataAdderTest.cc
lib/core/CDataSearcher.cc
lib/core/CStateCompressor.cc
lib/core/CStateDecompressor.cc
lib/core/unittest/CStateCompressorTest.cc
lib/test/CMultiFileDataAdder.cc
lib/test/CMultiFileSearcher.cc

The ML C++ code contains several references to the .ml-state
index.  These date back to the days when the C++ code decided
which index to store state in.  Now this decision is made in
the Java code, and the index used isn't even .ml-state any
more, so it was highly confusing to have this name embedded
in the C++ code.  This PR also changes a few interfaces to
make clearer that the C++ isn't choosing the index to store
state in.

[ML] Remove references to the .ml-state index from C++ code

---

include/maths/CBoostedTreeLeafNodeStatistics.h
include/maths/CDataFrameAnalysisInstrumentationInterface.h
lib/core/CDataFrame.cc
lib/maths/CBoostedTreeImpl.cc

None of these changes are critical to production use,
but they avoid compiler warnings and fix trace output.

[ML] A few minor fixes and warning removals

---

include/core/CDataFrame.h
include/core/CPackedBitVector.h
include/maths/CLinearAlgebraEigen.h
lib/maths/CBjkstUniqueValues.cc

C++17 deprecates inheriting from `std::iterator` for iterator trait typedefs. Our use of this generates a lot of deprecation warnings from our VS compiler. This change migrates the few instances we have to explicit typedefs.

[ML] Migrate away from inheriting from std::iterator

---

bin/autodetect/Main.cc
docs/CHANGELOG.asciidoc

Ensure that the static counter tracking the peak memory usage for a job
is included in the limited set to be persisted/restored from model state
snapshots.
Relates to elastic/elasticsearch#64154

[ML] Include peak memory usage in model snapshots

---

docs/CHANGELOG.asciidoc
include/api/CDataFrameAnalysisInstrumentation.h
include/maths/CBoostedTreeLeafNodeStatistics.h
include/maths/CDataFrameAnalysisInstrumentationInterface.h
include/test/CRandomNumbers.h
lib/maths/CBoostedTreeImpl.cc
lib/maths/CBoostedTreeLeafNodeStatistics.cc
lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
lib/test/CRandomNumbers.cc
mk/windows.mk

In this PR we start computing an upper bound on the potential gain from splitting a node. If the upper bound of the gain is lower than the currently smallest gain among all candidates, we ignore the node and this way prevent computations that are especially expensive on the large datasets.
Since we avoid computation of the splits that we wouldn't be added to the tree anyway, this PR does not change the qualitative results.
At the moment, we can only compute the upper bound for regression and binary classification. For multiclass classification we proceed as before.
Note: this PR contains additional instrumentation to assess the performance improvement. I will remove this instrumentation in a follow-up PR after tests.
Backport of #1537

[7.x][ML] Gain upper bound estimation for classification and regression 

---

bin/autodetect/Main.cc
docs/CHANGELOG.asciidoc

Ensure that the static counter tracking the peak memory usage for a job
is included in the limited set to be persisted/restored from model state
snapshots.
Relates to elastic/elasticsearch#64154
Backports #1572

[7.x][ML] Include peak memory usage in model snapshots (#1572)

---

bin/autodetect/Main.cc
docs/CHANGELOG.asciidoc

Ensure that the static counter tracking the peak memory usage for a job
is included in the limited set to be persisted/restored from model state
snapshots.
Relates to elastic/elasticsearch#64154
Backports #1572

[7.10][ML] Include peak memory usage in model snapshots (#1572)

---

include/api/CAnomalyJob.h
include/api/CFieldDataCategorizer.h
include/api/CSingleStreamDataAdder.h
include/api/ElasticsearchStateIndex.h
include/core/CDataAdder.h
include/core/CDataSearcher.h
include/core/CStateCompressor.h
include/core/CStateDecompressor.h
include/test/CMultiFileDataAdder.h
lib/api/CAnomalyJob.cc
lib/api/CDataFrameAnalysisRunner.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/CFieldDataCategorizer.cc
lib/api/CSingleStreamDataAdder.cc
lib/api/ElasticsearchStateIndex.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/api/unittest/CFieldDataCategorizerTest.cc
lib/api/unittest/CMockDataAdder.cc
lib/api/unittest/CMockDataAdder.h
lib/api/unittest/CMockSearcher.cc
lib/api/unittest/CMockSearcher.h
lib/api/unittest/CMultiFileDataAdderTest.cc
lib/core/CDataSearcher.cc
lib/core/CStateCompressor.cc
lib/core/CStateDecompressor.cc
lib/core/unittest/CStateCompressorTest.cc
lib/test/CMultiFileDataAdder.cc
lib/test/CMultiFileSearcher.cc

The ML C++ code contains several references to the .ml-state
index.  These date back to the days when the C++ code decided
which index to store state in.  Now this decision is made in
the Java code, and the index used isn't even .ml-state any
more, so it was highly confusing to have this name embedded
in the C++ code.  This PR also changes a few interfaces to
make clearer that the C++ isn't choosing the index to store
state in.
Backport of #1569

[7.x][ML] Remove references to the .ml-state index from C++ code

---

include/maths/CBoostedTreeLeafNodeStatistics.h
include/maths/CDataFrameAnalysisInstrumentationInterface.h
lib/core/CDataFrame.cc
lib/maths/CBoostedTreeImpl.cc

None of these changes are critical to production use,
but they avoid compiler warnings and fix trace output.
Backport of #1571

[7.x][ML] A few minor fixes and warning removals

---

include/core/CPackedBitVector.h

It seems that some versions of libc++ require that an iterator has a non void reference type to be used with `std::vector::assign`. This is an annoying unnecessary extra type requirement, since the code doesn't actually need operator* to return a reference, but never mind. Defining them - as we had implicitly before via `std::iterator` - should be harmless. Follows on from #1570.

[ML] Work around erroneous reference requirement for std::vector::assign

---

lib/api/CAnomalyJobConfig.cc

When building without optimisation RapidJson's templates
cause problems on Windows when used in different libraries.
This change works around the problem by telling the api
library to use the definition from the core library.  (We
don't notice this when optimisation is used because the
problematic classes end up being inlined away.)

[ML] Fixing the debug build

---

lib/api/CAnomalyJobConfig.cc

When building without optimisation RapidJson's templates
cause problems on Windows when used in different libraries.
This change works around the problem by telling the api
library to use the definition from the core library.  (We
don't notice this when optimisation is used because the
problematic classes end up being inlined away.)
Backport of #1579

[7.x][ML] Fixing the debug build

---

include/core/CPackedBitVector.h

[7.11][ML] Work around erroneous reference requirement for std::vector::assign

---

lib/maths/CTimeSeriesTestForChange.cc
lib/maths/CTimeSeriesTestForSeasonality.cc

We aren't guaranteed that H0 always has more degrees of freedom H1 in all cases where we were testing explained variance. This could therefore sometimes trigger log errors. In the cases this happens it is appropriate to treat the p-value of the alternative as 1, i.e. unproven.
Showed up running #1550 through the QA. Marking as a non issue since it fixes an issue in unreleased code.

[ML] Make sure we don't try and test significance when there is insufficient data

---

include/model/CResourceMonitor.h
lib/api/CAnomalyJob.cc
lib/model/CResourceMonitor.cc
lib/model/unittest/CResourceMonitorTest.cc

When a persist control message with arguments is received
by the anomaly detector it doesn't go through the standard
chain of persistence calls, as it unconditionally rewrites
the state (even if no data has been seen) and includes only
the anomaly detector state rather than the categorizer state
too.  Because of this the memory usage was not being
recalculated prior to persisting the state as would normally
happen.  This PR rectifies that omission.
Fixes one of the problems detailed in
https://github.com/elastic/elasticsearch/pull/64665#pullrequestreview-524548875

[ML] Recalculate memory usage before upgrading model state

---

include/model/CResourceMonitor.h
lib/api/CAnomalyJob.cc
lib/model/CResourceMonitor.cc
lib/model/unittest/CResourceMonitorTest.cc

When a persist control message with arguments is received
by the anomaly detector it doesn't go through the standard
chain of persistence calls, as it unconditionally rewrites
the state (even if no data has been seen) and includes only
the anomaly detector state rather than the categorizer state
too.  Because of this the memory usage was not being
recalculated prior to persisting the state as would normally
happen.  This PR rectifies that omission.
Fixes one of the problems detailed in
https://github.com/elastic/elasticsearch/pull/64665#pullrequestreview-524548875
Backport of #1585

[7.x][ML] Recalculate memory usage before upgrading model state

---

docs/CHANGELOG.asciidoc
lib/maths/CNaturalBreaksClassifier.cc
lib/maths/CXMeansOnline1d.cc

We are getting log errors like
```
[CXMeansOnline1d.cc@462] Bad category = (0.0017123, 2.27255e+10, 0): Error in function boost::math::normal_distribution<double>::normal_distribution...
```
from a long running QA job.
Whilst this has proven difficult to reproduce the underlying cause seems to be that numerical errors have resulted in a variance being around `-eps`. Since we take the `sqrt` of this in the offending code it generates a NaN which triggers this and other log errors. The code which does this should be defensive.
The only mechanism I can see causing this is if the weight used for update is somehow negative. This also shouldn't be possible and it is a large task to trace back how this might be occurring. I simply now also trap this case and discard the sample.
This can affect …

[ML] Trap potential cause of log errors from CXMeansOnline1d

---

include/maths/CExpandingWindow.h
include/maths/CSeasonalComponentAdaptiveBucketing.h
include/maths/CSignal.h
include/maths/CTimeSeriesDecompositionDetail.h
include/maths/CTimeSeriesTestForChange.h
include/maths/CTimeSeriesTestForSeasonality.h
include/maths/CTrendComponent.h
lib/maths/CExpandingWindow.cc
lib/maths/CSeasonalComponent.cc
lib/maths/CSeasonalComponentAdaptiveBucketing.cc
lib/maths/CSignal.cc
lib/maths/CTimeSeriesDecompositionDetail.cc
lib/maths/CTimeSeriesTestForChange.cc
lib/maths/CTimeSeriesTestForSeasonality.cc
lib/maths/CTrendComponent.cc
lib/maths/unittest/CExpandingWindowTest.cc
lib/maths/unittest/CTimeSeriesTestForSeasonalityTest.cc

Some more refinements following on from #1451 and #1580 aimed at fixing a specific QA regression.
This does the following:
1. Rolls out the refinement to the bucket predictor (for already modelled components) from change detection to the test for seasonal components. The previous approach introduced spurious errors for very long bucket lengths (which we use when testing for long, i.e. monthly, yearly, etc, seasonal components). These could cause us to detect spurious seasonality at multiples of the modelled components.
2. Precondition before testing for seasonal components by explicitly removing any modelled seasonality which is too short to test given the window bucket length. The intent is similar to 1 and works around any error in the seasonal model.
3. Don't adjust the gradient when …

[ML] Addressing a QA regression due to 1451 and 1580 

---

lib/core/CLogger.cc

When the logging named pipe is not connected because process
startup gets cancelled, the named pipe classes intentionally
do not log errors, as this would be confusing for people
reading the logs.  However, the logger class was still logging
an error message that implied a problem with the file system
rather than cancellation of startup.
This change stops that error message from being logged, using
the same mechanism that is used in the named pipe classes.
Relates elastic/elasticsearch#64578

[ML] Avoid misleading error message

---

lib/core/CLogger.cc

When the logging named pipe is not connected because process
startup gets cancelled, the named pipe classes intentionally
do not log errors, as this would be confusing for people
reading the logs.  However, the logger class was still logging
an error message that implied a problem with the file system
rather than cancellation of startup.
This change stops that error message from being logged, using
the same mechanism that is used in the named pipe classes.
Backport of #1591

[7.x][ML] Avoid misleading error message

---

lib/core/CLogger.cc

When the logging named pipe is not connected because process
startup gets cancelled, the named pipe classes intentionally
do not log errors, as this would be confusing for people
reading the logs.  However, the logger class was still logging
an error message that implied a problem with the file system
rather than cancellation of startup.
This change stops that error message from being logged, using
the same mechanism that is used in the named pipe classes.
Backport of #1591

[7.10][ML] Avoid misleading error message

---

include/maths/CTimeSeriesTestForSeasonality.h
lib/maths/CTimeSeriesTestForSeasonality.cc

We were running into an issue where [this](https://github.com/elastic/ml-cpp/compare/long-bucket-modelling-improvements...tveasey:untestable-edge-case?expand=1#diff-7b9b36a6bec1003216b0e96287772112bc8515fd2968580f7ceb55a4dfc357c2L986) check means that we can't compute test statistics for one of the components of the seasonality we're already modelling. In this case we choose not to change seasonality.

[ML] Handle edge case where missing values mean we can't test the existing seasonality

---

lib/maths/CExpandingWindow.cc
lib/maths/CTimeSeriesDecompositionDetail.cc

Reworks the calculation of bucket average sample times to avoid potential integer overflow.

[ML] Avoid potential integer overflow

---

bin/autodetect/Main.cc
include/api/CAnomalyJobConfig.h
include/model/CLimits.h
lib/api/CAnomalyJobConfig.cc
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/model/CLimits.cc
lib/model/unittest/CLimitsTest.cc

Initialise the max categorisation examples and model memory limit
settings in `CLimits` with values extracted from the JSON anomaly job
config file.

[ML] Initialise CLimits from JSON config

---

bin/autodetect/Main.cc
include/api/CAnomalyJobConfig.h
include/model/CLimits.h
lib/api/CAnomalyJobConfig.cc
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/model/CLimits.cc
lib/model/unittest/CLimitsTest.cc

Initialise the max categorisation examples and model memory limit
settings in CLimits with values extracted from the JSON anomaly job
config file.
Backports #1597 
Relates #1253

[7.x][ML] Initialise CLimits from JSON config (#1597)

---

lib/maths/CTimeSeriesDecompositionDetail.cc
lib/maths/unittest/CForecastTest.cc
lib/maths/unittest/CTimeSeriesDecompositionTest.cc
lib/maths/unittest/CTimeSeriesModelTest.cc
lib/model/unittest/CEventRateModelTest.cc

QA regressions associated #1451 and #1580 have shown we've increased false positives after changing the seasonal components included in the decomposition. This change injects a small amount of noise into the window values we test for seasonal components. This has two advantages:
1. If the signal if very stable we don't want to model seasonality if it's relative amplitude is too small
2. It avoids underestimating the variance when reinitialising the residual model which is the cause of the false positives

[ML] Address spurious anomalies after reinitialising time series decomposition

---

bin/autodetect/CCmdLineParser.cc
bin/autodetect/CCmdLineParser.h
bin/autodetect/Main.cc
include/api/CAnomalyJob.h
include/api/CAnomalyJobConfig.h
include/api/CConfigUpdater.h
lib/api/CAnomalyJob.cc
lib/api/CAnomalyJobConfig.cc
lib/api/CConfigUpdater.cc
lib/api/dump_state/Main.cc
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/api/unittest/CAnomalyJobLimitTest.cc
lib/api/unittest/CAnomalyJobTest.cc
lib/api/unittest/CConfigUpdaterTest.cc
lib/api/unittest/CForecastRunnerTest.cc
lib/api/unittest/CMultiFileDataAdderTest.cc
lib/api/unittest/CPersistenceManagerTest.cc
lib/api/unittest/CRestorePreviousStateTest.cc
lib/api/unittest/CSingleStreamDataAdderTest.cc
lib/api/unittest/CStringStoreTest.cc
lib/api/unittest/CTestAnomalyJob.cc
lib/api/unittest/CTestAnomalyJob.h

Initialise CAnomalyDetectorModelConfig with values from
the JSON config file parsed by CAnomalyJobConfig.

[ML] Init AD model config from JSON config

---

bin/autodetect/CCmdLineParser.cc
bin/autodetect/CCmdLineParser.h
bin/autodetect/Main.cc
include/api/CAnomalyJob.h
include/api/CAnomalyJobConfig.h
include/api/CConfigUpdater.h
lib/api/CAnomalyJob.cc
lib/api/CAnomalyJobConfig.cc
lib/api/CConfigUpdater.cc
lib/api/dump_state/Main.cc
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/api/unittest/CAnomalyJobLimitTest.cc
lib/api/unittest/CAnomalyJobTest.cc
lib/api/unittest/CConfigUpdaterTest.cc
lib/api/unittest/CForecastRunnerTest.cc
lib/api/unittest/CMultiFileDataAdderTest.cc
lib/api/unittest/CPersistenceManagerTest.cc
lib/api/unittest/CRestorePreviousStateTest.cc
lib/api/unittest/CSingleStreamDataAdderTest.cc
lib/api/unittest/CStringStoreTest.cc
lib/api/unittest/CTestAnomalyJob.cc
lib/api/unittest/CTestAnomalyJob.h

Initialise CAnomalyDetectorModelConfig with values from
the JSON config file parsed by CAnomalyJobConfig.
Backports #1602

[7.x][ML] Init AD model config from JSON config (#1602)

---

lib/maths/CTimeSeriesDecompositionDetail.cc
lib/maths/CTimeSeriesTestForSeasonality.cc

There was a bug in `fitAndRemoveUntestableModelledComponents` which should check the component length against the minimum component length in *window buckets* not time units. For very long bucket lengths we also need more values in the sliding window to test for changes. This is unreleased code so a non-issue.

[ML] Addressing a QA regression due to 1451 and 1580

---

bin/autodetect/Main.cc
include/api/CAnomalyJobConfig.h
lib/api/CAnomalyJobConfig.cc
lib/api/CConfigUpdater.cc
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/api/unittest/CConfigUpdaterTest.cc

* Scheduled events configuration exists outside of the job config.
As an interim step pass the scheduled events parsed from
the old-style field config to the new-style JSON parser.
* Ensure that updates to scheduled event rules are correctly handled.
* Tidy the code to create the anomaly detector model config.

[ML] Init AD job config with scheduled events

---

include/maths/CSignal.h
include/maths/CTimeSeriesSegmentation.h
include/maths/CTimeSeriesTestForSeasonality.h
lib/maths/CSignal.cc
lib/maths/CTimeSeriesDecompositionDetail.cc
lib/maths/CTimeSeriesSegmentation.cc
lib/maths/CTimeSeriesTestForSeasonality.cc
lib/maths/unittest/CSignalTest.cc
lib/maths/unittest/CTimeSeriesSegmentationTest.cc

We're running into issues where we estimate the residual distribution after removing seasonality using a larger more accurate model than we eventually choose. This means we can underestimate its variance and generate false transient positives. This change migrates to matching the model predictions to the model size we select so that our residual distribution is correctly initialised. The code isn't released so this is a non-issue.

[ML] Avoid overfit when reinitialising the residual model with new seasonal components

---

include/maths/CTimeSeriesDecompositionDetail.h
include/maths/CTimeSeriesTestForSeasonality.h
lib/maths/CAdaptiveBucketing.cc
lib/maths/CExpandingWindow.cc
lib/maths/CSignal.cc
lib/maths/CTimeSeriesDecompositionDetail.cc
lib/maths/CTimeSeriesSegmentation.cc
lib/maths/CTimeSeriesTestForSeasonality.cc

This primarily fixes two potential edge cases leading to invalid writes:
1. We weren't checking that the time supplied to `shiftTime` for the expanding window was after the start of the window. This led to unsigned integer underflow and bad arguments supplied to `std::fill`. This could very occasionally happen.
2. We were applying the wrongly indexing the seasonal hypothesis vector if some of them weren't testable. This could lead to an invalid write.
As part of tracking down these memory corruptions, I also audited potentially dangerous places in the code. These were safe, but relied on rather delicate invariants or inputs being correct. I've tightened up the logic to ensure that these assumptions are now checked.
This is unreleased code so marking as a non-issue.

[ML] Fix invalid writes and increase robustness

---

include/api/CForecastRunner.h
include/maths/CModel.h
lib/api/CForecastRunner.cc
lib/maths/CModel.cc
lib/maths/unittest/CForecastTest.cc

Due to a mistake in #1559 the forecast bounds were
reduced from 95% to 0.95%.
This change reinstates the correct bounds, and also
moves the definition of the constant to the maths
library, where it can be used in a unit test that
will fail if it is ever inadvertently changed again.
Fixes #1606

[ML] Fix incorrect forecast bounds

---

include/api/CForecastRunner.h
include/maths/CModel.h
lib/api/CForecastRunner.cc
lib/maths/CModel.cc
lib/maths/unittest/CForecastTest.cc

Due to a mistake in #1559 the forecast bounds were
reduced from 95% to 0.95%.
This change reinstates the correct bounds, and also
moves the definition of the constant to the maths
library, where it can be used in a unit test that
will fail if it is ever inadvertently changed again.
Backport of #1610

[7.x][ML] Fix incorrect forecast bounds

---

docs/CHANGELOG.asciidoc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc

Since downsampling affects the scaling of some hyperparameter, sometimes the scaled hyperparamters were outside of the defined bounding boxes. This fix restores the boundary constraint. It allows us to better describe the error surface.

[ML] Fix hyperparameter scaling

---

include/api/CDataFrameAnalysisInstrumentation.h
include/maths/CBoostedTreeLeafNodeStatistics.h
include/maths/CDataFrameAnalysisInstrumentationInterface.h
lib/maths/CBoostedTreeImpl.cc
lib/maths/CBoostedTreeLeafNodeStatistics.cc

Since we finished benchmarking  #1313, the instrumentation of computed and avoided statistics has become unnecessary. Since this instrumentation is not "for free" I am removing the code from the codebase.

[ML] Remove computed statistics instrumentation

---

docs/CHANGELOG.asciidoc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc

Since downsampling affects the scaling of some hyperparameter, sometimes the scaled hyperparamters were outside of the defined bounding boxes. This fix restores the boundary constraint. It allows us to better describe the error surface.
Backport of #1612

[7.x][ML] Fix hyperparameter scaling

---

include/api/CDataFrameAnalysisInstrumentation.h
include/maths/CBoostedTreeLeafNodeStatistics.h
include/maths/CDataFrameAnalysisInstrumentationInterface.h
lib/maths/CBoostedTreeImpl.cc
lib/maths/CBoostedTreeLeafNodeStatistics.cc

Since we finished benchmarking #1313, the instrumentation of computed and avoided statistics has become unnecessary. Since this instrumentation is not "for free" I am removing the code from the codebase.
Backport of #1617

[7.x][ML] Remove computed statistics instrumentation 

---

docs/CHANGELOG.asciidoc
include/core/CLogger.h
include/core/CLoggerThrottler.h
include/core/LogMacros.h
lib/core/CLogger.cc
lib/core/CLoggerThrottler.cc
lib/core/Makefile
lib/core/unittest/CLoggerTest.cc
lib/core/unittest/CLoggerThrottlerTest.cc
lib/core/unittest/Makefile

We have some C++ log message deduplication on the Java side, but it relies on the log messages repeating. If several different lines interleave their logging then all lines are logged. We've had situations where we get a lot of logging generated at ERROR level which can significantly slow down anomaly detection. They also spam the global Elasticsearch logs.
This proposes a simple mechanism to throttle logging at WARN and ERROR level on C++ side per process. In particular, it
1. Always outputs the first WARN or ERROR for a particular log line
2. Thereafter limits to outputting a duplicate line once per hour (wall clock)
This should be enough to allow us to check for presence of errors (useful for QA). Also, nearly always, only the first instance of an error is useful.
Since I only …

[ML] Warn and error level log throttling

---

include/core/Constants.h
include/test/CDataFrameAnalyzerTrainingFactory.h
lib/api/CAnomalyJobConfig.cc
lib/api/CDataFrameAnalysisInstrumentation.cc
lib/api/CDataFrameAnalysisRunner.cc
lib/api/CInferenceModelDefinition.cc
lib/api/CSingleStreamDataAdder.cc
lib/api/unittest/CAnomalyJobLimitTest.cc
lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
lib/core/CDataFrame.cc
lib/core/CStringUtils.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/model/CResourceMonitor.cc
lib/model/unittest/CResourceMonitorTest.cc

We have global constants for memory in KB, MB, etc, but we were not reliably using them. This is a small tidy up to migrate to using them consistently. Since this is a refactor I don't think it needs documentation and I'm marking as a non-issue.

[ML] Switch to using global memory constants

---

bin/autodetect/Main.cc
include/api/CAnomalyJob.h
include/api/CAnomalyJobConfig.h
lib/api/CAnomalyJob.cc
lib/api/CAnomalyJobConfig.cc
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/api/unittest/CAnomalyJobLimitTest.cc
lib/api/unittest/CAnomalyJobTest.cc
lib/api/unittest/CForecastRunnerTest.cc
lib/api/unittest/CStringStoreTest.cc
lib/api/unittest/CTestAnomalyJob.cc
lib/api/unittest/CTestAnomalyJob.h

Replicate CFieldConfig code that parses clauses and
determines function types in CAnomalyJobConfig.

[ML] Parse field clauses using CAnomalyJobConfig

---

bin/autodetect/Main.cc
bin/categorize/Main.cc
docs/CHANGELOG.asciidoc
include/core/CProgramCounters.h
include/model/CResourceMonitor.h
include/model/ModelTypes.h
lib/api/CAnomalyJob.cc
lib/api/CCmdSkeleton.cc
lib/api/CModelSizeStatsJsonWriter.cc
lib/api/unittest/CJsonOutputWriterTest.cc
lib/api/unittest/CModelSnapshotJsonWriterTest.cc
lib/core/CProgramCounters.cc
lib/model/CResourceMonitor.cc
lib/model/ModelTypes.cc
lib/model/unittest/CResourceMonitorTest.cc

This change is the companion to elastic/elasticsearch#65561.
It calculates the new model_size_stats field,
assignment_memory_basis, to indicate whether an actual model
size or the model memory limit should be used when assigning
jobs to nodes.  The switch only goes one way: once we have
switched from model memory limit to an actual model size we
never revert to using the limit.  This is a change compared
to 7.10, because with autoscaling flipping backwards and
forwards between model memory limit and actual model memory
could (in bad edge cases) cause the cluster to repeatedly
scale up and down.
Relates elastic/elasticsearch#65561
Closes elastic/elasticsearch#63163

[ML] Include assignment_memory_basis in model_size_stats

---

bin/autodetect/Main.cc
bin/categorize/Main.cc
docs/CHANGELOG.asciidoc
include/core/CProgramCounters.h
include/model/CResourceMonitor.h
include/model/ModelTypes.h
lib/api/CAnomalyJob.cc
lib/api/CCmdSkeleton.cc
lib/api/CModelSizeStatsJsonWriter.cc
lib/api/unittest/CJsonOutputWriterTest.cc
lib/api/unittest/CModelSnapshotJsonWriterTest.cc
lib/core/CProgramCounters.cc
lib/model/CResourceMonitor.cc
lib/model/ModelTypes.cc
lib/model/unittest/CResourceMonitorTest.cc

This change is the companion to elastic/elasticsearch#65561.
It calculates the new model_size_stats field,
assignment_memory_basis, to indicate whether an actual model
size or the model memory limit should be used when assigning
jobs to nodes.  The switch only goes one way: once we have
switched from model memory limit to an actual model size we
never revert to using the limit.  This is a change compared
to 7.10, because with autoscaling flipping backwards and
forwards between model memory limit and actual model memory
could (in bad edge cases) cause the cluster to repeatedly
scale up and down.
Backport of #1623

[7.x][ML] Include assignment_memory_basis in model_size_stats

---

lib/model/CResourceMonitor.cc
lib/model/unittest/CResourceMonitorTest.cc

The previous formula was vulnerable to dividing by zero
in unlikely edge cases.  This change rearranges the formula
to avoid that, and also adds a test to prove no crashes
occur in edge cases.
Relates #1623

[ML] Make coefficient of variation formula more robust

---

include/maths/CTimeSeriesTestForSeasonality.h
lib/maths/CTimeSeriesTestForSeasonality.cc
lib/maths/unittest/CTimeSeriesDecompositionTest.cc

Our regression test suite showed up some places where we are now over eager to drop all seasonal components. This turns out to be because we weren't properly considering whether the time window we test is suitable for making this decision. This rolls out the checks we were already performing per component to decide if we can drop seasonality modelling altogether. I've also included some consideration of the fraction of values in the window we've observed: we require more evidence to drop seasonality modelling if we're observing a fraction of the window.
This affects results, but it only impacts the decision to keep modelling specific seasonal components so the impact is small. Since this improves unreleased code I've marked it as a non-issue.

[ML] Improve test to decide whether to drop seasonal components

---

lib/model/CResourceMonitor.cc
lib/model/unittest/CResourceMonitorTest.cc

The previous formula was vulnerable to dividing by zero
in unlikely edge cases.  This change rearranges the formula
to avoid that, and also adds a test to prove no crashes
occur in edge cases.
Backport of #1631

[7.x][ML] Make coefficient of variation formula more robust

---

bin/autodetect/Main.cc
include/api/CAnomalyJob.h
include/api/CAnomalyJobConfig.h
lib/api/CAnomalyJob.cc
lib/api/CAnomalyJobConfig.cc
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/api/unittest/CAnomalyJobLimitTest.cc
lib/api/unittest/CAnomalyJobTest.cc
lib/api/unittest/CForecastRunnerTest.cc
lib/api/unittest/CStringStoreTest.cc
lib/api/unittest/CTestAnomalyJob.cc
lib/api/unittest/CTestAnomalyJob.h

Replicate CFieldConfig code that parses clauses and
determines function types in CAnomalyJobConfig.
Backports #1619

[7.x][ML] Parse field clauses using CAnomalyJobConfig (#1619)

---

docs/CHANGELOG.asciidoc
lib/maths/CSignal.cc

Investigating changes associated with #1614 in our QA suite turned up an existing deficiency related to us requiring a minimum number of repeats to estimate the period of non-diurnal seasonal components accurately. In particular, we could accept a period which is slightly less than the true period of the seasonality present in the data because it explained the time series well enough. From an anomaly detection standpoint this is a bad idea and it is better to wait until we've seen more data and can estimate the correct periodicity. We'd eventually recover, but it could create transient false positives. For example,
before
after
This change adds a "look ahead" which checks for significantly stronger autocorrelation among slightly longer periods than those for which we can currently …

[ML] Fix edge case in start up behaviour for non-diurnal seasonality

---

include/maths/CTimeSeriesTestForChange.h
lib/maths/CTimeSeriesDecompositionDetail.cc
lib/maths/CTimeSeriesTestForChange.cc
lib/maths/unittest/CTimeSeriesModelTest.cc

Scaling has little impact on values close to zero. This means if the window we test for change points overlap a region where the time series is small we cannot estimate scale points well. In such cases it is appropriate to wait to observe more data before committing the change. For example, this can easily happen with say an unusual Friday if the data display typical elevated values during trading days:
before
after
This checks the *predicted* values before and after a candidate scale change point and waits longer to accept the change if the values after are relatively closer to zero.
Since this only affects the decision to apply a scale change point and then only sometimes delays making the choice the scope should be limited. This affects unreleased code and I plan to port this …

[ML] Avoid applying scale change points when the scale can't be accurately estimated

---

bin/autodetect/CCmdLineParser.cc
bin/autodetect/CCmdLineParser.h
bin/autodetect/Main.cc
include/api/CAnomalyJobConfig.h
include/core/CPatternSet.h
lib/api/CAnomalyJobConfig.cc
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/core/CPatternSet.cc

Parse JSON config files supplied on the autodetect command line to
extract rule filters and scheduled events configuration.
The new functionality is currently disabled in autodetect until the Java
code to supply the new JSON configuration files has been committed.
It is imperative that these C++ changes be committed ahead of the
corresponding Java changes as the new command line options must be
recognised.
Relates to elastic/elasticsearch#66736

[ML] Parse rule filters and scheduled events from JSON config files

---

bin/autodetect/CCmdLineParser.cc
bin/autodetect/CCmdLineParser.h
bin/autodetect/Main.cc
include/api/CAnomalyJobConfig.h
include/core/CPatternSet.h
lib/api/CAnomalyJobConfig.cc
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/core/CPatternSet.cc

Parse JSON config files supplied on the autodetect command line to
extract rule filters and scheduled events configuration.
The new functionality is currently disabled in autodetect until the Java
code to supply the new JSON configuration files has been committed.
It is imperative that these C++ changes be committed ahead of the
corresponding Java changes as the new command line options must be
recognised.
Relates #1253 
Backports #1640

[7.x][ML] Parse filters and events from JSON config files (#1640)

---

include/api/CBoostedTreeInferenceModelBuilder.h
include/api/CDataFrameAnalysisInstrumentation.h
include/api/CInferenceModelDefinition.h
include/api/CInferenceModelMetadata.h
lib/api/CInferenceModelDefinition.cc
lib/model/unittest/CEventRatePopulationModelTest.cc

The memory instrumentation in core::CMemory exists for
boost::unordered_set and boost::unordered_map, but not
the std equivalents.  It is better that we switch all
uses in the codebase at the same time (or even switch
to completely different hash container implementations).
This change switches the few cases of std::unordered_map
and std::unordered_set to the boost versions.  This may
cause some increases in reported memory usage, where these
containers are in memory instrumented classes.  It won't
increase actual memory usage (at least not significantly),
just make the reporting more accurate.

[ML] Always use Boost unordered maps/sets

---

docs/CHANGELOG.asciidoc
include/api/CDataFrameTrainBoostedTreeRunner.h
include/api/CInferenceModelMetadata.h
include/maths/CBayesianOptimisation.h
include/maths/CBoostedTree.h
include/maths/CBoostedTreeImpl.h
include/maths/CBoostedTreeUtils.h
include/maths/CSampling.h
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/CInferenceModelMetadata.cc
lib/api/unittest/CInferenceModelMetadataTest.cc
lib/api/unittest/Makefile
lib/api/unittest/testfiles/model_meta_data/model_meta_data.schema.json
lib/maths/CBayesianOptimisation.cc
lib/maths/CBoostedTree.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/CSampling.cc
lib/maths/unittest/CBayesianOptimisationTest.cc
lib/maths/unittest/CSamplingTest.cc

This PR implements hyperparameter importance calculation using ANOVA decomposition of the Gaussian process model used in the Bayesian optimization routine. The results is recorded in the model metadata structure. For convenience, I record the anova variance as an absolute value as well as a fraction of the total variation. This "relative importance" simplifies the comparison between different parameters.
Additionally, I record the best value for the individual hyperparameter s.t. it can be used in a follow-up job configuration and doesn't have to be looked up separately.
Example output:
```json
"hyperparameter_importance": [
{
"name": "downsample_factor",
"value": 0.35355339059327386,
"absolute_importance": 0.123,
"relative_importance": 0.9123
},
{
"name": "alpha",
"value": …
```

[7.x][ML] Hyperparameter importance

---

lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc

This PR completes the assignment of hyperparameters using enumeration, which was started in  #1627. Using enums instead of fixed order allows preventing bugs if new hyperparameters will be added.

[ML] Fix scale initialization

---

include/api/CBoostedTreeInferenceModelBuilder.h
include/api/CDataFrameAnalysisInstrumentation.h
include/api/CInferenceModelDefinition.h
include/api/CInferenceModelMetadata.h
lib/api/CInferenceModelDefinition.cc
lib/model/unittest/CEventRatePopulationModelTest.cc

The memory instrumentation in core::CMemory exists for
boost::unordered_set and boost::unordered_map, but not
the std equivalents.  It is better that we switch all
uses in the codebase at the same time (or even switch
to completely different hash container implementations).
This change switches the few cases of std::unordered_map
and std::unordered_set to the boost versions.  This may
cause some increases in reported memory usage, where these
containers are in memory instrumented classes.  It won't
increase actual memory usage (at least not significantly),
just make the reporting more accurate.
Backport of #1647

[7.x][ML] Always use Boost unordered maps/sets

---

lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc

This PR completes the assignment of hyperparameters using enumeration, which was started in #1627. Using enums instead of fixed order allows preventing bugs if new hyperparameters will be added.
Backport of  #1650

[7.x] [ML] Fix scale initialization

---

3rd_party/3rd_party.sh
build-setup/macos.md
build.gradle
include/api/CInferenceModelMetadata.h
lib/core/CUname.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/maths/unittest/CLinearAlgebraTest.cc
mk/macosx.mk
set_env.sh

This allows native compilation on a Mac containing the
Apple M1 CPU.
PR builds will currently NOT test this platform, nor even
check compilation for it.  Release manager will not build
it either.  Still, it is a step in the right direction to
be able to compile locally for it.
Cross compilation for this platform is still NOT possible.
This can be investigated in a followup PR.  (Supporting
this actually requires considerable changes to the cross
compilation framework, as it currently contains a quite
deeply embedded assumption that macOS is x86_64 only.)
The last dregs of Linux MUSL port code are also removed.
(Most support for MUSL was removed previously, but a few
bits were missed.)

[ML] Changes to allow native compilation on ARM Macs

---

include/core/CProgramCounters.h
include/test/CProgramCounterClearingFixture.h
lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
lib/api/unittest/CInferenceModelMetadataTest.cc
lib/api/unittest/CRestorePreviousStateTest.cc
lib/core/unittest/CProgramCountersTest.cc
lib/test/CProgramCounterClearingFixture.cc
lib/test/Makefile

Program counters are implemented as a singleton object,
which means their values spill between unit tests unless
action is taken to prevent this.  Often it doesn't matter,
as most unit tests do not care about program counter
values.
Two unit test suites already reset program counters in
between tests: CProgramCountersTest and
CRestorePreviousStateTest.
It turns out that a third test suite should have been
resetting counters but wasn't:
CDataFrameAnalysisInstrumentationTest.
This PR rectifies that omission and also factors out the
code used to reset counters into the test library which
makes it easier to reuse if other suites also need the
functionality in the future.

[ML] Improve program counter resets between unit tests

---

lib/api/CInferenceModelMetadata.cc

When I was writing model metadata hyperparameters in #1627 , I was outputting `eta` values and was using `downsample_factor` label. This RP fixes this.

[ML] Fix wrong model metadata label

---

include/core/CProgramCounters.h
include/test/CProgramCounterClearingFixture.h
lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
lib/api/unittest/CInferenceModelMetadataTest.cc
lib/api/unittest/CRestorePreviousStateTest.cc
lib/core/unittest/CProgramCountersTest.cc
lib/test/CProgramCounterClearingFixture.cc
lib/test/Makefile

Program counters are implemented as a singleton object,
which means their values spill between unit tests unless
action is taken to prevent this.  Often it doesn't matter,
as most unit tests do not care about program counter
values.
Two unit test suites already reset program counters in
between tests: CProgramCountersTest and
CRestorePreviousStateTest.
It turns out that a third test suite should have been
resetting counters but wasn't:
CDataFrameAnalysisInstrumentationTest.
This PR rectifies that omission and also factors out the
code used to reset counters into the test library which
makes it easier to reuse if other suites also need the
functionality in the future.
Backport of #1656

[7.x][ML] Improve program counter resets between unit tests

---

include/core/CProgramCounters.h
include/test/CProgramCounterClearingFixture.h
lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
lib/api/unittest/CRestorePreviousStateTest.cc
lib/core/unittest/CProgramCountersTest.cc
lib/test/CProgramCounterClearingFixture.cc
lib/test/Makefile

Program counters are implemented as a singleton object,
which means their values spill between unit tests unless
action is taken to prevent this.  Often it doesn't matter,
as most unit tests do not care about program counter
values.
Two unit test suites already reset program counters in
between tests: CProgramCountersTest and
CRestorePreviousStateTest.
It turns out that a third test suite should have been
resetting counters but wasn't:
CDataFrameAnalysisInstrumentationTest.
This PR rectifies that omission and also factors out the
code used to reset counters into the test library which
makes it easier to reuse if other suites also need the
functionality in the future.
Backport of #1656

[7.11][ML] Improve program counter resets between unit tests

---

lib/api/CInferenceModelMetadata.cc

When I was writing model metadata hyperparameters in #1627 , I was outputting eta values and was using downsample_factor label. This RP fixes this.
Backport of  #1655.

[7.x][ML] Fix wrong model metadata label

---

docs/CHANGELOG.asciidoc
lib/maths/CSeasonalComponent.cc
lib/maths/CSeasonalComponentAdaptiveBucketing.cc
lib/maths/CTimeSeriesDecompositionDetail.cc
lib/maths/unittest/CSeasonalComponentTest.cc
lib/maths/unittest/CTimeSeriesDecompositionTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CMetricModelTest.cc

#1646 created some QA regressions. It also doesn't fully fix the underlying issues with time windowed components. I'm going to prepare a new PR which targets just this issue and introduces better unit testing and revert this in the mean time.

[ML] Revert "Improve time series model stability"

---

3rd_party/3rd_party.sh
build-setup/macos.md
build.gradle
include/api/CInferenceModelMetadata.h
lib/core/CUname.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/maths/unittest/CLinearAlgebraTest.cc
mk/macosx.mk
set_env.sh

This allows native compilation on a Mac containing the
Apple M1 CPU.
PR builds will currently NOT test this platform, nor even
check compilation for it.  Release manager will not build
it either.  Still, it is a step in the right direction to
be able to compile locally for it.
Cross compilation for this platform is still NOT possible.
This can be investigated in a followup PR.  (Supporting
this actually requires considerable changes to the cross
compilation framework, as it currently contains a quite
deeply embedded assumption that macOS is x86_64 only.)
The last dregs of Linux MUSL port code are also removed.
(Most support for MUSL was removed previously, but a few
bits were missed.)
Backport of #1651

[7.x][ML] Changes to allow native compilation on ARM Macs

---

lib/api/CAnomalyJobConfig.cc

Be more lenient when parsing the background_persist_interval field as it is: 
1. optional and 
2. not present in the job config in the majority of cases

[ML] Leniency parsing background_persist_interval

---

bin/autodetect/CCmdLineParser.cc
bin/autodetect/CCmdLineParser.h
bin/autodetect/Main.cc
include/api/CAnomalyJobConfig.h
lib/api/unittest/CAnomalyJobConfigTest.cc

Remove the now redundant `autodetect` command line options and
exit with error message on seeing unknown command line arguments

[ML] Remove redundant autodetect options

---

lib/api/CAnomalyJobConfig.cc

Be more lenient when parsing the background_persist_interval field as it
is a) optional and b) not present in the job config in the majority of
cases
relates #1253, #1648

[ML] Leniency parsing background_persist_interval (#1662)

---

bin/autodetect/CCmdLineParser.cc
bin/autodetect/CCmdLineParser.h
bin/autodetect/Main.cc
include/api/CAnomalyJobConfig.h
lib/api/unittest/CAnomalyJobConfigTest.cc

Remove the now redundant autodetect command line options and
exit with error message on seeing unknown command line arguments
Relates #1253
Backports #1663

[7.x][ML] Remove redundant autodetect options (#1663)

---

docs/CHANGELOG.asciidoc
include/maths/CDecayRateController.h
include/maths/CPRNG.h
include/maths/CTimeSeriesModel.h
lib/maths/CDecayRateController.cc
lib/maths/CPRNG.cc
lib/maths/CTimeSeriesModel.cc
lib/maths/unittest/CDecayRateControllerTest.cc

We were failing to persist and restore the checks we perform when controlling decay rate for time series models. The upshot is that we would disable decay rate control after a round of persist and restore. This could happen on failover or if the job is closed and restarted.
The checksum for the class was also incomplete which should have picked this up in the unit testing. I have however also added a test that the behaviour is preserved after persist and restore.

[ML] Fix bug persisting and restoring time series model decay rate controller

---

docs/CHANGELOG.asciidoc
include/maths/CDecayRateController.h
include/maths/CPRNG.h
lib/maths/CDecayRateController.cc
lib/maths/CPRNG.cc
lib/maths/CTimeSeriesModel.cc
lib/maths/unittest/CDecayRateControllerTest.cc

[7.12][ML] Fix bug persisting and restoring time series model decay rate controller

---

lib/maths/CTimeSeriesModel.cc

Unfortunately, using the state tag to determine if the state is incomplete is not forward compatible. This breaks upgrading state from the 6.8 branch to 7.x branches. I could introduce a new item (which would be ignored) to carry this information, but since this parameter is currently not user configurable I can simply check its value to determine if it is missing. This fixes fallout from #1674 so marking as a non-issue since it logically belongs with that change.

[6.8][ML] Fix bug persisting and restoring time series model decay rate controller (part 2)

---

docs/CHANGELOG.asciidoc
include/maths/CTimeSeriesModel.h
lib/maths/CTimeSeriesModel.cc
lib/maths/unittest/CTimeSeriesModelTest.cc

Whilst investigating #1680 I noticed another issue in state upgrade. This one is much more limited in scope and only affects pre 6.3 lat_long models.

[ML] Correct a bug in upgrade from pre 6.3 state for the lat_long function

---

include/api/CAnomalyJobConfig.h
include/api/CConfigUpdater.h
include/model/CAnomalyDetectorModelConfig.h
lib/api/CAnomalyJobConfig.cc
lib/api/CConfigUpdater.cc
lib/api/unittest/CConfigUpdaterTest.cc
lib/model/CAnomalyDetectorModelConfig.cc

Expect configuration update requests to be received in JSON formatted
strings. Remove support for old, ini file parsing.
Relates elastic/elasticsearch#67721, #1253

[ML] Parse JSON format config updates

---

include/api/CAnomalyJobConfig.h
include/api/CConfigUpdater.h
include/model/CAnomalyDetectorModelConfig.h
lib/api/CAnomalyJobConfig.cc
lib/api/CConfigUpdater.cc
lib/api/unittest/CConfigUpdaterTest.cc
lib/model/CAnomalyDetectorModelConfig.cc

* Expect configuration update requests to be received in JSON formatted
strings. 
* Remove support for old, ini file parsing.
Relates elastic/elasticsearch#67721, #1253
Backports #1682

[7.x][ML] Parse JSON format config updates (#1682)

---

lib/api/CDataFrameAnalysisInstrumentation.cc

Remove a temporary workaround which is no longer needed.

[ML] Tidy up data frame analysis progress monitoring

---

build-setup/linux.md

Instructions for installing the dependencies and building PyTorch on Linux
Follows the same commands used to build the docker image in #1678

[ML] Add PyTorch setup instructions for Linux

---

docs/CHANGELOG.asciidoc
include/api/CDataFrameTrainBoostedTreeRunner.h
include/maths/CBoostedTreeFactory.h
include/maths/CBoostedTreeImpl.h
include/test/CDataFrameAnalysisSpecificationFactory.h
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/test/CDataFrameAnalysisSpecificationFactory.cc

This PR implements early stopping of fine parameter tuning if the search process if the loss surfaces appear to be flat (very low total variation of the loss surface of hyperparameters). 
It also replaces uniform sampling of the hyperparameter in the first step of exploration by Sobol sampling which has a higher discrepancy.
I introduced the new configuration parameter `early_stopping_allowed` similar to the `disk_usage_allowed`. In the internal routines and for persist/restore, I call this flag `stopHyperparameterOptimizationEarly` similar to `stopCrossValidationEarly` that is already used.
Closes  #1669

[ML] Early stopping for hyperparameter optimization procedure

---

include/maths/CBoostedTreeFactory.h
include/maths/CBoostedTreeImpl.h
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc

The eta growth rate was historically controlled by the choice for the eta parameter, but setting them independently might sometimes yield better results. This adds the ability to override it manually. This isn't user facing yet (in the Java) so marking as a non-issue and not documenting.

[ML] Provide the ability to override eta growth rate hyperparameter

---

docs/CHANGELOG.asciidoc
include/api/CDataFrameTrainBoostedTreeRunner.h
include/maths/CBoostedTreeFactory.h
include/maths/CBoostedTreeImpl.h
include/test/CDataFrameAnalysisSpecificationFactory.h
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/test/CDataFrameAnalysisSpecificationFactory.cc

This PR implements early stopping of fine parameter tuning if the search process if the loss surfaces appear to be flat (very low total variation of the loss surface of hyperparameters).
It also replaces uniform sampling of the hyperparameter in the first step of exploration by Sobol sampling which has a higher discrepancy.
I introduced the new configuration parameter early_stopping_allowed similar to the disk_usage_allowed. In the internal routines and for persist/restore, I call this flag stopHyperparameterOptimizationEarly similar to stopCrossValidationEarly that is already used.
Backport for  #1676.

[7.x][ML] Early stopping for hyperparameter optimization procedure

---

build-setup/windows.md

This change sets extra flags during the PyTorch build to
avoid building unnecessary components, which dramatically
cuts the build time.  It also changes the location of
debug symbols from the libraries themselves to separate
.pdb files.
A couple of tweaks to the 1.7.1 build files are required
to get these options to work.  One of these is already
in the PyTorch master branch code.  There may be time to
get the other one incorporated in time for 1.8.0 too.

[ML] Improving PyTorch build on Windows

---

include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc

This PR adds debug information that can be used next time elastic/elasticsearch#59413 fails. The changes will be removed once we have collected this information.

[ML] Additional logging for the feature importance test failure

---

build-setup/linux.md
dev-tools/docker/linux_image/Dockerfile

Following https://github.com/elastic/ml-cpp/pull/1678#issuecomment-766327160 it is preferable to not have a dependency on libMKL for now at least. There are a number of alternative libraries that could be used in place of libMKL we have opted to use the header-only Eigen library. 
This uses the version of Eigen included in [PyTorch](https://github.com/pytorch/pytorch/tree/master/third_party) not the version in this repo.
Also sets the PyTorch library version number.
I've built and tested the docker image.

[ML] Use Eigen BLAS library when building PyTorch for Linux

---

docs/CHANGELOG.asciidoc
include/maths/CCalendarComponent.h
include/maths/CCalendarFeature.h
include/maths/CSeasonalComponent.h
include/maths/CSeasonalComponentAdaptiveBucketing.h
include/maths/CSeasonalTime.h
include/maths/CTimeSeriesDecompositionDetail.h
include/maths/CTimeSeriesModel.h
lib/maths/CCalendarComponent.cc
lib/maths/CCalendarComponentAdaptiveBucketing.cc
lib/maths/CCalendarFeature.cc
lib/maths/CDecayRateController.cc
lib/maths/CSeasonalComponent.cc
lib/maths/CSeasonalComponentAdaptiveBucketing.cc
lib/maths/CSeasonalTime.cc
lib/maths/CTimeSeriesDecomposition.cc
lib/maths/CTimeSeriesDecompositionDetail.cc
lib/maths/CTimeSeriesModel.cc
lib/maths/CTimeSeriesTestForSeasonality.cc
lib/maths/unittest/CDecayRateControllerTest.cc
lib/maths/unittest/CForecastTest.cc
lib/maths/unittest/CSeasonalComponentTest.cc
lib/maths/unittest/CTimeSeriesDecompositionTest.cc
lib/maths/unittest/CTimeSeriesModelTest.cc
lib/maths/unittest/CTimeSeriesTestForSeasonalityTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CMetricModelTest.cc

This addresses various sources of instability in the time series modelling for anomaly detection:
1. Our update dynamics were stable (just). However, we do other things which aren't considered in this analysis, such as apply different weights to different updates. I added a small margin.
2. There was an error in the times at which we asked for model predictions when component models were restricted to time windows, i.e. weekdays and weekends.
3. We could use stale predictions when there were long gaps in the data.
4. Changing the seasonal derivative too fast can create transient instability after data changes.
I've also added some more unit testing. Particular, in the area of when we refresh predictions and an explicit testing long term stability.

[ML] Assorted time series modelling stability fixes

---

lib/maths/unittest/CBoostedTreeTest.cc

As I was backporting unit tests on `7.x`, I noticed that due to numerical properties for different platforms and compilers, the unit test checks diverged somewhat. This PR synchronizes the code of `CBoostedTreeTest.cc` for `master` and `7.x`.

[ML] Unify CBoostedTreeTest in 7.x and master

---

include/api/CDataFrameTrainBoostedTreeRunner.h
include/maths/CBoostedTreeFactory.h
include/test/CDataFrameAnalysisSpecificationFactory.h
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/test/CDataFrameAnalysisSpecificationFactory.cc

We agreed that the parameter should be renamed to `early_stopping_enabled` for consistency. 
Within `CBoostedTreeImpl` I would still keep the differentiated set of flags to enable/disable early stopping in different stages. All this flags will be initialized in `CBoostedTreeFactory` using the value from `early_stopping_enabled` configuration from the API.
Relates #1676.

[ML] Rename the early stopping configuration parameter

---

lib/maths/CSeasonalComponent.cc
lib/maths/CTimeSeriesDecompositionDetail.cc
lib/maths/unittest/CForecastTest.cc
lib/maths/unittest/CSeasonalComponentTest.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CMetricModelTest.cc

#1675 introduced a subtle bug in the updating of newly initialised seasonal components. It switched to using state to track when it refreshes the seasonal model predictions to reflect new data (to correct behaviour when there are long gaps in the data). However, we test for seasonal components on a window which can sometimes extend beyond the current time (with future values set to "null"). As a result we were sometimes setting the time to refresh into the future and the model wasn't reflecting new data immediately after a seasonal component was added. The change has not been released so marking as a non-issue.

[ML] Fix seasonal model update immediately after initialisation

---

include/api/CDataFrameTrainBoostedTreeRunner.h
include/maths/CBoostedTreeFactory.h
include/test/CDataFrameAnalysisSpecificationFactory.h
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/test/CDataFrameAnalysisSpecificationFactory.cc

We agreed that the parameter should be renamed to early_stopping_enabled for consistency.
Within CBoostedTreeImpl I would still keep the differentiated set of flags to enable/disable early stopping in different stages. All this flags will be initialized in CBoostedTreeFactory using the value from early_stopping_enabled configuration from the API.
Backport of #1699.

[7.x][ML] Rename the early stopping configuration parameter

---

lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc

Running feature importance tests with early stopping activate resulted in [flacky tests in the CI](#1693). I disable early stopping to be able to test the complete functionality.
Fixes #1693.

[ML] Disable early stopping for the feature importance API tests

---

include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc

Now that elastic/elasticsearch#59413 has be clarified and solved, we don't need this additional logging.
I will also revert the corresponding backport PR.
Reverts elastic/ml-cpp#1694

[ML] Revert "[ML] Additional logging for the feature importance test failure"

---

lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc

Running feature importance tests with early stopping activate resulted in flacky tests in the CI. I disable early stopping to be able to test the complete functionality.
Backport for #1710

[7.x][ML] Disable early stopping for the feature importance API tests 

---

build-setup/linux.md
build-setup/macos.md
dev-tools/docker/linux_image/Dockerfile

Linux uses the Eigen BLAS library and macOS the Accelerate framework so MKL is not required.
This also fixes an intermittent problem building the Linux build image where the pytorch repo was not cleaned leaving a 23GB image. This fix takes the image size down to 5.4GB. 2GB of that is in `/usr/local/lib/python3.7` which could also be removed.

[ML] Remove mkl dependency and improve docker cleanup

---

lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc

CDataFrameAnalyzerFeatureImportanceTest.testRegressionFeatureImportanceNoImportance
gives slightly different results on macOS compared to Windows and Linux,
so the test thresholds need to be slightly wider.
Fixes #1693

[ML] Fix test threshold for macOS

---

lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc

CDataFrameAnalyzerFeatureImportanceTest.testRegressionFeatureImportanceNoImportance
gives slightly different results on macOS compared to Windows and Linux,
so the test thresholds need to be slightly wider.
Backport of #1715

[7.x][ML] Fix test threshold for macOS

---

docs/CHANGELOG.asciidoc
lib/maths/CSeasonalComponent.cc
lib/maths/CTimeSeriesDecompositionDetail.cc
lib/maths/CTimeSeriesTestForChange.cc
lib/maths/CTimeSeriesTestForSeasonality.cc
lib/maths/unittest/CForecastTest.cc
lib/maths/unittest/CTimeSeriesDecompositionTest.cc

While fixing #1646, I noticed we weren't reliably removing seasonal components from our time series model when the data flatlined. This happens for example, when a count anomaly detector stops receiving new data.
The behaviour was due to a bug in how we computed statistics related to the components we already modelled. Specifically, we would discard the correct statistics because `SHypothesisStats::isBetter` didn't consider whether or not the type was default initialised. In such cases, discarding seasonality leads to smaller, more accurate and more stable models.
I took the opportunity to remove the previous approach of perturbing the values to deal with low variation data, because this doesn't work when the values are zero, and otherwise should no longer be needed.

[ML] Make sure we remove seasonality modelling when data flatlines

---

mk/linux_crosscompile_macosx.mk
mk/macosx.mk

New versions of clang often bring new warnings that trigger
repetitively on our codebase and need to be silenced.  But
then older versions of clang complain about the options that
silence the new warnings.
This commit adds the flag that tells the older versions of
clang to ignore warning options they don't understand.  This
works nicely with our approach of enabling all warnings and
then disabling the ones that cause useless noise.

[ML] Use the clang flag to ignore unknown warning options

---

lib/maths/CQDigest.cc

A recently enabled check on invariants after state restoration is
failing on occasion. Disable the test until a full investigation can be
carried out.
Relates #1717
Closes #1728

[ML] Disabling ill behaved invariant check

---

bin/pytorch_inference/evaluate.py
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/linux_aarch64_native_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_image/Dockerfile

The main difference between the x86 and aarch builds is that FBGEMM requires [AVX2](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#Advanced_Vector_Extensions_2) instructions. FBGEMM cannot be compiled on aarch64, Caffe2 is used instead. 
x86 builds set `BUILD_CAFFE2=OFF` but it is required here and left unset.  
I've built and run the smoketest `evaluate.py` script on native linux aarch64. 
The process of building the libraries ml uses creates a lot of files that are not required in the final build image. The simple solution is to use a multi-stage build where the final image copies all the required dependencies built in the intermediate image. Primarily it is the contents of `/usr/local/gcc93` and `/usr/include` that must be copied and also some programs (make, git, etc) must …

[ML] Build libtorch for Linux aarch64

---

lib/maths/CQDigest.cc

A recently enabled check on invariants after state restoration is
failing on occasion. Disable the test until a full investigation can be
carried out.
Backports #1730 
Relates #1717
Closes #1728

[7.x][ML] Disabling ill behaved invariant check (#1730)

---

include/api/CDataFrameAnalysisConfigReader.h
include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
include/maths/CBoostedTree.h
include/maths/CBoostedTreeFactory.h
include/maths/CBoostedTreeImpl.h
include/maths/CDataFramePredictiveModel.h
include/test/CDataFrameAnalysisSpecificationFactory.h
lib/api/CDataFrameAnalysisConfigReader.cc
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/maths/CBoostedTree.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/test/CDataFrameAnalysisSpecificationFactory.cc
lib/test/CDataFrameAnalyzerTrainingFactory.cc

We plan to allow users to also set weights for class assignment via choosing a point on the ROC curve. In this case, the config should allow overriding class weights to reflect the user's error preferences if retraining. This introduces a new value in the parameters section of the JSON object of the form
```
"classification_weights": [{"class":"<string>", "weight": <double>}]
```
and a new class assignment objective `custom`.
Closes #1719. I've marked this as a non-issue because it isn't really user facing and we should only document when the Java side of the changes to support overriding the decision threshold is implemented.

[ML] Allow a user to override weights for assigning labels to classes

---

docs/CHANGELOG.asciidoc
include/maths/CBoostedTreeImpl.h
include/maths/CBoostedTreeLeafNodeStatistics.h
lib/maths/CBoostedTreeImpl.cc
lib/maths/CBoostedTreeLeafNodeStatistics.cc
lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
lib/maths/unittest/CBoostedTreeTest.cc

We already downsample candidate split features at node. However, because we can use different feature bags along a branch, cache split derivatives and use the parent and sibling derivatives to compute them for the child with more training examples, we compute them for all features. If we were to use a single feature bag for the entire tree then we could just compute these.
This change introduces a tree wide feature bag which contains the node feature bag. I explored replacing the per node feature bag altogether, but found evidence that enforcing some diversity in selected features by sampling within a tree was beneficial. However, I didn't find any evidence to warrant an extra hyperparameter and simply use a slightly, 1.5x times, larger feature bag for the tree.
There is some additional …

[ML] Use a per tree feature bag for boosted tree training

---

dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_tester/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
dev-tools/docker/macosx_builder/Dockerfile

Increment version for the docker builder file and build scripts for Linux Aarch64 and macOS

[ML] Increment docker versions for PyTorch images

---

build-setup/macos_cross_compiled.md
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/macosx_image/Dockerfile

A macOS Docker image that includes the PyTorch libraries

Updating macOS Docker image

---

bin/Makefile
bin/controller/Main.cc
bin/pytorch_inference/.gitignore

Now we have built libraries for all the different platforms
pytorch_inference can be added to the Makefile without
breaking CI.
If CI fails for this PR it will smoke out any mistakes in
Docker images or dependency bundles.
Also adding to controller as that's a one-liner.
Closes #1702

[ML] Add pytorch_inference to Makefile and controller

---

include/maths/CBoostedTree.h
include/maths/CBoostedTreeImpl.h
include/maths/CDataFramePredictiveModel.h
lib/maths/CBoostedTree.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc

Digging into regression test changes I realise there were two issues with #1733:
1. We weren't reliably choosing samples from the tree bag when sampling at nodes,
2. We were changing the sample probabilities because we used them unmodified when selecting from the tree bag even though they affect the bag composition.
This fixes 1 and approximately accounts for 2. I also took the opportunity to close off some of the TODOs in the unit tests.
This is unreleased code so marking as a non-issue.

[ML] Fix a bug in per tree feature bags and improve test coverage

---

lib/model/CDetectorEqualizer.cc
lib/model/CEventRateBucketGatherer.cc
lib/model/CIndividualModel.cc
lib/model/CPopulationModel.cc
lib/model/CTokenListCategory.cc

Add checking of invariants after restoration of several classes in the
model library.
Also change a number of conditions where an error was emitted during the
restoration process to be hard stops with LOG_ABORT.
Relates #1717
Backports #1737

[7.x][ML] Check invariants after restoration (#1737)

---

dev-tools/jenkins_ci.sh

PR builds will now fan out to workers that include macOS ARM
workers. But for old branches we cannot build on this architecture,
so just make such builds a no-op.
The approach is similar to #1203, and because the 6.8 branch
already contains #1203 this change is only needed for 7.11 and
7.12.

[ML] Do nothing on macOS ARM workers on old branches

---

docs/CHANGELOG.asciidoc
include/maths/CBoostedTreeFactory.h
include/maths/CBoostedTreeImpl.h
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc

Following on from #1733, we can get further speedups by line searching for the best feature bag fraction for data sets where we only need a fraction of the features per tree. For example, training time on Higgs 1M drops from 2585s to 1742s and we actually get a small improvement in accuracy because our hyperparameter search region is better initialised.
This makes three changes:
1. Adds a line search for the best initial feature bag fraction to use.
2. Adds a small linear penalty at most 1% minimum loss to encourage larger down sample factors and smaller feature bag fractions.
3. Handles better the case we have many features and relatively few training examples.
Some of the variable naming in `CBoostedTreeFactory` is also now misleading. I've split this change out into a non-functional …

[ML] Line search feature bag fraction for classification and regression model training

---

buildSrc/build.gradle
buildSrc/src/main/groovy/org/elastic/gradle/UploadS3Task.groovy
dev-tools/download_macos_deps.sh
dev-tools/jenkins_ci.sh
lib/core/unittest/CDualThreadStreamBufTest.cc
lib/core/unittest/CLoggerThrottlerTest.cc
lib/core/unittest/CMonotonicTimeTest.cc
lib/core/unittest/CStopWatchTest.cc
lib/maths/unittest/CBoostedTreeTest.cc
upload.gradle

This change adds coverage for macOS on ARM to CI.
There are 3 parts to this:
1. Download the pre-built 3rd party dependencies at the
beginning of the build.  Unlike Linux builds which can
get these dependencies by building in a Docker container,
the macOS CI machines need to get them via a more
primitive mechanism.
2. Adjust the Jenkins CI shell script to account for the
possibility of having to build natively on macOS as well
as in Docker on Linux.
3. Switch to the newer S3 API from Amazon.  The old S3 API
didn't work in Java 9 or above, which we worked around by
ensuring Java 8 was installed on the CI workers.  But
that's not possible for macOS on ARM, so it's finally
forced an upgrade.

[ML] Adding CI for macOS on ARM

---

dev-tools/jenkins_ci.sh

PR builds will now fan out to workers that include macOS ARM
workers. But for old branches we cannot build on this architecture,
so just make such builds a no-op.
The approach is similar to #1203, and because the 6.8 branch
already contains #1203 this change is only needed for 7.11 and
7.12.
Backport of #1749

[7.11][ML] Do nothing on macOS ARM workers on old branches

---

lib/maths/unittest/CBasicStatisticsTest.cc
lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
lib/maths/unittest/CSignalTest.cc
lib/maths/unittest/CTimeSeriesDecompositionTest.cc
lib/maths/unittest/CTimeSeriesSegmentationTest.cc
lib/maths/unittest/CTimeSeriesTestForChangeTest.cc
lib/maths/unittest/CTimeSeriesTestForSeasonalityTest.cc

BOOST_TEST_REQUIRE is better than BOOST_REQUIRE for assertions
that contain a single comparison operator and where both the
left hand side and right hand side of it are printable.  The
advantage is that on failure it prints the values that failed
the test.

[ML] Replace BOOST_REQUIRE with BOOST_TEST_REQUIRE

---

buildSrc/build.gradle
buildSrc/src/main/groovy/org/elastic/gradle/UploadS3Task.groovy
dev-tools/download_macos_deps.sh
dev-tools/jenkins_ci.sh
lib/core/unittest/CDualThreadStreamBufTest.cc
lib/core/unittest/CLoggerThrottlerTest.cc
lib/core/unittest/CMonotonicTimeTest.cc
lib/core/unittest/CStopWatchTest.cc
lib/maths/unittest/CBoostedTreeTest.cc
upload.gradle

This change adds coverage for macOS on ARM to CI.
There are 4 parts to this:
1. Download the pre-built 3rd party dependencies at the
beginning of the build.  Unlike Linux builds which can
get these dependencies by building in a Docker container,
the macOS CI machines need to get them via a more
primitive mechanism.
2. Adjust the Jenkins CI shell script to account for the
possibility of having to build natively on macOS as well
as in Docker on Linux.
3. Switch to the newer S3 API from Amazon.  The old S3 API
didn't work in Java 9 or above, which we worked around by
ensuring Java 8 was installed on the CI workers.  But
that's not possible for macOS on ARM, so it's finally
forced an upgrade.
4. Account for inaccurate sleeps when running from Jenkins.
For some reason when running from Jenkins …

[7.x][ML] Adding CI for macOS on ARM

---

lib/maths/unittest/CBasicStatisticsTest.cc
lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
lib/maths/unittest/CSignalTest.cc
lib/maths/unittest/CTimeSeriesDecompositionTest.cc
lib/maths/unittest/CTimeSeriesSegmentationTest.cc
lib/maths/unittest/CTimeSeriesTestForChangeTest.cc
lib/maths/unittest/CTimeSeriesTestForSeasonalityTest.cc

BOOST_TEST_REQUIRE is better than BOOST_REQUIRE for assertions
that contain a single comparison operator and where both the
left hand side and right hand side of it are printable.  The
advantage is that on failure it prints the values that failed
the test.
Backport of #1751

[7.x][ML] Replace BOOST_REQUIRE with BOOST_TEST_REQUIRE

---

lib/core/unittest/CLoggerThrottlerTest.cc

In the backport of #1745 the tolerance on the logger
throttler test had to be increased again due to a
problem with sleep calls sleeping for longer than
specified when running under Jenkins on macOS on ARM.
The change was in the 3rd commit on #1752.
This change makes the same increase on the master
branch, to keep the branches in sync.

[ML] Further increase tolerance for logger throttler test

---

dev-tools/download_macos_deps.sh
lib/core/unittest/CReadWriteLockTest.cc

When #1745 was backported to the 7.x branch in #1752
the version of the dependency bundle should have been
adjusted to the one that includes the correct dependencies
for the 7.x branch, but this step was missed. Although
the master dependency bundle works, the correct bundle
should be used for consistency across the whole 7.x
distribution.

[ML] Correct the macOS ARM dependency bundle for 7.x

---

lib/core/unittest/CReadWriteLockTest.cc

In #1759 the tolerance on the read/write lock test
had to be increased again due to a problem with sleep
calls sleeping for longer than specified when running
under Jenkins on macOS on ARM.  The change was in the
2nd commit on #1759.
This change makes the same increase on the master
branch, to keep the branches in sync.

[ML] Increase tolerance for read/write lock test

---

dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh

[ML] Retry getting AWS credentials in CI builds

---

dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh

[7.x][ML] Retry getting AWS credentials in CI builds

---

dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh

[7.12][ML] Retry getting AWS credentials in CI builds

---

dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh

[7.11][ML] Retry getting AWS credentials in CI builds

---

gradle/wrapper/gradle-wrapper.properties

Soon we will upgrade to version 7, and being on the
latest in the 6.x series reduces the risk of missing
a deprecation warning.

[ML] Upgrade to Gradle 6.8.3

---

gradle/wrapper/gradle-wrapper.properties

Soon we will upgrade to version 7, and being on the
latest in the 6.x series reduces the risk of missing
a deprecation warning.
Backport of #1768

[7.x][ML] Upgrade to Gradle 6.8.3

---

docs/CHANGELOG.asciidoc
include/maths/CBoostedTreeImpl.h
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc

As we move towards training for hyperparameter tuning on a small fraction of the data set and final training on more we will suffer issues with overfitting if we don't address the bias this introduces estimating regularisers. Interestingly, we already see a mismatch in train and test errors on larger data sets where we only use two-folds. I tested this correction, which is the one we use when we downsample, on a variety of data sets and we ended up with lower mismatch between train and test errors.

[ML] Scale regularisers for final train

---

include/api/CAnomalyJob.h
include/core/CProgramCounters.h
lib/api/CAnomalyJob.cc
lib/api/CFieldDataCategorizer.cc
lib/api/unittest/CPersistenceManagerTest.cc
lib/core/CProgramCounters.cc

The collection of static program counters is cached prior to
persistence. This provides the background persistence thread access to a
consistent set of counters as they are being written.
As it is desired to only persist the program counters the once for each
model state snapshot, their persistence, and the clearing of the cache,
is coupled to the persistence of the simple count detector, which is
assumed to always exist.
However there is a scenario where persistence operates on an empty
collection of detectors. This occurs when no data has been seen but time
has advanced (see #393 for more details). In this situation the program
counter cache is populated but not cleared. A subsequent persistence
operation will lead to a warning that the counter cache is being
overwritten.
To avoid the …

[7.x][ML] Ensure program counters cache always cleared (#1774)

---

dev-tools/run_es_tests.sh
set_env.sh

This has been observed to fail in Docker running
on CentOS 8.3.  It's also not necessary - those
ulimit commands were really intended for tests
running on static workers where we could log in
afterwards to look at core dumps.
Additionally, there are complexities with the Java
build used to run the subset of Elasticsearch tests.
We need to use a Java that was built on a
distribution with the same page size as the test
machine.

[ML] Fixes to get CI working on CentOS on AArch64

---

dev-tools/run_es_tests.sh
set_env.sh

Setting shell limits has been observed to fail in
Docker running on CentOS 8.3. It's also not
necessary - those ulimit commands were really
intended for tests running on static workers
where we could log in afterwards to look at core
dumps.
Additionally, there are complexities with the Java
build used to run the subset of Elasticsearch tests.
We need to use a Java that was built on a
distribution with the same page size as the test
machine.
Backport of #1777

[7.12][ML] Fixes to get CI working on CentOS on AArch64

---

dev-tools/run_es_tests.sh
set_env.sh

Setting shell limits has been observed to fail in
Docker running on CentOS 8.3. It's also not
necessary - those ulimit commands were really
intended for tests running on static workers
where we could log in afterwards to look at core
dumps.
Additionally, there are complexities with the Java
build used to run the subset of Elasticsearch tests.
We need to use a Java that was built on a
distribution with the same page size as the test
machine.
Backport of #1777

[7.x][ML] Fixes to get CI working on CentOS on AArch64

---

dev-tools/run_es_tests.sh
set_env.sh

Setting shell limits has been observed to fail in
Docker running on CentOS 8.3. It's also not
necessary - those ulimit commands were really
intended for tests running on static workers
where we could log in afterwards to look at core
dumps.
Additionally, there are complexities with the Java
build used to run the subset of Elasticsearch tests.
We need to use a Java that was built on a
distribution with the same page size as the test
machine.
Backport of #1777

[7.11][ML] Fixes to get CI working on CentOS on AArch64

---

.clang-tidy

This PR specifies the properties for clang-tidy static code analysis tool.
Backport of  #1771.

[7.x][ML] Add clang-tidy configuration

---

include/maths/CBoostedTree.h
include/maths/CBoostedTreeFactory.h
include/maths/CBoostedTreeImpl.h
include/maths/CBoostedTreeLeafNodeStatistics.h
include/maths/CBoostedTreeLeafNodeStatisticsIncremental.h
include/maths/CBoostedTreeLeafNodeStatisticsScratch.h
include/maths/CDataFramePredictiveModel.h
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
lib/maths/CBoostedTree.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/CBoostedTreeLeafNodeStatistics.cc
lib/maths/CBoostedTreeLeafNodeStatisticsScratch.cc
lib/maths/Makefile
lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
lib/maths/unittest/CBoostedTreeTest.cc

This makes some mainly interface changes in anticipation of incremental training. The plan is to adjust the loss function to include penalties for modifying the tree topology and results. It should be possible to manage this in `CBoostedTreeLeafNodeStatistics` and reuse our existing training code. As such I've made this a hierarchy. The current implementation moves into `CBoostedTreeLeafNodeStatisticsScratch` and I'll have a new implementation `CBoostedTreeLeafNodeStatisticsIncremental` (placeholder). There will likely need to be further tweaks down the line particularly to the workspace object, but I'll make those in the context of working on the implementation `CBoostedTreeLeafNodeStatisticsIncremental`. This feels like a useful place to break up the change before I move into …

[ML] Incremental train (part 1)

---

build-setup/macos.md
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/macosx_builder/Dockerfile
dev-tools/docker/macosx_image/Dockerfile
dev-tools/download_macos_deps.sh

Upgrades PyTorch from version 1.7.1 to version 1.8.0 on macOS.
It is now possible to build a version that works on Apple Silicon.
The build instructions are also adjusted to remove functions that
call an external compiler to build custom extensions. Although
these would never have worked in our programs due to system call
filtering, it's best if they aren't present at all as they could
alarm heuristic virus scanners.
(Similar upgrades will be done for Windows and Linux in the near
future.)

[ML] Upgrading to PyTorch 1.8.0 on macOS

---

include/core/CPersistUtils.h
include/maths/CBasicStatisticsPersist.h
lib/core/CProgramCounters.cc
lib/core/unittest/CProgramCountersTest.cc
lib/maths/CDataFrameUtils.cc

Fixes a few more places where array or vector bounds were not
checked during state restoration.
Follows on from #1717 and #1737

[ML] Improve bounds checks in state restore code

---

include/core/CPersistUtils.h

This implements what was discussed in
https://github.com/elastic/ml-cpp/pull/1798#discussion_r592515203
By making this change only on the master branch we will have a
long time to see if there are any unexpected side effects, where
we were accidentally relying on the bug.

[ML] Make too many array values on restore fatal

---

include/core/CPersistUtils.h
include/maths/CBasicStatisticsPersist.h
lib/core/CProgramCounters.cc
lib/core/unittest/CProgramCountersTest.cc
lib/maths/CDataFrameUtils.cc

Fixes a few more places where array or vector bounds were not
checked during state restoration.
Backport of #1798

[7.12][ML] Improve bounds checks in state restore code

---

include/core/CPersistUtils.h
include/maths/CBasicStatisticsPersist.h
lib/core/CStatistics.cc

Fixes a few more places where array or vector bounds were not
checked during state restoration.
Backport of #1798

[6.8][ML] Improve bounds checks in state restore code

---

include/core/CPersistUtils.h
include/maths/CBasicStatisticsPersist.h
lib/core/CProgramCounters.cc
lib/core/unittest/CProgramCountersTest.cc
lib/maths/CDataFrameUtils.cc

Fixes a few more places where array or vector bounds were not
checked during state restoration.
Backport of #1798

[7.x][ML] Improve bounds checks in state restore code

---

build-setup/windows.md
dev-tools/download_windows_deps.ps1

Upgrades PyTorch from version 1.7.1 to version 1.8.0 on Windows.
The build instructions are also adjusted to remove functions that
call an external compiler to build custom extensions. Although
these would never have worked in our programs due to system call
filtering, it's best if they aren't present at all as they could
alarm heuristic virus scanners.
(A similar upgrade will be done for Linux in the near future.)

[ML] Upgrading to PyTorch 1.8.0 on Windows

---

bin/autodetect/CCmdLineParser.cc
devbin/state_search_splitter/Main.cc

The autodetect executable needs to check for missing config after handling help and version requests. This also handles pretty printed search results in the state_search_splitter executable.

[ML] Some command line improvements

---

bin/pytorch_inference/CCmdLineParser.cc
bin/pytorch_inference/CCmdLineParser.h
bin/pytorch_inference/Main.cc

Renames pytorch process logging arguments to be
consistent with the other processes and with what java
provides.

[ML] Rename pytorch log pipe arg

---

.gitignore
include/core/CImmutableRadixSet.h
include/maths/CBoostedTree.h
include/maths/CBoostedTreeHyperparameters.h
include/maths/CBoostedTreeLeafNodeStatistics.h
include/maths/CBoostedTreeLeafNodeStatisticsIncremental.h
include/maths/CBoostedTreeLeafNodeStatisticsScratch.h
include/maths/CBoostedTreeUtils.h
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/CBoostedTreeLeafNodeStatistics.cc
lib/maths/CBoostedTreeLeafNodeStatisticsIncremental.cc
lib/maths/CBoostedTreeLeafNodeStatisticsScratch.cc
lib/maths/CBoostedTreeUtils.cc
lib/maths/Makefile

This is a first pass implementing leaf node statistics for incremental training. This introduces an extra term in the gain calculation penalising changing the topology of the tree being retrained. It also migrates common functionality back to `CBoostedTreeLeafNodeStatistics`. Note that I have not tried to compute look ahead bounds for incremental training (because this is complicated by the split dependent penalty). Therefore, I optionally disable the extra statistics we compute to support this. I decided not to unit test this yet because I think it will be more valuable in the context of end-to-end testing, but it represents a nice self contained piece of work, so I'm breaking this out into a PR.

[ML] Implement the boosted tree leaf node statistics for incremental training

---

lib/seccomp/CSystemCallFilter_Linux.cc

mmap and munmap are used by the malloc arenas functionality
of glibc. mprotect is also used by that functionality,
together with pthreads, which uses mprotect for managing
each pthread's stack.

[ML] Document the reason for allowing some syscalls

---

3rd_party/3rd_party.sh
mk/linux.mk
mk/linux_crosscompile_linux.mk

1. When setting RPATH using patchelf, use the --force-rpath
option, because otherwise it sets RUNPATH instead. This
only makes a difference when LD_LIBRARY_PATH is set, so
won't affect our expected production scenario where
LD_LIBRARY_PATH is _not_ set. But preferring RPATH may
avoid confusion in dev environments.
2. Use $ORIGIN instead of $ORIGIN/. when setting RPATH on
the link line. The /. gets appended automatically, so
we are actually using $ORIGIN/./. at the moment, which
works fine but looks messy.

[ML] A couple of improvements to setting RPATH

---

lib/seccomp/CSystemCallFilter_Linux.cc

mmap and munmap are used by the malloc arenas functionality
of glibc. mprotect is also used by that functionality,
together with pthreads, which uses mprotect for managing
each pthread's stack.
Backport of #1806

[7.x][ML] Document the reason for allowing some syscalls

---

3rd_party/3rd_party.sh
mk/linux.mk
mk/linux_crosscompile_linux.mk

1. When setting RPATH using patchelf, use the --force-rpath
option, because otherwise it sets RUNPATH instead. This
only makes a difference when LD_LIBRARY_PATH is set, so
won't affect our expected production scenario where
LD_LIBRARY_PATH is _not_ set. But preferring RPATH may
avoid confusion in dev environments.
2. Use $ORIGIN instead of $ORIGIN/. when setting RPATH on
the link line. The /. gets appended automatically, so
we are actually using $ORIGIN/./. at the moment, which
works fine but looks messy.
Backport of #1812

[7.x][ML] A couple of improvements to setting RPATH

---

3rd_party/licenses/pytorch-INFO.csv
3rd_party/licenses/pytorch-LICENSE.txt
3rd_party/licenses/pytorch-NOTICE.txt

The details are for version 1.8.0.
PyTorch will also show up in the public dependency report
once the feature branch is merged to master.

[ML] Add PyTorch license to repo

---

docs/CHANGELOG.asciidoc
lib/seccomp/CSystemCallFilter_Linux.cc

Under certain circumstances, the realloc() function in glibc
will make the mremap syscall. If this fails then realloc()
falls back to using malloc() and memcpy(), so the end result
is the same from the caller's perspective, it's just slower.
Prior to now we did not have the mremap syscall on our
permitted list in our seccomp filter. Not only did this mean
that our realloc() calls were slower than they could be, we
are also filling up audit logs in systems that audit syscalls
that seccomp blocks.
This change permits the mremap syscall. The risk is low,
because we already permit mmap and munmap and mremap can be
emulated using those two.

[ML] Adding mremap to syscall filter

---

docs/CHANGELOG.asciidoc
lib/seccomp/CSystemCallFilter_Linux.cc

Under certain circumstances, the realloc() function in glibc
will make the mremap syscall. If this fails then realloc()
falls back to using malloc() and memcpy(), so the end result
is the same from the caller's perspective, it's just slower.
Prior to now we did not have the mremap syscall on our
permitted list in our seccomp filter. Not only did this mean
that our realloc() calls were slower than they could be, we
are also filling up audit logs in systems that audit syscalls
that seccomp blocks.
This change permits the mremap syscall. The risk is low,
because we already permit mmap and munmap and mremap can be
emulated using those two.
Backport of #1819

[7.x][ML] Adding mremap to syscall filter

---

include/core/CLogger.h
lib/core/CLogger.cc
lib/core/unittest/CLoggerTest.cc

The LOG_ABORT macro calls CLogger::fatal(), which, prior
to this change, used to throw an exception.
We have a rule of thumb that we don't use exceptions in
our code and exceptions from third party libraries are
caught as close as possible to the call into that library.
When CLogger::fatal() was originally written this rule
was pretty universally applied, and it was a reasonable
assumption that a thrown exception would not be handled
and would hence abort the program. However, we now have so
many exceptions to this rule that an exception thrown by
a LOG_ABORT macro is quite likely to get caught, logged,
and cause some sort of minor workaround code to run. This
is not the intention for LOG_ABORT; it is intended to be
used only when the program is in a fatally compromised
state due to some …

[ML] Abort more explicitly

---

include/core/CLogger.h
lib/core/CLogger.cc
lib/core/unittest/CLoggerTest.cc

The LOG_ABORT macro calls CLogger::fatal(), which, prior
to this change, used to throw an exception.
We have a rule of thumb that we don't use exceptions in
our code and exceptions from third party libraries are
caught as close as possible to the call into that library.
When CLogger::fatal() was originally written this rule
was pretty universally applied, and it was a reasonable
assumption that a thrown exception would not be handled
and would hence abort the program. However, we now have so
many exceptions to this rule that an exception thrown by
a LOG_ABORT macro is quite likely to get caught, logged,
and cause some sort of minor workaround code to run. This
is not the intention for LOG_ABORT; it is intended to be
used only when the program is in a fatally compromised
state due to some …

[7.x][ML] Abort more explicitly

---

bin/pytorch_inference/CCommandParser.cc
bin/pytorch_inference/CCommandParser.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/unittest/CCommandParserTest.cc

Inference requests are JSON documents, previously the command parser would drop a malformed request with only a log message as evidence of its passing. 
This adds an error handler to the command processor that is called in the event of the bad inference request, the error is returned on the output so a client can expect a response for every request sent. 
In practice it is unlikely that a malformed request is sent during normal operation but I want to establish the contract that a client can always expect some sort of response.

[ML] Handle validation errors in PyTorch requests

---

include/core/CLogger.h
lib/core/CLogger.cc
lib/core/unittest/CLoggerTest.cc

The LOG_ABORT macro calls CLogger::fatal(), which, prior
to this change, used to throw an exception.
We have a rule of thumb that we don't use exceptions in
our code and exceptions from third party libraries are
caught as close as possible to the call into that library.
When CLogger::fatal() was originally written this rule
was pretty universally applied, and it was a reasonable
assumption that a thrown exception would not be handled
and would hence abort the program. However, we now have so
many exceptions to this rule that an exception thrown by
a LOG_ABORT macro is quite likely to get caught, logged,
and cause some sort of minor workaround code to run. This
is not the intention for LOG_ABORT; it is intended to be
used only when the program is in a fatally compromised
state due to some …

[6.8][ML] Abort more explicitly

---

bin/pytorch_inference/CCommandParser.cc
bin/pytorch_inference/CCommandParser.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/evaluate.py
bin/pytorch_inference/examples/simplest/test_run.json
bin/pytorch_inference/unittest/CCommandParserTest.cc

The main motivation for this change is to enable round trip testing of the Java and C++ processes with a small TorchScript model where downloading a large BERT model in the integration tests is not practical. Additionally this represents another use-case which is beneficial for evolving the design. 
PyTorch tensors have a type, BERT uses uint 64 whereas this model expects float 32, to distinguish between the 2 a new field has been added to the input JSON. The JSON document is used only for internal communications between Java and C++ and can be changed freely provided both sides are upgraded together, for this reason I have gone for a practical rather than elegant structure. 
`test_run.json` describes the input and output
The app knows little about the model is it evaluating, some …

[ML] Add ability to evaluate a simple PyTorch model

---

include/core/CLogger.h
lib/core/CLogger.cc
lib/core/unittest/CLoggerTest.cc

The LOG_ABORT macro calls CLogger::fatal(), which, prior
to this change, used to throw an exception.
We have a rule of thumb that we don't use exceptions in
our code and exceptions from third party libraries are
caught as close as possible to the call into that library.
When CLogger::fatal() was originally written this rule
was pretty universally applied, and it was a reasonable
assumption that a thrown exception would not be handled
and would hence abort the program. However, we now have so
many exceptions to this rule that an exception thrown by
a LOG_ABORT macro is quite likely to get caught, logged,
and cause some sort of minor workaround code to run. This
is not the intention for LOG_ABORT; it is intended to be
used only when the program is in a fatally compromised
state due to some …

[7.12][ML] Abort more explicitly

---

docs/CHANGELOG.asciidoc
lib/seccomp/CSystemCallFilter_Linux.cc

In glibc version 2.33 the implementation of the mknod() function
was consolidated so that the underlying syscall used was mknodat
for all architectures.
Prior to glibc 2.33 the aarch64 implementation of the mknod()
function used the mknodat syscall but other architectures used
the mknod syscall.
To allow the ML C++ to work with glibc 2.33 on x86_64, this change
moves mknodat into the list of syscalls that are permitted on all
architectures.
The mknod syscall is still also permitted on x86_64.  We will need
to leave this until our oldest supported distribution is using
glibc 2.33 or higher (10+ years in the future probably).
Fixes elastic/elasticsearch#70613

[ML] Make ML native processes work with glibc 2.33 on x86_64

---

docs/CHANGELOG.asciidoc
lib/seccomp/CSystemCallFilter_Linux.cc

In glibc version 2.33 the implementation of the mknod() function
was consolidated so that the underlying syscall used was mknodat
for all architectures.
Prior to glibc 2.33 the aarch64 implementation of the mknod()
function used the mknodat syscall but other architectures used
the mknod syscall.
To allow the ML C++ to work with glibc 2.33 on x86_64, this change
moves mknodat into the list of syscalls that are permitted on all
architectures.
The mknod syscall is still also permitted on x86_64.  We will need
to leave this until our oldest supported distribution is using
glibc 2.33 or higher (10+ years in the future probably).
Backport of #1828

[7.x][ML] Make ML native processes work with glibc 2.33 on x86_64

---

docs/CHANGELOG.asciidoc
lib/seccomp/CSystemCallFilter_Linux.cc

In glibc version 2.33 the implementation of the mknod() function
was consolidated so that the underlying syscall used was mknodat
for all architectures.
Prior to glibc 2.33 the aarch64 implementation of the mknod()
function used the mknodat syscall but other architectures used
the mknod syscall.
To allow the ML C++ to work with glibc 2.33 on x86_64, this change
moves mknodat into the list of syscalls that are permitted on all
architectures.
The mknod syscall is still also permitted on x86_64.  We will need
to leave this until our oldest supported distribution is using
glibc 2.33 or higher (10+ years in the future probably).
Backport of #1828

[7.12][ML] Make ML native processes work with glibc 2.33 on x86_64

---

include/maths/CBoostedTreeLoss.h
include/maths/CBoostedTreeUtils.h
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/CBoostedTreeLoss.cc
lib/maths/CBoostedTreeUtils.cc
lib/maths/CDataFrameCategoryEncoder.cc
lib/maths/CDataFrameUtils.cc
lib/maths/unittest/BoostedTreeTestData.cc
lib/maths/unittest/BoostedTreeTestData.h
lib/maths/unittest/CBoostedTreeLossTest.cc
lib/maths/unittest/CBoostedTreeUtilsTest.cc
lib/maths/unittest/Makefile

This selects trees with probability proportional to the total loss derivative for training examples for the leaves below each node. This tells you at least locally how much you can improve results by just adjusting the tree predictions (from their current values) and selecting this tree to retrain is analogous to gradient decent. I think however it makes sense to randomise selection since this is a heuristic and it gives us a simple way to refine: randomly sample from this distribution and choose the result which minimises the final training loss. This represents a relatively relatively simple to implement baseline strategy.
This also makes the necessary adjustments to not penalise changing predictions on the new training data. Since this could be out of domain of the original training …

[ML] Tree to retrain selection

---

build.gradle
dev-tools/aws_creds_from_vault.sh
dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_tester/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
dev-tools/docker/macosx_builder/Dockerfile
dev-tools/docker_build.sh
dev-tools/docker_test.sh
dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh
dev-tools/jenkins_cross_compile.sh
mk/toplevel.mk
set_env.sh

This is the first phase of a refactor that will eventually enable
the same Jenkins setup in elasticsearch-ci to run:
1. PR builds
2. Branch builds that cache artifacts for developers
3. Daily debug builds with assertions enabled
4. Builds for release to end users
A secondary goal is to speed up CI by spreading the build over
more servers.
In this first stage of the changes:
1. The extra options needed by debug builds and release builds are
passed through to the low level build commands
2. The cross compile steps are split into a separate build script,
which, eventually, will be run on a different server
Completing this project without lengthy ML CI downtime will
require a series of changes alternating between the ml-cpp repo
and the Jenkins configuration.  This is just the first step of …

[ML] Restructure Jenkins scripts

---

dev-tools/jenkins_ci.sh
dev-tools/jenkins_cross_compile.sh

This is a followup to #1835 that makes the scripts work
reliably nomatter where they are started from.

[ML] Make CI scripts independent of initial working directory

---

build.gradle
dev-tools/aws_creds_from_vault.sh
dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_tester/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
dev-tools/docker/macosx_builder/Dockerfile
dev-tools/docker_build.sh
dev-tools/docker_test.sh
dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh
dev-tools/jenkins_cross_compile.sh
mk/toplevel.mk
set_env.sh

This is the first phase of a refactor that will eventually enable
the same Jenkins setup in elasticsearch-ci to run:
1. PR builds
2. Branch builds that cache artifacts for developers
3. Daily debug builds with assertions enabled
4. Builds for release to end users
A secondary goal is to speed up CI by spreading the build over
more servers.
In this first stage of the changes:
1. The extra options needed by debug builds and release builds are
passed through to the low level build commands
2. The cross compile steps are split into a separate build script,
which, eventually, will be run on a different server
Completing this project without lengthy ML CI downtime will
require a series of changes alternating between the ml-cpp repo
and the Jenkins configuration.  This is just the first step of …

[7.x][ML] Restructure Jenkins scripts

---

build.gradle
dev-tools/aws_creds_from_vault.sh
dev-tools/docker/linux-musl_builder/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
dev-tools/docker/macosx_builder/Dockerfile
dev-tools/docker_build.sh
dev-tools/docker_test.sh
dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh
dev-tools/jenkins_cross_compile.sh
mk/toplevel.mk
set_env.sh

This is the first phase of a refactor that will eventually enable
the same Jenkins setup in elasticsearch-ci to run:
1. PR builds
2. Branch builds that cache artifacts for developers
3. Daily debug builds with assertions enabled
4. Builds for release to end users
A secondary goal is to speed up CI by spreading the build over
more servers.
In this first stage of the changes:
1. The extra options needed by debug builds and release builds are
passed through to the low level build commands
2. The cross compile steps are split into a separate build script,
which, eventually, will be run on a different server
Completing this project without lengthy ML CI downtime will
require a series of changes alternating between the ml-cpp repo
and the Jenkins configuration.  This is just the first step of …

[6.8][ML] Restructure Jenkins scripts

---

build.gradle
dev-tools/aws_creds_from_vault.sh
dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_tester/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
dev-tools/docker/macosx_builder/Dockerfile
dev-tools/docker_build.sh
dev-tools/docker_test.sh
dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh
dev-tools/jenkins_cross_compile.sh
mk/toplevel.mk
set_env.sh

This is the first phase of a refactor that will eventually enable
the same Jenkins setup in elasticsearch-ci to run:
1. PR builds
2. Branch builds that cache artifacts for developers
3. Daily debug builds with assertions enabled
4. Builds for release to end users
A secondary goal is to speed up CI by spreading the build over
more servers.
In this first stage of the changes:
1. The extra options needed by debug builds and release builds are
passed through to the low level build commands
2. The cross compile steps are split into a separate build script,
which, eventually, will be run on a different server
Completing this project without lengthy ML CI downtime will
require a series of changes alternating between the ml-cpp repo
and the Jenkins configuration.  This is just the first step of …

[7.12][ML] Restructure Jenkins scripts

---

dev-tools/jenkins_ci.sh

The changes of #1835 introduced a separate script for
cross compiling in Jenkins builds.  However, at that
time cross compiles still had to be done in the original
CI script too because Jenkins was not running the
dedicated script.
Now Jenkins _is_ running the dedicated script, and we
are in the situation where cross compiles are being done
twice for each build.  This PR tidies that up by making
jenkins_ci.sh dedicated to native compilation.
This should improve end-to-end build times.

[ML] Cross compile solely in dedicated script

---

dev-tools/jenkins_ci.sh

The changes of #1835 introduced a separate script for
cross compiling in Jenkins builds.  However, at that
time cross compiles still had to be done in the original
CI script too because Jenkins was not running the
dedicated script.
Now Jenkins _is_ running the dedicated script, and we
are in the situation where cross compiles are being done
twice for each build.  This PR tidies that up by making
jenkins_ci.sh dedicated to native compilation.
This should improve end-to-end build times.
Backport of #1844

[7.x][ML] Cross compile solely in dedicated script

---

dev-tools/jenkins_ci.sh
dev-tools/jenkins_cross_compile.sh

The changes of #1835 introduced a separate script for
cross compiling in Jenkins builds.  However, at that
time cross compiles still had to be done in the original
CI script too because Jenkins was not running the
dedicated script.
Now Jenkins _is_ running the dedicated script, and we
are in the situation where cross compiles are being done
twice for each build.  This PR tidies that up by making
jenkins_ci.sh dedicated to native compilation.
This should improve end-to-end build times.
Backport of #1844

[6.8][ML] Cross compile solely in dedicated script

---

docs/CHANGELOG.asciidoc
include/maths/CBoostedTreeImpl.h
lib/maths/CBoostedTreeImpl.cc

We were missing state used to adjust the loss function to select the best hyperparameters based on model size. This would sometimes cause us to select different hyperparameters if the modelling failed and was restarted during training.
Note that this already tested by `testRunBoostedTreeRegressionTrainingWithStateRecovery` but only fails if the change causes us to select a different model so this doesn't reliably fail.

[ML] Persist state for correcting loss to account for model size when training a boosted tree

---

docs/CHANGELOG.asciidoc
include/maths/CBoostedTreeImpl.h
lib/maths/CBoostedTreeImpl.cc

[7.13][ML] Persist state for correcting loss to account for model size when training a boosted tree

---

docs/CHANGELOG.asciidoc
lib/maths/CDataFrameUtils.cc
lib/maths/unittest/CBoostedTreeTest.cc

This explicitly checks we have enough data to even create a hold out set. This is a very weak condition and this isn't really enough data anyway, but before we could either throw (reserving collection with max size due to unsigned integer underflow) or hang (downsampling). This just adds an assertion at the point we create cross-validation row masks.

[ML] Gracefully handle insufficient training data for classification and regression model training

---

lib/model/unittest/CTokenListDataCategorizerTest.cc

At some point in the distant past there was a good reason
to enable trace logging in categorizer tests. Times have
changed and this is no longer a good idea:
1. We compile out trace logging when optimisation is
enabled, so it generally has no effect
2. When we do debug builds the extra logging generates
huge output files, which can blow Jenkins limits
In the future if somebody needs extra detailed logging
about categorization they can enable it manually on a
local test run.

[ML] Don't enable trace logging in categorizer tests

---

lib/model/unittest/CTokenListDataCategorizerTest.cc

At some point in the distant past there was a good reason
to enable trace logging in categorizer tests. Times have
changed and this is no longer a good idea:
1. We compile out trace logging when optimisation is
enabled, so it generally has no effect
2. When we do debug builds the extra logging generates
huge output files, which can blow Jenkins limits
In the future if somebody needs extra detailed logging
about categorization they can enable it manually on a
local test run.
Backport of #1856

[7.x][ML] Don't enable trace logging in categorizer tests

---

upload.gradle

This is another step towards moving the ML build in
release manager off of the Vagrant VMs and into the
standard elasticsearch-ci VMs.

[ML] Upload dependency report to S3 along with uber zip file

---

include/core/CDataFrame.h
include/test/CDataFrameAnalyzerTrainingFactory.h
lib/api/CDataFrameAnalyzer.cc
lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
lib/core/unittest/CDataFrameTest.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/CBoostedTreeLeafNodeStatistics.cc
lib/maths/CDataFrameUtils.cc
lib/maths/COutliers.cc
lib/maths/CTreeShapFeatureImportance.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/maths/unittest/CDataFrameUtilsTest.cc
lib/maths/unittest/COutliersTest.cc
lib/maths/unittest/CTreeShapFeatureImportanceTest.cc

This migrates the callback to read and write rows on a data frame to pass the iterators by constant reference. This generates clang-tidy warnings. Although the types are small and relatively a lot of work happens for each copy, each one is 64 bytes and there is no need to copy them.
I've marked as a non-issue because I don't think there is any need to document this change.

[ML] Pass row iterators by constant reference to callbacks

---

upload.gradle

This is another step towards moving the ML build in
release manager off of the Vagrant VMs and into the
standard elasticsearch-ci VMs.
Backport of #1861

[7.x][ML] Upload dependency report to S3 along with uber zip file

---

.dockerignore
.gitignore
docs/CHANGELOG.asciidoc
include/api/CInferenceModelMetadata.h
include/maths/CBoostedTreeUtils.h
include/test/CDataFrameAnalysisSpecificationFactory.h
include/test/CDataFrameAnalyzerTrainingFactory.h
lib/api/CInferenceModelMetadata.cc
lib/api/unittest/CInferenceModelMetadataTest.cc
lib/core/CLoopProgress.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/test/CDataFrameAnalysisSpecificationFactory.cc

We output max number trees as a hyperparameter in the model metadata and add a unit test to ensure that we achieve reproducible results when retraining a model with all hyperparameters specified.
Fixes #1853 .

[ML] Output max num trees in hyperparameters metadata

---

docs/CHANGELOG.asciidoc
include/maths/CMultivariateMultimodalPrior.h
lib/maths/CMultimodalPrior.cc

We were missing some checks that member state had been properly initialised to fail gracefully when restoring one of our model types for anomaly detection.
This also fixes a potential uninitialised variable problem (which generates a warning from clang), although would only happen for malformed state.

[ML] Fail gracefully on encountering unexpected state

---

lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc

Following on from #1867, we can and should be imposing the minimum depth constraint to the hyperparameter search bounding box. This was incorrectly applied before and also fixes the issue with reproducibility based on user overrides. This is a bit cleaner than applying the constraint magically in the code to adjust hyperparameters.

[ML] Apply tree depth constraint to hyperparameter search bounding box setup

---

.dockerignore
.gitignore
docs/CHANGELOG.asciidoc
include/api/CInferenceModelMetadata.h
include/maths/CBoostedTreeUtils.h
include/test/CDataFrameAnalysisSpecificationFactory.h
include/test/CDataFrameAnalyzerTrainingFactory.h
lib/api/CInferenceModelMetadata.cc
lib/api/unittest/CInferenceModelMetadataTest.cc
lib/core/CLoopProgress.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/test/CDataFrameAnalysisSpecificationFactory.cc

We output max number trees as a hyperparameter in the model metadata and add a unit test to ensure that we achieve reproducible results when retraining a model with all hyperparameters specified.
Backport of #1867 and #1870.

[7.x][ML] Output max num trees in hyperparameters metadata

---

.dockerignore
.gitignore
docs/CHANGELOG.asciidoc
include/api/CInferenceModelMetadata.h
include/maths/CBoostedTreeUtils.h
include/test/CDataFrameAnalysisSpecificationFactory.h
include/test/CDataFrameAnalyzerTrainingFactory.h
lib/api/CInferenceModelMetadata.cc
lib/api/unittest/CInferenceModelMetadataTest.cc
lib/core/CLoopProgress.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/test/CDataFrameAnalysisSpecificationFactory.cc

We output max number trees as a hyperparameter in the model metadata and add a unit test to ensure that we achieve reproducible results when retraining a model with all hyperparameters specified.
Backport of #1867 and #1870.

[7.13][ML] Output max num trees in hyperparameters metadata

---

.dockerignore
.gitignore
docs/CHANGELOG.asciidoc
include/api/CInferenceModelMetadata.h
include/maths/CBoostedTreeUtils.h
include/test/CDataFrameAnalysisSpecificationFactory.h
include/test/CDataFrameAnalyzerTrainingFactory.h
lib/api/CInferenceModelMetadata.cc
lib/api/unittest/CInferenceModelMetadataTest.cc
lib/core/CLoopProgress.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/test/CDataFrameAnalysisSpecificationFactory.cc

We output max number trees as a hyperparameter in the model metadata and add a unit test to ensure that we achieve reproducible results when retraining a model with all hyperparameters specified.
Fixes #1853 .
Backport of #1867 and #1870.

[7.12][ML] Output max num trees in hyperparameters metadata

---

include/api/CDataFrameTrainBoostedTreeRunner.h
include/maths/CBoostedTree.h
include/maths/CBoostedTreeFactory.h
include/test/CDataFrameAnalyzerTrainingFactory.h
jupyter/notebooks/utils/misc.py
lib/api/CBoostedTreeInferenceModelBuilder.cc
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/CDataSummarizationJsonSerializer.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/test/CDataFrameAnalysisSpecificationFactory.cc
lib/test/CDataFrameAnalyzerTrainingFactory.cc

This PR introduces a new task "predict" to initialize a trained model and use it only for predicting a new dataset, without updating the model itself. To this end, I implement a new factory method `CBoostedTreeFactory::buildForPredict` that handles the task-specific boosted tree generation.
This also enables us to reactivate the invariance checks, that were temporarily disabled.
I faced the problem of mapping the features from the model definition back to the encoded columns. To fix it temporarily, I deactivated the removal of unused features when the model definition is generated. However, since it is incompatible with our current model definition schema, we still need to properly fix it. I created #1869 to have a reminder.
Closes #1811.

[ML] Prediction task

---

docs/CHANGELOG.asciidoc

One PR that went into 7.13.0 was listed under 7.12.1
and another that went into 7.13.0 was duplicated under
7.12.1.

[ML] Fixing 7.12.1 and 7.13.0 changelogs

---

lib/api/CLengthEncodedInputParser.cc

When we flush the input stream the java side writes
enough spaces to fill the input stream buffer.
However, in the case of data frame analytics, this may
cause the job to freeze. The reason is that java
writes the data and flushes in the same thread that
goes on to then restore the state. However, when
c++ reads in the end-of-data control message, it stops
reading from the stream and goes on to perform the analysis.
If the 8KB of spaces do not fit in the OS buffer for the
names pipe, the java side blocks. It never proceeds with
restoring the state and this causes a job that is
being restarted and has state to freeze.
This commit reduces the buffer to 2KB. This means the
buffer is smaller than the buffer of all supported OS.
Note that it is 4KB on Windows. I have performed
a test to assess …

[ML] Reduce input stream buffer from 8KB to 2KB

---

lib/api/CLengthEncodedInputParser.cc

When we flush the input stream the java side writes
enough spaces to fill the input stream buffer.
However, in the case of data frame analytics, this may
cause the job to freeze. The reason is that java
writes the data and flushes in the same thread that
goes on to then restore the state. However, when
c++ reads in the end-of-data control message, it stops
reading from the stream and goes on to perform the analysis.
If the 8KB of spaces do not fit in the OS buffer for the
names pipe, the java side blocks. It never proceeds with
restoring the state and this causes a job that is
being restarted and has state to freeze.
This commit reduces the buffer to 2KB. This means the
buffer is smaller than the buffer of all supported OS.
Note that it is 4KB on Windows. I have performed
a test to assess …

[7.x][ML] Reduce input stream buffer from 8KB to 2KB (#1881)

---

lib/api/CLengthEncodedInputParser.cc

When we flush the input stream the java side writes
enough spaces to fill the input stream buffer.
However, in the case of data frame analytics, this may
cause the job to freeze. The reason is that java
writes the data and flushes in the same thread that
goes on to then restore the state. However, when
c++ reads in the end-of-data control message, it stops
reading from the stream and goes on to perform the analysis.
If the 8KB of spaces do not fit in the OS buffer for the
names pipe, the java side blocks. It never proceeds with
restoring the state and this causes a job that is
being restarted and has state to freeze.
This commit reduces the buffer to 2KB. This means the
buffer is smaller than the buffer of all supported OS.
Note that it is 4KB on Windows. I have performed
a test to assess …

[7.13][ML] Reduce input stream buffer from 8KB to 2KB (#1881)

---

lib/api/CLengthEncodedInputParser.cc

When we flush the input stream the java side writes
enough spaces to fill the input stream buffer.
However, in the case of data frame analytics, this may
cause the job to freeze. The reason is that java
writes the data and flushes in the same thread that
goes on to then restore the state. However, when
c++ reads in the end-of-data control message, it stops
reading from the stream and goes on to perform the analysis.
If the 8KB of spaces do not fit in the OS buffer for the
names pipe, the java side blocks. It never proceeds with
restoring the state and this causes a job that is
being restarted and has state to freeze.
This commit reduces the buffer to 2KB. This means the
buffer is smaller than the buffer of all supported OS.
Note that it is 4KB on Windows. I have performed
a test to assess …

[7.12][ML] Reduce input stream buffer from 8KB to 2KB (#1881)

---

include/core/CStoredStringPtr.h
lib/core/CStoredStringPtr.cc
lib/model/unittest/CStringStoreTest.cc

We have seen numerous failures of CStringStoreTest.testStringStore
caused by pruning not working as it should.
These failures invariably occur on aarch64 (both Mac and Linux).
The problem is that the pruning relies on std::shared_ptr::unique()
and this is not accurate. (In fact C++20 removes this method.)
The reason it's not accurate is that it returns the usage count
in a relaxed manner, i.e. returning the last value visible to the
current thread, but not forcing a resync between threads first.
The x86 architecture is more forgiving of theoretical memory
ordering bugs like this than the aarch64 architecture.
The solution is to change the use count in the thread that's
checking its value to be sure that this thread has accurate
visibility of the value.  Obviously this is inefficient, so …

[ML] Fix CStringStore unit test

---

docs/CHANGELOG.asciidoc
lib/model/CStringStore.cc
lib/model/unittest/CStringStoreTest.cc

Decrementing the write count with a relaxed memory order
on aarch64 can result in other threads not noticing for
a very long time.  Instead the "release" memory order
needs to be used.  (As we never saw this problem on x86
I suspect this is a case of us taking advantage of
atomics on x86 offering better synchronization than
required by the language constructs.)
Followup to #1887
Fixes #1885

[ML] Sync writing atomic more strongly in CStringStore

---

include/core/CStoredStringPtr.h
lib/core/CStoredStringPtr.cc
lib/model/unittest/CStringStoreTest.cc

We have seen numerous failures of CStringStoreTest.testStringStore
caused by pruning not working as it should.
These failures invariably occur on aarch64 (both Mac and Linux).
The problem is that the pruning relies on std::shared_ptr::unique()
and this is not accurate. (In fact C++20 removes this method.)
The reason it's not accurate is that it returns the usage count
in a relaxed manner, i.e. returning the last value visible to the
current thread, but not forcing a resync between threads first.
The x86 architecture is more forgiving of theoretical memory
ordering bugs like this than the aarch64 architecture.
The solution is to change the use count in the thread that's
checking its value to be sure that this thread has accurate
visibility of the value.  Obviously this is inefficient, so …

[7.13][ML] Fix CStringStore unit test

---

include/core/CStoredStringPtr.h
lib/core/CStoredStringPtr.cc
lib/model/unittest/CStringStoreTest.cc

We have seen numerous failures of CStringStoreTest.testStringStore
caused by pruning not working as it should.
These failures invariably occur on aarch64 (both Mac and Linux).
The problem is that the pruning relies on std::shared_ptr::unique()
and this is not accurate. (In fact C++20 removes this method.)
The reason it's not accurate is that it returns the usage count
in a relaxed manner, i.e. returning the last value visible to the
current thread, but not forcing a resync between threads first.
The x86 architecture is more forgiving of theoretical memory
ordering bugs like this than the aarch64 architecture.
The solution is to change the use count in the thread that's
checking its value to be sure that this thread has accurate
visibility of the value.  Obviously this is inefficient, so …

[7.x][ML] Fix CStringStore unit test

---

docs/CHANGELOG.asciidoc
lib/model/CStringStore.cc
lib/model/unittest/CStringStoreTest.cc

Decrementing the write count with a relaxed memory order
on aarch64 can result in other threads not noticing for
a very long time.  Instead the "release" memory order
needs to be used.  (As we never saw this problem on x86
I suspect this is a case of us taking advantage of
atomics on x86 offering better synchronization than
required by the language constructs.)
Backport of #1888

[7.x][ML] Sync writing atomic more strongly in CStringStore

---

docs/CHANGELOG.asciidoc
lib/model/CStringStore.cc
lib/model/unittest/CStringStoreTest.cc

Decrementing the write count with a relaxed memory order
on aarch64 can result in other threads not noticing for
a very long time.  Instead the "release" memory order
needs to be used.  (As we never saw this problem on x86
I suspect this is a case of us taking advantage of
atomics on x86 offering better synchronization than
required by the language constructs.)
Backport of #1888

[7.13][ML] Sync writing atomic more strongly in CStringStore

---

docs/CHANGELOG.asciidoc
include/maths/CIntegration.h
lib/model/CStringStore.cc

This PR is a followup to #1888 which makes one more relaxed
store of an atomic variable in the CStringStore class use
release memory ordering rather than relaxed.
Additionally, a relaxed load is changed to use acquire memory
ordering in the CIntegration class.
These changes only have an effect on the aarch64 architecture.
Relates #1885

[ML] Make atomic operations safer for aarch64

---

include/api/CDataFrameAnalysisRunner.h
include/api/CDataFrameTrainBoostedTreeRunner.h
include/api/CDataSummarizationJsonSerializer.h
lib/api/CDataFrameAnalysisRunner.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/CDataSummarizationJsonSerializer.cc
lib/api/unittest/CDataSummarizationJsonSerializerTest.cc

If fields are missing or the type doesn't match then rapidjson accessors result in undefined behaviour when compiled in release mode. We do not trust our state document and so need to verify that every field we expect exists and has the appropriate type. In the retrainable model state we were not reliably doing this. In this change I migrate to wrap all accessors in methods which check that both the fields exist and their type is correct. I also renamed the classes to match naming the names used for similar classes in the api library.

[ML] Improve error checking when reading trainable model

---

include/api/CDataSummarizationJsonSerializer.h
include/api/CInferenceModelDefinition.h
include/api/CSerializableToJson.h
lib/api/CDataFrameAnalyzer.cc
lib/api/CDataSummarizationJsonSerializer.cc
lib/api/CInferenceModelDefinition.cc
lib/api/CSerializableToJson.cc
lib/api/unittest/CSerializableToJsonTest.cc
lib/api/unittest/Makefile

Currently, we write large state documents out chunked but then only try and read the first chunk when restoring for incremental training. This means if our compressed state exceeds the maximum document size we fail to restore.
This change introduces a new `CSerializableFromCompressedChunkedJson` class which dechunks the compressed state into a temporary buffer. We expand this stream as we read it, so provided we read one document at a time (there is an enhancement for this), then the memory overhead is small if the compression factor is large, which it is.
I also took the opportunity to avoid all the temporary copies of compressed state by reading directly into a char array and then using pointers into this array to initialise the `rapidjson::String` objects during persist.
Fixes #1849.

[ML] Read summarisation and model from chunked state

---

bin/pytorch_inference/Main.cc

Tensors are read via `accessors` which have template parameters type (float, int, etc) and a dimension count. If the type or dimension is wrong the accessor will throw. Previously the only support type was a hard coded float, this change inspects the underlying tensor type and will either create a `double` or `float32` accessor. If the tensor is not one of those types an error is returned.

[ML] Improve robustness of tensor result processing

---

include/api/CDataFrameAnalysisRunner.h
include/api/CDataSummarizationJsonTags.h
include/api/CDataSummarizationJsonWriter.h
include/api/CRetrainableModelJsonReader.h
lib/api/CDataFrameAnalysisRunner.cc
lib/api/CDataFrameAnalyzer.cc
lib/api/CDataFrameOutliersRunner.cc
lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/CDataSummarizationJsonTags.cc
lib/api/CDataSummarizationJsonWriter.cc
lib/api/CRetrainableModelJsonReader.cc
lib/api/Makefile.first
lib/api/unittest/CDataFrameMockAnalysisRunner.cc
lib/api/unittest/CDataSummarizationJsonSerializerTest.cc

This implements the delayed suggestion in #1894 to split up the file containing the data summarisation writing and the retrainable model reading.

[ML] Split data summarisation writing and retrainable model reading

---

docs/CHANGELOG.asciidoc
lib/model/CCountingModel.cc

Fix a bug where calls to calculate the current bucket count for simple count
models always failed to return a value when the bucket span was one
second.
fixes #1908

[ML] Compute bucket counts for 1s bucket spans

---

docs/CHANGELOG.asciidoc
lib/model/CCountingModel.cc

Fix a bug where calls to calculate the current bucket count for simple count
models always failed to return a value when the bucket span was one
second.
Backports #1909

[7.x][ML] Compute bucket counts for 1s bucket spans (#1909)

---

include/maths/CBoostedTreeLeafNodeStatistics.h
include/maths/CBoostedTreeUtils.h
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/CBoostedTreeLeafNodeStatistics.cc
lib/maths/CBoostedTreeUtils.cc
lib/maths/unittest/CBoostedTreeTest.cc

This builds out the unit testing of incremental training QoR and fixes the bugs in:
1. The initialisation of the loss derivatives,
2. The initialisation of the predictions and previous predictions,
3. The value of `eta` to use for the retrained tree.
We also need to ensure that the feature bag includes the features used in the original tree so we can make the same choice again if it is appropriate.
(The test is still WIP, but I think there are enough fixes in this PR to be worthwhile pushing, so it doesn't hold up evaluation on real data sets.)

[ML] Improve incremental training test coverage

---

include/core/CImmutableRadixSet.h
include/maths/CBoostedTreeImpl.h
include/maths/CBoostedTreeLoss.h
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/CBoostedTreeLeafNodeStatisticsIncremental.cc
lib/maths/CBoostedTreeLoss.cc
lib/maths/unittest/CBoostedTreeLossTest.cc
lib/maths/unittest/CBoostedTreeTest.cc

This finishes up testing incremental training for MSE. It also fixes bugs in
1. The calculation of the penalty for changing the tree
2. The calculation of the candidate splits (which need the loss derivatives to be calculated first)
3. The tree leaf values, which were being computed after removing the next tree to retrain predictions
We should also have been persisting the new training data row mask for failover and I've unified some train and incremental train code by always filling in the new training data row mask.
Finally, a failing unit test showed up some improvements to make to the approach to minimise the incremental logistic loss. In particular, the term due to the cross-entropy between the old and new tree predictions can be treated completely independently from the term due to …

[ML] Finish up testing of incremental training with MSE loss

---

mk/linux.mk
mk/linux_crosscompile_linux.mk

#1933 shows that libnsl is no longer present on newer Linux distributions. The library should not be required on Linux as we do not use the networking functions.
This change makes setting `USE_NET=1` in a makefile a no-op for Linux and macOS, on Windows `WS2_32.lib` is linked (for the network to host byte order functions in one case). 
Closes #1933

[ML] Don't link libnsl on Linux when USE_NET is defined

---

include/api/CDataSummarizationJsonTags.h
include/api/CInferenceModelMetadata.h
jupyter/notebooks/utils/misc.py
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
lib/api/CDataSummarizationJsonTags.cc
lib/api/CInferenceModelMetadata.cc
lib/api/unittest/CInferenceModelMetadataTest.cc
lib/api/unittest/testfiles/model_meta_data/model_meta_data.schema.json

We write a number of rows in data summarization as a part of model metadata. This helps to estimate the correct number of rows for incremental learning.

[ML] Data summarization num rows in model metadata

---

bin/pytorch_inference/Main.cc
bin/pytorch_inference/evaluate.py

Adds a stopwatch timer and records the time in milliseconds for each inference call. The time is reported back in the result document. 
The total round trip time for an inference API call will also be of interest but this measure eliminates the vagaries of network overhead by being as close as possible to the libtorch call.

[ML] Time inference calls in the pytorch app

---

bin/autodetect/CCmdLineParser.cc
bin/autodetect/CCmdLineParser.h
bin/autodetect/Main.cc
bin/categorize/CCmdLineParser.cc
bin/categorize/CCmdLineParser.h
bin/categorize/Main.cc
bin/data_frame_analyzer/CCmdLineParser.cc
bin/data_frame_analyzer/CCmdLineParser.h
bin/data_frame_analyzer/Main.cc
bin/normalize/CCmdLineParser.cc
bin/normalize/CCmdLineParser.h
bin/normalize/Main.cc
bin/pytorch_inference/CCmdLineParser.cc
bin/pytorch_inference/CCmdLineParser.h
bin/pytorch_inference/Main.cc

All ml-cpp binaries (except controller) now must have '--validElasticLicenseKeyConfirmed=true' present in the command line arguments in order to run. Failure to do so will result in the binary to exit with an appropriate error message.

[ML] Add validElasticLicenseKeyConfirmed command line arg to ml-cpp binaries

---

bin/autodetect/CCmdLineParser.cc
bin/autodetect/CCmdLineParser.h
bin/autodetect/Main.cc
bin/categorize/CCmdLineParser.cc
bin/categorize/CCmdLineParser.h
bin/categorize/Main.cc
bin/data_frame_analyzer/CCmdLineParser.cc
bin/data_frame_analyzer/CCmdLineParser.h
bin/data_frame_analyzer/Main.cc
bin/normalize/CCmdLineParser.cc
bin/normalize/CCmdLineParser.h
bin/normalize/Main.cc

All ml-cpp binaries (except controller) now must have
'--validElasticLicenseKeyConfirmed=true' present in the
command line arguments in order to run. Failure to do so
will result in the binary to exit with an appropriate error message.
In order to keep integration tests happy, the default
value of the validElasticLicenseKeyConfirmed command line argument
is  temporarily set to `false`.
Backports #1944

[ML] Add validElasticLicenseKeyConfirmed command line arg to ml-cpp binaries (#1944)

---

include/api/CDataFrameTrainBoostedTreeRunner.h
include/maths/CBoostedTreeFactory.h
include/maths/CBoostedTreeHyperparameters.h
include/maths/CBoostedTreeImpl.h
include/maths/CBoostedTreeUtils.h
include/maths/CDataFrameAnalysisInstrumentationInterface.h
lib/api/CDataFrameAnalysisInstrumentation.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/CInferenceModelMetadata.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeHyperparameters.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc

The best shrinkage to use for trees we retrain is not expected to match that for train. The incremental loss function already builds in a mechanism for keeping the weights small by penalising the difference in predictions from the old tree. Furthermore, since we retrain fewer trees than we train it is likely that we need less shrinkage in order to impact the new training data loss sufficiently. Testing on both target drift and out of training domain scenarios shows that computing the best shrinkage by cross-validation and searching a wide range up to and including no shrinkage gives *greatly* improved QoR. This also adds new unit tests for out of training domain data and incremental binomial logistic regression.

[ML] Compute retrained tree weight shrinkage by cross-validation

---

bin/pytorch_inference/evaluate.py

When launching the pytorch app from `evaluate.py` pass `--validElasticLicenseKeyConfirmed=true` as required by #1944

[ML][PYTORCH] Pass --validElasticLicenseKeyConfirmed argument from evaluate.py

---

lib/maths/CBoostedTreeImpl.cc

We can exit hyperparameter tuning early if we don't think we're making progress up to the estimation error in the validation loss. Currently, we report that we do this but not which round we stopped. This decision is a candidate for causing variation in our QoR from run to run in our QA suite, but since we don't output which round we actually stopped we can't tell. Here I update the logging to report exactly which round we exit on.

[ML] Add logging so we know which round we exited hyperparameter tuning

---

lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/maths/CBoostedTreeFactory.cc

Since we don't store class weights, we must recompute them explicitly before performing the prediction task.

[ML] Recompute class weights before prediction task

---

include/api/CDataFrameAnalysisInstrumentation.h
include/api/CDataFrameTrainBoostedTreeRunner.h
include/api/CInferenceModelMetadata.h
include/core/CDataFrame.h
include/maths/CBoostedTree.h
include/maths/CBoostedTreeFactory.h
include/maths/CBoostedTreeImpl.h
include/maths/CDataFrameAnalysisInstrumentationInterface.h
include/maths/CDataFramePredictiveModel.h
include/test/CDataFrameAnalysisSpecificationFactory.h
lib/api/CDataFrameAnalysisInstrumentation.cc
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/CInferenceModelMetadata.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/api/unittest/testfiles/model_meta_data/model_meta_data.schema.json
lib/core/CDataFrame.cc
lib/core/unittest/CDataFrameTest.cc
lib/maths/CBoostedTree.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/test/CDataFrameAnalysisSpecificationFactory.cc

When we decide whether to accept the results of incremental training we compare the loss calculated for the best candidate with the loss calculated for the original model. Since the data summary comprises a subset of the training data we are in effect comparing training error on old data + validation error on new training data with something closer to validation error on all data. If we don't have much new data, or the improvement we can make on it is small, this typically causes us to reject models which actually perform better in test.
This pull request records the gap between the train and validation loss on the old training data and adds it on to the threshold to accept. This is recorded in the model meta data and needs to be added to the configuration parameters when Java calls …

[ML] Correct acceptance criterion for incremental training

---

docs/CHANGELOG.asciidoc
include/maths/CBoostedTreeImpl.h
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/CDataFrameUtils.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/maths/unittest/CDataFrameUtilsTest.cc

This makes two changes to deal better with small data sets highlighted by a failure in our QA suite as a result of #1941. In particular,
1. We could miss out rare classes altogether from our validation set for small data sets.
2. We can lose a lot of accuracy by over restricting the number of features we use for small data sets.
Problem 1 is a result of the stratified sampling we perform. If a class is rare and data set is small we could choose never to sample it in the validation set because it could constitute fewer than one example per fold. In this case, the fraction of each class is changing significantly in the remaining unsampled set for each fold we sample, but we compute the desired class counts once upfront based on their overall frequency. We simply need to recompute desired …

[ML] Improve regression and classification QoR for small data sets

---

CONTRIBUTING.md

We plan to rename the master branch to main in the
ml-cpp repo.
The contributing guide mentioned the master branch
in numerous places.  This updates it to talk about
main instead.
(There are also a few other files in this repo that
mention the master branch, but in the context of
other repos.  As those other repos rename master to
main we will have to follow up with further renames
within the ml-cpp repo.)

[ML] Preparation for renaming master branch to main

---

gradle/wrapper/gradle-wrapper.properties

Updates Gradle to the same version Elasticsearch uses.
For #1963

[ML] Upgrade Gradle wrapper to 7.1.1

---

build.gradle
dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh
dev-tools/jenkins_cross_compile.sh

Gradle has deprecated the -b option, which means that we
cannot continue to split functionality between build.gradle
and upload.gradle in the long term.
This PR starts the combination process by adding the tasks
from upload.gradle into build.gradle.
The PR does _not_ remove upload.gradle, as it is referenced
by CI jobs.  The overall change needs to be done as a
multi-stage process, first adding functionality to
build.gradle, then updating CI jobs, and finally removing
the upload.gradle file.
Fixes one more deprecation identified in #1963

[ML] Adding upload tasks to build.gradle

---

build.gradle
dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh
dev-tools/jenkins_cross_compile.sh

Gradle has deprecated the -b option, which means that we
cannot continue to split functionality between build.gradle
and upload.gradle in the long term.
This PR starts the combination process by adding the tasks
from upload.gradle into build.gradle.
The PR does _not_ remove upload.gradle, as it is referenced
by CI jobs.  The overall change needs to be done as a
multi-stage process, first adding functionality to
build.gradle, then updating CI jobs, and finally removing
the upload.gradle file.
Backport of #1970

[7.x] [ML] Adding upload tasks to build.gradle

---

3rd_party/3rd_party.sh

Previously PyTorch libraries were only included in
native builds.  This was a mistake.
Fixes elastic/elasticsearch#75685

[ML] Include PyTorch libraries in cross-compiled builds

---

build.gradle

After the changes of #1970 we get an instant failure when
building ml-cpp as part of the ES build by putting it under
elasticsearch-extra.
This change makes importing UploadS3Task and the tasks of
that type conditional on ml-cpp being standalone.

[ML] S3 upload task isn't available when embedded in ES build

---

build.gradle

After the changes of #1970 we get an instant failure when
building ml-cpp as part of the ES build by putting it under
elasticsearch-extra.
This change makes importing UploadS3Task and the tasks of
that type conditional on ml-cpp being standalone.
Backport of #1975

[7.x] [ML] S3 upload task isn't available when embedded in ES build

---

include/api/CDataSummarizationJsonTags.h
include/api/CDataSummarizationJsonWriter.h
include/api/CRetrainableModelJsonReader.h
include/api/CSerializableToJson.h
include/maths/CBoostedTreeLeafNodeStatisticsIncremental.h
include/maths/CBoostedTreeLeafNodeStatisticsScratch.h
jupyter/src/incremental_learning/misc.py
lib/api/CDataSummarizationJsonTags.cc
lib/api/CDataSummarizationJsonWriter.cc
lib/api/CRetrainableModelJsonReader.cc
lib/api/CSerializableToJson.cc
lib/api/unittest/CDataSummarizationJsonSerializerTest.cc
lib/api/unittest/CSerializableToJsonTest.cc
lib/maths/CBoostedTreeLeafNodeStatisticsIncremental.cc
lib/maths/CBoostedTreeLeafNodeStatisticsScratch.cc
lib/maths/unittest/BoostedTreeTestData.cc
lib/maths/unittest/BoostedTreeTestData.h
lib/maths/unittest/CBoostedTreeTest.cc
lib/maths/unittest/CBoostedTreeUtilsTest.cc

Applies #1952 to the feature branch.

[ML] Switch ml-cpp repo to Elastic License 2.0 on incremental training branch

---

docs/CHANGELOG.asciidoc
include/api/CAnomalyJob.h
include/api/CAnomalyJobConfig.h
include/model/CAnomalyDetector.h
include/model/CAnomalyDetectorModelConfig.h
include/model/FunctionTypes.h
lib/api/CAnomalyJob.cc
lib/api/CAnomalyJobConfig.cc
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/model/CAnomalyDetector.cc
lib/model/CAnomalyDetectorModelConfig.cc
lib/model/FunctionTypes.cc

Prune models (excluding for functions rare, freq_rare, time_of_day, time_of_week, lat_long) that haven't seen data updates for a
given period of time.
The window of time over which to prune is supplied in the `model_prune_window` field, which is an optional field in the job's `analysis_config` configuration. If not present no aggressive pruning is performed, no default value is used. However, the `bucket_span` value is used as a minimum value for the `model_prune_window` i.e. if the provided `model_prune_window` value is smaller than the `bucket_span` then the value of the `bucket_span` is used instead.

[ML] Aggressively prune dead split fields

---

docs/CHANGELOG.asciidoc

Somehow two sections for version 7.15 exist in the changelog. This
consolidates then to a single section.

[ML] Fix multiple 7.15 entries in changelog

---

docs/CHANGELOG.asciidoc
include/api/CAnomalyJob.h
include/api/CAnomalyJobConfig.h
include/model/CAnomalyDetector.h
include/model/CAnomalyDetectorModelConfig.h
include/model/FunctionTypes.h
lib/api/CAnomalyJob.cc
lib/api/CAnomalyJobConfig.cc
lib/api/unittest/CAnomalyJobConfigTest.cc
lib/model/CAnomalyDetector.cc
lib/model/CAnomalyDetectorModelConfig.cc
lib/model/FunctionTypes.cc

Prune models (excluding for functions rare, freq_rare, time_of_day,
time_of_week, lat_long) that haven't seen data updates for a
given period of time.
Backports #1962

[7.x][ML] Aggressively prune dead split fields (#1962)

---

CONTRIBUTING.md

The --include-build option replaces elasticsearch-extra
as the approved mechanism for testing ml-cpp and
elasticsearch changes together.

[ML] Adding --include-build docs

---

CONTRIBUTING.md

The --include-build option replaces elasticsearch-extra
as the approved mechanism for testing ml-cpp and
elasticsearch changes together.
Backport of #1979

[7.x] [ML] Adding --include-build docs

---

include/maths/CModel.h
include/model/CAnomalyDetector.h
include/model/CAnomalyDetectorModel.h
include/model/CCountingModel.h
include/model/CEventRatePopulationModel.h
include/model/CIndividualModel.h
include/model/CMetricPopulationModel.h
lib/api/CAnomalyJob.cc
lib/api/unittest/CStringStoreTest.cc
lib/maths/CModel.cc
lib/model/CAnomalyDetector.cc
lib/model/CAnomalyDetectorModel.cc
lib/model/CEventRatePopulationModel.cc
lib/model/CIndividualModel.cc
lib/model/CMetricPopulationModel.cc
lib/model/unittest/Mocks.cc
lib/model/unittest/Mocks.h

Pruning may result in a situation where all the feature models of a detector are effectively empty. This presents an opportunity to reclaim memory by way of excluding such a detector from the persisted state, as on restoration the detector will no longer be present.
Labelling as `<non-issue` as the only observable change of this PR is a potential reduction in model memory size following a persist/restore cycle.
Relates #1962

[ML] Do not persist detectors with only empty models

---

include/maths/CModel.h
include/model/CAnomalyDetector.h
include/model/CAnomalyDetectorModel.h
include/model/CCountingModel.h
include/model/CEventRatePopulationModel.h
include/model/CIndividualModel.h
include/model/CMetricPopulationModel.h
lib/api/CAnomalyJob.cc
lib/api/unittest/CStringStoreTest.cc
lib/maths/CModel.cc
lib/model/CAnomalyDetector.cc
lib/model/CAnomalyDetectorModel.cc
lib/model/CEventRatePopulationModel.cc
lib/model/CIndividualModel.cc
lib/model/CMetricPopulationModel.cc
lib/model/unittest/Mocks.cc
lib/model/unittest/Mocks.h

Pruning may result in a situation where all the feature models of a
detector are effectively empty. This presents an opportunity to reclaim
memory by way of excluding such a detector from the persisted state, as
on restoration the detector will no longer be present.
Backports #1986

[7.x][ML] Do not persist detectors with only empty models (#1986)

---

docs/CHANGELOG.asciidoc
include/maths/CBoostedTreeImpl.h
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/CDataFrameUtils.cc
lib/maths/unittest/CBoostedTreeTest.cc
lib/maths/unittest/CDataFrameUtilsTest.cc

[7.x][ML] Improve regression and classification QoR for small data sets

---

lib/maths/unittest/CBoostedTreeTest.cc

This test has failed for me in a back port and also a couple of times in pull requests builds. It depends on timing and so I make it more robust and incidentally test assertions in more cases, which should improve coverage slightly.
(Note that since a version of this is already committed to 7.x there is no need to back port.)

[ML] Improve test robustness

---

docs/CHANGELOG.asciidoc
lib/maths/CBoostedTreeLeafNodeStatistics.cc

The issue was caused by a mismatch in the condition to decide whether to split the root node and the condition to decide whether to bother to initialise all its state. In particular, we would, if we got very unlucky, try and split having not properly initialised state. This updates the offending condition so we always properly initialise state when we're going to try and split. (There was also a typo this fixes.)
Closes #1956.

[ML] Fix potential undefined behaviour in classification and regression training

---

jupyter/Makefile
jupyter/README.md
jupyter/data/configs/boston.json
jupyter/data/configs/ccpp.json
jupyter/data/configs/classification-2d.json
jupyter/scripts/incremental_learning/experiment_driver.py
jupyter/scripts/incremental_learning/experiments.json
jupyter/scripts/incremental_learning/generate_experiment_matrix.py
jupyter/scripts/incremental_learning/transform_templates.json
jupyter/src/incremental_learning/config.py
jupyter/src/incremental_learning/transforms.py
jupyter/template_config.ini
jupyter/tests/incremental_learning/test_transforms.py

This adds a script to generate random test cases from the full test matrix which comprises our target data sets and transforms. It also makes configuration of various directories more robust to different layouts and usage (for example it didn't work properly after installing the `incremental_learning` package using `setup.py` previously). I also changed transform to always copy the data set before transforming (this fits in better with `experiment_driver.py`) and made variable naming more consistent. Finally, this finishes up the implementation of `experiment_driver.py` to support all transform types.
The full experiments.json configuration file will added be a separate PR which migrates the data sets in this repo to our cloud bucket.

[ML] Scripting to generate full incremental training test matrix

---

build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_image/Dockerfile

As announced in https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html
Backport of #2004

[ML] Update boost download URL

---

bin/pytorch_inference/Main.cc

From the debug logging added in #2003 it is clear the input size is not being initialised correctly
`input size: [4354725592, 140222092279815]`
This change ensures the initialiser list ctor is called

[ML] Ensure initialiser list ctor is used

---

bin/pytorch_inference/Main.cc

Use a local var with same lifespan.
I've left the debug logging in place while this is tested and will clean it up once the tests have passed.

[ML] Fix invalid reference when initialising input sizes

---

include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
lib/maths/CDataFrameUtils.cc

An error in the transforms was causing us to generate spurious classes in the transformed data set. This showed up we weren't properly validating the input and in fact failed by SIGSEGV in this case. I've update the validate method to check the data is consistent with the config and also put in explicit protection at the point where we got the undefined behaviour.

[ML] Cleanly handle mismatch in the classification config num_classes and the number classes in the data

---

jupyter/src/.bumpversion.cfg
jupyter/src/incremental_learning/__init__.py
jupyter/src/incremental_learning/config.py
jupyter/src/incremental_learning/job.py
jupyter/src/incremental_learning/storage.py
jupyter/src/setup.py
jupyter/tests/incremental_learning/test_store_restore.py

This PR adds functionality to store and restore training jobs. It mainly requires storing the model blob object, but other metadata like `input_filename`, `dependent_variable`, `analysis_name` are also stored for completeness.  Jobs are stored as gzipped JSON files.
The job can be stored with 
```python
job.store(destination=local_path)
```
and restored with 
```python
job = Job.fromFile(source=local_path)
```
See unit tests in `test_store_restore.py` for more examples.
Furthermore, I implemented functionality to upload, download and delete job files in the Google storage bucket.

[ML] Store and restore training jobs with  models

---

jupyter/src/.bumpversion.cfg
jupyter/src/incremental_learning/__init__.py
jupyter/src/incremental_learning/job.py
jupyter/src/setup.py

This is a minor changes that adds the stderr output from the `data_frame_analyzer` run to the logs of the SACRED run object.

[ML] Output logs from data_frame_analyzer

---

jupyter/src/.bumpversion.cfg
jupyter/src/incremental_learning/__init__.py
jupyter/src/incremental_learning/job.py
jupyter/src/setup.py

When the training job fails, we want the failure to propagate through the Python framework to mark the experiment as failed.

[ML] Raise runtime error when C++ process fails

---

jupyter/src/.bumpversion.cfg
jupyter/src/incremental_learning/__init__.py
jupyter/src/incremental_learning/job.py
jupyter/src/setup.py
jupyter/tests/incremental_learning/test_classification.py

This PR extends Job functionality with an ability to return prediction probabilities for label "true" for binary classification. This is important for the computation of ROC AUC.

[ML] Obtain prediction probabilities

---

include/api/CDataFrameTrainBoostedTreeRunner.h
include/maths/CBoostedTreeFactory.h
include/maths/CBoostedTreeImpl.h
jupyter/scripts/incremental_learning/experiment_driver.py
jupyter/scripts/incremental_learning/job_submitter.py
jupyter/src/incremental_learning/job.py
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/maths/CBoostedTreeFactory.cc
lib/maths/CBoostedTreeImpl.cc

Currently, we assess whether we think that incremental training will reduce loss vs the original model before committing the change. This relies on us being able to accurately estimate the test error for the original model. I've run into cases where we seem to significantly underestimate this on the transformed data we simulate in our test framework. It isn't clear why this is happening: I'm still investigating. However, it is also convenient to simply force accept the best change we found, both for test and also as a user (if one can assess model generalisation error independently). This adds the option and a parameter to the test framework.

[ML] Add an option to force update the model

---

jupyter/src/.bumpversion.cfg
jupyter/src/incremental_learning/__init__.py
jupyter/src/incremental_learning/job.py
jupyter/src/setup.py
jupyter/tests/incremental_learning/test_regression.py
jupyter/tests/incremental_learning/test_sacred.py

This change allows passing the `seed` parameter to the configuration of the `data_frame_analytics`. It also adds a unit test for reproducible runs with sacred.

[ML] Random seed support for experiment tracking

---

bin/pytorch_inference/CCmdLineParser.cc
bin/pytorch_inference/CCmdLineParser.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/evaluate.py

Parallelizes model forwarding. A new parameter called `numParallelForwardingThreads`
specifies the size of the thread pool used to do model forwarding in parallel. The default
value is `1` for now.

[ML] Parallelize calls to forward on pytorch models

---

build-setup/macos.md
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/macosx_builder/Dockerfile
dev-tools/docker/macosx_image/Dockerfile
dev-tools/download_macos_deps.sh

Changes the BLAS library to be explicitly set to `vecLib` which is part of the `Accelerate` framework.
non-issue as the change is to unreleased code

[ML][PYTORCH] Update macOS build to libtorch 1.9

---

bin/pytorch_inference/Main.cc

... are used. This is a follow up to #2023. Now that we start the
thread pool for parallel forwarding to LibTorch models, if the setting
is `1` we start an additional thread that isn't necessary. This commit
removes the use of that extra thread if `numParallelForwardingThreads`
is set to `1`.

[ML] Only start thread pool for parallel forwarding if multiple threads

---

bin/pytorch_inference/Main.cc

In order to simplify control of threading for the LibTorch
process, we set the known environment variables for the threading
of the math lib to one. In this commit, those include:
- MKL_NUM_THREADS: for the MKL lib
- OMP_NUM_THREADS: for OpenMP
- VECLIB_MAXIMUM_THREADS: for Mac's Accelerated framework
Note we do not override the variables if they are already set
in order to allow experimenting in benchmarking. Depending on
findings, we might revisit this and override them.

[ML] Set LibTorch math lib threads to one

---

build-setup/windows.md
dev-tools/download_windows_deps.ps1

macOS and Linux have already been upgraded.
Moving to version 1.9 allows a build workaround
to be removed.
We also enable oneDNN, but do not yet use MKL as
the BLAS. (Potentially we can try that in the next
upgrade, after we've had a chance to see the Linux
benefit in production.)

[ML] Upgrade to PyTorch 1.9 on Windows

---

jupyter/docker/Dockerfile
lib/maths/CBoostedTreeLeafNodeStatistics.cc
lib/maths/unittest/CDataFrameUtilsTest.cc

The base image needs to match what the source code
expects, which is version 19 since #2028 was merged.

[ML] Use gcc 10.3 Docker image for Jupyter Dockerfile

---

bin/pytorch_inference/CCommandParser.cc

The [Windows debug build](https://elasticsearch-ci.elastic.co/job/elastic+machine-learning+main+windows+debug/) of pytorch_inference has been
failing with this error:
```
libMlCore.lib(libMlCore.dll) : error LNK2005: "public: bool __cdecl rapidjson::Writer<class rapidjson::GenericStringBuffer<struct rapidjson::UTF8<char>,class rapidjson::CrtAllocator>,struct rapidjson::UTF8<char>,struct rapidjson::UTF8<char>,class rapidjson::CrtAllocator,0>::Uint64(unsigned __int64)" (?Uint64@?$Writer@V?$GenericStringBuffer@U?$UTF8@D@rapidjson@@VCrtAllocator@2@@rapidjson@@U?$UTF8@D@2@U32@VCrtAllocator@2@$0A@@rapidjson@@QEAA_N_K@Z) already defined in CCommandParser.obj
libMlCore.lib(libMlCore.dll) : error LNK2005: "public: bool __cdecl rapidjson::Writer<class rapidjson::GenericStringBuffer<struct …
```

[ML] Fix Windows debug build of pytorch_inference

---

bin/pytorch_inference/Main.cc

Optimisation for inference only workloads see https://github.com/ailzhang/rfcs/blob/rfc0011/RFC-0011-InferenceMode.md
`InferenceMode` was added to libtorch in version 1.9 so this PR should not be merged until all platforms have been upgraded.
Closes #1954

[ML][PYTORCH] Use InferenceMode RAII guard

---

lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc

A number of minor fixes for the `testIgnoreSamplingGivenDetectionRules`
tests that exercise the skip_model_update rule.
In some test cases the rule was improperly configured leading to it
never being executed.
In the case of
`CMetricPopulationModelTest/testIgnoreSamplingGivenDetectionRules`
messages were not being sampled by the models, leading to the rule never
firing as no data was being passed to it. This was resolved by
generating a more complex set of messages to pass to the models.

[ML] Fix unit tests for skip_model_update rule

---

include/core/CStateMachine.h

CStateMachine.h contained a warning about a problem that was
fixed four years ago. When it was fixed the unit test was
reenabled (and hasn't failed since), but the warning comment
was left in. This PR removes the comment.

[ML] Remove obsolete warning

---

include/core/CStateMachine.h

CStateMachine.h contained a warning about a problem that was
fixed four years ago. When it was fixed the unit test was
reenabled (and hasn't failed since), but the warning comment
was left in. This PR removes the comment.
Backport of #2046

[7.x] [ML] Remove obsolete warning

---

jupyter/docker/Dockerfile
jupyter/docker/linux_image/Dockerfile

This PR fixes caching when building Docker containers. New `ccache` sloppiness settings help to improve cache hits and accelerate re-building. 
I also pre-build the part of the Jupyter container that does not rely on `requirements.txt`. Now, it can be downloaded from the docker registry and does not has to be built locally.

[ML] Fix Docker build caching

---

bin/pytorch_inference/evaluate.py

Adds a mode for benchmarking the different threading parameters
of the libtorch process. The new flag is `--threading_benchmark`.

[ML] Add threading benchmark mode to LibTorch evaluate.py

---

include/api/CDataFrameAnalyzer.h
include/core/CDataFrame.h
lib/api/CDataFrameAnalyzer.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/core/CDataFrame.cc
lib/maths/CBoostedTreeImpl.cc
lib/maths/CBoostedTreeLeafNodeStatistics.cc

The data which was prepared for incremental training of the DGA model from sunburst domains used a different field order and renamed one of the fields. Whilst this wouldn't typically happen in Java, which sorts the field values it supplies by name, it is fragile to rely on this. It is also conceivable that a subset of features aren't available for the update data. This checks that there are no additional fields supplied (likely to indicate a user error) and handles the case that the fields are supplied in a different order or are missing altogether.

[ML] Handle field mismatch in incremental training

---

bin/pytorch_inference/CCmdLineParser.cc
bin/pytorch_inference/CCmdLineParser.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/evaluate.py

Renames `--numLibTorchThreads` to `--inferenceThreads`.
Renames `--numParallelForwardingThreads` to `--modelThreads`.

[ML] Rename LibTorch threading parameters

---

docs/CHANGELOG.asciidoc
include/maths/CModel.h
include/model/CAnomalyDetectorModel.h
lib/maths/CModel.cc
lib/maths/CTimeSeriesModel.cc
lib/maths/unittest/CTimeSeriesModelTest.cc
lib/model/CAnomalyDetectorModel.cc
lib/model/CEventRateModel.cc
lib/model/CEventRatePopulationModel.cc
lib/model/CMetricModel.cc
lib/model/CMetricPopulationModel.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc

Move away from completely ignoring a sample when the skip_model_update
rule applies to instead adding the sample with a small multiplicative
weight applied. This has the benefit of reducing the impact of the
matched samples on the model while still allowing the model to react to
changes in data characteristics.
Related to elastic/ml-cpp#1272

[ML] Improve aspects of skip_model_update rule

---

docs/CHANGELOG.asciidoc
include/maths/CModel.h
include/model/CAnomalyDetectorModel.h
lib/maths/CModel.cc
lib/maths/CTimeSeriesModel.cc
lib/maths/unittest/CTimeSeriesModelTest.cc
lib/model/CAnomalyDetectorModel.cc
lib/model/CEventRateModel.cc
lib/model/CEventRatePopulationModel.cc
lib/model/CMetricModel.cc
lib/model/CMetricPopulationModel.cc
lib/model/unittest/CEventRateModelTest.cc
lib/model/unittest/CEventRatePopulationModelTest.cc
lib/model/unittest/CMetricModelTest.cc
lib/model/unittest/CMetricPopulationModelTest.cc

Move away from completely ignoring a sample when the skip_model_update
rule applies to instead adding the sample with a small multiplicative
weight applied. This has the benefit of reducing the impact of the
matched samples on the model while still allowing the model to react to
changes in data characteristics.
Backports #2053

[7.x][ML] Improve aspects of skip_model_update rule (#2053)

---

jupyter/src/incremental_learning/job.py

If either the data summary or model is large enough to require chunking we need to ensure we pass all the chunks to the `data_frame_analyzer` from the Python `Job` object. It doesn't matter how we join documents because we read the stream using `kParseStopWhenDoneFlag`.

[ML] Handle chunked state in Python Job object

---

docs/CHANGELOG.asciidoc
lib/maths/CBoostedTreeImpl.cc

We were missing a capture of the best hyperparameters by instrumentation after restoring for final train. This is most noticeable when training with all parameters overridden in which case we see uninitialised values in the analysis stats for the job, i.e. before
[
](url)
after
As above I've confirmed it works manually and I don't think the cost benefit means it is worthwhile writing a unit test since  the test is not straightforward to write and it is unlikely that this behaviour will get broken.

[ML] Capture best hyperparameters after restoring for final train

---

include/maths/common/CLbfgs.h
include/maths/common/CLowessDetail.h
lib/maths/analytics/CBoostedTreeLoss.cc
lib/maths/analytics/CDataFrameUtils.cc
lib/maths/analytics/unittest/CBoostedTreeLossTest.cc
lib/maths/common/CBayesianOptimisation.cc
lib/maths/common/CXMeansOnline1d.cc
lib/maths/common/unittest/CLbfgsTest.cc

If an Eigen expression is deduced as the return type of a lambda one can run into the problem that it is only evaluated after the function returns and references out-of-scope variables. `CLbfgs/testMinimizeWithVerySmallGradient` was failing for our debug build as a result of this problem.
This change audits the use of lambdas in minimisation routines in the code base, which are related to this problem, and adds explicit return types.
Given how easy it is to introduce subtle errors in this area it may be worthwhile mandating in our coding standard to always explicitly define lambda return types. However, this is beyond the scope of the change we want to make to address the failing test and possibly related problems.
Although this is a potential bug, as far as we know this was only …

[ML] Avoid possible referencing out-of-scope temporary in lambda return types

---

dev-tools/jenkins_ci.sh
mk/macosx.mk

If we upgrade Xcode on one of our macOS ARM build servers
then we won't rebuild Boost for old branches that are past
feature freeze, but Boost adds the compiler version into
the names of its libraries. Therefore when running in CI
we need to hardcode the version of clang that was used to
build Boost for each branch.
We used to avoid this problem by always using a macOS
build platform for which Xcode was no longer being updated.
For example, the last version of Xcode that works on
Mojave is 11.3, so by advancing the build platform to
Mojave after Xcode 11.4 was released we could be sure that
Xcode would never be upgraded on a build server where we
build for release. (Plus this meant the code was proven by
unit tests to run on old versions of macOS.) With Big Sur
on ARM this approach wasn't …

[7.16] [ML] Lock the clang version used to build Boost in ARM CI

---

dev-tools/jenkins_ci.sh
mk/macosx.mk

If we upgrade Xcode on one of our macOS ARM build servers
then we won't rebuild Boost for old branches that are past
feature freeze, but Boost adds the compiler version into
the names of its libraries. Therefore when running in CI
we need to hardcode the version of clang that was used to
build Boost for each branch.
We used to avoid this problem by always using a macOS
build platform for which Xcode was no longer being updated.
For example, the last version of Xcode that works on
Mojave is 11.3, so by advancing the build platform to
Mojave after Xcode 11.4 was released we could be sure that
Xcode would never be upgraded on a build server where we
build for release. (Plus this meant the code was proven by
unit tests to run on old versions of macOS.) With Big Sur
on ARM this approach wasn't …

[8.0] [ML] Lock the clang version used to build Boost in ARM CI

---

dev-tools/jenkins_ci.sh
mk/macosx.mk

If we upgrade Xcode on one of our macOS ARM build servers
then we won't rebuild Boost for old branches that are past
feature freeze, but Boost adds the compiler version into
the names of its libraries. Therefore when running in CI
we need to hardcode the version of clang that was used to
build Boost for each branch.
We used to avoid this problem by always using a macOS
build platform for which Xcode was no longer being updated.
For example, the last version of Xcode that works on
Mojave is 11.3, so by advancing the build platform to
Mojave after Xcode 11.4 was released we could be sure that
Xcode would never be upgraded on a build server where we
build for release. (Plus this meant the code was proven by
unit tests to run on old versions of macOS.) With Big Sur
on ARM this approach wasn't …

[7.15] [ML] Lock the clang version used to build Boost in ARM CI

---

docs/CHANGELOG.asciidoc
lib/seccomp/CSystemCallFilter_Linux.cc
lib/seccomp/unittest/CSystemCallFilterTest.cc

In recent versions of glibc the pthread_kill function
requires the __NR_getpid system call. This is the case
in Ubuntu 18.04. It is not the case in RHEL/CentOS 7.
Since __NR_getpid was not permitted by our system call
filter pthread_kill did not work on recent versions of
glibc with bad consequences for cleaning up after
connection timeouts.
Additionally there was a much more minor bug where the
named pipe did not get removed if cancellation of the
named pipe connection occurred at one specific place.
Backport of #2102

[7.15] [ML] Fix blocking call cancellation on recent glibc

---

docs/CHANGELOG.asciidoc
lib/core/CNamedPipeFactory.cc
lib/seccomp/CSystemCallFilter_Linux.cc
lib/seccomp/unittest/CSystemCallFilterTest.cc

In recent versions of glibc the pthread_kill function
requires the __NR_getpid system call. This is the case
in Ubuntu 18.04. It is not the case in RHEL/CentOS 7.
Since __NR_getpid was not permitted by our system call
filter pthread_kill did not work on recent versions of
glibc with bad consequences for cleaning up after
connection timeouts.
Additionally there was a much more minor bug where the
named pipe did not get removed if cancellation of the
named pipe connection occurred at one specific place.

[ML] Fix blocking call cancellation on recent glibc

---

lib/maths/time_series/CTimeSeriesModel.cc

The upgrade to boost 1.77 has resulted in a few test cases failing. This
PR provides a fix.
Labelling as a non-issue as it doesn't seem that this would ever cause a problem in production code.
Closes #2107

[ML] Fix for test case assertions

---

docs/CHANGELOG.asciidoc
lib/seccomp/CSystemCallFilter_Linux.cc
lib/seccomp/unittest/CSystemCallFilterTest.cc

In recent versions of glibc the pthread_kill function
requires the __NR_getpid system call. This is the case
in Ubuntu 18.04. It is not the case in RHEL/CentOS 7.
Since __NR_getpid was not permitted by our system call
filter pthread_kill did not work on recent versions of
glibc with bad consequences for cleaning up after
connection timeouts.
Additionally there was a much more minor bug where the
named pipe did not get removed if cancellation of the
named pipe connection occurred at one specific place.
Backport of #2102

[7.16] [ML] Fix blocking call cancellation on recent glibc

---

lib/maths/time_series/CTimeSeriesModel.cc

The upgrade to boost 1.77 has resulted in a few test cases failing. This
PR provides a fix.
Closes #2107
Backports #2110

[7.16][ML] Fix for test case assertions (#2110)

---

include/maths/common/CLinearAlgebra.h

We shouldn't just cast `double` to `uint64_t` for the checksum implementation. We have a proper implementation which hashes the raw bytes and we should switch to using that.
This won't actually affect any results so marking as a non-issue.
Closes #2079.

[ML] Better vector and matrix checksum implementation

---

docs/CHANGELOG.asciidoc
lib/seccomp/CSystemCallFilter_Linux.cc
lib/seccomp/unittest/CSystemCallFilterTest.cc

In recent versions of glibc the pthread_kill function
requires the __NR_getpid system call. This is the case
in Ubuntu 18.04. It is not the case in RHEL/CentOS 7.
Since __NR_getpid was not permitted by our system call
filter pthread_kill did not work on recent versions of
glibc with bad consequences for cleaning up after
connection timeouts.
Additionally there was a much more minor bug where the
named pipe did not get removed if cancellation of the
named pipe connection occurred at one specific place.
Backport of #2102

[8.0] [ML] Fix blocking call cancellation on recent glibc

---

lib/maths/time_series/CTimeSeriesModel.cc

The upgrade to boost 1.77 has resulted in a few test cases failing. This
PR provides a fix.
Closes #2107
Backports #2110

[8.0][ML] Fix for test case assertions (#2110)

---

bin/pytorch_inference/CCommandParser.cc
include/core/CRapidJsonUnbufferedIStreamWrapper.h
include/core/CStateDecompressor.h
lib/core/CRapidJsonUnbufferedIStreamWrapper.cc
lib/core/CStateDecompressor.cc
lib/core/Makefile
lib/core/unittest/CRapidJsonUnbufferedIStreamWrapperTest.cc
lib/core/unittest/Makefile

In #2106 it became apparent that the behaviour of RapidJSON's
own IStreamWrapper class had changed between the 2017 version
we used previously and the latest 2021 version. In the older
version it was unbuffered and in the newer version it was
buffered.
An attempt was made to work around this in #2106 by specifying
a single character buffer, however, in debug builds this then
fell foul of an assertion that the buffer size was at least 4
characters.
This PR adds a separate unbuffered istream wrapper class that
we can use with RapidJSON in cases where we don't want the
wrapper to consume extra characters beyond the end of the
document that's being parsed. Having a separate class should
also reduce the inefficiency of taking one character at a
time, as there's no need to call a stream method …

[ML] Adding an unbuffered istream wrapper for RapidJSON

---

lib/api/unittest/CSerializableToJsonTest.cc

Like #2118 but for the incremental-learning branch.

[ML] Fixing RapidJSON istream wrapper on incremental learning branch

---

include/core/Concurrency.h
include/maths/common/CBjkstUniqueValues.h
include/maths/common/CBootstrapClusterer.h
include/maths/common/CMixtureDistribution.h
include/maths/common/CSetTools.h
include/maths/time_series/CCountMinSketch.h
include/model/CModelTools.h
lib/core/unittest/CMemoryUsageTest.cc
lib/maths/common/CBjkstUniqueValues.cc
lib/maths/time_series/CCountMinSketch.cc
lib/model/CModelTools.cc

Fixes or workarounds for C++17 deprecation warnings emanating directly
from the ml-cpp codebase (not 3rd-party)
Relates #2120

[ML] Fix C++17 deprecation warnings

---

3rd_party/3rd_party.sh
build.gradle
dev-tools/docker/docker_entrypoint.sh
dev-tools/docker_test.sh
dev-tools/jenkins_ci.sh

Our system call filtering is particularly sensitive to the
exact glibc and kernel versions being used. At present our
CI builds only run the C++ unit tests inside the Docker
container. This means the seccomp unit tests will only run
in CI on glibc 2.17 (with our current CentOS 7 build Docker
images). We can improve coverage by copying the test program
out of the Docker container and running it again on the host
operating system. Then it will run against the glibc version
on the host operating system, which is likely to be much
newer than the version in the Docker container. (The Docker
container deliberately uses the oldest glibc version that we
need to be able to run on.)
Potentially we could re-run more unit tests in the future
using the same approach, but some would dramatically …

[ML] Re-run seccomp unit tests on more Linux distributions

---

docs/CHANGELOG.asciidoc
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc

When we adjust the downsample factor we scale the parameters which are added to terms which are proportional to the amount of data so that the degree of regularisation remains constant in expectation. We do this correctly when we fine tune, but using the wrong scaling when doing the initial search for downsample factor. This is liable to lead to us choosing smaller downsample factors than we otherwise might.

[ML] Fix a bug in hyperparameter scaling for classification and regression model training

---

gradle/wrapper/gradle-wrapper.properties

This version supports Java 17, which will make life easier
for developers who have this as their default Java version.

[ML] Upgrade to gradle 7.3

---

gradle/wrapper/gradle-wrapper.properties

This version supports Java 17, which will make life easier
for developers who have this as their default Java version.
Backport of #2132

[8.0] [ML] Upgrade to gradle 7.3

---

gradle/wrapper/gradle-wrapper.properties

This version supports Java 17, which will make life easier
for developers who have this as their default Java version.
Backport of #2132

[7.16] [ML] Upgrade to gradle 7.3

---

include/core/CJsonStateRestoreTraverser.h
lib/core/CJsonStateRestoreTraverser.cc

One of the changes of #2135 applies to the main branch as well
as the incremental learning branch. Although it doesn't cause
any test failures it should be replaced before 8.1 feature
freeze just in case there's a place where buffering makes a
difference in a scenario not covered by our testing.

[ML] Replace rapidjson::istreamwrapper in CJsonStateRestoreTraverser

---

include/core/CJsonStateRestoreTraverser.h
lib/api/CRetrainableModelJsonReader.cc
lib/api/CSerializableToJson.cc

After #2121, there were still some places in the code where the old rapidjson istream wrapper was used. This led to errors, and this PR fixes this.

[ML] Use unbufferred RapidJSON istream wrapper everywhere in the code

---

docs/CHANGELOG.asciidoc
lib/api/CAnomalyJob.cc

Setting this for the new major version gives us a nice
clean break for model state compatibility.  Model snapshots
generated by 8.0 will not be loadable by 7.x nodes, and
in the version where we eventually stop supporting upgrades
from 7.x to the latest version we'll be able to remove all
the model state backwards compatibility code related to
version 7.x.
Proactively avoiding a repeat of elastic/elasticsearch#81011

[ML] Set model state compatibility version to 8.0.0

---

docs/CHANGELOG.asciidoc
lib/api/CAnomalyJob.cc

Setting this for the new major version gives us a nice
clean break for model state compatibility.  Model snapshots
generated by 8.0 will not be loadable by 7.x nodes, and
in the version where we eventually stop supporting upgrades
from 7.x to the latest version we'll be able to remove all
the model state backwards compatibility code related to
version 7.x.
Backport of #2139

[8.0] [ML] Set model state compatibility version to 8.0.0

---

include/maths/analytics/CBoostedTreeFactory.h
include/maths/analytics/CBoostedTreeHyperparameters.h
include/maths/analytics/CBoostedTreeImpl.h
include/maths/analytics/CBoostedTreeUtils.h
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/api/unittest/CInferenceModelMetadataTest.cc
lib/maths/analytics/CBoostedTree.cc
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeHyperparameters.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/unittest/CBoostedTreeHyperparametersTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc

This moves handling of initialisation of parameter search ranges largely into `CBoostedTreeHyperparameters`. Previously it was split between there and `CBoostedTreeFactory`. It also improves handling of user overrides of parameter search ranges and properly encapsulates the logic for searching logged values or not in the parameter definition.

[ML] Refactor parameter search initialisation

---

3rd_party/licenses/eigen-INFO.csv
3rd_party/licenses/eigen-NOTICE.txt
3rd_party/pull-eigen.sh
docs/CHANGELOG.asciidoc
include/maths/common/CLeastSquaresOnlineRegressionDetail.h
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/common/unittest/CLinearAlgebraTest.cc

Eigen 3.4.0 has better support for more modern C++ language features and
as such quietens a few C++17 deprecation warnings encountered with
version 3.3.7.
Relates to #2120

[ML] Upgrade to Eigen 3.4.0

---

docs/CHANGELOG.asciidoc
include/maths/common/CLbfgs.h
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/common/CBayesianOptimisation.cc

We need to check that the objective actually decreases after snapping to the constraint bounding box for L-BFGS with constraint. Also, addresses some cross platform variation due to variation `std::exp` and  `std::log` when computing ANOVA for hyperparameter losses.

[ML] Improve training stability for regression and classification models

---

docs/CHANGELOG.asciidoc
include/maths/common/CBayesianOptimisation.h
include/maths/common/CLbfgs.h
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/common/CBayesianOptimisation.cc
lib/maths/common/unittest/CBayesianOptimisationTest.cc

These were found debugging sources of cross-platform variation.
1. `1 + erf` underflows when `erf` is within double epsilon of 1. `boost::normal` distribution has a better cdf implementation which computes values accurate to double precision as small as minimum (positive) double. This means we get better estimates of EI and its gradient.
2. Depending on the kernel parameters EI can be very small. In the case when it underflows we broke ties by dimension lexicograpical order for the points. From an optimisation standpoint this is a silly choice. I've changed it to prefer the we tried point which is most dissimilar to points we've already tried (i.e. pure exploration).
Both of these incidentally mean the exact choice of points BO will propose is more sensitive to numerics which can vary …

[ML] Some improvements to Bayesian Optimisation implementation

---

docs/CHANGELOG.asciidoc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc

Currently, if we make any different choice in any round of training it affects the random number generator state which will affect the numbers we choose for all subsequent rounds. This tends to amplify differences in results especially those related to say slightly different numerics on different platforms.
With this change I reset the rng and then jump (by 2^64 values) after each forest we train. This means different choices for a particular round don't affect random numbers drawn in subsequent rounds. The jump is large enough that sequences don't overlap.

[ML] Improve regression and classification training stability

---

include/api/CHierarchicalResultsWriter.h
include/core/CBase64Filter.h
include/core/CFastMutex.h
include/core/CVectorRange.h
include/core/CXmlNode.h
include/maths/common/CClusterer.h
include/maths/common/CMultivariateNormalConjugate.h
include/model/CHierarchicalResults.h
include/model/CHierarchicalResultsAggregator.h
include/model/CHierarchicalResultsLevelSet.h
include/model/CHierarchicalResultsNormalizer.h
include/model/CHierarchicalResultsPopulator.h
include/model/CHierarchicalResultsProbabilityFinalizer.h
lib/api/CInferenceModelMetadata.cc
lib/core/CBase64Filter.cc
lib/core/CFastMutex_MacOSX.cc
lib/core/CXmlNode.cc
lib/maths/common/unittest/COrderingsTest.cc
lib/model/CHierarchicalResults.cc

Deprecation warnings were enabled for a build on macOS 11.6.1 using clang
13.0.0 by way of adding the `-Wdeprecated` flag to clang's arguments.
The majority of the warnings related to implicit constructors of one
sort or another, with a notable exception being `OSSpinLock` being
deprecated in favour of `os_unfair_lock` since macOS 10.12.
labelling as `>non-issue` as no functional change has been made.

[ML] Fix deprecation warning for macOS build

---

include/maths/analytics/CBoostedTreeHyperparameters.h
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc

We were computing downsampled old and new training data masks as follows:
```
this->downsample(oldTrainingRowMask) | this->downsample(newTrainingRowMask);
```
The compiler is at liberty to reorder evaluation of calls to compute `operator|` arguments. Since this changes the state of our internal random number generator this changes the rows we select to compute splits. We now split these calls into separate statements.
We also need to follow the paradigm used by train from scratch and reseed the rng when performing final train so running again with parameters overridden produces identical results.

[ML] Fix sources of cross platform variation in incremental training

---

lib/maths/analytics/unittest/CBoostedTreeTest.cc

One of the thresholds that was tightened up in #2150 causes
failures in builds without optimisation, for example:
1. https://elasticsearch-ci.elastic.co/job/elastic+machine-learning+main+linux-aarch64+debug/130/testReport
2. https://elasticsearch-ci.elastic.co/job/elastic+machine-learning+main+macos-aarch64+debug/130/testReport

[ML] Relax test threshold

---

bin/pytorch_inference/Main.cc

When the `pytorch_inference` process starts, we validate the given
thread settings and adjust them if necessary. This commit changes
the process to write the actual thread settings back to ES.

[ML] Write actual thread settings after pytorch process starts

---

dev-tools/run_es_tests.sh

PR CI tests run some of the Elasticsearch integration tests.
We've always had a slightly hacky way of doing this on
linux-aarch64.  For JDK 17 things are a bit different because
Java has fixed the page size issues that affected earlier
versions.  Each Elasticsearch CI worker now has a symlink
from "jdk17" to the actual JDK directory on the machine, so
we should use that.
This PR should fix errors like "ERROR: JAVA_HOME is set to an
invalid directory: /var/lib/jenkins/.java/adoptopenjdk17" in
https://elasticsearch-ci.elastic.co/job/elastic+machine-learning+pull-request+linux-aarch64/749/console

[ML] Fixing the way we set up the ES JVM on linux-aarch64

---

dev-tools/run_es_tests.sh

PR CI tests run some of the Elasticsearch integration tests.
We've always had a slightly hacky way of doing this on
linux-aarch64.  For JDK 17 things are a bit different because
Java has fixed the page size issues that affected earlier
versions.  Each Elasticsearch CI worker now has a symlink
from "jdk17" to the actual JDK directory on the machine, so
we should use that.
This PR should fix errors like "ERROR: JAVA_HOME is set to an
invalid directory: /var/lib/jenkins/.java/adoptopenjdk17" in
https://elasticsearch-ci.elastic.co/job/elastic+machine-learning+pull-request+linux-aarch64/749/console
Backport of #2160

[8.0] [ML] Fixing the way we set up the ES JVM on linux-aarch64

---

3rd_party/3rd_party.sh

The old pattern was too lax, copying all files with "c10" in
their names, which also matches "gcc10". This was causing us
to copy the symlinked versions of the Boost libraries and hence
ship each Boost library twice on Linux.

[ML] Tighten up the pattern used to copy Torch dependencies

---

3rd_party/3rd_party.sh

The old pattern was too lax, copying all files with "c10" in
their names, which also matches "gcc10". This was causing us
to copy the symlinked versions of the Boost libraries and hence
ship each Boost library twice on Linux.
Backport of #2164

[8.0] [ML] Tighten up the pattern used to copy Torch dependencies

---

docs/CHANGELOG.asciidoc
include/maths/time_series/CExpandingWindow.h
include/maths/time_series/CTimeSeriesDecompositionDetail.h
include/maths/time_series/CTimeSeriesTestForSeasonality.h
lib/maths/time_series/CExpandingWindow.cc
lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
lib/maths/time_series/CTimeSeriesTestForSeasonality.cc
lib/maths/time_series/unittest/CTimeSeriesDecompositionTest.cc
lib/maths/time_series/unittest/CTimeSeriesTestForSeasonalityTest.cc

When we retest if a modelled seasonal component is still appropriate or may contain bias we now require higher resolution if shorter time windows are available. This is important because if the time series has a mixture of fast and slow seasonality we will detect the fast seasonality first and then potentially reinitialise it when we detect the slow seasonality. We should only do this if the window provides us with sufficient resolution to initialise it properly.
Closes #2166.

[ML] Ensure we have sufficient resolution when we reinitialise component models 

---

docs/CHANGELOG.asciidoc
include/maths/time_series/CExpandingWindow.h
include/maths/time_series/CTimeSeriesDecompositionDetail.h
include/maths/time_series/CTimeSeriesTestForSeasonality.h
lib/maths/time_series/CExpandingWindow.cc
lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
lib/maths/time_series/CTimeSeriesTestForSeasonality.cc
lib/maths/time_series/unittest/CTimeSeriesDecompositionTest.cc
lib/maths/time_series/unittest/CTimeSeriesTestForSeasonalityTest.cc

[8.0][ML] Ensure we have sufficient resolution when we reinitialise component models

---

dev-tools/docker/build_check_style_image.sh
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/prefetch_docker_image.sh
dev-tools/docker_build.sh
dev-tools/docker_check_style.sh
dev-tools/docker_test.sh
dev-tools/jenkins_combine_artifacts.sh

The upload to S3 is done in the same way as before, except
that the call to Gradle is now made from a script rather
than being part of the Jenkins job config. This will make
it easier to evolve in the future without making infra
changes.
The upload to GCS is done by a Docker image owned by the
release team that generates checksums and metadata such
that release manager can generate a release from a specific
ml-cpp commit rather than always using the latest commit on
a given branch.

[ML] Upload combined artifacts to GCS as well as S3

---

dev-tools/docker/build_check_style_image.sh
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/prefetch_docker_image.sh
dev-tools/docker_build.sh
dev-tools/docker_check_style.sh
dev-tools/docker_test.sh
dev-tools/jenkins_combine_artifacts.sh

The upload to S3 is done in the same way as before, except
that the call to Gradle is now made from a script rather
than being part of the Jenkins job config. This will make
it easier to evolve in the future without making infra
changes.
The upload to GCS is done by a Docker image owned by the
release team that generates checksums and metadata such
that release manager can generate a release from a specific
ml-cpp commit rather than always using the latest commit on
a given branch.
Backport of #2173

[8.0] [ML] Upload combined artifacts to GCS as well as S3

---

dev-tools/docker/build_check_style_image.sh
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/prefetch_docker_image.sh
dev-tools/docker_build.sh
dev-tools/docker_check_style.sh
dev-tools/docker_test.sh
dev-tools/jenkins_combine_artifacts.sh

The upload to S3 is done in the same way as before, except
that the call to Gradle is now made from a script rather
than being part of the Jenkins job config. This will make
it easier to evolve in the future without making infra
changes.
The upload to GCS is done by a Docker image owned by the
release team that generates checksums and metadata such
that release manager can generate a release from a specific
ml-cpp commit rather than always using the latest commit on
a given branch.
Backport of #2173

[7.17] [ML] Upload combined artifacts to GCS as well as S3

---

build.gradle

The "combine artifacts" step of the ML CI workflow previously
used to download platform-specific binaries from S3 and upload
an artifact built by combining them to S3. It didn't need to
do anything with the platform-specific debug symbols that were
already on S3.
Now that the "combine artifacts" step also uploads artifacts to
GCS it also needs to upload the zips containing the debug symbols.
Therefore, this commit changes the step that downloads
platform-specific artifacts to get the debug symbols too.
Followup to #2173

[ML] Download debug symbols as well as binaries in combine step

---

build.gradle

The "combine artifacts" step of the ML CI workflow previously
used to download platform-specific binaries from S3 and upload
an artifact built by combining them to S3. It didn't need to
do anything with the platform-specific debug symbols that were
already on S3.
Now that the "combine artifacts" step also uploads artifacts to
GCS it also needs to upload the zips containing the debug symbols.
Therefore, this commit changes the step that downloads
platform-specific artifacts to get the debug symbols too.
Backport of #2177

[8.0] [ML] Download debug symbols as well as binaries in combine step

---

build.gradle

The "combine artifacts" step of the ML CI workflow previously
used to download platform-specific binaries from S3 and upload
an artifact built by combining them to S3. It didn't need to
do anything with the platform-specific debug symbols that were
already on S3.
Now that the "combine artifacts" step also uploads artifacts to
GCS it also needs to upload the zips containing the debug symbols.
Therefore, this commit changes the step that downloads
platform-specific artifacts to get the debug symbols too.
Backport of #2177

[7.17] [ML] Download debug symbols as well as binaries in combine step

---

build.gradle

Currently the dependency report is always simply "dependencies.csv".
For integration into the new release manager workflow the file name
needs to also contain the qualified version.

[ML] Include version in dependency report file name

---

build.gradle

Currently the dependency report is always simply "dependencies.csv".
For integration into the new release manager workflow the file name
needs to also contain the qualified version.
Backport of #2180

[7.17] [ML] Include version in dependency report file name

---

build.gradle

Currently the dependency report is always simply "dependencies.csv".
For integration into the new release manager workflow the file name
needs to also contain the qualified version.
Backport of #2180

[8.0] [ML] Include version in dependency report file name

---

3rd_party/3rd_party.sh

PyTorch on Windows requires Microsoft's OMP redistributable,
vcomp140.dll. Our 3rd party library script needs to copy this
to the distribution directory.
Fixes #2185

[ML] Ship vcomp140.dll for PyTorch on Windows

---

dev-tools/jenkins_combine_artifacts.sh

The infra repo is still using a master branch instead of main.
However, the infra Docker image has been changed so that if the
branch to use is specified as main then it gets mapped to master.
Therefore it's more future-proof to specify main rather than
master. Specifying main means that when the infra repo is changed
from master to main nothing will need changing in the ml-cpp
repo. The change at that time will be in the infra repo, which is
easier to coordinate with a branch rename in that same repo.

[ML] Specify main instead of master when using infra Docker image

---

3rd_party/3rd_party.sh

PyTorch on Windows requires Microsoft's OMP redistributable,
vcomp140.dll. Our 3rd party library script needs to copy this
to the distribution directory.
Backport of #2186

[8.0] [ML] Ship vcomp140.dll for PyTorch on Windows

---

include/api/CDataFrameTrainBoostedTreeRunner.h
include/maths/analytics/CBoostedTree.h
include/maths/analytics/CBoostedTreeFactory.h
include/maths/analytics/CBoostedTreeHyperparameters.h
include/maths/analytics/CBoostedTreeImpl.h
include/maths/analytics/CDataFramePredictiveModel.h
include/test/CDataFrameAnalyzerTrainingFactory.h
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/maths/analytics/CBoostedTree.cc
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeHyperparameters.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc

When training from scratch on very large data sets using multiple rounds of incremental training, we have both plenty of data and we don't want the examples selected to include in the training set in later rounds to be used for validation. They will depend on the selection criterion and so will not be a uniform sampling of the full data set. Also this process is likely to leak information about the model.
In this case, it is better to use a fixed evaluation set which is held out from training and can be sampled at random upfront. This change introduces that holdout set. Since we maintain row masks for the test and train sets for cross-validation it is easy to hijack the cross-validation mechanism for this purpose by simply having one fold.

[ML] Support testing on a holdout set rather than cross-validation when training

---

docs/CHANGELOG.asciidoc
include/maths/common/CStatisticalTests.h
lib/maths/common/CStatisticalTests.cc
lib/maths/time_series/CSignal.cc
lib/maths/time_series/CTimeSeriesSegmentation.cc
lib/maths/time_series/CTimeSeriesTestForChange.cc
lib/maths/time_series/CTimeSeriesTestForSeasonality.cc
lib/maths/time_series/unittest/CForecastTest.cc
lib/maths/time_series/unittest/CTimeSeriesDecompositionTest.cc
lib/maths/time_series/unittest/CTimeSeriesModelTest.cc
lib/maths/time_series/unittest/CTimeSeriesTestForSeasonalityTest.cc

This unifies the handling of edge cases for calculating the F-test statistic which needs to handle 0 / 0 and x / 0. This was spread over various places and not always applied consistently. There were also some uses which did not properly scale the statistic by the degrees of freedom. This second fix has an impact (albeit v.small) on our results as tweaks to the test thresholds signify.
This addresses some sources of errors observed in our cloud logging clusters.

[ML] Address cause of "[CStatisticalTests.cc@102] Test statistic is nan"  log errors

---

docs/CHANGELOG.asciidoc
include/maths/common/CStatisticalTests.h
lib/maths/common/CStatisticalTests.cc
lib/maths/time_series/CSignal.cc
lib/maths/time_series/CTimeSeriesSegmentation.cc
lib/maths/time_series/CTimeSeriesTestForChange.cc
lib/maths/time_series/CTimeSeriesTestForSeasonality.cc
lib/maths/time_series/unittest/CForecastTest.cc
lib/maths/time_series/unittest/CTimeSeriesDecompositionTest.cc
lib/maths/time_series/unittest/CTimeSeriesModelTest.cc
lib/maths/time_series/unittest/CTimeSeriesTestForSeasonalityTest.cc

[8.1][ML] Address causes of "[CStatisticalTests.cc@102] Test statistic is nan"  log errors

---

docs/CHANGELOG.asciidoc
include/maths/common/CLbfgs.h
include/maths/common/CLowessDetail.h
include/maths/common/CSolvers.h
include/maths/time_series/CSeasonalComponent.h
include/maths/time_series/CTimeSeriesDecomposition.h
include/maths/time_series/CTimeSeriesDecompositionDetail.h
include/maths/time_series/CTimeSeriesDecompositionInterface.h
include/maths/time_series/CTimeSeriesDecompositionStub.h
include/maths/time_series/CTimeSeriesModel.h
include/maths/time_series/CTimeSeriesMultibucketFeatureSerialiser.h
include/maths/time_series/CTimeSeriesMultibucketFeatures.h
include/maths/time_series/CTimeSeriesMultibucketFeaturesFwd.h
include/maths/time_series/CTimeSeriesTestForSeasonality.h
include/model/ModelTypes.h
lib/maths/common/CPrior.cc
lib/maths/time_series/CSeasonalComponent.cc
lib/maths/time_series/CTimeSeriesDecomposition.cc
lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
lib/maths/time_series/CTimeSeriesDecompositionStub.cc
lib/maths/time_series/CTimeSeriesModel.cc
lib/maths/time_series/CTimeSeriesMultibucketFeatureSerialiser.cc
lib/maths/time_series/CTimeSeriesTestForSeasonality.cc
lib/maths/time_series/unittest/CSeasonalComponentTest.cc
lib/maths/time_series/unittest/CTimeSeriesDecompositionTest.cc
lib/maths/time_series/unittest/CTimeSeriesModelTest.cc
lib/maths/time_series/unittest/CTimeSeriesMultibucketFeaturesTest.cc
lib/model/ModelTypes.cc
lib/model/unittest/CModelTestFixtureBase.cc

Currently, we have can issues with our time series modelling when:
1. The data are seasonal and the period is not a multiple of the bucket length (or at least not very close to a multiple),
2. The data have seasonality, but the pattern shifts from time to time.
In both cases we get precession of the periodic pattern and generally we don't adapt to this fast enough. The effect is we lose prediction accuracy and sensitivity over time.
This change introduces a latent time shift for each seasonal component and solves for the shift which minimises the difference between the predictions and the observed values. Shifts are accumulated over each period which is observed, which allows us to handle slow precession.

[ML] Handle precession and time shifts of seasonality in anomaly detection

---

docs/CHANGELOG.asciidoc
include/maths/common/CStatisticalTests.h
lib/maths/common/CStatisticalTests.cc
lib/maths/time_series/CSignal.cc
lib/maths/time_series/CTimeSeriesSegmentation.cc
lib/maths/time_series/CTimeSeriesTestForChange.cc
lib/maths/time_series/CTimeSeriesTestForSeasonality.cc
lib/maths/time_series/unittest/CForecastTest.cc
lib/maths/time_series/unittest/CTimeSeriesDecompositionTest.cc
lib/maths/time_series/unittest/CTimeSeriesModelTest.cc
lib/maths/time_series/unittest/CTimeSeriesTestForSeasonalityTest.cc

[7.17][ML] Address causes of "[CStatisticalTests.cc@102] Test statistic is nan" log errors

---

include/maths/analytics/CBoostedTreeImpl.h
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc

When we are assessing generalisation error using a holdout set there is no need to account for the train/test loss gap comparing the output of  incremental training with the original model.

[ML] Correct loss gap calculation when evaluating using a holdout set

---

dev-tools/jenkins_combine_artifacts.sh

Previously the release manager integration code used its own
version number. Generally this didn't matter, but it meant
there was a period when builds would fail as the version was
bumped in all the repos. Passing in the version from the ml-cpp
repo will mean that builds don't fail if the version bumps in
ml-cpp and infra are out of sync.

[ML] Pass ml-cpp version to release manager integration code

---

dev-tools/jenkins_combine_artifacts.sh

Previously the release manager integration code used its own
version number. Generally this didn't matter, but it meant
there was a period when builds would fail as the version was
bumped in all the repos. Passing in the version from the ml-cpp
repo will mean that builds don't fail if the version bumps in
ml-cpp and infra are out of sync.
Backport of #2208

[8.1] [ML] Pass ml-cpp version to release manager integration code

---

dev-tools/jenkins_combine_artifacts.sh

Previously the release manager integration code used its own
version number. Generally this didn't matter, but it meant
there was a period when builds would fail as the version was
bumped in all the repos. Passing in the version from the ml-cpp
repo will mean that builds don't fail if the version bumps in
ml-cpp and infra are out of sync.
Backport of #2208

[8.0] [ML] Pass ml-cpp version to release manager integration code

---

dev-tools/jenkins_combine_artifacts.sh

Previously the release manager integration code used its own
version number. Generally this didn't matter, but it meant
there was a period when builds would fail as the version was
bumped in all the repos. Passing in the version from the ml-cpp
repo will mean that builds don't fail if the version bumps in
ml-cpp and infra are out of sync.
Backport of #2208

[7.17] [ML] Pass ml-cpp version to release manager integration code

---

docs/CHANGELOG.asciidoc
lib/model/CEventRateBucketGatherer.cc

We were not properly restoring the data gatherer state for time of day and week anomaly detection functions. This could lead to "No queue item for time <x>" and "Time <x> is out of range. Returning earliest bucket index" log errors and us potentially missing data for them.

[ML] Fix bug restoring data gatherer state for time of day/week and anomaly detection

---

include/model/CBucketGatherer.h
include/model/CBucketQueue.h
include/model/CDataGatherer.h
lib/model/CBucketGatherer.cc
lib/model/CDataGatherer.cc
lib/model/CEventRateBucketGatherer.cc
lib/model/CMetricBucketGatherer.cc
lib/model/unittest/CEventRateDataGathererTest.cc

This PR removes some functionality for updating time which was not being used and in fact wasn't properly maintaining class invariants. It also adds some extra useful information in various log messages, in case we still have problems in this area, after fixing #2213.
Finally, it addresses assorted warnings in this code generated by clang-tidy. Principally, we were using bind, because the code predated lambdas, however calling via lambdas often produces better inlining.

[ML] Remove some unused (and buggy) functionality in anomaly detection data gathering

---

lib/api/CAnomalyJob.cc
lib/api/CSingleFieldDataCategorizer.cc
lib/core/CJsonStateRestoreTraverser.cc
lib/model/CBucketGatherer.cc
lib/model/CDataCategorizer.cc
lib/model/CDataGatherer.cc
lib/model/CEventRateBucketGatherer.cc
lib/model/CMetricBucketGatherer.cc

Centralise checks for bad state in the public methods of the state
traverser itself.
Relates #2219

[ML] Refactor state traverser checks for bad state

---

build.gradle
dev-tools/docker/docker_entrypoint.sh
dev-tools/jenkins_ci.sh

This relates to https://github.com/elastic/elasticsearch/pull/84536. For composite build integration to work using the separate "deps" and "nodeps" artifacts, we need to tweak the build to expose _both_ as project artifacts so they can be properly resolved by the Elasticsearch build. This PR includes a few things to make that happen:
1. Apply the Gradle "base" plugin to inherit the necessary configuration so that the `default` configuration is properly consumed by the ES build.
2. Introduce additional tasks to create the "deps" and "nodeps" artifacts from the locally built zip (isntead of from a downloaded snapshot)
3. Remove superfluous configuration which is provided by base plugin conventions.
4. Modify lifecycle tasks (ie. clean, assemble, check, etc) to work with base plugin.

Use deps and nodeps archives for project artifacts

---

docs/CHANGELOG.asciidoc
include/maths/common/CBasicStatistics.h
include/maths/common/CLeastSquaresOnlineRegression.h
include/maths/common/CLeastSquaresOnlineRegressionDetail.h
include/maths/time_series/CTimeSeriesSegmentation.h
lib/maths/common/unittest/CLeastSquaresOnlineRegressionTest.cc
lib/maths/time_series/CTimeSeriesSegmentation.cc

We check for change points in the trend both when performing change point detection and detecting trend and seasonality in our time series modelling. We do this by testing the significance of the change in residual variance with and without the change point. The current approach has O(n^2) complexity with respect to the time window length n. However, least squares regression allows one to compute residual moments in an online fashion, using largely the same set of statistics we currently maintain for estimating parameters. This allows one to drop the complexity to O(n). The slight downside is that we compute variance using the numerically lossy E[X^2] - E[X]^2 formulation. However, we can centre the data before computing variance which means in practice this isn't a problem.
For the sort …

[ML] Speedup finding change points in the time series trend

---

docs/CHANGELOG.asciidoc
include/maths/analytics/CBoostedTreeImpl.h
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc

If the number of distinct values of a feature is less than the number of splits we test, we can compute an exhaustive set of splits once upfront and cache the rows' split for the duration of training. This speed up training by 30% on a data set with many low cardinality features.

[ML] Better handling of low cardinality features for training classification and regression models

---

docs/CHANGELOG.asciidoc
include/maths/time_series/CSignal.h
include/maths/time_series/CTimeSeriesTestForSeasonality.h
lib/maths/time_series/CSignal.cc
lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
lib/maths/time_series/CTimeSeriesTestForChange.cc
lib/maths/time_series/CTimeSeriesTestForSeasonality.cc
lib/maths/time_series/unittest/CSignalTest.cc

We currently handle outliers when decomposing time series on a window by reducing their weight. This is usually sufficient, however extreme outliers can still create problems given the current approach. Ignoring values altogether is risky; for example, periodic spikes are large outliers for many measures. In the sorts of data we deal with extreme values are often localised in time, for example a very large spike. This PR makes a couple of changes to try and deal better with extreme values:
1. Exclude a single short interval within the window being decomposed which is very different from all other values in that window.
2. Discard any component scaling or trend piece we fit to a short interval when computing values with which to initialise the model (since such pieces are often used to …

[ML] Better handling of extreme outliers in time series modelling

---

include/core/CStaticThreadPool.h
lib/core/CStaticThreadPool.cc
lib/core/unittest/CStaticThreadPoolTest.cc

For PyTorch model inference we want to be able to control the number of threads we assign to parallel calls to forward on-the-fly to adjust the number of cores each model consumes on a node as cluster wide tasks are added or removed. This lays the groundwork by adding a dynamic setting for the number of threads the pool will use. The idea is we always start the process thread pool with the hardware concurrency (divided by the number of threads we give libtorch), but then adjust the threads actually used by control message. Unused threads will simply be idle waiting to pop an empty queue so are effectively free.
cc @dimitris-athanasiou.

[ML] Allow on-the-fly adjustment of the number of threads in use

---

docs/CHANGELOG.asciidoc
include/maths/time_series/CCalendarComponent.h
include/maths/time_series/CCalendarComponentAdaptiveBucketing.h
include/maths/time_series/CCalendarCyclicTest.h
include/maths/time_series/CCalendarFeature.h
include/maths/time_series/CTimeSeriesDecompositionDetail.h
lib/maths/time_series/CCalendarComponent.cc
lib/maths/time_series/CCalendarComponentAdaptiveBucketing.cc
lib/maths/time_series/CCalendarCyclicTest.cc
lib/maths/time_series/CCalendarFeature.cc
lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
lib/maths/time_series/unittest/CCalendarComponentAdaptiveBucketingTest.cc
lib/maths/time_series/unittest/CCalendarComponentTest.cc
lib/maths/time_series/unittest/CCalendarCyclicTestTest.cc
lib/maths/time_series/unittest/CSeasonalComponentTest.cc
lib/maths/time_series/unittest/Makefile

Currently, we test to see whether there is significant evidence for calendar predictive calendar features for time series modelling. The approach we use has two deficiencies:
1. If there is a single bucket with a very large deviation predicted by a calendar feature, then our existing test will not necessarily pick this up,
2. For "day of week, week of month" features (for example 1st Monday of the month) one must account for time zone shifts to reliably detect. For example, if the Monday lands on the first day of the month then the time zone may mean that it is in a different month in GMT.
This change addresses both deficiencies. We now test shifting the pattern up to one day earlier or later to allow for the time zone. We also keep track of very large errors. Even if one such error …

[ML] Improve calendar component test

---

lib/maths/time_series/CCalendarCyclicTest.cc

Following on from #2236, we weren't properly handling the case that all values for a time series are the same and triggering a log error. This simply traps the edge case and exits the calculation early.
This is unreleased code so marking as a non-issue.

[ML] Fix cause of log error

---

docs/CHANGELOG.asciidoc
include/maths/time_series/CCalendarCyclicTest.h
lib/maths/time_series/CCalendarCyclicTest.cc
lib/maths/time_series/CTimeSeriesDecompositionDetail.cc

Currently, if we detect a change in seasonal components we reset the calendar component test state. This is because unmodelled seasonal components can result in large errors and so our estimation of the prediction error distribution is unreliable. However, we can also choose a different seasonal decomposition if the data characteristics change somewhat from time-to-time. Resetting the large error count statistics mean we have to start again trying to detect predictive calendar features, which is a multi-month process. Since the primary driver for resetting the test state is the poor error distribution characterisation, this change switches to instead keeping large error count statistics but resetting the error distribution estimate.

[ML] Speedup detection of calendar components

---

build-setup/windows.md
dev-tools/download_windows_deps.ps1

There are no changes to the build process since 1.9.
We still don't ship with MKL on Windows. The size of MKL proved
controversial on Linux, so it's best not to increase distribution
size even further by adding in the Windows version. (We can still
revisit this in the future if there's sufficient demand for NLP
in production on Windows.)

[ML] Upgrade to PyTorch 1.11 on Windows

---

build-setup/macos.md
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/macosx_builder/Dockerfile
dev-tools/docker/macosx_image/Dockerfile
dev-tools/download_macos_deps.sh

It's now possible to use the MKLDNN library on macOS on ARM.
There are no other changes to the build process since 1.9.
I've added a comment to say we should upgrade the version of
Python we use to build PyTorch before the next upgrade, as
this seems to be the root cause of the difficulties with
correct architecture detection on ARM.

[ML] Upgrade to PyTorch 1.11 on macOS

---

3rd_party/3rd_party.sh
3rd_party/licenses/pytorch-INFO.csv
build-setup/linux.md
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/linux_aarch64_native_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_aarch64_native_tester/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_image/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
docs/CHANGELOG.asciidoc

Together with #2233 and #2235 this completes the upgrade to
PyTorch 1.11 for all platforms.
A small change to the way things are done is that we now copy
all MKL libraries into the Docker images, then copy the required
subset into our release distribution. This means we can change
the subset of MKL libraries that we redistribute without having
to rebuild our Docker images.
Fixes #2126

[ML] Upgrade to PyTorch 1.11 on Linux

---

lib/maths/analytics/CBoostedTreeHyperparameters.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc

#2245 introduced a using variable after moving it mistake. This corrects that. Since it hasn't been released, I've marked as a non-issue.

[ML] Don't use moved from variable

---

build-setup/clion/using_clion.md
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc

There was a mistake in `testRunBoostedTreeRegressionTrainingWithStateRecovery` state parsing introduced in #2245. This fixes it. Since the code is unreleased I'm marking as a non-issue.

[ML] Fix test

---

docs/CHANGELOG.asciidoc
include/maths/analytics/CBoostedTreeHyperparameters.h
lib/maths/analytics/CBoostedTreeHyperparameters.cc
lib/maths/analytics/CBoostedTreeImpl.cc

Previously, we would enter fine tuning loop even if we exited early in the event of restart from failover. This adds state to record early exit so we pick up correctly. Also, to monitor progress correctly we need to always start progress monitoring for final train, independent of whether we're training using a hold set or cross-validation.

[ML] Correct restart from failure when fine tuning classification and regression models

---

3rd_party/licenses/zlib-INFO.csv
build-setup/windows.md
dev-tools/download_windows_deps.ps1
docs/CHANGELOG.asciidoc

Version 1.2.12 has these key improvements over 1.2.11:
- Fix a deflate bug when using the Z_FIXED strategy that can result
in out-of-bound accesses.
- Fix a deflate bug when the window is full in deflate_stored().
- Speed up CRC-32 computations by a factor of 1.5 to 3.
- Use the hardware CRC-32 instruction on ARMv8 processors.
- Speed up crc32_combine() with powers of x tables.
- Add crc32_combine_gen() and crc32_combine_op() for fast combines.
For Linux and macOS we use the zlib provided by the OS install.
Users on Linux and macOS are advised to install the latest OS
updates if they wish to take advantage of these improvements.

[ML] Upgrade to zlib 1.2.12 on Windows

---

docs/CHANGELOG.asciidoc
include/maths/common/CBayesianOptimisation.h
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/common/CBayesianOptimisation.cc
lib/maths/common/unittest/CBayesianOptimisationTest.cc

This corrects the handling of the shifting and scaling of the function values when computing various quantities related to the GP. In particular, we were not properly undoing the transform in `evaluate`, `evaluate1D` and various ANOVA related functionality. We could end up computing square roots of negative numbers in `evaluate1D` and `anovaTotalVariance`. At the same time I took the opportunity to ensure GP domain is [0, 1]^n rather than just scaling. This leads to more predictable numerics for ML and also simplifies the code.
I've added tests that the kernel parameters are invariant under operations to the function range which should preserve its value: changing level and scale. I also do the same for `evaluate`, `evaluate1D` and various ANOVA related functionality.

[ML] Some corrections to ANOVA for Bayesian Optimisation

---

docs/CHANGELOG.asciidoc
lib/maths/time_series/CTimeSeriesTestForSeasonality.cc

There are various reasons we can decide not to remove the seasonal component from a portion of the window we test when we think the seasonality is piecewise linearly scaled. In this case the residual values there are unreliable and should be ignored when reinitialising the trend model. This issue could lead to us to very significantly over estimate the prediction errors and inflate the model bounds after detecting new seasonal components in certain edge cases.

[ML] Correct initialisation of the trend model after detecting seasonality for edge case

---

lib/core/unittest/CStaticThreadPoolTest.cc

BOOST_REQUIRE is a simple boolean assertion whereas
BOOST_TEST_REQUIRE prints the values either side of
comparison operators when the assertion fails.

[ML] Adjust test assertion to print values on failure

---

docs/CHANGELOG.asciidoc
lib/seccomp/CSystemCallFilter_Linux.cc

Ubuntu 22.04 uses glibc 2.35 and the implementation of
pthread_create has been changed to use more system calls
than it used to.
In order for pthread_create to work on glibc 2.35 we need
to allow the rt_sigprocmask, rseq and clone3 system calls.
Fixes elastic/elasticsearch#86877

[ML] Permit new system calls used by Ubuntu 22.04

---

docs/CHANGELOG.asciidoc
include/core/CWordDictionary.h
include/core/WindowsSafe.h
include/model/CTokenListCategory.h
include/model/CTokenListDataCategorizer.h
include/model/CTokenListDataCategorizerBase.h
lib/core/unittest/CWordDictionaryTest.cc
lib/model/CTokenListCategory.cc
lib/model/CTokenListDataCategorizerBase.cc
lib/model/unittest/CTokenListDataCategorizerTest.cc
mk/windows.mk

In #1903 we changed dictionary weighting in categorization to give
higher weighting when there were 3 or more adjacent dictionary
words. This was the first time that we'd ever had the situation
where the same token could have a different weight in different
messages. Unfortunately the way this interacted with us requiring
equal weights when checking for common tokens meant tokens could
be bizarrely removed from categories. For example, with the
following two messages we'd put them in the same category but say
that "started" was not a common token:
- Service abcd was started
- Service reaper was started
This happens because "abcd" is not a dictionary word but "reaper"
is, so then "started" has weight 6 in the first message but weight
31 in the second. Considering "started" to NOT be a …

[ML] Adjacency weighting fixes in categorization

---

docs/CHANGELOG.asciidoc
include/core/CWordDictionary.h
include/core/WindowsSafe.h
include/model/CTokenListCategory.h
include/model/CTokenListDataCategorizer.h
include/model/CTokenListDataCategorizerBase.h
lib/core/unittest/CWordDictionaryTest.cc
lib/model/CTokenListCategory.cc
lib/model/CTokenListDataCategorizerBase.cc
lib/model/unittest/CTokenListDataCategorizerTest.cc
mk/windows.mk

In #1903 we changed dictionary weighting in categorization to give
higher weighting when there were 3 or more adjacent dictionary
words. This was the first time that we'd ever had the situation
where the same token could have a different weight in different
messages. Unfortunately the way this interacted with us requiring
equal weights when checking for common tokens meant tokens could
be bizarrely removed from categories. For example, with the
following two messages we'd put them in the same category but say
that "started" was not a common token:
- Service abcd was started
- Service reaper was started
This happens because "abcd" is not a dictionary word but "reaper"
is, so then "started" has weight 6 in the first message but weight
31 in the second. Considering "started" to NOT be a …

[7.17] [ML] Adjacency weighting fixes in categorization

---

docs/CHANGELOG.asciidoc
include/maths/time_series/CTimeSeriesDecomposition.h
include/maths/time_series/CTimeSeriesDecompositionDetail.h
include/maths/time_series/CTimeSeriesDecompositionInterface.h
include/maths/time_series/CTimeSeriesDecompositionStub.h
include/maths/time_series/CTimeSeriesTestForChange.h
lib/api/CAnomalyJob.cc
lib/maths/time_series/CTimeSeriesDecomposition.cc
lib/maths/time_series/CTimeSeriesDecompositionDetail.cc
lib/maths/time_series/CTimeSeriesDecompositionStub.cc
lib/maths/time_series/CTimeSeriesModel.cc
lib/maths/time_series/CTimeSeriesTestForChange.cc
lib/maths/time_series/unittest/CTimeSeriesModelTest.cc

We have some code which affects the weighting we apply to outliers immediately after detecting a change in a time series. This is to deal with time series which flip-flop between values: we don't want to flag every change as anomalous, but rather learn the "envelope" of the changes. However, we need to be a bit more careful than we are with allowing the model to incorporate unusual values just after a change. If we get unlucky and there is a large outlier around this time it pollutes the model.
To address the flip-flop case we simply need to increase the weight of values whose prediction error is on the same scale as the change we detected. Values whose prediction error is significantly larger can be reweighted as normal. I noticed this while debugging #2276.
**Before**
**After**

[ML] Improve robustness to outliers after detecting changes in time series

---

lib/maths/time_series/CCalendarCyclicTest.cc

#2270 showed up an edge case which caused us to start generating error messages in one of our QA tests. We simply need to exit early in this case.
Although this could in theory have happened before, we've never seen the error, so I'm marking as a non-issue since it doesn't seem worthwhile documenting.

[ML] Trap edge case leading to "No values added to quantile sketch" log error

---

docs/CHANGELOG.asciidoc
include/core/CWordDictionary.h
include/core/WindowsSafe.h
include/model/CTokenListCategory.h
include/model/CTokenListDataCategorizer.h
include/model/CTokenListDataCategorizerBase.h
lib/core/unittest/CWordDictionaryTest.cc
lib/model/CTokenListCategory.cc
lib/model/CTokenListDataCategorizerBase.cc
lib/model/unittest/CTokenListDataCategorizerTest.cc
mk/windows.mk

In #1903 we changed dictionary weighting in categorization to give
higher weighting when there were 3 or more adjacent dictionary
words. This was the first time that we'd ever had the situation
where the same token could have a different weight in different
messages. Unfortunately the way this interacted with us requiring
equal weights when checking for common tokens meant tokens could
be bizarrely removed from categories. For example, with the
following two messages we'd put them in the same category but say
that "started" was not a common token:
- Service abcd was started
- Service reaper was started
This happens because "abcd" is not a dictionary word but "reaper"
is, so then "started" has weight 6 in the first message but weight
31 in the second. Considering "started" to NOT be a …

[8.2] [ML] Adjacency weighting fixes in categorization

---

docs/CHANGELOG.asciidoc
lib/maths/common/CGammaRateConjugate.cc
lib/maths/common/CNaturalBreaksClassifier.cc
lib/maths/common/CSampling.cc
lib/maths/common/CTools.cc
lib/maths/common/unittest/CToolsTest.cc

Recent changes to anomaly detection code exposed a pre-existing bug in sampling code for one of our distribution models. In particular, we were computing `E[X 1{[a, b]}] / E[1{[a, b]}]` for log-normal and gamma distributions and not properly handling the case `a -> 0`. As `a` gets close to 0 one can simply snap it to 0 and use an alternative form for `E[X 1{[0, b]}]` which is more numerically pleasant. Even then we can run into `E[X 1{[a, b]}] / E[1{[a, b]}] = 0/0` for finite precision. In this case, we need to compute an asymptotic approximation.
The upshot is previously we would generate NaN samples. These were subsequently discarded, so as far as I can tell the actual impact isn't too severe. However, it would generate log errors when we trapped and discarded the bad values.

[ML] Fix a source of "Discarding sample = nan, weights = ..." log errors

---

docs/CHANGELOG.asciidoc
include/model/CAnomalyScore.h
lib/api/unittest/CResultNormalizerTest.cc
lib/model/CAnomalyScore.cc
lib/model/unittest/CAnomalyScoreTest.cc
lib/model/unittest/CHierarchicalResultsTest.cc

This changes the way we normalise for short bucket lengths.
Previously, we tried to apply consistent rate limiting of alerts across different bucket lengths by accounting for the different number of results we receive per time interval. The approach we took proved to interact badly with uncertainty in the estimates of extreme quantiles. The upshot is we actually could get bias where our scores would be too low short bucket lengths. The problem was particularly severe if the time series had extended runs of unusual values.
This takes a different approach: we simply only update the quantiles with the high water mark in each fixed time interval. This achieves the same thing, but works reliably for shorter bucket lengths. I've added a test that rate limiting is working as expected across …

[ML] Improve normalisation of anomaly detection results for short bucket lengths

---

3rd_party/licenses/libxml2-INFO.csv
build-setup/linux.md
build-setup/windows.md
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/linux_aarch64_native_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_aarch64_native_tester/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_image/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
dev-tools/download_windows_deps.ps1
docs/CHANGELOG.asciidoc

Upgrades libxml2 to version 2.9.14 on Linux and Windows.
(On macOS, as before, we use the libxml2 that ships with the OS.)

[ML] Upgrade libxml2 to version 2.9.14

---

dev-tools/run_es_tests.sh

PR CI tests run some of the Elasticsearch integration tests.
We've always had a slightly hacky way of doing this on
linux-aarch64.  For JDK 17 things are a bit different because
Java has fixed the page size issues that affected earlier
versions.  Each Elasticsearch CI worker now has a symlink
from "jdk17" to the actual JDK directory on the machine, so
we should use that.
This PR should fix errors like "ERROR: JAVA_HOME is set to an
invalid directory: /var/lib/jenkins/.java/adoptopenjdk17" in
https://elasticsearch-ci.elastic.co/job/elastic+machine-learning+pull-request+linux-aarch64/1198/console
Backport of #2160

[7.17] [ML] Fixing the way we set up the ES JVM on linux-aarch64

---

.clang-tidy
docs/CHANGELOG.asciidoc
include/core/CContainerPrinter.h
include/maths/analytics/CBoostedTreeFactory.h
include/maths/analytics/CBoostedTreeHyperparameters.h
include/maths/common/CBayesianOptimisation.h
include/maths/common/CLinearAlgebraEigen.h
lib/core/unittest/CContainerPrinterTest.cc
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeHyperparameters.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/unittest/CBoostedTreeHyperparametersTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/common/CBayesianOptimisation.cc
lib/maths/common/unittest/CBayesianOptimisationTest.cc

This PR enables the early stopping of hyperparameter tuning after the coarse parameter tuning. Skipping fine parameter tuning should improve training time at the cost of potentially slightly lower accuracy.

[ML] Early stopping for coarse parameter tuning

---

include/api/CDataFrameTrainBoostedTreeRunner.h
include/api/CInferenceModelMetadata.h
include/core/CDataFrame.h
include/maths/analytics/CBoostedTreeFactory.h
include/maths/analytics/CBoostedTreeImpl.h
include/maths/analytics/CBoostedTreeUtils.h
include/maths/analytics/CDataFrameCategoryEncoder.h
include/maths/common/CNaturalBreaksClassifier.h
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/api/CInferenceModelMetadata.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/api/unittest/testfiles/model_meta_data/model_meta_data.schema.json
lib/core/CDataFrame.cc
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/CDataFrameCategoryEncoder.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/analytics/unittest/CDataFrameCategoryEncoderTest.cc
lib/maths/analytics/unittest/COutliersTest.cc

We were missing memory management for the new incremental training, prediction and compute encodings tasks. This change adds it in. Note that we also need to write out the trained model size to meta data and supply this when we call tasks which load a pre-existing model to do proper accounting.
Closes #1790.

[ML] Memory management for incremental training

---

include/core/CStaticThreadPool.h
lib/core/CStaticThreadPool.cc
lib/core/unittest/CStaticThreadPoolTest.cc

We had a race in our test of limiting the number of threads in use. It was possible for a worker thread to have loaded `m_NumberThreadsInUse` before it got reset in the main thread and so steal one task. This was causing occasional test failures. 
We don't care about this in practice. We only expect that the thread pool soon adapts to only scheduling tasks on a limited number of threads after making a change to `m_NumberThreadsInUse` (thread specific queues need to be drained anyway). Therefore, we simply update the test logic to reflect that this can happen.
Fixes #2263

[ML] Fix flaky test

---

CMakeLists.txt
lib/ver/CMakeLists.txt

Our CI build scripts explicitly specify the toolchain file
on the command line. To simplify developer builds allow
the toolchain to be obtained from an environment variable,
failing that the toolchain is determined from host processor
and platform

[ML] Determine default value for cmake toolchain file

---

include/maths/analytics/CBoostedTreeHyperparameters.h
include/maths/common/CLinearAlgebraEigen.h
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeHyperparameters.cc

We were running into an issue where we decide during coarse tuning that there was no advantage in adjusting a hyperparameter further, but this wasn't reflected in vectors we captured for testing whether to skip fine tuning parameters. This caused a dimension mismatch when we came to perform ANOVA, which blows up an Eigen assertion in debug builds, and also caused the results to be wrong in this case.
Since this fixes a problem with #2298, which is not released yet, I've marked as a non-issue.

[ML] Fix edge cases for early stopping for training classification and regression models

---

dev-tools/mlcpp-release-notes.pl
dev-tools/run_es_tests.sh

We renamed the master branch to main in this repo a while ago.
This change renames a couple of references to master in other
repos where the branch rename occurred later.

[ML] External master -> main renames

---

include/maths/analytics/CBoostedTreeFactory.h
include/maths/analytics/CBoostedTreeHyperparameters.h
include/maths/common/CBayesianOptimisation.h
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeHyperparameters.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/common/CBayesianOptimisation.cc

There was a mistake when we decided to lock down hyperparameter values during coarse search. We would skip the parameter when initialising BO but retain the loss points. This change simply discards the points for which the parameter value doesn't match the fixed value. (It would be better to update the GP code so it can handle zero width dimensions but that is a larger change.)
We now also recheck the stopping condition after one round of fine-tune. At this point we have an estimate of cross-fold variation. Generally, non-zero variance increases the chance of stopping since maximum likelihood will prefer a flat process if the variation in the loss between parameter values is within their margin of error.
Finally, I use the several rounds of maximum likelihood when we estimate parameters …

[ML] Fix edge case early stopping when parameters are fixed during coarse tuning

---

docs/CHANGELOG.asciidoc
include/maths/analytics/CDataFrameUtils.h
include/maths/common/CBasicStatistics.h
include/maths/common/CQuantileSketch.h
jupyter/scripts/incremental_learning/origin/experiment_driver.py
jupyter/src/incremental_learning/job.py
lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/CDataFrameUtils.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/analytics/unittest/CDataFrameUtilsTest.cc
lib/maths/common/CBasicStatistics.cc
lib/maths/common/CQuantileSketch.cc
lib/maths/common/unittest/CBasicStatisticsTest.cc
lib/maths/common/unittest/CQuantileSketchTest.cc
lib/maths/time_series/CCalendarCyclicTest.cc
lib/maths/time_series/unittest/CCalendarCyclicTestTest.cc

Investigating slowdowns on a couple of large QA data sets as a result of #2298 showed up some interesting things. We spend a lot of time updating quantiles and recomputing split indices for the data sets which slowed down. These data sets have relatively many metric features and the runtime share of these operations is larger in such cases. This change introduces some changes to address long run times in such cases. 
I'd planned to use a fast version of the quantile sketch, but a silly mistake meant it never actually got wired in. I've also made a further tweak to the fast version which gives it another 50% performance boost at the expense of slightly changing its behaviour. I tested accuracy fairly extensively for the new scheme, which still often produces the same results, and found no …

[ML] Address some bottlenecks training classification and regression models on large data sets

---

include/core/CPersistUtils.h
include/maths/analytics/CBoostedTreeHyperparameters.h
include/maths/analytics/CBoostedTreeImpl.h
include/maths/common/CBayesianOptimisation.h
include/maths/common/CChecksum.h
include/maths/common/CSampling.h
lib/core/unittest/CPersistUtilsTest.cc
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeHyperparameters.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/unittest/CBoostedTreeHyperparametersTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/common/CBayesianOptimisation.cc
lib/maths/common/CSampling.cc
lib/maths/common/unittest/CBayesianOptimisationTest.cc

We can use bootstrap estimates of the sample error in the test loss to better decide if we should continue searching hyperparameters: any variation which is small on the scale of the sample error is not worth burning runtime on.
Also, I've allowed us to decide just to use a hold out set if training data are plentiful rather than cross-validating. This will save us 50% of fine tune on large data sets.
This logically belongs with #2332: speed ups for large data sets. As such I don't want to document separately and marking as a non-issue.

[ML] Bootstrap estimate sample error in the test loss for training classification and regression models

---

build.gradle

As some of the more basic CI workers don't have cmake installed only use
the portable cmake dependency report script on Windows

[ML] Revert to using dependency_report.sh on Mac/Linux

---

lib/api/unittest/CSerializableToJsonTest.cc
lib/core/unittest/CLoggerTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/analytics/unittest/Main.cc
lib/maths/common/unittest/Main.cc
lib/maths/time_series/unittest/CSignalTest.cc
lib/maths/time_series/unittest/Main.cc

Currently our CI test reports are not great.
- They mix the results from the three maths libraries together,
which confuses the timings.
- Tests that don't make any assertions cause a very weird test
result structure.
This change:
- Splits out the results from the three maths libraries into
different packages.
- Ensures every test makes at least one assertion.

[ML] Clean up CI test reports

---

lib/core/unittest/CLoggerTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/analytics/unittest/Main.cc
lib/maths/common/unittest/Main.cc
lib/maths/time_series/unittest/CSignalTest.cc
lib/maths/time_series/unittest/Main.cc

Currently our CI test reports are not great.
- They mix the results from the three maths libraries together,
which confuses the timings.
- Tests that don't make any assertions cause a very weird test
result structure.
This change:
- Splits out the results from the three maths libraries into
different packages.
- Ensures every test makes at least one assertion.
Backport of #2348

[7.17] [ML] Clean up CI test reports

---

lib/core/unittest/CLoggerTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/analytics/unittest/Main.cc
lib/maths/common/unittest/Main.cc
lib/maths/time_series/unittest/CSignalTest.cc
lib/maths/time_series/unittest/Main.cc

Currently our CI test reports are not great.
- They mix the results from the three maths libraries together,
which confuses the timings.
- Tests that don't make any assertions cause a very weird test
result structure.
This change:
- Splits out the results from the three maths libraries into
different packages.
- Ensures every test makes at least one assertion.
Backport of #2348

[8.3] [ML] Clean up CI test reports

---

lib/core/unittest/CCompressedLfuCacheTest.cc

Similar to #2348, this PR is adding an assertion to a test
that didn't previously have one, so that it doesn't mess
up the CI test report format.

[ML] Add an assertion to CCompressedLfuCacheTest

---

bin/pytorch_inference/CThreadSettings.cc
bin/pytorch_inference/CThreadSettings.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/unittest/CThreadSettingsTest.cc

The Java code now works on the basis that `num_threads_per_allocation`
should be multiplied by the number of allocations to give the total
number of threads required.
This PR changes the C++ code to reflect that.
The logic for calling `at::set_num_threads()` and
`ml::core::defaultAsyncExecutor().numberThreadsInUse()` was already
correct given how libgomp on Linux does threading, but this PR
fixes the validation, adds comments and corrects the variable
names in the unit test.

[ML] Adjust PyTorch thread setting naming and validation

---

include/core/CCompressedLfuCache.h
include/core/CMemory.h
lib/core/unittest/CCompressedLfuCacheTest.cc

The LFU cache was assuming that if a new item wouldn't
fit into it then there must already be a cached item
in it. This wasn't true in the case of a very tiny
cache size.
The code now accounts for the possibility of an item
not fitting into an empty cache.
This scenario was always very unlikely in production,
but more likely for test scenarios.
Fixes #2370

[ML] Handle cache size too small for single item

---

docs/CHANGELOG.asciidoc
include/maths/common/CQuantileSketch.h
include/model/CGathererTools.h
include/model/CMetricStatisticWrappers.h
lib/api/CHierarchicalResultsWriter.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/common/CQuantileSketch.cc
lib/maths/common/unittest/CQuantileSketchTest.cc
lib/maths/time_series/unittest/CCalendarCyclicTestTest.cc
lib/model/unittest/CDetectorEqualizerTest.cc
lib/model/unittest/CMetricModelTest.cc

We use a histogram sketch for estimating data quantiles and also computing the time bucket median for anomaly detection.
Once data are merged into buckets we have to make some assumptions about how values are distributed on buckets. Previously, we assumed data are uniformly distributed on buckets whose endpoints are the midpoints between the bucket "centres" we track. In fact, the points we track are the weighted means of the values in each bucket, so it is more accurate to assume that roughly half the data in a bucket falls either side of this point.
This changes the interpolation scheme to use the same endpoints but to incorporate this new assumption. This gives a very nice additional property: a quantile which falls between two buckets each containing a single value is computed …

[ML] Improve quantile estimation accuracy and median accuracy for anomaly detection

---

bin/pytorch_inference/CCommandParser.cc
bin/pytorch_inference/Main.cc

This is a companion to https://github.com/elastic/elasticsearch/pull/88287.
In addition to adding a `cache_hit` indicator, the meaning of `time_ms` is
changed from "original inference time" to "cache lookup plus inference time
if necessary".

[ML] Adding a cache_hit indicator to inference results

---

bin/pytorch_inference/CCommandParser.cc
bin/pytorch_inference/CCommandParser.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/unittest/CCommandParserTest.cc
include/core/CCompressedLfuCache.h
lib/core/unittest/CCompressedLfuCacheTest.cc

This is likely to be useful for QA performance tests once
it's exposed on the Java side.

[ML] Add a "clear cache" control message to pytorch_inference

---

lib/maths/analytics/CBoostedTreeImpl.cc

#2339 introduced an inefficiency where we calculate loss per row more times than we should. This showed up as surprisingly expensive in profiling. This hasn't been released so marking as a non-issue.

[ML] Fix inefficiency in bootstrap loss calculation

---

lib/maths/analytics/CBoostedTreeImpl.cc

#2339 introduced an inefficiency where we calculate loss per row more times than we should. This showed up as surprisingly expensive in profiling.

[8.4][ML] Fix inefficiency in bootstrap loss calculation (#2377)

---

bin/controller/unittest/Main.cc
bin/pytorch_inference/unittest/Main.cc
lib/api/unittest/Main.cc
lib/core/unittest/Main.cc
lib/maths/analytics/unittest/Main.cc
lib/maths/common/unittest/Main.cc
lib/maths/time_series/unittest/Main.cc
lib/model/unittest/Main.cc
lib/seccomp/unittest/Main.cc
lib/ver/unittest/Main.cc

These have had a silly mistake ever since they were written.
The observer was unregistered after main() returned. Clearly
it didn't matter, as the program was about to exit anyway,
but it's nice to tidy up the code.

[ML] Fix main() functions for test suites

---

docs/CHANGELOG.asciidoc
include/maths/common/CQuantileSketch.h
include/model/CGathererTools.h
include/model/CMetricStatisticWrappers.h
lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/analytics/unittest/CDataFrameUtilsTest.cc
lib/maths/common/CQuantileSketch.cc
lib/maths/common/unittest/CQuantileSketchTest.cc
lib/maths/time_series/unittest/CCalendarCyclicTestTest.cc
lib/model/unittest/CDetectorEqualizerTest.cc
lib/model/unittest/CMetricModelTest.cc

[7.17][ML] Improve quantile estimation accuracy and median accuracy for anomaly detection

---

bin/pytorch_inference/CResultWriter.cc
include/core/CRapidJsonLineWriter.h

In #2376 the results writer for inference was changed
to splice a preformatted cached section of the final result
document into an outer wrapper that varies per request.
The approach used worked when assertions were disabled but
tripped assertions in RapidJSON due to its internal counters
thinking that the spliced portion was a single value instead
of a key and value together.
This PR fixes the code when assertions are enabled by
taking advantage of the fact that the internal value
count of the RapidJSON writer is accessible to derived
classes, so we can add a method that adds a key and
value together and increments the counter twice.

[ML] Fix debug build for raw JSON splicing

---

docs/CHANGELOG.asciidoc
lib/maths/analytics/CBoostedTreeImpl.cc

Debugging an intermittent SIGSEGV triggered by another change I'm working on showed up this potential out-of-bounds read. It would happen very infrequently. It was introduced by #1537.

[ML] Fix potential out-of-bounds read

---

dev-tools/jenkins_cross_compile.sh
lib/maths/analytics/CBoostedTreeImpl.cc

People rarely build the code with debug enabled, so it's
possible for an error in the code that only affects debug
builds to get committed.
This change adds a step to build (but not unit test) the
code with debug enabled in every PR build. Doing this in
the cross compile sub-job should mean that it doesn't
increase the overall PR CI duration, as the cross compile
sub-job is faster than the sub-jobs that run unit tests.

[ML] Detect debug-only compile errors in PR builds

---

docs/CHANGELOG.asciidoc
include/maths/analytics/CBoostedTreeLeafNodeStatistics.h
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/CBoostedTreeLeafNodeStatistics.cc
lib/maths/analytics/CBoostedTreeLeafNodeStatisticsIncremental.cc
lib/maths/analytics/CBoostedTreeLeafNodeStatisticsScratch.cc

Profiling showed we spend a surprising amount of time creating and destroying leaf statistics state training on large data sets. These objects are large O("number splits" * "number features" * ("gradient" + "hessian")) we also have to map out the memory of individual split vectors and this work has to be done each time we allocate a new object. In fact, we can just recycle the objects when we determine that no splits are useful at a leaf as long as the objects are "conformable", i.e. same dimensions, which they usually are.
This change saves up to 40% of the work on the main thread for some data sets, it should also lead to better LOR. It logically belongs with #2380 so I'll document together with that change.

[ML] Improve memory management for training on large data sets

---

docs/CHANGELOG.asciidoc
include/core/CFloatStorage.h
include/core/CMemoryDef.h
include/maths/analytics/CBoostedTreeImpl.h
include/maths/analytics/CBoostedTreeUtils.h
include/maths/common/CQuantileSketch.h
include/model/CDetectorEqualizer.h
include/model/CGathererTools.h
include/model/CMetricStatisticWrappers.h
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/CDataFrameUtils.cc
lib/maths/analytics/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/analytics/unittest/CDataFrameUtilsTest.cc
lib/maths/common/CQuantileSketch.cc
lib/maths/common/unittest/CQuantileSketchTest.cc
lib/maths/time_series/CCalendarCyclicTest.cc
lib/model/CDetectorEqualizer.cc

This is the second part of #2380.
Quantile estimation during training is expensive for data sets with many numeric features. This change makes various speed ups in this area:
1. Batch computes merge costs using explicit vectorisation,
2. Use a larger reduce factor when merging buckets. I've held the reduced size fixed to maintain roughly similar accuracy, the upshot being more memory but less work per bucket,
3. Improve handling of duplicate values: we should deduplicate new values before merging because it reduces the cost of `inplace_merge`,
4. Be a bit more careful with how random numbers for tiebreaks are generated.
Together these drop the amortised add cost from around 100ns to 50ns per item on my i9. The remaining costs are 50% `std::nth_element` and 30% `std::sort` + …

[ML] Improve quantile estimation performance for train

---

docs/CHANGELOG.asciidoc
include/api/CDataFrameTrainBoostedTreeRunner.h
include/maths/analytics/CBoostedTree.h
include/maths/analytics/CBoostedTreeFactory.h
include/maths/analytics/CBoostedTreeLeafNodeStatistics.h
include/maths/analytics/CBoostedTreeLeafNodeStatisticsIncremental.h
include/maths/analytics/CBoostedTreeLeafNodeStatisticsScratch.h
include/maths/analytics/CBoostedTreeLeafNodeStatisticsThreading.h
include/maths/analytics/CBoostedTreeLoss.h
include/maths/analytics/CBoostedTreeUtils.h
lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
lib/api/CDataFrameTrainBoostedTreeRunner.cc
lib/maths/analytics/CBoostedTree.cc
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeImpl.cc
lib/maths/analytics/CBoostedTreeLeafNodeStatistics.cc
lib/maths/analytics/CBoostedTreeLeafNodeStatisticsIncremental.cc
lib/maths/analytics/CBoostedTreeLeafNodeStatisticsScratch.cc
lib/maths/analytics/CBoostedTreeLeafNodeStatisticsThreading.cc
lib/maths/analytics/CBoostedTreeLoss.cc
lib/maths/analytics/CBoostedTreeUtils.cc
lib/maths/analytics/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
lib/maths/analytics/unittest/CBoostedTreeLossTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc

This addresses the bottleneck preventing us from increasing the maximum number of distinct classes we'll support and raises the limit from 30 to 100.
The issue is computing the hessian which scales like `n(n+1)/2` for `n` distinct classes. Here I've taken the approach of targeting just the classes which satisfy `arg top-k_{c \in C}{ \sum_i 1{c_i = c} loss(p_i, c_i) }` where `p_i` are the prediction probabilities for the i'th example, `c_i` is the true class, `C` is the set of all classes and `1{.}` denotes the indicator function, when computing best splits. This limits the hessian to `k(k+1)/2` and I've capped `k` at 20. We simply lump all classes not selected into a hold all other class when we chose the best splits and compute the expected derivatives of the loss for them. However, …

[ML] Raise the limit on maximum number of classes for multi-class classification

---

docs/CHANGELOG.asciidoc
include/model/CTokenListDataCategorizerBase.h
lib/model/CTokenListDataCategorizerBase.cc
lib/model/unittest/CTokenListDataCategorizerTest.cc

In categorization, when a new message matches an existing category
we don't need to keep a record of any new distinct tokens found in
the new message, as the category definition doesn't need them.
We used to store all unique tokens ever seen, but this can lead to
unbounded memory build-up if a particular type of logs has some
sort of unique ID that doesn't get filtered by the token filter of
the categorization analyzer.
This PR removes new distinct tokens from the token store for all
code paths other than a message causing a new category to be
created.

[ML] Don't keep categorization tokens when existing category matches

---

docs/CHANGELOG.asciidoc
include/model/CTokenListDataCategorizerBase.h
lib/model/CTokenListDataCategorizerBase.cc
lib/model/unittest/CTokenListDataCategorizerTest.cc

In categorization, when a new message matches an existing category
we don't need to keep a record of any new distinct tokens found in
the new message, as the category definition doesn't need them.
We used to store all unique tokens ever seen, but this can lead to
unbounded memory build-up if a particular type of logs has some
sort of unique ID that doesn't get filtered by the token filter of
the categorization analyzer.
This PR removes new distinct tokens from the token store for all
code paths other than a message causing a new category to be
created.
Backport of #2398

[8.4] [ML] Don't keep categorization tokens when existing category matches

---

docs/CHANGELOG.asciidoc
include/model/CTokenListDataCategorizerBase.h
lib/model/CTokenListDataCategorizerBase.cc
lib/model/unittest/CTokenListDataCategorizerTest.cc

In categorization, when a new message matches an existing category
we don't need to keep a record of any new distinct tokens found in
the new message, as the category definition doesn't need them.
We used to store all unique tokens ever seen, but this can lead to
unbounded memory build-up if a particular type of logs has some
sort of unique ID that doesn't get filtered by the token filter of
the categorization analyzer.
This PR removes new distinct tokens from the token store for all
code paths other than a message causing a new category to be
created.
Backport of #2398

[7.17] [ML] Don't keep categorization tokens when existing category matches

---

include/maths/common/COrderings.h

This only shows up as a problem when inlining is disabled.
Followup to #2397

[ML] Add missing Windows export

---

docs/CHANGELOG.asciidoc
lib/api/CDataFrameTrainBoostedTreeRunner.cc

Java backend was passing the seed configuration parameter using the name `randomize_seed`, while C++ code was expecting `seed`. This PR fixes the misalignment.

[ML] Fix seed parameter name

---

include/maths/common/CSampling.h
include/maths/time_series/CTimeSeriesDecompositionDetail.h
lib/maths/analytics/CBoostedTreeFactory.cc
lib/maths/analytics/CBoostedTreeLoss.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/common/unittest/CSamplingTest.cc

In the case that all the samples are duplicates, merging our stream dissimilar vector sampler discards all samples. This behaviour was introduced by #2401: subsequently categorical sample without replacement will not select any sample with zero weight. The upshot is that leaf weight estimation for multi-class classification, which makes use of this class, could yield undefined behaviour. I now explicitly trap the error case and fail gracefully. I also explicitly handle duplicates in both sampling and merging dissimilar vector samplers.
This fixes fallout from #2401. Since this isn't released I've marked as a non-issue.

[ML] Fix failure computing leaf values with multithreading for multi-class classification

---

lib/api/CDataFrameTrainBoostedTreeRunner.cc

In #2404 we used `std::size_t` as the data type for the `radomize_seed` parameter. However, Java uses a larger type. Hence, we change the C++ parameter to `std::ptrdiff_t` to accommodate for this.

[ML] Change randomize_seed parameter type

---

devbin/model_extractor/Main.cc
docs/CHANGELOG.asciidoc
lib/model/CIndividualModel.cc
lib/model/CMetricModel.cc

An anomaly detector job ignores records that fall in the initial, incomplete bucket. However, a model is created with a start time of -1 in the expectation that more records will be received that fall into subsequent buckets. In the case that no more records are received the model continues to exist with start time of -1.
In the scenario that a job is created initially as lookback and has such models with start time of -1 in existence at the point the job closes, and then is re-opened as a realtime job at some point in the future, any attempt to sample the model will fail with the 'No statistics at ...' error message due to the start time (-1) falling outside the current bucket.
This change always updates the model's current bucket stats start time to that of the current record, even if …

[ML] Fix for 'No statistics' error message

---

bin/pytorch_inference/CCmdLineParser.cc
bin/pytorch_inference/CCmdLineParser.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/evaluate.py

This commit adds an option `--lowPriority` to the pytorch_inference program so it can be run in low priority.

[ML] Add option to run pytorch_inference in low priority

---

lib/maths/time_series/CTimeSeriesModel.cc

To investigate the impact of the confidence interval computation for anomalies this PR temporarily deactivates the functionality.

[ML] Deactivate confidence bounds computation

---

lib/maths/time_series/CTimeSeriesModel.cc

Since the anomaly length in buckets is computed as the difference between the bucket timestamps, for the first occurance of the anomaly the method was returning the length 0. This PR adds +1 makes the first occurance has the bucket length 1.

[ML] Fix anomaly length computation

---

docs/CHANGELOG.asciidoc
include/core/CDetachedProcessSpawner.h
lib/core/CDetachedProcessSpawner.cc

Before spawning new processes from the `controller` we close all open file descriptors except for stdin, stdout and stderr.
Previously this was done by checking every possible file descriptor to see if it was open, but this is very expensive if the file descriptor limit is high.  During a lookback a large number of `normalize` processes get started, and this could lead to significant CPU usage by the `controller` process.
This change makes the file closure code learn the highest open file descriptor each time it is used, and work on the basis that no more than 10 files will be opened in between calls to it. This significantly reduces `controller` CPU usage on machines that have high file descriptor limits and run a lot of `normalize` processes.

[ML] Improve performance of closing files before spawning

---

docs/CHANGELOG.asciidoc
include/core/CDetachedProcessSpawner.h
lib/core/CDetachedProcessSpawner.cc

Before spawning new processes from the `controller` we close all open file descriptors except for stdin, stdout and stderr.
Previously this was done by checking every possible file descriptor to see if it was open, but this is very expensive if the file descriptor limit is high.  During a lookback a large number of `normalize` processes get started, and this could lead to significant CPU usage by the `controller` process.
This change makes the file closure code learn the highest open file descriptor each time it is used, and work on the basis that no more than 10 files will be opened in between calls to it. This significantly reduces `controller` CPU usage on machines that have high file descriptor limits and run a lot of `normalize` processes.
Backport of #2424

[8.6] [ML] Improve performance of closing files before spawning

---

lib/api/CJsonOutputWriter.cc
lib/api/CModelSnapshotJsonWriter.cc
lib/core/CJsonLogLayout.cc
lib/core/CMemoryUsageJsonWriter.cc
lib/core/CProgramCounters.cc

Rapidjson introduced a `Key()` function on the writers which is effectively the same as `String()`. However, using it where keys are written improves readability of the code.
Closes #383

[ML] Use rapidjson's key function where possible

---

CONTRIBUTING.md
bin/pytorch_inference/CCmdLineParser.cc
build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/linux_aarch64_native_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_aarch64_native_tester/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_image/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
dev-tools/docker/macosx_builder/Dockerfile
dev-tools/docker/macosx_image/Dockerfile
dev-tools/download_macos_deps.sh
dev-tools/download_windows_deps.ps1
docs/CHANGELOG.asciidoc

Upgrade to the latest version of PyTorch 1, which is 1.13.1.
The version of Python used for the build is also upgraded, from 3.7 to 3.10. Python 3.10 runs natively on macOS on ARM, and this makes the macOS ARM build much less fiddly and error-prone.

[ML] Upgrade PyTorch to version 1.13.1

---

build-setup/macos.md

Small typo, an extra `x` in the link

[ML] Fix link to Python download in macOS setup instructions

---

build-setup/windows.md

On Windows, recent updates of Visual Studio 2019 include an experimental improved OMP library. Because this library is experimental redistribution is not permitted.
When we built PyTorch 1.13.1 CMake's FindOpenMP module decided to link to this experimental OMP library, which then means the resulting library only works on machines with Visual Studio installed.
It's not very clear where in the PyTorch build configuration the fault lies. It could be in CMake itself or maybe there's some option PyTorch could be using to control CMake more tightly. CMake was _also_ linking to Microsoft's GA OMP library, so this PR works around the problem by temporarily renaming the experimental libraries during the build so that CMake does not find them.
Fixes #2432

[ML] Fix instructions for building PyTorch on Windows

---

.buildkite/job-build-test-all-debug.yml

Fix formatting in `.buildkite/job-build-test-all-debug.yml` such that the pipeline for the nightly debug build executes.

[ML] Perform a nightly debug build with assertions enabled

---

.buildkite/pipeline.yml
.buildkite/scripts/steps/upload_to_s3.sh

Take into account that BuildKite always sets a value for BUILDKITE_PULL_REQUEST and that it is set to "false" for non PR builds.

Fix s3 upload script

---

.buildkite/pipeline.yml
dev-tools/aws_creds_from_vault.sh
dev-tools/docker/build_linux_jdk.sh
dev-tools/docker/ml_cpp_jdk/Dockerfile

Fix a typo affecting the path to the AWS credentials used for uploading artifacts to S3

[ML] Correct path to AWS credentials in CI vault

---

docs/CHANGELOG.asciidoc
include/maths/common/CModel.h
include/maths/common/COneOfNPrior.h
include/maths/common/CPrior.h
include/maths/time_series/CTimeSeriesModel.h
lib/api/CJsonOutputWriter.cc
lib/maths/common/COneOfNPrior.cc
lib/maths/common/CPrior.cc
lib/maths/common/unittest/COneOfNPriorTest.cc
lib/maths/time_series/CTimeSeriesModel.cc

As an enhancement for explaining anomalies, it would be helpful to inform the users whether the prior distribution of the observed time series is multi-modal or has a single mode. For instance, if the distribution has two modes, the typical value may lie between the modes and hence not constitute the most probable value.
Closes #2416.

[ML] Identify multimodal prior distributions for anomaly explanation

---

.buildkite/branch.json.py
.buildkite/branch.yml
.buildkite/dra.json.py
.buildkite/job-build-test-all-debug.json.py
.buildkite/ml_pipeline/config.py
.buildkite/ml_pipeline/step.py
.buildkite/pipeline.json.py
.buildkite/pipelines/build_linux.json.py
.buildkite/pipelines/build_macos.json.py
.buildkite/pipelines/build_windows.json.py
.buildkite/pull-requests.json
.buildkite/scripts/steps/build_and_test.sh
.buildkite/scripts/steps/run_es_tests.sh
.buildkite/snapshot.yml
.buildkite/staging.yml

Separate the concerns of branch builds away from those of PR builds. This simplifies and fixes a problem of the latter whereby builds were being triggered twice, once by BuildKite directly and again from an API call from within a PR webhook.

Add separate BuildKite pipeline for branch builds

---

.buildkite/branch.json.py
.buildkite/dra.json.py
.buildkite/job-build-test-all-debug.json.py
.buildkite/ml_pipeline/config.py
.buildkite/ml_pipeline/step.py
.buildkite/pipelines/build_linux.json.py
.buildkite/pipelines/build_macos.json.py
.buildkite/pipelines/build_windows.json.py
.buildkite/pull-requests.json
.buildkite/scripts/steps/build_and_test.sh
.buildkite/scripts/steps/run_es_tests.sh
.buildkite/snapshot.yml
.buildkite/staging.yml

Separate the concerns of branch builds away from those of PR builds. This simplifies and fixes a problem of the latter whereby builds were being triggered twice, once by BuildKite directly and again from an API call from within a PR webhook.
Backports #2452

[8.7][ML]Add separate BuildKite pipeline for branch builds (#2452)

---

bin/pytorch_inference/Main.cc
docs/CHANGELOG.asciidoc
include/core/CConcurrentQueue.h
include/core/CConcurrentWrapper.h
include/core/CJsonOutputStreamWrapper.h
include/core/CStaticThreadPool.h
include/core/Concurrency.h
lib/core/CJsonOutputStreamWrapper.cc
lib/core/CStaticThreadPool.cc
lib/core/Concurrency.cc
lib/core/unittest/CConcurrentWrapperTest.cc

`CstaticThreadPool` uses a `CConcurrentQueue` to buffer work. The size of the work queue is a template parameter which makes it difficult to change in `CstaticThreadPool`. This change makes the queue size an ctor argument which is passed down to `CConcurrentQueue`
The `pytorch_inference` app is changed to use a queue of 1.
The motivation for this change is to avoid queuing work in the `pytorch_inference` process as requests are already queued on the Java side and certain features require the ability to jump to the front of the queue. Also the number of items in the Java queue is reported via the stats API but that number is not accurate if work is also queued in `pytorch_inference`.

Parameterise CConcurrentQueue work queue size 

---

bin/pytorch_inference/Main.cc
docs/CHANGELOG.asciidoc
include/core/CConcurrentQueue.h
include/core/CConcurrentWrapper.h
include/core/CJsonOutputStreamWrapper.h
include/core/CStaticThreadPool.h
include/core/Concurrency.h
lib/core/CJsonOutputStreamWrapper.cc
lib/core/CStaticThreadPool.cc
lib/core/Concurrency.cc
lib/core/unittest/CConcurrentWrapperTest.cc

Work is queued in Elasticsearch and does not need to be queued here. 
Makes the queue size a ctor parameter to CConcurrentQueue.
Backport of #2456

[8.7] [ML] Use a work queue of size 1 in pytorch inference 

---

.buildkite/pull-requests.json

Since "publish_commit_status" is set to "false" on the ml-cpp pipeline it should also be disabled in the pull request config with "set_commit_status: false"
This is because the PR service only sends a commit status when it triggers the build, so if the pipeline isn't configured to send a commit status, a "complete" status will never get sent
This fixes a problem with a PR check for "ml-cpp-ci" continually stuck in the "pending" state.

[ML] Don't expect commit status in PR config

---

build.gradle

Tweak the gradle `uploadAll` task to pick up "debug" artifacts on the `7.17` branch.

Fix gradle uploadAll task to include debug artifacts

---

.buildkite/hooks/post-checkout
.buildkite/pipelines/build_linux.json.py
.buildkite/pipelines/build_macos.json.py
.buildkite/pipelines/build_windows.json.py
.buildkite/scripts/steps/build_and_test.sh

Add a step to build natively on the MacOS aarch64 VM
Backports #2470

[8.8][ML] Add native MacOS aarch64 build support in BuildKite (#2470)

---

.buildkite/hooks/post-checkout
.buildkite/pipelines/build_linux.json.py
.buildkite/pipelines/build_macos.json.py
.buildkite/pipelines/build_windows.json.py
.buildkite/scripts/steps/build_and_test.sh

Add a step to build natively on the MacOS aarch64 VM
Backports #2470

[8.7][ML] Add native MacOS aarch64 build support in BuildKite (#2470)

---

.buildkite/hooks/post-checkout
.buildkite/pipelines/build_linux.json.py
.buildkite/pipelines/build_macos.json.py
.buildkite/pipelines/build_windows.json.py
.buildkite/scripts/steps/build_and_test.sh

Add a step to build natively on the MacOS aarch64 VM
Backports #2470

[7.17][ML] Add native MacOS aarch64 build support in BuildKite (#2470)

---

set_env.sh

Our Linux build setup instructions say that cmake should be installed in /usr/local/cmake/bin, but if you do this then you could not build with Gradle because our environment file did not put this directory on the PATH.
This PR changes the PATH to include /usr/local/cmake/bin.

[ML] Fix Linux PATH in environment file

---

buildSrc/build.gradle
dev-tools/docker_build.sh
dev-tools/docker_test.sh

Our Gradle build uses the AWS SDK. We should upgrade to the latest version.
Backport of #2489

[8.8] [ML] Upgrade to latest AWS SDK version

---

buildSrc/build.gradle
dev-tools/docker_build.sh
dev-tools/docker_test.sh

Our Gradle build uses the AWS SDK. We should upgrade to the latest version.
Backport of #2489

[7.17] [ML] Upgrade to latest AWS SDK version

---

catalog-info.yaml

Ensure pipeline definitions in catalog-info.yaml are identical to those originally defined in the CI repo

[ML] Fix pipeline definitions in catalog-info.yaml

---

catalog-info.yaml

The value of the BUILD_SNAPSHOT env vars must be a quoted string, either "true" or "false"

[ML] Fix BUILD_SNAPSHOT env vars in catalog-info.yaml

---

.buildkite/pipelines/format_and_validation.yml.sh
.buildkite/pipelines/run_es_tests.yml.sh

The format validation step and the ES integration tests step were missing configuration to notify github about their status. This PR remedies that.

[ML] Add missing contexts for github commit statuses

---

.buildkite/pipelines/format_and_validation.yml.sh
.buildkite/pipelines/run_es_tests.yml.sh

The format validation step and the ES integration step were missing configuration to notify github about their status. This PR _should_ remedy that.
Backports #2513

[8.8][ML] Add missing contexts for github commit statuses (#2513)

---

.buildkite/pipelines/format_and_validation.yml.sh
.buildkite/pipelines/run_es_tests.yml.sh

The format validation step and the ES integration step were missing configuration to notify github about their status. This PR remedies that.
Backports #2513

[7.17][ML] Add missing contexts for github commit statuses (#2513)

---

.buildkite/scripts/steps/build_and_test.ps1
.buildkite/scripts/steps/build_and_test.sh

Ensure test results and output files are uploaded as artifacts should the tests fail, on all platforms.
Backports #2496

[7.17][ML] Better handle test suite failures (#2496)

---

.buildkite/scripts/steps/build_and_test.ps1
.buildkite/scripts/steps/build_and_test.sh

Ensure test results and output files are uploaded as artifacts should the tests fail, on all platforms.
Backports #2496

[8.8][ML] Better handle test suite failures (#2496)

---

.buildkite/pipelines/upload_dra_to_gcs.yml.sh
build.gradle
dev-tools/jenkins_ci.ps1
dev-tools/jenkins_ci.sh
dev-tools/jenkins_combine_artifacts.sh

For the snapshot and staging builds:
* Disable uploading from Jenkins
* Enable uploading from BuildKite
The intention is to merge this at a point where it will cause least disruption should anything go wrong.
Likewise, the backports will happen slowly, after a number of days. Again to ensure all is at it should be.

[ML] Upload build artifacts from BuildKite

---

.buildkite/pipelines/build_macos.json.py

The macos cross compilation build on the 7.17 branch is inadvertently being built with full debugging symbols. This change corrects that.

[ML] Fix macos cross compilation build for 7.17

---

.buildkite/branch.json.py
.buildkite/pipelines/create_dra.yml.sh
.buildkite/pipelines/upload_dra_to_gcs.yml.sh
.buildkite/pipelines/upload_dra_to_s3.yml.sh

Add the steps to create and upload build artifacts directly into the branch pipelines. This makes notification and diagnosis of build failures simpler.
Backports #2520

[7.17][ML] Amalgamate DRA pipeline into branch builds (#2520)

---

include/api/CAnomalyJob.h
include/api/CJsonOutputWriter.h
lib/api/CAnomalyJob.cc
lib/api/CJsonOutputWriter.cc
lib/api/unittest/CFieldDataCategorizerTest.cc

When datafeeds send flush requests they don't require the indices to be refreshed.
Round trip the "should_refresh" flag from ES to ml-cpp code and back again.

[ML] Add internal flag to flush api determining whether to refresh indices or not.

---

dev-tools/autodetect_profiling_macos/autodetect_profiling_on_macos.md
dev-tools/autodetect_profiling_macos/record_memgraph.sh
dev-tools/autodetect_profiling_macos/record_xctrace.sh

This PR adds bash scripts and a description of how to profile the anomaly detection process started from the Elasticsearch Java backend.

[ML] How to profile autodetect on MacOS

---

.buildkite/pipelines/upload_dra_to_gcs.yml.sh
.buildkite/pipelines/upload_dra_to_s3.yml.sh

The DRA upload pipelines are currently downloading required artifacts from multiple pipeline steps. While this is not an error or causing any harm it is slightly more efficient to only download the artifacts once, from the `create_dra_artifacts` step.
Backports #2534

[8.8][ML] DRA upload: Only download artifacts once (#2534)

---

.buildkite/pipelines/upload_dra_to_gcs.yml.sh
.buildkite/pipelines/upload_dra_to_s3.yml.sh

The DRA upload pipelines are currently downloading required artifacts from multiple pipeline steps. While this is not an error or causing any harm it is slightly more efficient to only download the artifacts once, from the `create_dra_artifacts` step.
Backports #2534

[7.17][ML] DRA upload: Only download artifacts once (#2534)

---

lib/core/CProcessStats_MacOSX.cc

Max RSS returned by macOS `getrusage` is in bytes not kilobytes. 
The man page for `getrusage` on my mac (Ventura 13.4) states this:
```
ru_maxrss    the maximum resident set size utilized (in bytes).
```
I think the confusion arose because a search for `macOS getrusage` takes you to the [IOS man page](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getrusage.2.html) where the `ru_maxrss` field _is_ in KB not B
Non issue as this code is not in any public release yet.

Bytes not Kilobytes

---

bin/pytorch_inference/CCommandParser.cc
bin/pytorch_inference/CCommandParser.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/evaluate.py
docs/CHANGELOG.asciidoc

Batch inference calls use more memory which can lead to OOM errors in extreme cases. This change iterates over the requests in a batch evaluating them one at a time.
Comparing batched to un-batched evaluation, benchmarking shows that memory usage is significantly lower and the total time for inference is similar in both cases. The benchmark data was generated with the ELSER model with different size batches. Each item in the batch contained 512 tokens. *Inference Time* is the time to process the entire batch whether singularly or all at once.
| Num items in request | Memory Max RSS (MB) **Batched** | Memory Max RSS (MB)  | Inference Time (ms) **Batched** |  Inference Time (ms) |
| ------------- | ------------- |---------| ---------|---------|
| 0        |          946  | 943  | 0 | 0 |
| …

[NLP] Evaluate batched inference calls singularly 

---

bin/pytorch_inference/CCommandParser.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/evaluate.py
docs/CHANGELOG.asciidoc
include/core/CCompressedLfuCache.h
lib/core/unittest/CCompressedLfuCacheTest.cc

Inference was previously wrapped in a try catch statement but that was lost during a refactoring which means the errors are swallowed by the executing thread and not propagated to the error handler. 
https://github.com/elastic/ml-cpp/commit/4266662428dd204e99a456a2a40e77bace4df44e#diff-5984f43760a98454db757ddada7f1f9f82a87ffaa4aa1c8a89966f4fc94a8829
Since the refactoring inference is performed from the `computeValue` callback of the `CCompressedLfuCache`. As inference may throw `computeValue` must handle failed computations. I've changed the signature to return a std::optional, if the nullopt is returned the cache will not cache the value.
The consequence of this is that the `readValue` function is never called if `computeValue` fails. Users must be aware that calling `lookup` on the …

[NLP] Catch exceptions thrown during inference and report as errors

---

catalog-info.yaml

Currently the default value of "main" is used for the default_branch configuration option for the "ml-cpp-pr-build" pipeline. This results in no useful information about PR build history being displayed for that pipeline in the BuildKite UI.
By explicitly setting the default_branch config option to nul BuildKite will display build information for all PR branches, which is much more useful.

[ML] Display info for all branches for PR builds

---

lib/seccomp/CSystemCallFilter_Linux.cc

In support of https://github.com/elastic/ml-cpp/pull/2487
Closes #2546
Non-issue as no production code calls getrusge

[ML] Add getrusage to list of allowed syscall

---

dev-tools/download_windows_deps.ps1

Change Windows build scripts to obtain dependency archives from a new location on GCS, rather than AWS S3, which is proving unreliable.
Labelling as a non issue as this is not a notable change for end users.

[ML] Download Windows build dependencies from GCS

---

bin/pytorch_inference/Main.cc

pytorch_inference must respond to every request as Elasticsearch is waiting for a response. The switch statement in the command handler code logged an error when an unknown command was received but did not write a response. This change adds an error response. 
In practice I cannot see how an unrecognised command could be sent as the Elasticsearch side is closely tied to pytorch_inference, I've labelled this a non-issue rather than a bug for that reason.

[NLP] Respond to the server when an unknown command is received 

---

dev-tools/download_windows_deps.ps1

Change Windows build scripts to obtain dependency archives from a new location on GCS, rather that AWS S3, which is proving unreliable.
Backports #2554

[7.17][ML] Download Windows build dependencies from GCS (#2554)

---

lib/core/CDataFrameRowSlice.cc

Our two ARM macOS build servers have somehow ended up running different versions of Xcode - one is running version 12 and the other version 13.
There have been changes to the C++ standard library between these versions that reveal a technical violation that we were previously getting away with: CDataFrameRowSlice.cc uses file streams without including the necessary header. Previously it must have been indirectly included. This PR includes it explicitly.

[ML] Include an extra header in CDataFrameRowSlice

---

include/model/CStringStore.h
lib/core/CDataFrameRowSlice.cc

Our two ARM macOS build servers have somehow ended up running different versions of Xcode - one is running version 12 and the other version 13.
There have been changes to the C++ standard library between these versions that reveal a technical violation that we were previously getting away with: CDataFrameRowSlice.cc uses file streams without including the necessary header. Previously it must have been indirectly included. This PR includes it explicitly.
Backport of #2563

[7.17] [ML] Include an extra header in CDataFrameRowSlice

---

cmake/variables.cmake

A Boost upgrade is not trivial and we don't want CMake deciding to do one for us.

[ML] Treat Boost version as exact required, not minimum

---

cmake/variables.cmake

A Boost upgrade is not trivial and we don't want CMake deciding to do one for us.
Backport of #2566

[8.9] [ML] Treat Boost version as exact required, not minimum

---

include/model/CStringStore.h
lib/core/CDataFrameRowSlice.cc

Our two ARM macOS build servers have somehow ended up running different versions of Xcode - one is running version 12 and the other version 13.
There have been changes to the C++ standard library between these versions that reveal a technical violation that we were previously getting away with: CDataFrameRowSlice.cc uses file streams without including the necessary header. Previously it must have been indirectly included. This PR includes it explicitly.
Backport of #2563

[8.10] [ML] Include an extra header in CDataFrameRowSlice

---

lib/core/unittest/CHashingTest.cc

The upgrade to Boost 1.83 has resulted in testMurmurHash failing more often. Occasional failures are expected and accounted for in the test with a "slack factor". Increase that factor to 8% to make the test more resilient.

[ML] Increase testMurmurHash slack factor to 8%

---

.buildkite/pipelines/build_linux.json.py
.buildkite/pipelines/build_macos.json.py
.buildkite/pipelines/build_windows.json.py
cmake/test-runner.cmake

It appears that the seccomp test may hang on occasion on macOS when instrumented for debug builds.
This PR attempts to gather extra information (temporarily) regarding the tests in general and the seccomp tests in particular.

[ML] Add extra debug handling for the seccomp test.

---

docs/CHANGELOG.asciidoc
include/core/CCompressedLfuCache.h

Cache writes can time out acquiring the write lock, in this situation the `readValue` function should still be called even though the computed value has not been added to the cache.
The failure to call `readValue` under a contended lock causes the `pytorch_inference` process to loose the request and not respond to it. This in turn leaves Elasticsearch waiting for a response causing processing to hang.
`CCompressedLfuCache::lookup` returns true if the value was read from the cache, that is not of interest the way it is used in `pytorch_inference` so there is no need to check the return value. The general contract for use by `pytorch_inference` is that if `computeValue` returns a null or nullopt then the caller must handle the request response otherwise it can be left to the `readValue` …

[ML] Call readvalue even if cache write fails

---

docs/CHANGELOG.asciidoc

Previously we've release noted major library upgrades like this one.
Relates #2560

[ML] Add a release note for Boost 1.83 upgrade

---

lib/core/unittest/CHashingTest.cc

Since the upgrade from Boost 1.77 to 1.83 murmur hash is no longer significantly faster than the default Boost hash.
More details in #2574

[ML] Removing assertion on murmur hash lookup performance

---

include/core/CCompressedLfuCache.h

#2576 added an error message when a null value was is read in `CCompressedLfuCache::lookup` as the cache should not contain null values. This was based on a misreading of the code, a null value means the item was not found in the cache.
The curious thing is that the message was only logged once by my application when I would expect to see it every time `CCompressedLfuCache::lookup` was called, I'm assuming this is due to the log throttler removing exact duplicate messages.

[ML] Remove inaccurate log message

---

include/core/CMemoryDec.h
include/core/CMemoryDef.h
lib/api/unittest/CAnomalyJobLimitTest.cc
lib/core/unittest/CCompressedLfuCacheTest.cc

Boost 1.83 has an entirely different implementation of its unordered containers compared to Boost 1.77 (the previous version used by `ml-cpp`).
This PR adjusts the calculations for memory usage of the unordered containers (map/set) to be commensurate with the new implementation.

[ML] Adjust memory calculations for unordered containers

---

docs/CHANGELOG.asciidoc
include/maths/common/CNaiveBayes.h
lib/core/CStateRestoreTraverser.cc
lib/maths/common/CNaiveBayes.cc
lib/maths/common/unittest/CLbfgsTest.cc
lib/maths/common/unittest/CNaiveBayesTest.cc
lib/maths/time_series/CTrendComponent.cc
lib/maths/time_series/unittest/CTrendComponentTest.cc
lib/model/unittest/CMetricDataGathererTest.cc
lib/model/unittest/CMetricPopulationDataGathererTest.cc
lib/model/unittest/CResourceMonitorTest.cc

We model the level of a time series which we've observed having step discontinuities via a Markov process for forecasting. Specifically, we estimate the historical step size distribution and the distribution of the steps in time and as a function of the time series value. For this second part we use an online naive Bayes model to estimate the probability that at any given point in a roll out for forecasting we will get a step.
This approach generally works well unless we're in the tails of the distribution values we've observed for the time series historically when we roll out. In this case, our prediction probability are very sensitive to the tail behaviour of the distributions we fit to the time series values where we saw a step and sometimes we predict far too many steps as a result. …

[ML] Improve forecasting for time series with step changes

---

docs/CHANGELOG.asciidoc
include/maths/common/CNaiveBayes.h
lib/core/CStateRestoreTraverser.cc
lib/maths/common/CNaiveBayes.cc
lib/maths/common/unittest/CLbfgsTest.cc
lib/maths/common/unittest/CNaiveBayesTest.cc
lib/maths/time_series/CTrendComponent.cc
lib/maths/time_series/unittest/CTrendComponentTest.cc
lib/model/unittest/CMetricDataGathererTest.cc
lib/model/unittest/CMetricPopulationDataGathererTest.cc
lib/model/unittest/CResourceMonitorTest.cc

We model the level of a time series which we've observed having step discontinuities via a Markov process for forecasting. Specifically, we estimate the historical step size distribution and the distribution of the steps in time and as a function of the time series value. For this second part we use an online naive Bayes model to estimate the probability that at any given point in a roll out for forecasting we will get a step.
This approach generally works well unless we're in the tails of the distribution values we've observed for the time series historically when we roll out. In this case, our prediction probability are very sensitive to the tail behaviour of the distributions we fit to the time series values where we saw a step and sometimes we predict far too many steps as a result. …

[7.17][ML] Improve forecasting for time series with step changes (#2591)

---

.buildkite/pipelines/run_qa_tests.yml.sh

Set the BuildKite environment variable `QAF_TESTS_TO_RUN` to be `ml_cpp_pr` in the step that triggers QA tests to run when the PR in question is labelled with `ci:run-qa-tests`.
Which specific tests will be run may change over time.

[ML] Set QAF_TESTS_TO_RUN to ml_cpp_pr

---

docs/CHANGELOG.asciidoc
include/maths/common/CNaiveBayes.h
lib/core/CStateRestoreTraverser.cc
lib/maths/common/CNaiveBayes.cc
lib/maths/common/unittest/CLbfgsTest.cc
lib/maths/common/unittest/CNaiveBayesTest.cc
lib/maths/time_series/CTrendComponent.cc
lib/maths/time_series/unittest/CTrendComponentTest.cc
lib/model/unittest/CMetricDataGathererTest.cc
lib/model/unittest/CMetricPopulationDataGathererTest.cc
lib/model/unittest/CResourceMonitorTest.cc

[8.11][ML] Improve forecasting for time series with step changes

---

docs/CHANGELOG.asciidoc

Release notes are correct on the 8.11 branch, but need updating on main.

[ML] Update release notes following extra backport of #2597

---

.buildkite/pipelines/build_linux.json.py
.buildkite/scripts/steps/build_and_test.sh

Up to now we've built the Linux x86_64 artifacts in a Docker container hosted on Kubernetes. This means the BuildKite agent needs to run in the build Docker image and use its Git to get the correct code to build. This no longer works with the ancient version of Git on CentOS 6. By building in a VM, BuildKite can run on the (modern) VM distribution and just the compiler needs to run in the ancient Docker image (which is needed for 7.x platform support).

[ML] Build Linux x86_64 image in VM

---

3rd_party/pull-eigen.sh

Ubuntu 16.04 can no longer clone the Eigen repo without this extra option.

[ML] Another build fix for old OS used with 7.17

---

docs/CHANGELOG.asciidoc

IPEX is now removed from 8.12.
Followup to #2605

[ML] Fix release notes

---

.buildkite/pipeline.json.py
.buildkite/pipelines/run_es_tests_aarch64.yml.sh
.buildkite/pipelines/run_es_tests_x86_64.yml.sh

Currently the Java integration tests we run against PRs are only run on ARM. Since Intel is our primary platform for Cloud we should also run these tests on Intel.

[ML] Run Java integration tests on both Intel and ARM

---

.buildkite/scripts/steps/create_dra.sh

Ensure that the zip archive files created for the daily releasable artifacts are identical when the contents are identical. This means:
* Set the timestamps of the contents to be a fixed value
* Sort the files before archiving
* Exclude any extra file attributes from the archive
Creating as a non-issue as this affects the build/CI processes only

[ML] Create identical dependency archives for identical contents

---

.buildkite/pipelines/build_linux.json.py
.buildkite/pipelines/build_macos.json.py
3rd_party/licenses/pytorch-INFO.csv
3rd_party/licenses/zlib-INFO.csv
build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/linux_aarch64_native_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_aarch64_native_tester/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_image/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
dev-tools/docker/macosx_builder/Dockerfile
dev-tools/docker/macosx_image/Dockerfile
dev-tools/download_macos_deps.sh
dev-tools/download_windows_deps.ps1
docs/CHANGELOG.asciidoc

This reverts commit 435d3f915a5f983dcf83fa4daefafde458593c19.
Investigating why this passed CI in the initial PR but has caused failures in the ES integration tests

Revert "Revert "[ML] Upgrade to Pytorch 2.1.2 and zlib 1.2.13 (#2588)""

---

.buildkite/pipelines/run_qa_tests.yml.sh

The target QA tests pipeline has been renamed to solve an issue in CI, and the pipeline slug has changed in the process.
This updates the `run_qa_tests.yml.sh` pipeline generator file with the new slug.

Update QA tests pipeline slug

---

lib/maths/time_series/CTimeSeriesTestForChange.cc

This is something that was flagged as a compiler warning.
There was a test where an `auto` variable resolved to an `int`, but it really should be 64 bit. It's being used to store a time in epoch seconds, so we get away with this type of error in general until 2038. In the exact test where the problem occurred it will never be a problem as the times being used are very small. However, it's not good practice to use a technically incorrect pattern that may get copied to other places where it matters.

[ML] Fix incorrect auto type

---

bin/pytorch_inference/CCommandParser.cc

This commit added an extra debug log: https://github.com/elastic/ml-cpp/commit/a8634eb4d74fb102f252736a85591750e475ff16#diff-d55591b8583d119527b80207e8bba9567594f95d206572afa4cca65e3f17a6a4R187
It was printing information for every inference call.
Back-porting to 8.13.0

Remove unnecessary debug info log from inference

---

include/core/CBoostJsonWriterBase.h

Use json::serialize to perform escaping of special characters.
Backports #2631

[8.13][ML] Escape special characters in keys as well as string values

---

.buildkite/pull-requests.json

To work around a problem with BuildKite PR builds on bare metal machines (currently only macOS aarch64 builds), set the value of the character separating username and branchname to be "+" rather than the default ":"
Marking as `>non-issue` as this only affects the internal build system and is not worthy of a release note.

[ML] Set buildkite_branch_name_separator to "+"

---

.buildkite/pull-requests.json

To work around a problem with BuildKite PR builds on bare metal machines (currently only macOS aarch64 builds), set the value of the character separating username and branchname to be "+" rather than the default ":"
Backports #2641

[8.13][ML] Set buildkite_branch_name_separator to "+" (#2641)

---

.buildkite/pull-requests.json

To work around a problem with BuildKite PR builds on bare metal machines (currently only macOS aarch64 builds), set the value of the character separating username and branchname to be "+" rather than the default ":"
Backports #2641

[8.12][ML] Set buildkite_branch_name_separator to "+" (#2641)

---

.buildkite/pull-requests.json

To work around a problem with BuildKite PR builds on bare metal machines (currently only macOS aarch64 builds), set the value of the character separating username and branchname to be "+" rather than the default ":"
Backports #2641

[7.17][ML] Set buildkite_branch_name_separator to "+" (#2641)

---

include/core/BoostJsonConstants.h
include/core/CJsonStateRestoreTraverser.h
include/core/CStateDecompressor.h
lib/api/CNdJsonInputParser.cc
lib/api/CRetrainableModelJsonReader.cc
lib/api/CSerializableToJson.cc
lib/maths/analytics/COutliers.cc

Set sensible values for Boost.JSON parser limits
* fixed a few typos in the comments
* quietened some compiler warnings
Also, modified some exception handling code to be consistent with elsewhere.
Labeled as `>non-issue` as these changes have no external effects and are not worthy of release noting.
Relates #2622

[ML] Final tidy up of Boost.JSON migration

---

3rd_party/CMakeLists.txt

The scripts that clone the eigen repo already have logic to remove an existing directory structure prior to cloning, and removing it as part of the clean step forces a cmake reconfigure before subsequent builds will succeed (as the eigen headers will be missing)
Labelling as `>non-issue` as this only affects the build scripts.

[ML] Do not remove eigen directory as part of "clean" step

---

bin/pytorch_inference/CCommandParser.cc

The windows build logs show the warnings
```
9>C:\buildkite-agent\builds\bk-agent-prod-gcp-1712709148528061232\elastic\ml-cpp-snapshot-builds\bin\pytorch_inference\CCommandParser.cc(26,68): warning C4273: 'boost::json::operator <<': inconsistent dll linkage [C:\buildkite-agent\builds\bk-agent-prod-gcp-1712709148528061232\elastic\ml-cpp-snapshot-builds\cmake-build-relwithdebinfo\bin\pytorch_inference\Mlpytorch_inference.vcxproj]
C:\buildkite-agent\builds\bk-agent-prod-gcp-1712709148528061232\elastic\ml-cpp-snapshot-builds\bin\pytorch_inference\CCommandParser.cc(26,68): warning C4273: std::ostream& operator<<(std::ostream& os, const json::value& doc) { [C:\buildkite-agent\builds\bk-agent-prod-gcp-1712709148528061232\elastic\ml-cpp-snapshot-builds\cmake-build-relwithdebinfo\bin\pytorch_infere …
```

[ML] Fix warning: 'boost::json::operator <<': inconsistent dll linkage

---

lib/core/CMakeLists.txt

The link step for libMlCore generates many [LNK4217](https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4217?view=msvc-170) warnings referencing `Boost::Json` symbols. The warning is indicating that the definitions of the symbols have already been imported in other translation units in the library.
These warnings are harmless and are safe to suppress (and are not avoidable by any other means as far as I can tell)
Relates #2653

[ML] Suppress LNK4217 linker warning for libMlCore

---

cmake/compiler/msvc.cmake
lib/model/CTokenListDataCategorizerBase.cc

Windows build logs contain the warning
```
lib\model\CTokenListDataCategorizerBase.cc(429,1): warning C4573: the usage of 'ml::model::CTokenListDataCategorizerBase::acceptPersistInserter' requires the compiler to capture 'this' but the current default capture mode does not allow it
```
This PR fixes that by explicitly capturing the "this" pointer.
Relates #2653

[ML] Fix lambda capture triggering warning on Windows

---

dev-tools/download_windows_deps.ps1

Our logs for Windows CI builds contain warnings similar to:
```
zlib.lib(deflate.obj) : warning LNK4099: PDB 'zlib.pdb' was not found with 'zlib.lib(deflate.obj)'...
```
The PDB file is already built as part of the Windows bootstrapping process - see `build-setup/windows.md`. This change ensures that the dependencies archive deployed to the CI build host contains it.
Relates #2653

[ML] Add zlib.pdb file to Windows' CI dependencies

---

.buildkite/pipelines/build_macos.json.py
.buildkite/scripts/steps/build_and_test.sh

At the moment macOS ARM builds are performed on bare metal Mac Minis provided by MacStadium. For consistency with the rest of engineering, ease of maintenance, reproducibility of builds, automation of provisioning builders etc. it is preferred that we migrate to using VMs provided by MacStadium Orka.
This PR makes use of an image built using "packer". Where the packer config will live is still TBD.
Labelling as a non-issue as this is purely build related.

[ML] Use Orka for macOS ARM builds.

---

.ci/orka/README.md
.ci/orka/gobld-bootstrap.plist
.ci/orka/gobld-bootstrap.sh
.ci/orka/install.sh
.ci/orka/orka-macos-12-arm.pkr.hcl

Adds the Packer configuration files and installation scripts required to create the macOS ARM image used for BuildKite CI builds.
Labelling as `>non-issue` as this is purely related to the internal build system.

[ML] Packer configuration for macOS ARM Orka image

---

.buildkite/pipelines/build_macos.json.py
.buildkite/scripts/steps/build_and_test.sh
.ci/orka/README.md
.ci/orka/gobld-bootstrap.plist
.ci/orka/gobld-bootstrap.sh
.ci/orka/install.sh
.ci/orka/orka-macos-12-arm.pkr.hcl

The MacOS ARM builds running on an Orka based image have been running successfully.
This PR backports https://github.com/elastic/ml-cpp/pull/2662 & https://github.com/elastic/ml-cpp/pull/2663 to 8.13

[8.13][ML] Backport Orka PRs

---

.buildkite/pipelines/build_macos.json.py
.buildkite/scripts/steps/build_and_test.sh
.ci/orka/README.md
.ci/orka/gobld-bootstrap.plist
.ci/orka/gobld-bootstrap.sh
.ci/orka/install.sh
.ci/orka/orka-macos-12-arm.pkr.hcl

The MacOS ARM builds running on an Orka based image have been running successfully.
This PR backports https://github.com/elastic/ml-cpp/pull/2662 & https://github.com/elastic/ml-cpp/pull/2663 to 7.17

[7.17][ML] Backport Orka PRs

---

.buildkite/pipelines/build_macos.json.py

The backport of the Orka related changes to the `7.17` branch introduced a change that inadvertently set the build type to be `DEBUG`. (This is due to differences in the build scripts in `7.17` to those more recent branches). Consequently the build takes ~ 3.5 hours to complete and all binaries will have full debug symbols and assertions enabled.

[ML] Fix error introduced by backport

---

cmake/variables.cmake

Add configuration for compiling with Address Sanitizer flags set for Linux and Windows (they're already present for macOS).
To use:
* cmake -B cmake-build-sanitizer -DCMAKE_BUILD_TYPE="Sanitizer"
* cmake --build cmake-build-sanitizer -j\`nproc\` -t install
* cmake -B cmake-build
* cmake --build cmake-build --config Sanitizer -j\`nproc\` -t install
In addition, certain flags may want to be set via the environment variable `ASAN_OPTIONS`, see
https://github.com/google/sanitizers/wiki/AddressSanitizerFlags#run-time-flags for more details.

[ML] Add CMake config for Address Sanitizer builds

---

docs/CHANGELOG.asciidoc
lib/model/CHierarchicalResultsNormalizer.cc

When running the "autodetect" binary, compiled with the address sanitizer enabled, the following error was emitted
```
==7993==ERROR: AddressSanitizer: stack-use-after-scope on address 0x00016bbf0d37 at pc 0x000106e71b70 bp 0x00016bbf0c40 sp 0x00016bbf0c38
READ of size 1 at 0x00016bbf0d37 thread T0
==7993==WARNING: Failed to use and restart external symbolizer!
#0 0x106e71b6c in std::__1::__function::__func<ml::model::CHierarchicalResultsNormalizer::isMemberOfPopulation(ml::model::hierarchical_results_detail::SNode const&, std::__1::function<bool (ml::model::hierarchical_results_detail::SNode const&)>)::$_0, std::__1::allocator<ml::model::CHierarchicalResultsNormalizer::isMemberOfPopulation(ml::model::hierarchical_results_detail::SNode const&, std::__1::function<bool …
```

[ML] Fix stack-use-after-scope error

---

bin/pytorch_inference/Main.cc
docs/CHANGELOG.asciidoc

The `pytorch_inference` process must respond to every request as the Java side is waiting for a response. Partly this is ensured by a try catch block, we can't be certain what types of exception might be thrown so better to catch the base `std::exception` rather than derived classes.

[ML] Catch any exception thrown by inference 

---

docs/CHANGELOG.asciidoc
include/api/CJsonOutputWriter.h
include/core/CRapidJsonWriterBase.h
include/core/CScopedRapidJsonPoolAllocator.h
lib/api/CJsonOutputWriter.cc

In the CBoostJsonWriteBase class, we maintain a cache of allocators that should be reused when we write new results. Although we took measures to free memory in these allocators, it was still not entirely possible. As a result, we noticed a gradual increase in memory usage by native processes due to the increasing size of the allocators in the cache.
This PR ensures that the allocator is removed from the cache and the memory is freed.
Backport of #2679 to 7.17

[Backport] [ML] Remove allocators from cache after usage

---

docs/CHANGELOG.asciidoc
include/api/CJsonOutputWriter.h
include/core/CBoostJsonWriterBase.h
include/core/CScopedBoostJsonPoolAllocator.h
lib/api/CJsonOutputWriter.cc

In the `CBoostJsonWriteBase` class, we maintain a cache of allocators that should be reused when we write new results. Although we took measures to free memory in these allocators, it was still not completely possible. As a result, we noticed a gradual increase in memory usage by native processes due to the increasing size of the allocators in the cache.
This PR ensures that the allocator is removed from the cache and the memory is freed.
Related to #2664

[ML] Remove allocators from cache after usage

---

docs/CHANGELOG.asciidoc
include/api/CJsonOutputWriter.h
include/core/CBoostJsonWriterBase.h
include/core/CScopedBoostJsonPoolAllocator.h
lib/api/CJsonOutputWriter.cc

In the CBoostJsonWriteBase class, we maintain a cache of allocators that should be reused when we write new results. Although we took measures to free memory in these allocators, it was still not entirely possible. As a result, we noticed a gradual increase in memory usage by native processes due to the increasing size of the allocators in the cache.
This PR ensures that the allocator is removed from the cache and the memory is freed.
Backport of #2679 to 8.14

[Backport][ML] Remove allocators from cache after usage (#2679)

---

bin/autodetect/Main.cc
dev-tools/run_es_tests.sh
docs/CHANGELOG.asciidoc
include/api/CJsonOutputWriter.h
include/core/CBoostJsonPoolAllocator.h
include/core/CBoostJsonWriterBase.h
include/core/CProgramCounters.h
include/model/CResourceMonitor.h
lib/api/CAnomalyJob.cc
lib/api/CJsonOutputWriter.cc
lib/api/CModelSizeStatsJsonWriter.cc
lib/api/unittest/CAnomalyJobLimitTest.cc
lib/api/unittest/CModelSnapshotJsonWriterTest.cc
lib/model/CForecastDataSink.cc
lib/model/CResourceMonitor.cc

The current code uses the monotonic resource allocator, for allocating memory to boost::json objects, which allocates memory in ever increasing chunks, which can lead to over allocation.
The other disadvantage of the monotonic resource allocator is that no deallocations are performed until the resource allocator is destroyed - hence the name monotonic as resource allocations can only increase during its lifetime.
These factors make the choice of the monotonic resource allocator unsuitable for its current use.
This PR introduces a very simplistic custom allocator that allocates and deallocates individual objects upon request using standard operator ::new and ::delete. This gives a much better experience as only as much memory is allocated at any point in time as absolutely needs to be, and …

[8.14][ML] Use custom Boost::JSON allocator (#2674)

---

.entitlements.xml
bin/autodetect/CMakeLists.txt
bin/pytorch_inference/CMakeLists.txt
cmake/functions.cmake

This PR adds the `codesign_autodetect` and `codesign_pytorch_inference` targets to CMake. These targets add the `get-task-allow` entitlement to the respective executables, which is necessary to allow debugging with e.g. `Instruments` on `macOS`
The `codesign` targets are only applicable on `macOS`. Attempting to run them on any other platform will fail with an explanatory message.
Labelling as a `>non-issue` as this is purely a development aid.

[ML] Add `codesign` CMake target

---

docs/CHANGELOG.asciidoc
lib/model/CIndividualModel.cc

The condition is considered harmless and should not be logged as an error

[ML] Log 'No statistics at.. ' as a warning

---

.buildkite/pipelines/build_linux.json.py
.buildkite/pipelines/build_macos.json.py
.buildkite/scripts/steps/build_and_test.sh
.ci/orka/README.md
.ci/orka/orka-macos-12-x86_64.pkr.hcl
3rd_party/licenses/pytorch-INFO.csv
build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/linux_aarch64_native_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_aarch64_native_tester/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_image/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
dev-tools/docker/macosx_builder/Dockerfile
dev-tools/docker/macosx_image/Dockerfile
dev-tools/download_macos_deps.sh
dev-tools/download_windows_deps.ps1
docs/CHANGELOG.asciidoc

Update Docker images and dependency files with PyTorch 2.3.1.
Testing on Linux x86_64 gives promising indications that this version of
PyTorch may resolve some memory allocation issues related to the
`pytorch_inference` process.
Opening this PR to better test it across the range of platforms and
architectures that we support.

[ML] Upgrade to PyTorch 2.3.1

---

.buildkite/pull-requests.json

Fix the `trigger_comment_regex` regular expression that is used to provide a high degree of flexibility when triggering PR builds. 
See https://github.com/elastic/buildkite-pr-bot/blob/c229bf261668611aa11d47455fd980cc0eb86002/README.md for more info.

[ML] Fix the regex used to trigger PR builds with flexible configuration

---

.buildkite/hooks/post-checkout
.buildkite/pipeline.json.py
.buildkite/pipelines/build_pytorch_docker_image.yml.sh
.buildkite/pipelines/run_pytorch_tests.yml.sh
dev-tools/docker/build_pytorch_linux_build_image.sh

Tidy the PyTorch Docker build scripts and configuration, in order to:
* Enable full logging from the docker build process - to simplify investigation should something go wrong
* Read Docker credentials from Vault.
* Limit the scope during which the Docker credentials are in play.
* Push PyTorch Docker image to registry upon successful build.
* Simplify Buildkite pipeline steps so that the QA tests are only run upon success of `Linux x86_64 builds`
* Use a `c2-standard-16` GCP machine for the Docker build step - this greatly improves build times.
* Trigger the `appex-qa-stateful-custom-ml-cpp-build-testing ` pipeline after successfully building the `ml-cpp` code in the newly built PyTorch Docker image - This may be subject to change, but does serve the purpose of some QA testing on the …

[ML] Productionize the PyTorch Docker build

---

include/model/CAnomalyDetectorModel.h
include/model/CCountingModel.h
include/model/CEventRateModel.h
include/model/CEventRatePopulationModel.h
include/model/CMetricModel.h
include/model/CMetricPopulationModel.h
lib/model/CCountingModel.cc
lib/model/CEventRateModel.cc
lib/model/CEventRatePopulationModel.cc
lib/model/CMetricModel.cc
lib/model/CMetricPopulationModel.cc
lib/model/unittest/Mocks.cc
lib/model/unittest/Mocks.h

This PR adds a simple protected interface to add annotations to the model. It is factored out of #2695 for a simpler review.
This functionality will be unit-tested in #2695, where the new `addAnnotation` function will be used.

[ML] Refactor add annotation

---

include/api/CDetectionRulesJsonParser.h
include/model/CDetectionRule.h
lib/model/CCountingModel.cc
lib/model/CDetectionRule.cc
lib/model/CEventRatePopulationModel.cc
lib/model/CIndividualModel.cc
lib/model/CMetricPopulationModel.cc

When performing a time shift callback, what should be the time at which the shift should be applied? 
The original implementation was using `now()` which would work fine for live data, but not for backtesting. This PR changes this behavior. Now, we use the first timestamp when the detection rules have passed the conditions test. 
Also, previous implementation missed the fact that each detector configuration is associated with two detectors: a simple counting detector and a specialized detector (e.g. metric). This means, that the same rule should shift two different models. Hence, I modified the logic responsible for making sure that every model is shifted only once.
The functionality was not released yet, hence I mark it as a non-issue.

[ML] Fixing force time shift logic

---

.buildkite/pipelines/build_linux.json.py
.buildkite/pipelines/build_macos.json.py
.buildkite/scripts/steps/build_and_test.sh
.ci/orka/README.md
.ci/orka/orka-macos-12-x86_64.pkr.hcl
3rd_party/licenses/pytorch-INFO.csv
build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/build_macosx_build_image.sh
dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/linux_aarch64_native_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_aarch64_native_tester/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_image/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
dev-tools/docker/macosx_builder/Dockerfile
dev-tools/docker/macosx_image/Dockerfile
dev-tools/download_macos_deps.sh
dev-tools/download_windows_deps.ps1
docs/CHANGELOG.asciidoc

Update Docker images and dependency files with PyTorch 2.3.1.
Testing on Linux x86_64 gives promising indications that this version of PyTorch may resolve some memory allocation issues related to the `pytorch_inference` process.
Backports #2688

[8.15][ML] Upgrade to PyTorch 2.3.1 (#2688)

---

docs/CHANGELOG.asciidoc

Release notes need updating following backport of PyTorch 2.3.1 changes to 8.15.1
Relates #2688, #2705

[ML] Update release notes following backport of #2688 (#2705)

---

.buildkite/pipelines/create_dra.yml.sh

Refer to `build_test_macos-x86_64-RelWithDebInfo` instead of `build_macos_x86_64_cross-RelWithDebInfo`
Labelling as `>non-issue` as this is purely related to CI builds.

[ML] Correct the reference to a Buildkite step name

---

dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/macosx_image/Dockerfile
dev-tools/download_macos_deps.sh

Use the `elastic-dev` account for the S3 bucket containing the dependencies for the macOS x86 build.

[ML] Migrate to S3 bucket in elastic-dev AWS account for 3rd party dependencies

---

dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/macosx_image/Dockerfile
dev-tools/download_macos_deps.sh

Handle the migration to a new S3 bucket in 2 stages:
1. Migrate the 3rd party dependencies that the ml-cpp builds require to the new S3 bucket (this PR)
2. In a follow up PR. Update where the built `ml-cpp` artifacts get written to. Because this step will also require updating references in e.g. the `elasticsearch` repo some coordination is required. A good approach may be to:
* update the `ml-cpp` scripts to briefly store the artifacts in both the old `prelert-artifacts` bucket and also in the new `ml-cpp-artifacts` bucket
* update the `elasticsearch` repo appropriately to refer to the new bucket.
* finally remove all references to the `prelert-artifacts` bucket from the `ml-cpp` repo.
Backports #2703

[8.15][ML] Migrate to S3 bucket in elastic-dev AWS account for 3rd party dependencies (#2703)

---

dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/macosx_image/Dockerfile
dev-tools/download_macos_deps.sh

Handle the migration to a new S3 bucket in 2 stages:
1. Migrate the 3rd party dependencies that the ml-cpp builds require to the new S3 bucket (this PR)
2. In a follow up PR. Update where the built `ml-cpp` artifacts get written to. Because this step will also require updating references in e.g. the `elasticsearch` repo some coordination is required. A good approach may be to:
* update the `ml-cpp` scripts to briefly store the artifacts in both the old `prelert-artifacts` bucket and also in the new `ml-cpp-artifacts` bucket
* update the `elasticsearch` repo appropriately to refer to the new bucket.
* finally remove all references to the `prelert-artifacts` bucket from the `ml-cpp` repo.
Backports #2703

[8.14][ML] Migrate to S3 bucket in elastic-dev AWS account for 3rd party dependencies (#2703)

---

dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/macosx_image/Dockerfile
dev-tools/download_macos_deps.sh

Handle the migration to a new S3 bucket in 2 stages:
1. Migrate the 3rd party dependencies that the ml-cpp builds require to the new S3 bucket (this PR)
2. In a follow up PR. Update where the built `ml-cpp` artifacts get written to. Because this step will also require updating references in e.g. the `elasticsearch` repo some coordination is required. A good approach may be to:
* update the `ml-cpp` scripts to briefly store the artifacts in both the old `prelert-artifacts` bucket and also in the new `ml-cpp-artifacts` bucket
* update the `elasticsearch` repo appropriately to refer to the new bucket.
* finally remove all references to the `prelert-artifacts` bucket from the `ml-cpp` repo.
Backports #2703

[7.17][ML] Migrate to S3 bucket in elastic-dev AWS account for 3rd party dependencies (#2703)

---

catalog-info.yaml

Now that 8.15.0 is out support for 8.14 has ended.

[ML] Remove 8.14 branch from build schedule

---

docs/CHANGELOG.asciidoc

The PyTorch upgrade did not make into 8.15.1 #2688 it will now be in the 8.15.2 build

Correct version PyTorch upgraded in changelog

---

build-setup/macos.md

There was an extra "install" in the Pytorch line which caused it to fail

Fix typo in build-setup/macos.md

---

bin/pytorch_inference/CResultWriter.cc
bin/pytorch_inference/CResultWriter.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/unittest/CResultWriterTest.cc
docs/CHANGELOG.asciidoc

Allow for single dimensional vectors / zero dimensional tensors in pytorch inference

Change result writing to allow for a single value

---

bin/pytorch_inference/Main.cc

The recent change to support zero dimensional tensors was failing in QA tests, and the root cause was this debug line which printed out each of the results, which can be quite large for some models. 
I aslo removed std::move from the reshape because it was causing compile time warnings, but that wasn't the cause of this problem.
This issue only affected QA so it is a non-issue

Remove debug line that was printing out huge tensors causing timeouts in QA

---

bin/pytorch_inference/CResultWriter.cc
bin/pytorch_inference/CResultWriter.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/unittest/CResultWriterTest.cc
docs/CHANGELOG.asciidoc

backport of https://github.com/elastic/ml-cpp/pull/2720

[backport 8.15.2] Change result writing to allow for a single value

---

bin/pytorch_inference/CResultWriter.cc
bin/pytorch_inference/CResultWriter.h
bin/pytorch_inference/Main.cc
bin/pytorch_inference/unittest/CResultWriterTest.cc
docs/CHANGELOG.asciidoc

backport of https://github.com/elastic/ml-cpp/pull/2720

[backport 8.16] Zero dimensional tensor

---

.buildkite/pipelines/build_macos.json.py

The macOS x86_64 debug build has been timing out recently (since migrating to building on Orka instances). Bump the timeout for all macOS builds by another hour.

[ML] Increase timeout for macOS debug builds

---

.buildkite/hooks/post-checkout

Ensure that macOS x86_64 unit test results are stored correctly in Buildkite test analytics.
(At the moment macOS x86_64 test results are being bundled in with the Windows ones)

[ML] Correct home for macOS x86_64 test results

---

lib/api/unittest/CIoManagerTest.cc

Bump a test thread timeout to increase the chance of successfully reading from a test file on slower machines.
Prior to this change the `CIoManagerTest/testFileIoIsGood` test has been failing approx 5 - 15 pct of the time. Testing the change with this script
```
testFailures=0; for i in {1..1000}; do ../../../cmake-build-relwithdebinfo/test/lib/api/unittest/ml_test_api --run_test=CIoManagerTest/testFileIoGood; if [ $? != 0 ]; then ((++testFailures)); fi; done; echo $testFailures
```
echoes `0` upon completion.

[ML] Fix failing testFileIoIsGood test on mac x86

---

lib/api/unittest/CIoManagerTest.cc

Bump a test thread timeout to increase the chance of successfully reading from a test file on slower machines.
Prior to this change the `CIoManagerTest/testFileIoIsGood` test has been failing approx 5 - 15 pct of the time. Testing the change with this script
```
testFailures=0; for i in {1..1000}; do ../../../cmake-build-relwithdebinfo/test/lib/api/unittest/ml_test_api --run_test=CIoManagerTest/testFileIoGood; if [ $? != 0 ]; then ((++testFailures)); fi; done; echo $testFailures
```
echoes `0` upon completion.
Backports #2728

[8.16][ML] Fix failing testFileIoIsGood test on mac x86 (#2728)

---

lib/api/unittest/CIoManagerTest.cc

Bump a test thread timeout to increase the chance of successfully reading from a test file on slower machines.
Prior to this change the `CIoManagerTest/testFileIoIsGood` test has been failing approx 5 - 15 pct of the time. Testing the change with this script
```
testFailures=0; for i in {1..1000}; do ../../../cmake-build-relwithdebinfo/test/lib/api/unittest/ml_test_api --run_test=CIoManagerTest/testFileIoGood; if [ $? != 0 ]; then ((++testFailures)); fi; done; echo $testFailures
```
echoes `0` upon completion.
Backports #2728

[8.15][ML] Fix failing testFileIoIsGood test on mac x86 (#2728)

---

lib/api/unittest/CIoManagerTest.cc

Bump a test thread timeout to increase the chance of successfully reading from a test file on slower machines.
Prior to this change the `CIoManagerTest/testFileIoIsGood` test has been failing approx 5 - 15 pct of the time. Testing the change with this script
```
testFailures=0; for i in {1..1000}; do ../../../cmake-build-relwithdebinfo/test/lib/api/unittest/ml_test_api --run_test=CIoManagerTest/testFileIoGood; if [ $? != 0 ]; then ((++testFailures)); fi; done; echo $testFailures
```
Backports #2728 
echoes `0` upon completion.

[7.17][ML] Fix failing testFileIoIsGood test on mac x86 (#2728)

---

.buildkite/hooks/post-checkout

Ensure that macOS x86_64 unit test results are stored correctly in Buildkite test analytics.
Backports #2725

[8.16][ML] Correct home for macOS x86_64 test results (#2725)

---

.buildkite/hooks/post-checkout

Ensure that macOS x86_64 unit test results are stored correctly in Buildkite test analytics.
Backports #2725

[8.15][ML] Correct home for macOS x86_64 test results (#2725)

---

.buildkite/pipelines/run_es_tests_aarch64.yml.sh
.buildkite/pipelines/run_es_tests_x86_64.yml.sh

The recommended method of installing Java 21 on AWS EC2 instances is to use `yum` to install `java-21-amazon-corretto`. This does require a bit of pre-configuration however, as detailed here - https://docs.aws.amazon.com/corretto/latest/corretto-21-ug/generic-linux-install.html#rpm-linux-install-instruct
This PR replaces the ad-hoc installation of Java 21 (using `curl` etc.) in #2727 with the recommended method.

[ML] Install Java 21 on AWS EC2 using yum

---

lib/model/CDetectionRule.cc
lib/model/unittest/CDetectionRuleTest.cc

The way the application of the force_time_shift custom rule was configured before, is to specify the amount of time the model's frame of reference should shift by. 
This is counter-intuitive for the users, since in spring when they need to move their clock forward, they would be expected to specify force_time_shift by -3600, aka backward.
This PR switches the sign inside the C++ implementation and allows a more intuitive configuration.
I marked it as a non-issue since the functionality has not yet been released.

[ML] Change time shift sign for intuitive configuration

---

lib/model/CDetectionRule.cc
lib/model/unittest/CDetectionRuleTest.cc

The way the application of the force_time_shift custom rule was configured before, is to specify the amount of time the model's frame of reference should shift.
This is counter-intuitive for the users since when they need to move their clock forward in spring, they would be expected to specify force_time_shift by -3600, aka backward.
This PR switches the sign inside the C++ implementation and allows a more intuitive configuration.
I marked it as a non-issue since the functionality has not yet been released.

[ML] Change time shift sign for intuitive configuration (#2737)

---

catalog-info.yaml

This PR addresses the timeliness of the `ml-cpp` "Staging" (release) builds.
With this change a Buildkite Staging build will be triggered each time a code change is merged to a branch matching the filter condition, i.e. branches names consisting of two or three groups of numbers separated by dots. 
Up until now we have relied upon human processes to trigger these types of builds. However this approach does allow scope to fail.
It it is not necessary to perform Staging builds any more frequently than upon code change. This is due to the fact that the same code is incorporated into Snapshot builds, that are built daily, regardless of code change (in order to run a frequent barrage of tests).

[ML] Trigger a "staging" build on merge to branch

---

lib/maths/common/unittest/CKMostCorrelatedTest.cc

Add a bit of tolerance for a CKMostCorrelatedTest/testScale comparison. This _should_ reduce the frequency of failures on `macOS x86_64` CI builds that are a bit slooooower than the rest.

[ML] Fudge for CKMostCorrelatedTest/testScale

---

CMakeLists.txt
bin/autodetect/CMakeLists.txt
bin/pytorch_inference/CMakeLists.txt
cmake/variables.cmake

Add options to link in libprofiler and/or libtcmalloc to autodetact and pytorch_inference.
*  For Linux builds only.
*  Not for production releases.

[ML] Add CMake config to integrate gperftools

---

cmake/variables.cmake
lib/api/unittest/CJsonOutputWriterTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/time_series/CTrendComponent.cc
lib/maths/time_series/unittest/CCalendarCyclicTestTest.cc

Fix a few issues picked up by the address sanitizer.
These are mostly related to unit tests, including one that leads to an occasional crash on Windows, see https://github.com/elastic/ml-cpp/issues/2651, e.g. https://buildkite.com/organizations/elastic/analytics/suites/ml-cpp-windows-x86-64/tests/f2b19f6b-bc4a-8cff-91e2-f5702ab86274?branch=main

[ML] Fix a few address sanitizer issues

---

lib/api/unittest/CJsonOutputWriterTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/time_series/CTrendComponent.cc

Fix a few issues picked up by the address sanitizer. These are mostly related to unit tests, including one that leads to an occasional crash on Windows - #2651, and also:
* Fix a heap-buffer-overflow in test case Address Sanitizer picked up a heap-buffer-overflow in `CBoostedTreeTest/testEdgeCases`. Rework the test slightly to avoid it.
* Optimize code when running the Address Sanitizer Add the `O3` flag to those used for compiling with the Address Sanitizer enabled. In most cases this is sufficient and cuts the run time significantly.
Backports #2738

[7.17][ML] Fix a few address sanitizer issues (#2738)

---

cmake/variables.cmake
lib/api/unittest/CJsonOutputWriterTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/time_series/CTrendComponent.cc
lib/maths/time_series/unittest/CCalendarCyclicTestTest.cc

Fix a few issues picked up by the address sanitizer. These are mostly related to unit tests, including one that leads to an occasional crash on Windows - #2651, and also:
* Fix a heap-buffer-overflow in test case Address Sanitizer picked up a heap-buffer-overflow in `CBoostedTreeTest/testEdgeCases`. Rework the test slightly to avoid it.
* Optimize code when running the Address Sanitizer Add the `O3` flag to those used for compiling with the Address Sanitizer enabled. In most cases this is sufficient and cuts the run time significantly.
Backports #2738

[8.15][ML] Fix a few address sanitizer issues (#2738)

---

lib/maths/common/unittest/CKMostCorrelatedTest.cc

Add a bit of tolerance for a CKMostCorrelatedTest/testScale comparison. This _should_ reduce the frequency of failures on macOS x86_64 CI builds that are a bit slooooower than the rest.
Backports #2729

[7.17][ML] Fudge for CKMostCorrelatedTest/testScale (#2729)

---

lib/maths/common/unittest/CKMostCorrelatedTest.cc

Add a bit of tolerance for a CKMostCorrelatedTest/testScale comparison. This _should_ reduce the frequency of failures on macOS x86_64 CI builds that are a bit slooooower than the rest.
Backports #2729

[8.16][ML] Fudge for CKMostCorrelatedTest/testScale (#2729)

---

lib/maths/common/unittest/CKMostCorrelatedTest.cc

Add a bit of tolerance for a CKMostCorrelatedTest/testScale comparison. This _should_ reduce the frequency of failures on macOS x86_64 CI builds that are a bit slooooower than the rest.
Backports #2729

[8.15][ML] Fudge for CKMostCorrelatedTest/testScale (#2729)

---

CMakeLists.txt
bin/autodetect/CMakeLists.txt
bin/pytorch_inference/CMakeLists.txt

Add options to link in libprofiler and/or libtcmalloc to autodetact and pytorch_inference. For Linux builds only. Not for production releases.
Backports #2713

[8.16][ML] Add CMake config to integrate gperftools (#2713)

---

CMakeLists.txt
bin/autodetect/CMakeLists.txt
bin/pytorch_inference/CMakeLists.txt

Add options to link in libprofiler and/or libtcmalloc to autodetact and pytorch_inference. For Linux builds only. Not for production releases.
Backports #2713

[8.15][ML] Add CMake config to integrate gperftools (#2713)

---

cmake/variables.cmake
lib/api/unittest/CJsonOutputWriterTest.cc
lib/maths/analytics/unittest/CBoostedTreeTest.cc
lib/maths/time_series/CTrendComponent.cc
lib/maths/time_series/unittest/CCalendarCyclicTestTest.cc

Fix a few issues picked up by the address sanitizer. These are mostly related to unit tests, including one that leads to an occasional crash on Windows - #2651, and also:
* Fix a heap-buffer-overflow in test case Address Sanitizer picked up a heap-buffer-overflow in `CBoostedTreeTest/testEdgeCases`. Rework the test slightly to avoid it.
* Optimize code when running the Address Sanitizer Add the `O3` flag to those used for compiling with the Address Sanitizer enabled. In most cases this is sufficient and cuts the run time significantly.
Backports #2738

[8.16][ML] Fix a few address sanitizer issues (#2738)

---

catalog-info.yaml

Triggering a Staging build via a Github webhook
requires a slight tweak to the branch filter regular expression.
Tested by briefly modifying the regex in Buildkite pipeline settings and pushing an empty commit to the `8.15` branch. Checking the Staging pipeline in Buildkite shows that a build was indeed triggered, see - https://buildkite.com/elastic/ml-cpp-staging-builds/builds/111
Relates #2717

[ML] Correct filter regex for Staging builds

---

.buildkite/ml_pipeline/config.py
.buildkite/pipelines/run_qa_tests.yml.sh
.buildkite/pull-requests.json

Enable being able to specify a particular ES branch and stack version when running QA tests on a PR. The syntax of the GitHub comment to do this is, e.g.:
```
buildkite run_qa_tests for ES_BRANCH=8.x with STACK_VERSION=8.16.0
```

[8.16][ML] QA tests on specific branch and version (#2742)

---

.buildkite/ml_pipeline/config.py
.buildkite/pipelines/run_qa_tests.yml.sh
.buildkite/pull-requests.json

Enable being able to specify a particular ES branch and stack version when running QA tests on a PR. The syntax of the GitHub comment to do this is, e.g.:
```
buildkite run_qa_tests for ES_BRANCH=8.x with STACK_VERSION=8.16.0
```
Backports #2742

[8.15][ML] QA tests on specific branch and version (#2742)

---

docs/CHANGELOG.asciidoc
lib/maths/time_series/CTrendComponent.cc
lib/model/CForecastModelPersist.cc
lib/model/unittest/CForecastModelPersistTest.cc

We fix initialization of the `decayRate` parameter when models have to spill to disk

[ML] Fix forecasting parameters initialization for large models

---

docs/CHANGELOG.asciidoc
lib/model/CForecastModelPersist.cc
lib/model/unittest/CForecastModelPersistTest.cc

We fix initialization of the decayRate parameter when models have to spill to disk

[ML] Fix forecasting parameters initialization for large models (#2759)

---

include/maths/time_series/CTimeSeriesMultibucketFeatures.h

On recent versions of macOS, e.g. Sonoma 14.7 with `clang` version on or about `16.0.0` we experience multiple unit test failures in the `model` and `api` libraries that stem from
a failed dynamic_cast when running code optimized in any way - i.e. not Debug builds. An example test failure is
```
../../../cmake-build-relwithdebinfo/test/lib/model/unittest/ml_test_model --run_test=CEventRateAnomalyDetectorTest/testPersist
Running 1 test case...
2024-10-16 01:54:42,963125 UTC [91925] DEBUG /Users/eds/src/elasticsearch/ml-cpp/lib/test/CTestObserver.cc@28 +---------------------------------------------+
2024-10-16 01:54:42,963145 UTC [91925] DEBUG /Users/eds/src/elasticsearch/ml-cpp/lib/test/CTestObserver.cc@29 |  CEventRateAnomalyDetectorTest/testPersist  |
2024-10-16 01:54:42,963151 UTC …
```

[ML] Fix source of multiple unit test failures on macos

---

catalog-info.yaml

This PR adds the daily snapshot build schedule for the 8.15 branch.

[ML] Add daily snapshot for 8.15 to catalog-info.yaml

---

catalog-info.yaml

Allow the 8.15 branch to be included in snapshot builds upon GitHub activity, as well as daily schedule.
Changes are required only to be merged to `main`, hence labelling as `v9.0.0` .

[ML] Permit 8.15 builds to be triggered by GH activity

---

.buildkite/pipelines/create_dra.yml.sh

Remove the dependency on the macOS x86 build (as it no longer exists) allowing the DRA upload step to proceed

[ML] Remove dependency on macos_x86_64 build step

---

3rd_party/licenses/pytorch-INFO.csv
build-setup/windows.md
dev-tools/download_windows_deps.ps1
docs/CHANGELOG.asciidoc

Update build scripts and docs to refer to PyTorch 2.5.0
Note the slightly different procedure between the Windows 2022 and 2016 builds.
Backports #2783

[8.18][ML] Upgrade to PyTorch 2.5.0 on Windows 2016 builds (#2783)

---

.buildkite/pipelines/build_windows.json.py
build-setup/windows.md
dev-tools/build_windows_third_party_deps.ps1
docs/CHANGELOG.asciidoc

Update docs and configuration to refer to PyTorch 2.5.1

[ML] Windows 2022: Upgrade PyTorch to version 2.5.1

---

build-setup/windows.md
dev-tools/download_windows_deps.ps1
docs/CHANGELOG.asciidoc

Update docs and configuration to refer to PyTorch 2.5.1
Backports #2799

[8.18][ML] Windows 2022: Upgrade PyTorch to version 2.5.1 (#2799)

---

3rd_party/licenses/pytorch-INFO.csv
build-setup/macos.md
dev-tools/download_macos_deps.sh
docs/CHANGELOG.asciidoc

Update docs and build scripts to refer to PyTorch v2.5.1
Backports #2798

[8.18][ML] macOS ARM: Upgrade PyTorch to version 2.5.1 (#2798)

---

dev-tools/docker/README.md
dev-tools/docker/build_linux_dependency_builder_image.sh
dev-tools/docker/pytorch_linux_image/Dockerfile

Update Docker configs/version numbers in order that the nightly pytorch_latest builds pickup the latest base image changes - e.g. `Boost 1.86.0`.
The base image `docker.elastic.co/ml-dev/ml-linux-build:33` contains the `Boost 1.86.0` libraries required by the `ml-cpp` code, but the latest dependency builder image `docker.elastic.co/ml-dev/ml-linux-dependency-builder:3` built on top of it does not. To solve the issue bump the dependency builder version number to `4` and rebuild the docker image.
See https://buildkite.com/elastic/ml-cpp-pr-builds/builds/1396

[ML] Rebuild Docker image for nightly pytorch latest builds

---

lib/maths/common/unittest/CKMeansOnlineTest.cc

CKMeansOnlineTest fails to build on mac and windows (a previous attempted fix was insufficient for debug builds). 
This PR provides the correct fix for those compilation errors.

[ML] Fix for CKMeansOnlineTest compilation errors

---

docs/CHANGELOG.asciidoc
include/core/BoostJsonConstants.h

The maximum size limits for several features of the Boost.JSON SAX parser are currently set to arbitrary "largeish" values. This PR increases those upper limits to be as large as possible.
Closes #2808

[ML] Increase the upper limits for the Boost.JSON SAX parser

---

docs/CHANGELOG.asciidoc
include/core/BoostJsonConstants.h

The maximum size limits for several features of the Boost.JSON SAX style parser are currently set to arbitrary "largeish" values. This PR increases those upper limits to be as large as possible.
Closes #2808
Backports #2809

[8.17][ML] Increase the upper limits for the Boost.JSON SAX parser (#2809)

---

docs/CHANGELOG.asciidoc
include/core/BoostJsonConstants.h

The maximum size limits for several features of the Boost.JSON SAX style parser are currently set to arbitrary "largeish" values. This PR increases those upper limits to be as large as possible.
Closes #2808
Backports #2809

[8.16][ML] Increase the upper limits for the Boost.JSON SAX parser (#2809)

---

CONTRIBUTING.md
build.gradle
cmake/functions.cmake
cmake/test-runner.cmake

Give the ability to specify which tests (or suites of tests) will be executed. Regular expressions are also allowed. In addition any other valid Boost.TEST flag can be passed to the process. This is especially useful when running tests from the command line. For example:
```
TEST_FLAGS="--show-progress" TESTS="*/testPersist" cmake --build cmake-build-relwithdebinfo -j 8 -t test_model
```
would run the `testPersist` test in all suites in the `model` unit tests, and show progress while doing so.

[ML] Refine execution of unit tests

---

.ci/orka/third_party_deps.sh
build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/build_windows_third_party_deps.ps1
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_image/Dockerfile
dev-tools/docker/ubuntu_devbox/Dockerfile
dev-tools/docker/ubuntu_devbox/Dockerfile.8.11
dev-tools/docker/ubuntu_devbox/Dockerfile.8.16

[ML] Update location of boost libraries repo

---

.ci/orka/third_party_deps.sh
build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/build_windows_third_party_deps.ps1
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_image/Dockerfile
dev-tools/docker/ubuntu_devbox/Dockerfile
dev-tools/docker/ubuntu_devbox/Dockerfile.8.11
dev-tools/docker/ubuntu_devbox/Dockerfile.8.16

[9.0][ML] Update location of boost libraries repo (#2829)

---

build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_image/Dockerfile

[ML] Update location of boost libraries repo (#2829)

---

build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_image/Dockerfile

[8.18][ML] Update location of boost libraries repo (#2829)

---

build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_image/Dockerfile

[8.16][ML] Update location of boost libraries repo (#2829)

---

build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_image/Dockerfile

[8.17][ML] Update location of boost libraries repo (#2829)

---

docs/CHANGELOG.asciidoc
lib/core/CDetachedProcessSpawner.cc

This PR provides a more detailed message when a process is terminated with SIGKILL.
On Linux, the OOM (Out Of Memory) system handler will kill processes, according to heuristics, when the OS runs low on memory.
Our native processes (apart from controller) are configured so that they would be chosen first to be terminated in such a situation.
The OOM handler terminates processes with a SIGKILL (signal 9). SIGKILL is not able to be handled by processes and will result in immediate termination, not allowing for any logging of the situation. However, the parent process - controller - can detect and report on the death of its children.
Relates https://github.com/elastic/ml-team/issues/1158
Backports #2841

[9.0][ML] Better messaging regarding OOM process termination (#2841)

---

docs/CHANGELOG.asciidoc
lib/core/CDetachedProcessSpawner.cc

This PR provides a more detailed message when a process is terminated with SIGKILL.
On Linux, the OOM (Out Of Memory) system handler will kill processes, according to heuristics, when the OS runs low on memory.
Our native processes (apart from controller) are configured so that they would be chosen first to be terminated in such a situation.
The OOM handler terminates processes with a SIGKILL (signal 9). SIGKILL is not able to be handled by processes and will result in immediate termination, not allowing for any logging of the situation. However, the parent process - controller - can detect and report on the death of its children.
Relates https://github.com/elastic/ml-team/issues/1158
Backports #2841

[8.19][ML] Better messaging regarding OOM process termination (#2841)

---

lib/model/unittest/CDetectionRuleTest.cc
lib/model/unittest/CEventRateDataGathererTest.cc
lib/model/unittest/CEventRatePopulationDataGathererTest.cc
lib/model/unittest/CHierarchicalResultsTest.cc
lib/model/unittest/CMetricDataGathererTest.cc
lib/model/unittest/CMetricPopulationDataGathererTest.cc
lib/model/unittest/CModelDetailsViewTest.cc
lib/model/unittest/CRuleConditionTest.cc
lib/model/unittest/ModelTestHelpers.h

This is a refactoring PR. It cleans up and refactors some unit tests. No functional changes have been made. 
It also fixes the linting issues from clang-tidy and SonarQube.

[ML] Refactor tests that use CDataGatherer constructor

---

bin/pytorch_inference/Main.cc
docs/CHANGELOG.asciidoc

This will backport the following commits from `main` to `8.17`:
- [[ML] Restrict file system access for pytorch models (#2851)](https://github.com/elastic/ml-cpp/pull/2851)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

[8.17] [ML] Restrict file system access for pytorch models (#2851)

---

bin/pytorch_inference/Main.cc
docs/CHANGELOG.asciidoc

This will backport the following commits from `main` to `8.18`:
- [[ML] Restrict file system access for pytorch models (#2851)](https://github.com/elastic/ml-cpp/pull/2851)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

[8.18] [ML] Restrict file system access for pytorch models (#2851)

---

bin/pytorch_inference/Main.cc
docs/CHANGELOG.asciidoc

This will backport the following commits from `main` to `8.19`:
- [[ML] Restrict file system access for pytorch models (#2851)](https://github.com/elastic/ml-cpp/pull/2851)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

[8.19] [ML] Restrict file system access for pytorch models (#2851)

---

bin/pytorch_inference/Main.cc
docs/CHANGELOG.asciidoc

This will backport the following commits from `main` to `9.0`:
- [[ML] Restrict file system access for pytorch models (#2851)](https://github.com/elastic/ml-cpp/pull/2851)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

[9.0] [ML] Restrict file system access for pytorch models (#2851)

---

dev-tools/docker/pytorch_linux_image/Dockerfile

Recent runs of the nightly PyTorch builds have been failing. Investigation shows that it is due to an issue with the installation of some python packages
```
Installed /usr/local/lib/python3.12/site-packages/torch-2.9.0a0+git2022588-py3.12-linux-x86_64.egg
Processing dependencies for torch==2.9.0a0+git2022588
Searching for fsspec
Reading https://pypi.org/simple/fsspec/
Download error on https://pypi.org/simple/fsspec/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000) -- Some packages may not be found!
Couldn't find index page for 'fsspec' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] …
```

[ML] Fix dependencies for nightly pytorch build

---

.buildkite/pipelines/build_linux.json.py
.buildkite/pipelines/build_macos.json.py
.buildkite/pipelines/build_windows.json.py
.ci/orka/README.md
.ci/orka/orka-macos-13-arm.pkr.hcl
.ci/orka/third_party_deps.sh
3rd_party/licenses/pytorch-INFO.csv
build-setup/linux.md
build-setup/macos.md
build-setup/windows.md
dev-tools/build_windows_third_party_deps.ps1
dev-tools/docker/build_linux_aarch64_cross_build_image.sh
dev-tools/docker/build_linux_aarch64_native_build_image.sh
dev-tools/docker/build_linux_build_image.sh
dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
dev-tools/docker/linux_aarch64_cross_image/Dockerfile
dev-tools/docker/linux_aarch64_native_builder/Dockerfile
dev-tools/docker/linux_aarch64_native_image/Dockerfile
dev-tools/docker/linux_aarch64_native_tester/Dockerfile
dev-tools/docker/linux_builder/Dockerfile
dev-tools/docker/linux_dependency_builder_image/Dockerfile
dev-tools/docker/linux_image/Dockerfile
dev-tools/docker/linux_tester/Dockerfile
dev-tools/docker/ubuntu_devbox/Dockerfile
dev-tools/docker_build.sh
dev-tools/docker_test.sh
docs/CHANGELOG.asciidoc
include/maths/common/CXMeans.h
lib/maths/common/unittest/CXMeansTest.cc

PyTorch 2.7.1 is the latest stable release of PyTorch and contains several bug and security fixes.

[ML] Upgrade to PyTorch 2.7.1
