elastic/ml-cpp

- lib/maths/CTrendComponent.cc
- lib/maths/unittest/CForecastTest.cc
Whilst profiling end-of-bucket processing to evaluate #54 another hotspot was uncovered.
We have multiple trend models and use a weighted combination of these to make a prediction at some future time. However, depending on the time the prediction is required and the current decay rate, a number of these will have very low weight. We can exclude these altogether from the prediction and save the time to compute corresponding prediction with minimal impact on the result.
This saves another 7% on the end-of-bucket processing for the test scenario described in #53. It has a small impact on predictions for count and metric model and so a small impact on results.
> [ML] Speed up trend model component prediction

- include/model/CModelParams.h
- include/model/CModelTools.h
- lib/model/CEventRatePopulationModel.cc
- lib/model/CMetricPopulationModel.cc
- lib/model/CModelParams.cc
- lib/model/CModelTools.cc
- lib/model/unittest/CEventRatePopulationModelTest.cc
- lib/model/unittest/CModelToolsTest.cc
Whilst investigating #57 it became clear that at least for this analysis we get many exact duplicates per bucket. It is reasonable to expect this may be relatively common, at least for integer valued data.
We already have a mechanism (for fuzzy de-duplication) to combine equivalent samples and re-weight the unique values. Therefore, it is relatively easy to always combine identical values.
De-duplicating has two advantages: 1) it makes the job of clustering somewhat easier since we only visit the values serially, 2) for cases such as the analysis described in #57 we get significant runtime improvements. In particular, with this change we get more stable model selection and the runtime to process all 14M records on my laptop drops from around 9m40s to around 6m40s for this job.
This will …
> [ML] Always combine duplicate samples when updating population models

- include/model/CEventRateModel.h
- include/model/CIndividualModel.h
- include/model/CMetricModel.h
- lib/model/CAnomalyDetectorModel.cc
- lib/model/CCountingModel.cc
- lib/model/CEventRateModel.cc
- lib/model/CIndividualModel.cc
- lib/model/CMetricModel.cc
- lib/model/CPopulationModel.cc
Add failsafes to ensure that we never try and reset state for identifiers outside vector bounds. This shouldn't happen, but this is the likely cause of #76 and there are no side effects from checking and issuing an error in such cases. Investigating and fixing the root cause of #76 will be the subject of separate PR.
> [ML] Check range in bounds when clearing recycled models

- include/maths/CTimeSeriesDecompositionDetail.h
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
- lib/model/unittest/CEventRateAnomalyDetectorTest.cc
As of 6.3, we started running the long and short time range periodicity tests at additional times (so that we can detect diurnal periodicity early). However, we only need to run the long time range test if the short time range one is not available, since its resolution, hence accuracy for these periods, is worse.
For example, #75 showed up the case that we're now detecting periodicity in the long range test, because of the extra smoothing due to longer buckets, in data for which don't want to model periodicity at the selected bucket length.
A step towards #75.
> [ML] Only run the long time range periodicity test if the data bucketing precludes the short time range test

- docs/CHANGELOG.asciidoc
- lib/model/ModelTypes.cc
- lib/model/unittest/CModelTypesTest.cc
> [ML] Correct function description for population lat_long

- docs/CHANGELOG.asciidoc
- lib/model/CModelDetailsView.cc
This commit restores respecting the model_plot_config.terms
for by-fields. The bug seems to have been introduced in 6.2.0.
Note that I am also adding an integration test in the java
side to ensure such regressions are caught in the future.
Closes elastic/elasticsearch#30004
> [ML] By-fields should respect model_plot_config.terms

- docs/CHANGELOG.asciidoc
- lib/maths/CAdaptiveBucketing.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/unittest/CForecastTest.cc
- lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.cc
- lib/maths/unittest/CSeasonalComponentTest.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
We were previously not using periodic boundary conditions when fitting seasonal components. This is because the value need not be the same at the start and end of the period because of variation in the gradient within the component. A better strategy is to use the predicted value in the next and previous period, since we expect the component to be continuous. As a result, we can enable periodic boundary conditions by default.
This gives a smoother fit to periodic signals. We get lower maximum prediction errors for smooth signals as a result which is reflected in some of the tighter unit test thresholds and also some manual testing I've done. This will affect results for event rate and metric analysis of periodic signals.
> [ML] Improve and use periodic boundary condition in seasonal component

- docs/CHANGELOG.asciidoc
- lib/maths/CSeasonalComponentAdaptiveBucketing.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/unittest/CForecastTest.cc
- lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.cc
- lib/maths/unittest/CSeasonalComponentTest.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
Investigating a forecasting regression associated with changes targeting #87 showed up an issue with the way we age periodically repeating partitions of the data (such as weekday/end splits). In particular, we were ageing them too fast and their decay rate should be prorated by the fraction of values with which they are updated. For subtle reasons, related to interaction between components in the decomposition, this could lead to biased predictions.
This can affect results for metric and count analyses when the data has distinct weekday/end repeating pattern.
> [ML] Correct ageing of windowed seasonal components

- docs/CHANGELOG.asciidoc
- include/maths/CPeriodicityHypothesisTests.h
- include/maths/CTimeSeriesDecompositionDetail.h
- include/maths/CTools.h
- include/maths/Constants.h
- lib/maths/CPeriodicityHypothesisTests.cc
- lib/maths/CSeasonalComponent.cc
- lib/maths/CSeasonalComponentAdaptiveBucketing.cc
- lib/maths/CSignal.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/CTrendComponent.cc
- lib/maths/unittest/CForecastTest.cc
- lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
- lib/maths/unittest/CPeriodicityHypothesisTestsTest.h
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.h
- lib/maths/unittest/CTimeSeriesModelTest.cc
This makes two principle changes:
1) Iteratively reweights outliers w.r.t. the seasonal component under test and for initialisation. These are defined as a fraction of values with highest residual w.r.t. the component's predictions.
2) Switches marginal test decisions for decomposition components to use logistic regression on top of the various factors, i.e. variance reduction, autocorrelation, number of periods of data observed, etc.
I've tested this on a variety of synthetic and real examples where initial periodic patterns are distorted by outliers and this approach has proved effective, see #87 for more details. Otherwise, it seems to have no detrimental effects.
This will affect results on count and metric analyses when there is seasonality and significant distortion due to outliers.
> [ML] Improve robustness w.r.t. outliers of detection and initialisation of seasonal components

- docs/CHANGELOG.asciidoc
- include/maths/CAdaptiveBucketing.h
- include/maths/CCalendarComponent.h
- include/maths/CDecompositionComponent.h
- include/maths/CSeasonalComponent.h
- include/maths/CTimeSeriesDecompositionDetail.h
- lib/api/CAnomalyJob.cc
- lib/maths/CAdaptiveBucketing.cc
- lib/maths/CCalendarComponent.cc
- lib/maths/CDecompositionComponent.cc
- lib/maths/CSeasonalComponent.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/CTimeSeriesModel.cc
- lib/maths/unittest/CForecastTest.cc
- lib/maths/unittest/CSeasonalComponentTest.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.h
- lib/maths/unittest/CTimeSeriesModelTest.cc
- lib/model/unittest/CEventRateModelTest.cc
In the course of other testing related to #6, I found evidence of potential instability in the decomposition when the seasonal components in the time series abruptly change. In addition, our lifecycle management of seasonal components was not reliably removing components which were no longer improving predictions. This was related to the way we were trying to preserve components which carry information about periodic variance in the data.
This adds a unit test to exercise these problems and makes some related improvements. As part of these I've implemented a failsafe to remove all seasonal components and start again if instability occurs. The current behaviour on this unit test (red actuals, blue predictions) is as follows:
For reference, this is what was happening before:
This can affect …
> [ML] Extend unit testing and make some improvements to deal with changes in seasonal components

- include/maths/CBasicStatistics.h
- lib/maths/CTimeSeriesDecompositionDetail.cc
Do not re-weight outliers if there is just 1, preventing a crash downstream
and harden accumulators to prevent empty containers.
relates to #90 
fixes #94
Note: backport to be done together with pending backport of #90
> [ML] fix segfault caused by to few outliers and harden container usage

- docs/CHANGELOG.asciidoc
- lib/maths/CExpandingWindow.cc
- lib/maths/unittest/CExpandingWindowTest.cc
- lib/maths/unittest/CExpandingWindowTest.h
- lib/maths/unittest/Main.cc
- lib/maths/unittest/Makefile
We were not persisting and restoring the mean offset time of the values added to the expanding window w.r.t. the start of the data buckets. This was therefore getting reset to 0 on a persist restore cycle.
This will introduce a small error when initialising periodic components after a persist and restore and would affect results in this context.
> [ML] Don't lose mean offset in expanding window when persisting

- lib/core/unittest/CLoggerTest.cc
The non-ASCII logging test could hang indefinitely if the VM it
was running on stalled for 200ms before reconfiguring the logger
to use the test pipe.
This change makes it more robust.  A stall of up to 5 seconds is
now tolerated, but with checks every 50ms to avoid slowing the
test down.
> [ML] Make logger test more robust to slow VMs

- include/core/COsFileFuncs.h
- include/core/CProcess.h
- include/core/CWordDictionary.h
- include/core/CXmlParser.h
- include/core/CoreTypes.h
- include/model/ModelTypes.h
- lib/api/unittest/CIoManagerTest.cc
- lib/core/CMutex_Windows.cc
- lib/core/COsFileFuncs.cc
- lib/core/COsFileFuncs_Windows.cc
- lib/core/CProcess.cc
- lib/core/CProcess_Windows.cc
- lib/core/CResourceLocator.cc
- lib/core/CStatistics.cc
- lib/core/CUname_Windows.cc
- lib/core/CWindowsError_Windows.cc
- lib/core/CWordDictionary.cc
- lib/core/CXmlParser.cc
- lib/core/unittest/CDualThreadStreamBufTest.cc
- lib/core/unittest/CLoggerTest.cc
- lib/core/unittest/CNamedPipeFactoryTest.cc
- lib/maths/CSampling.cc
- lib/maths/CXMeansOnline1d.cc
- lib/model/CForecastModelPersist.cc
1. There's no need for constants declared in unnamed namespaces
to be declared `static` - they already have internal linkage.
2. Constants of type `char*` pointing to literals should be
declared `const char* const` - declaring them `const char*` does
not result in internal linkage because it allows them to be
changed to point at something completely different!
> [ML] Correct the way internal linkage of constants is achieved

- CONTRIBUTING.md
Adding guidelines about PR's as well as discussed backport PR's.
A readable version can be found at: https://github.com/hendrikmuhs/ml-cpp/blob/PR-guidelines/CONTRIBUTING.md#pull-requests
> [ML] PR guidelines

- lib/seccomp/CSystemCallFilter_Linux.cc
This warning was noticed in the test logs when run on Amazon Linux:
```
[CMonotonicTime.cc@40] Failed to get reading from hi-res clock
```
`clock_gettime` is used to measure end of bucket processing time if the call fails it defaults to using a 1 second resolution timer
Add `__NR_clock_gettime` to the sys call filter
> [ML] Add clock_gettime to Seccomp filter

- docs/CHANGELOG.asciidoc
- lib/maths/CTrendComponent.cc
If all the values added to a model before a forecast are identical, it triggers the following error in the confidence interval when forecasting: `ERROR CTrendComponent.cc@67 Failed calculating confidence interval: Error in function boost::math::normal_distribution<double>::normal_distribution: Scale parameter is 0, but must be > 0 !, prediction = 0, variance = 0, confidence = 95`. In fact, this error is harmless (since we take the correct action in this case).
This change explicitly traps the problem case, i.e. creating a distribution with zero variance. It doesn't result in any change in behaviour, but does suppress the error.
> [ML] Trap zero variance in forecast confidence interval calculation causing error to be logged

- docs/CHANGELOG.asciidoc
- lib/maths/CTrendComponent.cc
> [6.4][ML] Trap zero variance in forecast confidence interval calculation causing error to be logged

- docs/CHANGELOG.asciidoc
- include/maths/CTools.h
- lib/maths/CTools.cc
- lib/maths/CXMeansOnline1d.cc
- lib/maths/unittest/CToolsTest.cc
- lib/maths/unittest/CToolsTest.h
Minimal fix for #51, replacing boost::lgamma with std::lgamma and guarding the output of lgamma for finite values.
fixes #51
Notes:
- this is a minimal fix, further re-factorings are target of separate PR's (follow-up issues tbd)
- I target this for 6.4, but keep the door open for a backport to 6.3 (according to bug report)
- tested on 6.x (VS 2013)
- tested e2e, yields exactly the same results as before (the lgamma calculation failures are therefore benign for the end result, `affect-results` does not apply)
> [ML] Fix #51 - fix lgamma calculation for x-means clustering

- include/core/CRapidJsonWriterBase.h
- include/maths/CMathsFuncs.h
- include/maths/CMultivariateNormalConjugate.h
- include/maths/CTools.h
- lib/maths/CCategoricalTools.cc
- lib/maths/CGammaRateConjugate.cc
- lib/maths/CLogNormalMeanPrecConjugate.cc
- lib/maths/CMathsFuncs.cc
- lib/maths/CMultinomialConjugate.cc
- lib/maths/CNormalMeanPrecConjugate.cc
- lib/maths/CPoissonMeanConjugate.cc
- lib/maths/CRadialBasisFunction.cc
- lib/maths/CStatisticalTests.cc
- lib/maths/CTools.cc
- lib/maths/ProbabilityAggregators.cc
- lib/maths/unittest/CIntegerToolsTest.cc
- lib/maths/unittest/CProbabilityAggregatorsTest.cc
- lib/maths/unittest/CSamplingTest.cc
- lib/maths/unittest/CToolsTest.cc
Migrate remaining codebase to `std::lgamma`, std::{isfinite,isinf,isnan}` and `std::erf`.
Notes:
- uses CTools::lgamma when possible, in some cases it was better to stay with `std::lgamma` e.g. if error handling was already in place
- improves some error handling to correctly report overflowing
fixes #128
> [ML] Refactor code to use std::lgamma instead of boost::math::lgamma

- lib/model/CProbabilityAndInfluenceCalculator.cc
skip calculation of influencer probabilities if no influences specified
> [ML] skip calculation of influencer probabilities if no influences specified

- docs/CHANGELOG.asciidoc
- lib/model/CMetricPopulationModel.cc
- lib/model/CProbabilityAndInfluenceCalculator.cc
- lib/model/unittest/CMetricPopulationModelTest.cc
This fixes counting of influencer per bucket, prior this fix the count has always been set to 1.
Notes:
- fix == 1st commit, the 2nd and 3rd add test coverage and improve doc/robustness
- it turned out that this functionality had a test (`testVarp`) but test was forgotten to be added in the test suite
- change affects results if influencers are used as influencer score are now changed
Fixes #24
> [ML] Fix influencer count and influence calculation

- include/maths/CAdaptiveBucketing.h
- include/maths/CCalendarComponentAdaptiveBucketing.h
- include/maths/CSeasonalComponentAdaptiveBucketing.h
- lib/maths/CAdaptiveBucketing.cc
- lib/maths/CCalendarComponentAdaptiveBucketing.cc
- lib/maths/CSeasonalComponentAdaptiveBucketing.cc
- lib/maths/unittest/CCalendarComponentAdaptiveBucketingTest.cc
- lib/maths/unittest/CCalendarComponentAdaptiveBucketingTest.h
- lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.cc
- lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.h
This change improves the logging of the error message reported in #142.  I hope this gives us more insight the next time this happens.
relates #142 
Non-issue because it only improves logging but does not fix anything yet.
> [ML]improve error message for splitting failure

- build-setup/linux.md
- build-setup/macos.md
- build-setup/windows.md
- dev-tools/docker/linux-musl_image/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/vagrant/linux/provision.sh
enable build of boost test framework in all provision steps and change documentation accordingly
Relates to #156
> [ML] build boost test framework in buildenv

- include/maths/CTimeSeriesDecompositionDetail.h
- lib/maths/CTimeSeriesDecomposition.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
Internal QA test revealed a problem with deleting the periodicity test after detecting a changepoint, causing a regression in an internal dataset. This fix removes the clearance part of changepoint detection (only a small part of cp detection, see #95), effectively restoring the old behavior.
Non-issue because this fixes an issue of an unreleased feature.
> [ML] do not clear periodicity test after detecting a changepoint

- include/maths/CTimeSeriesDecompositionDetail.h
- lib/maths/CTimeSeriesDecomposition.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
> [6.4][ML] do not clear periodicity test after detecting a changepoint

- lib/api/unittest/CTokenListDataTyperTest.cc
This test fails annoyingly often in CI running on
overcommitted VMs.  The VM can stall or suffer a noisy
neighbour at the wrong moment.
> [ML] Skip pre-tokenised performance assertion in CI

- lib/api/unittest/CTokenListDataTyperTest.cc
This test fails annoyingly often in CI running on
overcommitted VMs.  The VM can stall or suffer a noisy
neighbour at the wrong moment.
Backport of #158
> [6.4][ML] Skip pre-tokenised performance assertion in CI

- lib/maths/CAdaptiveBucketing.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
> [6.4][ML] Don't use higher resolution for cyclic component models than data bucketing supports

- docs/CHANGELOG.asciidoc
- include/maths/CTimeSeriesModel.h
- lib/maths/CMultimodalPrior.cc
- lib/maths/CMultivariateOneOfNPrior.cc
- lib/maths/CTimeSeriesModel.cc
- lib/model/unittest/CEventRateModelTest.cc
There were a couple of issues in the multivariate probability calculation for discovered correlations:
1. When detecting a trend the only the correlation models should have been cleared, since the univariate time series model still exists.
2. When copying and swapping the multivariate distribution models we need to handle the case that no clusterer is present (marginal and conditional distributions are initialised without one).
3. The indexing of some quantities relating to the different correlated variables was incorrect.
This also splits up the probability calculation into a correlated and uncorrelated version since the existing function was cumbersome.
This can only affect results, but only for analysis with multivariate by fields enabled.
> [ML] Fixes potentials for SIGSEGV in multivariate probability calculation

- lib/api/unittest/CAnomalyJobLimitTest.cc
- lib/maths/CTimeSeriesModel.cc
This implements a 6.4 only pad of the estimated model memory in anticipation of the memory which will be consumed by multi-bucket analysis, which will be released in 6.5.
This serves to avoid unnecessary churn in estimated memory usage between versions since there were a number of memory reductions in 6.4, partly in anticipation of multi-bucket analysis. This quantity is used for among other things the job allocation decision.
> [ML] Pad estimated memory usage in anticipation of multi-bucket analysis

- docs/CHANGELOG.asciidoc
- include/maths/CMultimodalPriorUtils.h
- lib/maths/unittest/CMultimodalPriorTest.cc
- lib/model/unittest/CEventRateModelTest.cc
The multimodal confidence interval calculation solves for specific values of the c.d.f. However, if a count weight is applied it scales the log of the c.d.f. by this weight. No scaling should be applied for the purpose of computing confidence intervals. The easiest fix is to apply the equivalent scaling to the target value to solve for, which this change makes.
We were getting log errors generated as a result, see #155, because we couldn't solve for the target value after scaling.
This could affect the predicted value and model bounds for the model, but shouldn't affect the probability calculation and so anomalies detected.
Fixes #155.
> [ML] Correct the multimodal prior confidence interval calculation

- build.gradle
- dev-tools/docker/docker_entrypoint.sh
- dev-tools/docker/linux-musl_builder/Dockerfile
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/docker/macosx_builder/Dockerfile
- dev-tools/docker_build.sh
- dev-tools/docker_test.sh
- gradle.properties
- lib/ver/Makefile
- mk/make_rc_defines.sh
- upload.gradle
Preivously version qualifier like "alpha1" or "rc2" have been
part of the version number stored in the repo.  This means that
to move from a release candidate to a GA build we have to change
a file and rebuild, and this runs the risk that other files have
been changed too.  There is a desire for the GA build to be
built from identical code to the final release candidate.
This change moves the version qualifier from gradle.properties
to a Gradle system property and, in the inner workings of the
build system, an environment variable.
For this to fully work as intended release manager and CI also
need to be updated.  In this initial commit the version qualifier
defaults to "alpha1" if not specified.  The default will be
changed to no version qualifier once CI and release manager are
setting …
> [ML] Move version qualifier to variable

- bin/autodetect/CCmdLineParser.cc
- bin/autodetect/CCmdLineParser.h
- bin/autodetect/Main.cc
- bin/normalize/CCmdLineParser.cc
- bin/normalize/CCmdLineParser.h
- bin/normalize/Main.cc
- include/api/CHierarchicalResultsWriter.h
- include/api/CJsonOutputWriter.h
- include/api/CResultNormalizer.h
- include/model/CAnomalyDetectorModelConfig.h
- include/model/CHierarchicalResultsLevelSet.h
- lib/api/CHierarchicalResultsWriter.cc
- lib/api/CJsonOutputWriter.cc
- lib/api/CResultNormalizer.cc
- lib/api/unittest/CJsonOutputWriterTest.cc
- lib/api/unittest/CJsonOutputWriterTest.h
- lib/model/CAnomalyDetectorModelConfig.cc
- lib/model/CHierarchicalResultsNormalizer.cc
- lib/model/unittest/CAnomalyDetectorModelConfigTest.cc
- lib/model/unittest/CHierarchicalResultsLevelSetTest.cc
- lib/model/unittest/CHierarchicalResultsLevelSetTest.h
Per-partition normalization is an old, undocumented feature that was
never used by clients. It has been superseded by per-partition maximum
scoring (see #32748).
This PR removes the now redundant code.
Relates https://github.com/elastic/elasticsearch/pull/32816
> [ML] Remove old per-partition normalization code

- bin/autodetect/CCmdLineParser.cc
- bin/autodetect/CCmdLineParser.h
- bin/autodetect/Main.cc
- bin/normalize/CCmdLineParser.cc
- bin/normalize/CCmdLineParser.h
- bin/normalize/Main.cc
- include/api/CHierarchicalResultsWriter.h
- include/api/CJsonOutputWriter.h
- include/api/CResultNormalizer.h
- include/model/CAnomalyDetectorModelConfig.h
- include/model/CHierarchicalResultsLevelSet.h
- lib/api/CHierarchicalResultsWriter.cc
- lib/api/CJsonOutputWriter.cc
- lib/api/CResultNormalizer.cc
- lib/api/unittest/CJsonOutputWriterTest.cc
- lib/api/unittest/CJsonOutputWriterTest.h
- lib/model/CAnomalyDetectorModelConfig.cc
- lib/model/CHierarchicalResultsNormalizer.cc
- lib/model/unittest/CAnomalyDetectorModelConfigTest.cc
- lib/model/unittest/CHierarchicalResultsLevelSetTest.cc
- lib/model/unittest/CHierarchicalResultsLevelSetTest.h
Per-partition normalization is an old, undocumented feature that was
never used by clients. It has been superseded by per-partition maximum
scoring (see #32748).
This PR removes the now redundant code.
Relates https://github.com/elastic/elasticsearch/pull/32816
> [ML] Remove old per-partition normalization code (#184)

- lib/maths/CTimeSeriesDecompositionDetail.cc
Suppresses warnings from `g++ -std=gnu++14` on Linux regarding need for explicit instantiation of base class in copy ctor - https://internal-ci.elastic.co/job/elastic+release-manager+master+unified-snapshot/608/console
> [ML] Quieten compilation warnings

- lib/model/CMetricModel.cc
Vector of value counts was never populated causing assertion failures
and hence CMetricModelTest::testInterimCorrectionsWithCorrelations to
fail when run from a debug enabled build.
> [ML] Bugfix. Add value counts to MetricModel results

- lib/model/CMetricModel.cc
Vector of value counts was never populated causing assertion failures
and hence CMetricModelTest::testInterimCorrectionsWithCorrelations to
fail when run from a debug enabled build.
> [ML] Bugfix. Add value counts to MetricModel results (#189)

- build.gradle
- dev-tools/docker_build.sh
- dev-tools/docker_test.sh
- upload.gradle
When the version-qualifier-in-a-variable functionality was first
added in #179 it defaulted to "alpha1" to preserve the previous
default for 7.0.0 because the tools that kick off builds had not
been updated.
Now the external tools have been updated there is no need for a
default version qualifier; builds where no version qualifier is
specified in the appropriate variable will have no version
qualifier.
> [ML] Set default version qualifier to nothing

- include/maths/CModel.h
- include/maths/CTimeSeriesMultibucketFeatures.h
- lib/maths/CModel.cc
- lib/maths/CTimeSeriesModel.cc
- lib/maths/unittest/CTimeSeriesMultibucketFeaturesTest.cc
- lib/model/CEventRatePopulationModel.cc
- lib/model/CMetricPopulationModel.cc
- lib/model/unittest/CEventRateAnomalyDetectorTest.cc
- lib/model/unittest/CMetricAnomalyDetectorTest.cc
This makes some further changes to multi-bucket analysis to address regressions in our QA suite. In particular:
1) I fixed a bug in the feature persist which meant the sliding window length could be incorrect after persist and restore.
2) I have reverted to something closer to what we had previously for features used to model anomalous intervals: duration and average absolute difference from the prediction.
3) I only update the anomalous time interval features if the *bucket* value is unusual: this is to mitigate the interaction between the anomaly model and multi-bucket features, which otherwise (positively) skew our anomalous interval feature values.
4) I avoid the systematic increase in sparse metric probabilities associated with multi-bucket by applying a correction to both …
> [ML] Improvements to address QA regressions associated with multi-bucket

- lib/api/CAnomalyJob.cc
Ensure that normalizers (and hence quantile state) are persisted only
once, when time is advanced
> [ML] Optimization to quantile persistence

- docs/CHANGELOG.asciidoc
- include/maths/CNaiveBayes.h
- lib/maths/CNaiveBayes.cc
- lib/maths/unittest/CNaiveBayesTest.cc
- lib/maths/unittest/CNaiveBayesTest.h
Check that distributions aren't improper before using the NB classifier.
This was sometimes triggering errors when forecasting if there have been no step changes in the time series history.
This only affects forecasting and in this case it shouldn't materially affect the forecasts because we should never create a jump in the roll out because the class probability would be zero.
Closes #206.
> [ML] Trap case triggering "Bad density value..." log errors whilst forecasting

- docs/CHANGELOG.asciidoc
- include/maths/CExpandingWindow.h
- include/maths/CTimeSeriesDecomposition.h
- include/maths/CTimeSeriesDecompositionDetail.h
- include/maths/CTimeSeriesDecompositionInterface.h
- include/maths/CTimeSeriesDecompositionStub.h
- include/maths/CTimeSeriesModel.h
- lib/maths/CExpandingWindow.cc
- lib/maths/CTimeSeriesDecomposition.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/CTimeSeriesDecompositionStub.cc
- lib/maths/CTimeSeriesModel.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
Currently we use a small random sample of historical values to initialise the prediction residual model after we've detected new components of the time series decomposition. This sample is not large enough to be reliably representative of true variation we should expect and can occasionally lead to spurious anomalies immediately after a component is detected. As a result of the increased sensitivity related to #181 this has become more important.
We actually have a better sample available in the window of values we use to perform decomposition (albeit aggregated at a different time scale than the bucketing interval). This change switches to use these values instead to reinitialise the residual model.
> [ML] Improve initialisation of the residual model after detecting new decomposition component

- build-setup/linux.md
If this package is not installed then the date/time parsing unit
tests will fail.
Closes #220
> [ML] Add tzdata to required OS packages in setup instructions

- build-setup/macos.md
- dev-tools/docker/build_macosx_build_image.sh
- dev-tools/docker/macosx_builder/Dockerfile
- dev-tools/docker/macosx_image/Dockerfile
- docs/CHANGELOG.asciidoc
- mk/linux_crosscompile_macosx.mk
- mk/macosx.mk
This is to support Homebrew, which changes the @rpaths of libraries
it installs to (potentially very long) absolute paths.
> [ML] Add -headerpad_max_install_names to macOS linker args

- build-setup/macos.md
- dev-tools/docker/build_macosx_build_image.sh
- dev-tools/docker/macosx_builder/Dockerfile
- dev-tools/docker/macosx_image/Dockerfile
- docs/CHANGELOG.asciidoc
- mk/linux_crosscompile_macosx.mk
- mk/macosx.mk
This is to support Homebrew, which changes the @rpaths of libraries
it installs to (potentially very long) absolute paths.
Backport of #225.
> [ML][6.5] Add -headerpad_max_install_names to macOS linker args

- build-setup/macos.md
- dev-tools/docker/build_macosx_build_image.sh
- dev-tools/docker/macosx_builder/Dockerfile
- dev-tools/docker/macosx_image/Dockerfile
- docs/CHANGELOG.asciidoc
- mk/linux_crosscompile_macosx.mk
- mk/macosx.mk
This is to support Homebrew, which changes the @rpaths of libraries
it installs to (potentially very long) absolute paths.
Backport of #225.
> [ML][6.4] Add -headerpad_max_install_names to macOS linker args

- docs/CHANGELOG.asciidoc
- include/model/CBucketGatherer.h
- include/model/CEventRateBucketGatherer.h
- include/model/CMetricBucketGatherer.h
- lib/model/CBucketGatherer.cc
- lib/model/CEventRateBucketGatherer.cc
- lib/model/CMetricBucketGatherer.cc
- lib/model/unittest/CEventRateDataGathererTest.cc
- lib/model/unittest/CEventRateModelTest.cc
We are not correctly attributing all anomalies to influencers in the case that:
1. The bucket is empty,
2. The influencer is one of the job's partitioning fields.
Among the side-effects is that the anomaly explorer can incorrectly colour tiles and put swim lanes in the wrong order. For example:
Before
After
We can see the major severity anomalies for status 304 corresponding zero count buckets in the single metric viewer
> [ML] Fix incorrectly missing anomaly influences for empty buckets

- docs/CHANGELOG.asciidoc
- include/maths/CPeriodicityHypothesisTests.h
- include/maths/CRegression.h
- include/maths/CTimeSeriesDecomposition.h
- include/maths/CTimeSeriesDecompositionDetail.h
- include/maths/CTimeSeriesDecompositionInterface.h
- include/maths/CTimeSeriesSegmentation.h
- lib/maths/CPeriodicityHypothesisTests.cc
- lib/maths/CTimeSeriesChangeDetector.cc
- lib/maths/CTimeSeriesDecomposition.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/CTimeSeriesSegmentation.cc
- lib/maths/Makefile
- lib/maths/unittest/CForecastTest.cc
- lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
- lib/maths/unittest/CPeriodicityHypothesisTestsTest.h
- lib/maths/unittest/CTimeSeriesChangeDetectorTest.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
- lib/maths/unittest/CTimeSeriesSegmentationTest.cc
- lib/maths/unittest/CTimeSeriesSegmentationTest.h
- lib/maths/unittest/Main.cc
- lib/maths/unittest/Makefile
- lib/model/unittest/CEventRateAnomalyDetectorTest.cc
- lib/model/unittest/CMetricPopulationDataGathererTest.cc
> [6.5][ML] Improve time series decomposition in the presence of change points

- include/maths/CPeriodicityHypothesisTests.h
- lib/maths/CPeriodicityHypothesisTests.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
This fixes a couple of potential issues:
1. If the variance of the data was zero it could cause a nan in the decomposition component errors. The most serious side effect is that it would cause us to fail to restore state on Windows.
2. The check for low coefficient of variation data in the periodic component test should **always** use the raw bucket values to calculate the mean.
This turned up in a unit test failure back porting #198 to 6.5. As such this is effectively a forward port of the fix I made directly to that commit. I've marked this as a non-issue as this is related to unreleased code.
> [ML] Improve robustness to very low variance data

- docs/CHANGELOG.asciidoc
- include/api/CHierarchicalResultsWriter.h
- include/maths/CModel.h
- include/maths/CTimeSeriesDecompositionDetail.h
- include/model/CAnnotatedProbability.h
- include/model/CAnnotatedProbabilityBuilder.h
- include/model/CAnomalyDetectorModelConfig.h
- include/model/CProbabilityAndInfluenceCalculator.h
- lib/api/CHierarchicalResultsWriter.cc
- lib/api/CJsonOutputWriter.cc
- lib/api/unittest/CJsonOutputWriterTest.cc
- lib/maths/CModel.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/CTimeSeriesModel.cc
- lib/model/CAnnotatedProbabilityBuilder.cc
- lib/model/CAnomalyDetectorModelConfig.cc
- lib/model/CEventRateModel.cc
- lib/model/CMetricModel.cc
- lib/model/CProbabilityAndInfluenceCalculator.cc
- lib/model/unittest/CEventRateModelTest.cc
- lib/model/unittest/CEventRateModelTest.h
Add a label indicating the impact of the multi bucket analysis on the
overall probability. The value is in the range -5 to 5 where -5
indicates a wholly single bucket contribution and 5 a wholly multi
bucket contribution to the final probability.
> [ML] Add multi_bucket_impact label to anomalies

- dev-tools/ci
- dev-tools/ci.bat
The CI scripts will now behave differently if triggered from
a PR build:
1. The code style will be checked first and style violations
will cause the PR check to fail
2. The artifacts will only be uploaded to S3 for non-PR builds
PR builds are detected by checking whether a PR_AUTHOR environment
variable exists.
> [ML] Add support for PR CI builds

- dev-tools/ci
- dev-tools/ci.bat
The CI scripts will now behave differently if triggered from
a PR build:
1. The code style will be checked first and style violations
will cause the PR check to fail
2. The artifacts will only be uploaded to S3 for non-PR builds
PR builds are detected by checking whether a PR_AUTHOR environment
variable exists.
Backport of #233.
> [ML][6.5] Add support for PR CI builds

- dev-tools/ci
- dev-tools/ci.bat
The CI scripts will now behave differently if triggered from
a PR build:
1. The code style will be checked first and style violations
will cause the PR check to fail
2. The artifacts will only be uploaded to S3 for non-PR builds
PR builds are detected by checking whether a PR_AUTHOR environment
variable exists.
Backport of #233.
> [ML][6.4] Add support for PR CI builds

- docs/CHANGELOG.asciidoc
- include/api/CHierarchicalResultsWriter.h
- include/maths/CModel.h
- include/model/CAnnotatedProbability.h
- include/model/CAnnotatedProbabilityBuilder.h
- include/model/CAnomalyDetectorModelConfig.h
- include/model/CProbabilityAndInfluenceCalculator.h
- lib/api/CHierarchicalResultsWriter.cc
- lib/api/CJsonOutputWriter.cc
- lib/api/unittest/CJsonOutputWriterTest.cc
- lib/maths/CModel.cc
- lib/maths/CTimeSeriesModel.cc
- lib/model/CAnnotatedProbabilityBuilder.cc
- lib/model/CAnomalyDetectorModelConfig.cc
- lib/model/CEventRateModel.cc
- lib/model/CMetricModel.cc
- lib/model/CProbabilityAndInfluenceCalculator.cc
- lib/model/unittest/CEventRateModelTest.cc
- lib/model/unittest/CEventRateModelTest.h
Add a label indicating the impact of the multi bucket analysis on the
overall probability. The value is in the range -5 to 5 where -5
indicates a wholly single bucket contribution and 5 a wholly multi
bucket contribution to the final probability.
Backports #230
>  [6.5][ML] Add multi_bucket_impact label to anomalies

- lib/model/CAnnotatedProbability.cc
Fixes uninitialized member resulting in out of range values for
multi_bucket_impact
fixes #240
> [ML] Bug-fix for multi_bucket_impact

- lib/model/CAnnotatedProbability.cc
Fixes uninitialized member resulting in out of range values for
multi_bucket_impact
Backport of #241
fixes #240
> [6.5][ML] Bug-fix for multi_bucket_impact (#241)

- dev-tools/jenkins_ci.ps1
- dev-tools/jenkins_ci.sh
Powershell script was modelled on https://github.com/elastic/beats/pull/8268,
and should prevent silent failures such as
https://elasticsearch-ci.elastic.co/job/elastic+machine-learning+master+windows/4/console
Backports #237 and #238.
> [ci][6.4] Add `jenkins-ci` helper scripts for Linux and Windows CI

- dev-tools/ci
- dev-tools/ci.bat
Jenkins will set BUILD_SNAPSHOT to true/false.  We must propagate
this to Gradle and Docker.
> [ML] Fix handling of snapshot flag in CI builds

- dev-tools/ci
- dev-tools/ci.bat
Jenkins will set BUILD_SNAPSHOT to true/false.  We must propagate
this to Gradle and Docker.
Backports #236.
> [ML][6.5] Fix handling of snapshot flag in CI builds

- dev-tools/ci
- dev-tools/ci.bat
Jenkins will set BUILD_SNAPSHOT to true/false.  We must propagate
this to Gradle and Docker.
Backports #236.
> [ML][6.4] Fix handling of snapshot flag in CI builds

- gradle/wrapper/gradle-wrapper.properties
Because Gradle 4.3 is getting quite old now and a
couple of builds have failed due to gradlew failing
to download it.
> [ML] Upgrade to Gradle 4.10

- gradle/wrapper/gradle-wrapper.properties
Because Gradle 4.3 is getting quite old now and a
couple of builds have failed due to gradlew failing
to download it.
Backports #254.
> [ML][6.5] Upgrade to Gradle 4.10

- docs/CHANGELOG.asciidoc
- include/model/CResourceMonitor.h
- lib/api/unittest/CAnomalyJobLimitTest.cc
- lib/model/CResourceMonitor.cc
Changed the calculation to decrease the byte limit margin to account
for bucket spans greater than 1 day
> [ML] hard_limit memory error fix

- include/core/CConcurrentQueue.h
- include/core/CDataAdder.h
- include/core/CDataFrame.h
- include/core/CDataFrameRowSlice.h
- lib/core/CCompressOStream.cc
- lib/core/CDataFrame.cc
- lib/core/CDataFrameRowSlice.cc
- lib/core/Makefile
- lib/core/unittest/CDataFrameTest.cc
- lib/core/unittest/CDataFrameTest.h
- lib/core/unittest/Main.cc
- lib/core/unittest/Makefile
This is a first step towards supporting ML tasks on dense (i.e. mostly no missing elements) Elastic Dataframes.
It provides infrastructure for creating and reading (pieces of) data frames in a process to perform some ML task on them.
The interface is purposely minimal at this point: it supports threaded non-contending reads, sequential writes and the ability to reserve space to append new columns. This should cover many of our planned use cases. The read and write operations are via callbacks to maximally decouple from calling code and also to allow us to do certain operations efficiently. For example, a stream can be read/written directly to/from the data frame storage by wrapping in the appropriate writer/reader functions.
We will have to extend the interface somewhat (for example …
> [ML-Dataframe][FEATURE] A dense data frame

- docs/CHANGELOG.asciidoc
- include/maths/CModel.h
- lib/maths/CModel.cc
- lib/maths/CTimeSeriesModel.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
- lib/maths/unittest/CTimeSeriesModelTest.h
- lib/model/CEventRateModel.cc
- lib/model/CEventRatePopulationModel.cc
- lib/model/CMetricModel.cc
- lib/model/CMetricPopulationModel.cc
Skip model update was not being communicated
to the anomaly model resulting to the score/probability
of results triggering the skip-model-update rule
to reduce.
This commit skips updates to the anomaly model as well.
Closes #217
> [ML] Skip model update in anomaly model

- build-setup/linux.md
- build-setup/macos.md
- build-setup/windows.md
- dev-tools/docker/build_linux-musl_build_image.sh
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/build_linux_test_image.sh
- dev-tools/docker/build_macosx_build_image.sh
- dev-tools/docker/linux-musl_image/Dockerfile
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_test_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/docker/macosx_builder/Dockerfile
- dev-tools/docker/macosx_image/Dockerfile
- dev-tools/download_windows_deps.ps1
- dev-tools/vagrant/linux/provision.sh
Relates #156
This change includes changes similar to those made in #157,
but for the 6.x branch, and also incorporates rebuilds of
VM setup bundles and Docker image updates.
> [ML] Add Boost Test to build environment

- docs/CHANGELOG.asciidoc
- include/maths/CTimeSeriesChangeDetector.h
- include/maths/CTimeSeriesDecomposition.h
- lib/maths/CTimeSeriesChangeDetector.cc
- lib/maths/CTimeSeriesDecomposition.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/CTimeSeriesModel.cc
- lib/maths/unittest/CTimeSeriesChangeDetectorTest.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
- lib/model/CAnomalyDetectorModelConfig.cc
This makes changes driven by latest round reviewing 6.5 results against our QA suite. It primarily targets model robustness to outliers.
In particular, it
1. Mitigates the impact of outliers on change point detection,
2. Delays detecting changes for slightly longer (to reduce false positives detecting time shifts),
3. Increases the sample p-value at we apply minimum weight for model update.
> [ML] Improvements to model robustness to outliers

- docs/CHANGELOG.asciidoc
- include/maths/CModel.h
- lib/maths/CModel.cc
- lib/maths/CTimeSeriesModel.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
- lib/maths/unittest/CTimeSeriesModelTest.h
- lib/model/CEventRateModel.cc
- lib/model/CEventRatePopulationModel.cc
- lib/model/CMetricModel.cc
- lib/model/CMetricPopulationModel.cc
Skip model update was not being communicated
to the anomaly model resulting to the score/probability
of results triggering the skip-model-update rule
to reduce.
This commit skips updates to the anomaly model as well.
Closes #217
> [ML] Backport skip model update in anomaly model (#222)

- docs/CHANGELOG.asciidoc
- lib/maths/CStatisticalTests.cc
A quick-fix for #271 - Perform a check for `isnan` before attempting to compute significance.
A more in-depth analysis of the cause of #271 is required in due course
> [ML] Do isnan check when computing significance

- docs/CHANGELOG.asciidoc
- lib/maths/CStatisticalTests.cc
check for 'not-a-number' condition prior to computing significance
> [6.5][ML] Do isnan check when computing significance (#272)

- build-setup/macos.md
Newer macOS versions can use newer Xcode versions.
Backport of #267
> [ML][6.6] Change Mac compiler version in build setup docs

- lib/maths/CStatisticalTests.cc
- lib/maths/CTimeSeriesSegmentation.cc
This fixes a 0/0 edge case in the time series segmentation code which could occasionally cause log errors of the form `[CStatisticalTests.cc@99] Failed to compute significance Error in function boost::math::cdf(fisher_f_distribution const&, double): Random Variable parameter was -nan, but must be > 0 ! d1 = 335, d2 = 333, x = -nan`
For the data set which exhibited the problem, see #271, the outcome before and after this fix was to reject the segmentation in the case the error was triggered. This therefore didn't affect results, but it is conceivable that it might in another case. I also added in a log error under the check for nan in the f tests which was introduced as a work around, because we want to know if this happens in future.
I haven't added a unit test, because it is difficult to …
> [ML] Fix underlying cause of "Failed to compute significance Error in function boost::math::cdf(fisher_f_distribution..." log error

- lib/maths/CStatisticalTests.cc
- lib/maths/CTimeSeriesSegmentation.cc
> [6.6][ML] Fix underlying cause of "Failed to compute significance Error in function boost::math::cdf(fisher_f_distribution..." log error

- dev-tools/docker/build_check_style_image.sh
- dev-tools/docker/build_linux-musl_build_image.sh
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/build_linux_test_image.sh
- dev-tools/docker/build_macosx_build_image.sh
- dev-tools/docker/linux-musl_builder/Dockerfile
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_test_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/docker/macosx_builder/Dockerfile
- dev-tools/docker/style_checker/Dockerfile
Previously the Docker images were hosted on Docker Hub,
i.e. registry-1.docker.io.  This change moves them to
Elastic's Docker registry at docker.elastic.co.
(I did not actually rebuild all the images using the
updated scripts.  I merely re-tagged the already-built
images and pushed them to the new registry.  But it's
good to update the image build scripts so that the next
change pushes directly to the correct registry.)
Backport of #288
> [ML][6.4] Switch Docker registry to docker.elastic.co

- docs/CHANGELOG.asciidoc
- include/maths/CTimeSeriesDecomposition.h
- include/maths/CTimeSeriesDecompositionDetail.h
- include/maths/CTimeSeriesDecompositionInterface.h
- include/maths/CTimeSeriesDecompositionStub.h
- lib/maths/CTimeSeriesDecomposition.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/CTimeSeriesDecompositionStub.cc
- lib/maths/CTimeSeriesModel.cc
Our QA suite showed up an issue where detecting a trend interferes with detecting a change. The resulting model is poorly reinitialised in this case which damages anomaly detection for some time.
This PR prevents us adding a trend component whilst change detection is occurring. If no change is subsequently detected we'll add a trend component as soon as change detection is abandoned, so this simply marginally delays when we first detect a trend.
Since this is covered by a regression test I haven't duplicated as a unit test.
> [ML] Prevent trend detection during a change in a time series creating a poorly reinitialised model

- dev-tools/docker/build_check_style_image.sh
- dev-tools/docker/build_linux-musl_build_image.sh
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/build_linux_test_image.sh
- dev-tools/docker/build_macosx_build_image.sh
- dev-tools/docker/linux-musl_builder/Dockerfile
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_test_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/docker/macosx_builder/Dockerfile
- dev-tools/docker/style_checker/Dockerfile
Previously the Docker images were hosted on Docker Hub,
i.e. registry-1.docker.io.  This change moves them to
Elastic's Docker registry at docker.elastic.co.
(I did not actually rebuild all the images using the
updated scripts.  I merely re-tagged the already-built
images and pushed them to the new registry.  But it's
good to update the image build scripts so that the next
change pushes directly to the correct registry.)
Backport of #288
> [ML][6.5] Switch Docker registry to docker.elastic.co

- dev-tools/docker/build_check_style_image.sh
- dev-tools/docker/build_linux-musl_build_image.sh
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/build_linux_test_image.sh
- dev-tools/docker/build_macosx_build_image.sh
- dev-tools/docker/linux-musl_builder/Dockerfile
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_test_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/docker/macosx_builder/Dockerfile
- dev-tools/docker/style_checker/Dockerfile
Previously the Docker images were hosted on Docker Hub,
i.e. registry-1.docker.io.  This change moves them to
Elastic's Docker registry at docker.elastic.co.
(I did not actually rebuild all the images using the
updated scripts.  I merely re-tagged the already-built
images and pushed them to the new registry.  But it's
good to update the image build scripts so that the next
change pushes directly to the correct registry.)
Backport of #288
> [ML][6.6] Switch Docker registry to docker.elastic.co

- docs/CHANGELOG.asciidoc
- lib/maths/CGammaRateConjugate.cc
- lib/maths/CMultimodalPrior.cc
- lib/maths/COneOfNPrior.cc
- lib/maths/unittest/CMultimodalPriorTest.cc
Removed check for 'non informative' modes when sampling marginal
likelihood in COneOfNPrior. The check is unneeded as the modes all
return some form of sample in any case.
fixes #274
> [ML] Fix cause of multimodal prior error

- docs/CHANGELOG.asciidoc
- lib/maths/CGammaRateConjugate.cc
- lib/maths/CMultimodalPrior.cc
- lib/maths/COneOfNPrior.cc
- lib/maths/unittest/CMultimodalPriorTest.cc
Removed check for 'non informative' modes when sampling marginal
likelihood in COneOfNPrior. The check is unneeded as the modes all
return some form of sample in any case.
backports #294
> [6.6][ML] Fix cause of multimodal prior error (#294)

- docs/CHANGELOG.asciidoc
- lib/maths/CGammaRateConjugate.cc
- lib/maths/CMultimodalPrior.cc
- lib/maths/COneOfNPrior.cc
- lib/maths/unittest/CMultimodalPriorTest.cc
Removed check for 'non informative' modes when sampling marginal
likelihood in COneOfNPrior. The check is unneeded as the modes all
return some form of sample in any case.
backport of #294
> [6.5][ML] Fix cause of multimodal prior error (#294)

- dev-tools/docker/docker_entrypoint.sh
- dev-tools/docker_test.sh
- lib/core/unittest/CByteSwapperTest.cc
If the only thing that goes wrong with a Docker build is unit test
failures then we want to keep the cppunit_results.xml files that
store the details of the failure.  Prior to this change these
files were getting lost because the Docker container was discarded
on the first non-zero exit code.  Following this change the status
of the unit tests is stored in a status file and a non-zero exit
code of the unit tests suppressed within the Docker container.
Then the outer script checks the status file after copying out the
cppunit_results.xml files.
> [ML] Preserve test report if unit tests fail inside Docker

- dev-tools/docker/docker_entrypoint.sh
- dev-tools/docker_test.sh
If the only thing that goes wrong with a Docker build is unit test
failures then we want to keep the cppunit_results.xml files that
store the details of the failure.  Prior to this change these
files were getting lost because the Docker container was discarded
on the first non-zero exit code.  Following this change the status
of the unit tests is stored in a status file and a non-zero exit
code of the unit tests suppressed within the Docker container.
Then the outer script checks the status file after copying out the
cppunit_results.xml files.
Backport of #300
> [ML][6.6] Preserve test report if unit tests fail inside Docker

- include/maths/CBasicStatistics.h
- include/maths/CKdTree.h
- include/maths/CLinearAlgebraEigen.h
- include/maths/CLinearAlgebraShims.h
- include/maths/CLocalOutlierFactors.h
- lib/maths/unittest/CLocalOutlierFactorsTest.cc
- lib/model/unittest/CEventRateModelTest.cc
This makes necessary changes to support outlier detection on memory mapped vector types. I need to separate code paths (because we need to use different types for projected vectors) and this leads to some refactoring of `CLocalOutlierFactors`.
I also migrate to passing vector collections by value to the top-level APIs. This is important because it means we can, as will be the case for data frame analysis, move these in to place in the calling code. The result is we never need to duplicate the collection, so halve our memory overhead.
Finally, as well as testing with memory mapped vectors, I've expanded the unit testing, in particular, adding some unit testing for the case we're (randomly) projecting vectors.
> [FEATURE][ML] Outliers for memory mapped vectors

- docs/CHANGELOG.asciidoc
- include/api/CForecastRunner.h
- include/model/CForecastDataSink.h
- lib/api/CForecastRunner.cc
- lib/model/CForecastDataSink.cc
- lib/model/CModelDetailsView.cc
We were querying for the model bounds and forecast points at the beginning of each bucket. Instead we should match the time offset we apply to bucket samples when we update the model.
The upshot was that model bounds and forecasts were (typically) offset in time with respect to the data values. The problem is particularly noticeable for long bucket lengths. For example, the figures below show the model bounds for 1 day buckets before and after the fix.
Before:
After:
> [ML] Correct query times for model plot and forecast

- docs/CHANGELOG.asciidoc
- include/api/CForecastRunner.h
- include/model/CForecastDataSink.h
- lib/api/CForecastRunner.cc
- lib/model/CForecastDataSink.cc
- lib/model/CModelDetailsView.cc
Reverts #329
The change that was made in #329 changes the rule that all ML results had timestamps that were the start time of the bucket they relate to.  I don't think this change should be made in a patch.  Further investigation of the side effects is required.
> Revert "[ML] Correct query times for model plot and forecast"

- lib/model/CForecastDataSink.cc
The Java notion of "bucket time" is the start of a job's time buckets, i.e. if the job uses 30 minute time buckets then the "bucket time" is the start of each 30 minute time interval (from 00:00:00 in UTC). Currently, all anomaly detection results are written at bucket time for the buckets which contain them.
As a result of #327, we started evaluating forecasts at the sample offset in the time bucket (for good reasons). In addition, we reported their times as at the evaluation time rather than "bucket time" for the bucket which contains them. This change reverts to report them at bucket time.
Going forward we will probably want to revisit this behaviour and decouple the notion of bucket time from forecast documents. They would simply hold a time and the forecast at that time, *whatever* …
> [ML] Write out forecasts predictions at "bucket time" rather than the actual times they are made in the time buckets

- bin/data_frame_analyzer/Main.cc
- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameAnalysisSpecification.h
- include/api/CDataFrameAnalyzer.h
- include/api/CDataFrameOutliersRunner.h
- include/core/CDataFrame.h
- include/core/CRapidJsonConcurrentLineWriter.h
- include/core/CRapidJsonLineWriter.h
- include/core/CRapidJsonWriterBase.h
- include/core/CStaticThreadPool.h
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.h
- lib/api/unittest/Main.cc
- lib/api/unittest/Makefile
- lib/core/CDataFrame.cc
- lib/core/CStaticThreadPool.cc
- lib/core/unittest/CDataFrameTest.cc
- lib/maths/CLocalOutlierFactors.cc
This finishes up the implementation of `CDataFrameAnalyzer`: wiring in outlier detection and writing results to the output stream.
It also fixes a couple of bugs discovered while testing and renames some functions to be consistent across all functionality related to a data frame.
> [FEATURE][ML] Wire outlier detection into the data_frame_analyzer command

- docs/CHANGELOG.asciidoc
- lib/maths/CPoissonMeanConjugate.cc
- lib/maths/unittest/CPoissonMeanConjugateTest.cc
- lib/maths/unittest/CPoissonMeanConjugateTest.h
- lib/maths/unittest/testfiles/log4cxx.properties
- lib/maths/unittest/testfiles/testLogErrorsLog4cxx.properties
Fix for "sample out of bounds" error generated from
CPoissonMeanConjugate
> [ML] Fix for CPoissonMeanConjugate sampling error.

- include/core/CDataFrame.h
- include/core/CDataFrameRowSlice.h
- include/maths/CLinearAlgebraEigen.h
- lib/api/CDataFrameAnalyzer.cc
- lib/core/CDataFrame.cc
- lib/core/CDataFrameRowSlice.cc
- lib/maths/CLocalOutlierFactors.cc
We have a problem with the copy semantics of memory mapped matrix and vector types (which they inherit from Eigen::Map) for our usage. Basically, copy and move overwrite the values in the referenced memory, whereas for our purposes we'd like to treat these as immutable and simply copy the reference.
This causes a real problem in our current implementation of outlier detection on a data frame when using memory mapped types, because for example, building k-d tree reorders a `std::vector` of memory mapped vectors and in doing so copies values between the rows of the data frame.
We could wrap everything in a `std::reference_wrapper`, but 1) we then still need to create an immutable vector of mapped types that is referenced (which is wasteful) and 2) have to adapt all code to unwrap any vector …
> [FEATURE][ML] Shallow copy memory mapped vector and matrix types

- gradle.properties
changes the artifact name to  `ml-cpp-df` in order setup a CI build that uploads builds without clashing with master builds
Before the feature branch is merged, this change must be reverted.
@dimitris-athanasiou
> [FEATURE][ML] change artifactname in order to create a CI build job

- include/core/CConcurrentQueue.h
- include/core/CStaticThreadPool.h
- lib/core/CStaticThreadPool.cc
- lib/core/unittest/CStaticThreadPoolTest.cc
- lib/core/unittest/CStaticThreadPoolTest.h
There was an error in the shutdown of the thread pool. In particular, although threads process tasks in their queue by preference, if there is a context switch whilst the main thread is adding shutdown messages to another thread which isn't waiting to pop its queue and hasn't yet had its shutdown message added then it could steal another queue's shutdown task. The thread whose shutdown task is stolen will then deadlock waiting for its last message iff its queue was already empty.
~~This PR changes shutdown to wait until all tasks have been processed before enqueuing shutdown tasks. This ensures that every task is blocked waiting to pop its own queue and will process only its own shutdown message and exit. This also means we get better concurrency draining the queues while shutting down …
> [FEATURE][ML] Fix possible deadlock in thread pool shutdown

- include/core/CDataFrame.h
- include/core/Concurrency.h
- lib/core/CDataFrame.cc
- lib/core/unittest/CStaticThreadPoolTest.cc
This reworks the data frame writer to use the thread pool rather than launching its own threads to write to storage in the background. Aside from simplifying the code, this also means that we properly enforce the number of threads constraint supplied to the data_frame_analyzer command. I also improved a couple of comments from #322.
> [FEATURE][ML] Migrate data frame background write to storage to use thread pool

- docs/CHANGELOG.asciidoc
This PR edits the ml-cpp entries for inclusion in the Elasticsearch 6.5.4 release notes.  In particular, it references the following PR: https://github.com/elastic/ml-cpp/pull/327
> [DOCS] Edits 6.5.4 release notes entries

- docs/CHANGELOG.asciidoc
- lib/seccomp/CSystemCallFilter_Linux.cc
Fedora 29 uses different system calls to platforms
we've previously tested on, and hence suffers from
certain functionality failing due to the seccomp
filter.
This commit permits 3 additional system calls:
1. __NR_gettimeofday
2. __NR_unlinkat
3. __NR_getdents64
(It is likely that other Linux distributions using
modern glibc would also hit one or more of these
system calls.  Non-fatal problems probably got
progressively worse in the lead up to the fatal
problem that surfaced in Fedora 29.)
Fixes #350
> [ML] Update seccomp filter for Fedora 29

- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameAnalysisSpecification.h
- include/api/CDataFrameOutliersRunner.h
- include/core/CDataFrame.h
- include/maths/CKdTree.h
- include/maths/CLinearAlgebraShims.h
- include/maths/CLocalOutlierFactors.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.h
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/Main.cc
- lib/api/unittest/Makefile
- lib/core/CDataFrame.cc
This is some of the groundwork for partitioning data frame analyses in general and outlier detection in particular.
It adds functionality to compute the expected memory usage for a `CDataFrame` and for bookkeeping for the algorithms which run on it. This is used to estimate the size of the partition, the maximum number of rows per partition subset and whether to store the data frame in or out of main memory. I've also added a placeholder for passing the directory to use for out-of-core storage from Java.
It isn't fully testable yet because not all the associated functionality is implemented, so I've left some todos in the unit tests.
> [FEATURE][ML] Groundwork for partitioning data frame analyses

- lib/api/CForecastRunner.cc
fix a race condition if a forecast job requires overflowing to disk but cleanup of temporary storage fails. This can cause the autodetect process to hang on exit, if more forecast requests are in the queue
relates to #350
6.x #353
6.6.0 #357 
6.5.5 #356
> [ML] do not exit the worker after warning about failed cleanup

- docs/CHANGELOG.asciidoc
- lib/api/CForecastRunner.cc
fix a race condition if a forecast job requires overflowing to disk but cleanup of temporary storage fails. This can cause the autodetect process to hang on exit, if more forecast requests are in the queue
backport of #352
> [6.7][ML] do not exit the worker after warning about failed cleanup

- docs/CHANGELOG.asciidoc
- lib/api/CForecastRunner.cc
fix a race condition if a forecast job requires overflowing to disk but cleanup of temporary storage fails. This can cause the autodetect process to hang on exit, if more forecast requests are in the queue
backport of #352
> [6.6][ML] do not exit the worker after warning about failed cleanup

- docs/CHANGELOG.asciidoc
- lib/api/CForecastRunner.cc
fix a race condition if a forecast job requires overflowing to disk but cleanup of temporary storage fails. This can cause the autodetect process to hang on exit, if more forecast requests are in the queue
backport of #352
> [6.5][ML] do not exit the worker after warning about failed cleanup

- build-setup/macos.md
Documents the additional step required to install headers into `/usr/include` on macOs Mojave
> Update setup instructions for Mojave

- include/api/CDataFrameAnalyzer.h
- include/core/CDataFrame.h
- include/core/CDataFrameRowSlice.h
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.h
- lib/core/CDataFrame.cc
- lib/core/CDataFrameRowSlice.cc
- lib/core/unittest/CDataFrameTest.cc
- lib/core/unittest/CDataFrameTest.h
We're going to round trip hashes of the Elasticsearch document identifiers to sanity check the join of analysis results with existing data frame row documents. This makes the necessary changes for doing this in the data_frame_analyzer command.
> [FEATURE][ML] Store and retrieve doc id (32 bit hashes) for data frame analyses

- include/api/CDataFrameAnalysisRunner.h
- include/core/CLoopProgress.h
- include/core/Concurrency.h
- include/maths/CLocalOutlierFactors.h
- include/maths/CRegressionDetail.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/core/CLoopProgress.cc
- lib/core/Concurrency.cc
- lib/core/Makefile
- lib/core/unittest/CConcurrencyTest.cc
- lib/core/unittest/CConcurrencyTest.h
- lib/core/unittest/CLoopProgressTest.cc
- lib/core/unittest/CLoopProgressTest.h
- lib/core/unittest/Main.cc
- lib/core/unittest/Makefile
- lib/maths/CLocalOutlierFactors.cc
- lib/maths/unittest/CLocalOutlierFactorsTest.cc
- lib/maths/unittest/CLocalOutlierFactorsTest.h
This wires in progress monitoring to the data frame analysis framework. I've discretised the progress so I can efficiently update atomically. The actual progress is updated via a callback to maximally decouple the "observer" from the algorithms whose progress is being observed. This also makes it trivial to stub out progress monitoring.
Note I haven't yet done anything to pass this back during a long running analysis, because the Java side isn't expecting anything yet.
> [FEATURE][ML] Progress monitoring

- include/maths/CKdTree.h
- include/maths/CLocalOutlierFactors.h
- lib/maths/unittest/CLocalOutlierFactorsTest.cc
- lib/maths/unittest/CLocalOutlierFactorsTest.h
This revisits the storage format for some bookkeeping state used during outlier detection. It also makes sure to reclaim memory allocated for the vector buffer which is moved into the k-d tree.
In particular, this will save us at least `# rows * sizeof(point type)` + `# rows * sizeof(std::vector)` + `# rows * 8 * k` bytes, for k nearest neighbours, during a run of ensemble or LOF outlier detection and `# rows * sizeof(point type)` for all other methods.
> [FEATURE][ML] Reduce bookkeeping memory usage for outlier detection

- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameAnalysisSpecification.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.h
- lib/api/unittest/Makefile
- lib/test/CTestRunner.cc
This ensures the data_frame_analyzer command never reports progress as greater than or equal to one until the analysis task is complete. It also uses much greater precision for progress monitoring since (provided the sum of values added is close to one as it should be) this won't overflow the integer representation.
I also factored out the mock data frame. I had planned to use this in `CDataFrameAnalysisRunnerTest` but decided the existing test coverage of progress monitoring was good enough. However, I think it is useful to have this in its own file for reusability.
@droberts195 this address your comment in #367.
> [FEATURE][ML] Ensure progress is less than one for unfinished data frame analysis tasks

- bin/data_frame_analyzer/Main.cc
- include/core/CDataFrame.h
- include/maths/CDataFrameUtils.h
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/COutliers.cc
- lib/maths/Makefile
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.h
- lib/maths/unittest/Main.cc
- lib/maths/unittest/Makefile
This adds in standardisation of column(feature) values prior to outlier detection (we prefer standardisation to min-max normalisation because it is more resilient to extreme outliers). This will be configurable for the power user (that change will be made in a separate PR focusing on user configuration).
The default behaviour will be to standardise since it guards against obvious misuse when mixing features with very different value ranges.
> [FEATURE][ML] Per column standardisation prior to outlier detection

- lib/core/CDataFrameRowSlice.cc
Correct variable name in trace logging. Make naming consistent.
> [ML] Fix the debug build

- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
There is a test that passes input to the data frame
specification that is not a JSON object. The constructor
is not guarding against that and proceeds into calling
`HasMember` which then triggers the assertion that the
document is not an object.
> [ML] Defend against data frame spec not being an object

- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
There is a test that passes input to the data frame
specification that is not a JSON object. The constructor
is not guarding against that and proceeds into calling
`HasMember` which then triggers the assertion that the
document is not an object.
Backport of #384
> [7.1][ML] Defend against data frame spec not being an object (#384)

- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameOutliersRunner.h
- include/maths/CKdTree.h
- include/maths/COutliers.h
- include/maths/CSampling.h
- include/test/CDataFrameTestUtils.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.h
- lib/core/unittest/CDataFrameTest.cc
- lib/maths/COutliers.cc
- lib/maths/unittest/COutliersTest.cc
This reworks outlier detection to provide a more principled ensemble. We want a diverse ensemble (independent errors) and as such randomise ensemble members on various key parameters:
1. The method (I've stratified along general classes of method so we get equal numbers local and global methods),
2. The vector projections,
3. The point subset used for nearest neighbour queries and
4. The number of nearest neighbours.
I've also overhauled ensemble aggregation along Bayesian lines. We start off with a (potentially configurable) prior probability that a point is an outlier and update our conditional belief that the point is actually an outlier based on its outlier score for each ensemble member.
We already calculated a quantity which relates to the chance that the raw score (or larger) is …
> [ML] Enhancements to outlier detection ensemble

- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
We could conceivably set the task to finished between checking the loop exit condition and checking the progress is less than one. This would cause the assertion to trigger. This has been observed in CI.
> [ML] Fix race condition in test assertion

- include/core/CDataFrame.h
- include/core/CDataFrameRowSlice.h
- include/maths/CDataFrameUtils.h
- include/maths/COutliers.h
- include/test/CDataFrameTestUtils.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.h
- lib/core/CDataFrame.cc
- lib/core/CDataFrameRowSlice.cc
- lib/core/unittest/CDataFrameTest.cc
- lib/core/unittest/CDataFrameTest.h
- lib/maths/COutliers.cc
- lib/maths/unittest/COutliersTest.cc
This fills in the missing functionality to perform out-of-core outlier detection paging in only as many points as will fit given the main memory constraint.
The bulk of this change is to add efficient read/write row range methods to a data frame.
I also slightly tightened up the constraint on minimum row count to trigger a failure. This is now proportional to (number rows)^(1/2) since it should still allow us to process very large data sets subject to a reasonable memory constraint. If the partition count gets too high there are significant runtime overheads so I think it makes sense to just request the user allots more memory in these cases.
> [ML] Partitioned outlier detection

- lib/core/Concurrency.cc
We need to wait on the result of all futures before eventually propagating the (last) exception. Carrying on straightaway meant other threads could still be working on state which had been cleaned up by the stack unwinding.
This caused a rare SIGSEGV in CConcurrencyTest.
> [ML] Prevent potential invalid read if worker throws an exception in parallel_for_each

- lib/core/unittest/CConcurrentWrapperTest.cc
There is a race to the assert in the main thread and for the worker thread in the `CConcurrentWrapper` to process every message it has been passed. We should make sure the worker thread has joined before asserting that all messages have been processed.
Closes #398.
> [ML] Fix race to assert and process all messages in CConcurrentWrapperTest

- include/maths/CKdTree.h
- include/maths/COrderings.h
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/maths/unittest/COutliersTest.cc
There was a silly copy of the point class into a temporary in the `CKdTree::nearestNeighbours`. After fixing that creating temporary pairs to (maybe) push onto the heap still added 25% to its runtime so I've refactored to avoid this. Improving the lower bound on the search (to be the distance to point at the intersection of all hyperplanes above the current node in the recursion) gets a further 20% improvement. Finally, the modulo turned out much slower than a (predictable) branch for getting the next coordinate on which to compare and I've made some tweaks to take a few operations off the critical path. All-in-all this gives us around a 6x performance improvement of outlier detection.
> [ML] Improve performance of k-d tree nearest neighbour search

- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/config/CTools.cc
Follow-on to #102.  Fixing more places where pointers intended
to be immutable could be changed to a point at a different
constant.
> [ML] Make constants truly constant

- lib/api/CDataFrameAnalysisRunner.cc
While it's pedantically correct that MB means 1000000 bytes, nobody
in the field of computing uses this except hard disk manufacturers,
and (most importantly) we need to be consistent with what
ByteSizeUnit does in the Java code.
> [ML] Use 1024 * 1024 bytes in MB

- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/config/CTools.cc
Follow-on to #102.  Fixing more places where pointers intended
to be immutable could be changed to a point at a different
constant.
Backport of #409
> [7.1][ML] Make constants truly constant

- lib/api/CDataFrameAnalysisRunner.cc
While it's pedantically correct that MB means 1000000 bytes, nobody
in the field of computing uses this except hard disk manufacturers,
and (most importantly) we need to be consistent with what
ByteSizeUnit does in the Java code.
Backport of #410
> [7.1][ML] Use 1024 * 1024 bytes in MB

- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameAnalyzer.h
- include/api/CDataFrameOutliersRunner.h
- include/maths/CLinearAlgebraShims.h
- include/maths/COutliers.h
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.h
- lib/maths/COutliers.cc
- lib/maths/unittest/COutliersTest.cc
- lib/maths/unittest/COutliersTest.h
This wires in a calculation of which features are most responsible for a point being an outlier. Very briefly, this is based on understanding how the outlier score changes as we change each feature value independently. The greater the change in the score the greater the feature's influence. I'll prepare some separate detailed documentation.
The extra values are written with the label `feature_influence.<feature_name>` in the result document.
Although this wires it through to result writing it is default disabled and not currently possible to enable. I need to finish up supporting user configuration and will make the change to allow it to be optionally enabled and unit test the result writing in a separate PR.
> [ML] Features influencing outliers

- include/core/LogMacros.h
- include/maths/CSolvers.h
- lib/api/CAnomalyJob.cc
- lib/maths/CLinearAlgebraTools.cc
- lib/maths/CMultinomialConjugate.cc
- lib/maths/CNaturalBreaksClassifier.cc
- lib/maths/COutliers.cc
- lib/maths/CTrendComponent.cc
We have had a few situations where LOG_TRACE macros
contained syntax errors which were only found by the
nightly debug build because most builds optimise
away these trace macros.
This commit changes the approach for optimising away
LOG_TRACE.  Instead of completely ignoring the contents
of the macro they are used within an anonymous lambda
that is immediately discarded.  The hope then is that
the compiler's dead-code elimination optimisation will
completely remove any generated code from the final
program, leading to the same shipped product we had
before but without the pain of having to fix syntax
errors when building debug binaries.
> [ML] Syntax-check log trace even when optimised out

- include/api/CDataFrameAnalysisConfigReader.h
- include/api/CDataFrameAnalysisSpecification.h
- include/api/CDataFrameOutliersRunner.h
- include/maths/CDataFrameUtils.h
- include/maths/COutliers.h
- lib/api/CDataFrameAnalysisConfigReader.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/Makefile.first
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.h
- lib/maths/COutliers.cc
- lib/maths/unittest/COutliersTest.cc
This factors out the validation of the data_frame_analyzer command parameters into a standalone parameter reader class.
I've also added in some additional parameters for outlier detection, allowing the user to opt out of computing feature influences, adjust the minimum outlier score at which we'll write influences out and support disabling column standardisation as part of outlier detection.
As a result I've also been able to finish up unit testing the API with feature influence.
> [ML] Rework user overrides for data frame analytics plus support overriding additional parameters for outlier detection

- include/core/LogMacros.h
- include/maths/CSolvers.h
- lib/api/CAnomalyJob.cc
- lib/maths/CLinearAlgebraTools.cc
- lib/maths/CMultinomialConjugate.cc
- lib/maths/CNaturalBreaksClassifier.cc
- lib/maths/COutliers.cc
- lib/maths/CTrendComponent.cc
We have had a few situations where LOG_TRACE macros
contained syntax errors which were only found by the
nightly debug build because most builds optimise
away these trace macros.
This commit changes the approach for optimising away
LOG_TRACE.  Instead of completly ignoring the contents
of the macro it is used within an anonymous lambda
that is immediately discarded.  The hope then is that
the compiler's dead-code elimination optimisation will
completely remove any generated code from the final
program, leading to the same shipped product we had
before but without the pain of having to fix syntax
errors when building debug binaries.
Backport of #417
> [7.1][ML] Syntax-check log trace even when optimised out

- include/api/CDataFrameAnalysisConfigReader.h
- lib/api/CDataFrameAnalysisConfigReader.cc
Some unit tests override the fatal error handling to not terminate the process in order to check error messages on bad input. We need to guard calls to Get* on rapidjson::Value in these cases or the tests hit an assertion in a debug build.
> [ML] Guard calls to Get* in config parser in the case the fatal error handler is overridden

- include/api/CDataFrameAnalysisConfigReader.h
- lib/api/CDataFrameAnalysisConfigReader.cc
> [7.1][ML] Guard calls to Get* in config parser in the case the fatal error handler is overridden

- include/api/CDataFrameOutliersRunner.h
- include/maths/CAnnotatedVector.h
- include/maths/CKdTree.h
- include/maths/COutliers.h
- lib/api/CDataFrameOutliersRunner.cc
- lib/maths/COutliers.cc
- lib/maths/unittest/COutliersTest.cc
- lib/maths/unittest/COutliersTest.h
This simplifies the API to estimate outlier detection memory and moves the logic about vector types behind it. This means I can move the `CEnsemble` class definition out of the header.
This also makes some corrections to our estimates, adds in memory monitoring and tests that our estimates agree (up to a reasonable error) with the high water mark of the memory estimate.
I haven't yet wired through memory monitoring to the `CDataFrameAnalysisRunner`, but it would be a useful counter to add for monitoring of the analytics process. I'll add this in a later pull request.
> [ML] Outlier memory monitoring plus improvements to memory estimation

- lib/api/CDataFrameAnalysisConfigReader.cc
`rapidjson::Writer<rapidjson::StringBuffer>` is exported from
the core library (implicitly rather than explicitly, because
`CRapidJsonConcurrentLineWriter` inherits from it and is exported).
To avoid violating the one-definition rule, other libraries
that link to the core library (i.e. all of them) and use
`rapidjson::Writer<rapidjson::StringBuffer>` must import the
instantiation in the core library rather than reinstantiating
the template themselves.
This change is basically working around item 2 in
http://developercommunity.visualstudio.com/solutions/228892/view.html
It's only strictly necessary to do this at the moment when
building with debug as in an optimised build the clashing methods
get inlined, so don't generate clashing symbols.  However, future
code changes could cause the …
> [ML] Fix the debug build on Windows

- lib/api/CDataFrameAnalysisConfigReader.cc
rapidjson::Writer<rapidjson::StringBuffer> is exported from
the core library (implicitly rather than explicitly, because
CRapidJsonConcurrentLineWriter inherits from it and is exported).
To avoid violating the one-definition rule, other libraries
that link to the core library (i.e. all of them) and use
rapidjson::Writer<rapidjson::StringBuffer> must import the
instantiation in the core library rather than reinstantiating
the template themselves.
This change is basically working around item 2 in
http://developercommunity.visualstudio.com/solutions/228892/view.html
It's only strictly necessary to do this at the moment when
building with debug as in an optimised build the clashing methods
get inlined, so don't generate clashing symbols.  However, future
code changes could cause the compiler …
> [7.1][ML] Fix the debug build on Windows

- docs/CHANGELOG.asciidoc
- include/maths/CAdaptiveBucketing.h
- include/maths/CCalendarComponent.h
- include/maths/CCalendarComponentAdaptiveBucketing.h
- include/maths/CMathsFuncsDetail.h
- include/maths/CRegression.h
- include/maths/CSeasonalComponent.h
- include/maths/CSeasonalComponentAdaptiveBucketing.h
- include/maths/CTimeSeriesDecomposition.h
- include/maths/CTimeSeriesDecompositionDetail.h
- lib/maths/CCalendarComponent.cc
- lib/maths/CCalendarComponentAdaptiveBucketing.cc
- lib/maths/CDecompositionComponent.cc
- lib/maths/CPeriodicityHypothesisTests.cc
- lib/maths/CSeasonalComponentAdaptiveBucketing.cc
- lib/maths/CTimeSeriesDecomposition.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.h
While it is as yet unknown how it can occur, NaN values have been
observed to be present in seasonal components when detrending, resulting
in a chain of errors in the logs as the NaN values percolate up the call
stack.
This PR attempts to detect the NaN values as close as possible to their
source and ensure that they do not unduly affect the analysis.
The approach is to check for bad values in seasonal and calendar
components from within
CTimeSeriesDecompositionDetail::CComponents::interpolate, which is
called periodically. If invalid values are detected in a component then
it is removed from the decomposition.
> [7.1][ML] Handle NaNs when detrending seasonal components (#408)

- include/core/CConcurrentQueue.h
- include/core/CDataFrame.h
- include/core/CStaticThreadPool.h
- include/core/Concurrency.h
- lib/core/CDataFrame.cc
- lib/core/CStaticThreadPool.cc
- lib/core/Concurrency.cc
- lib/core/unittest/CStaticThreadPoolTest.cc
Wrapping function calls in a `std::packaged_task` was slightly more than doubling the runtime overhead per task in the thread pool. This moves to using a standard function pointer which can (optionally) hold the promise to which results are written. A nice side effect is we don't actually need a custom wrapper around std::future to unpack the result of function passed to the thread pool, so the code is slightly cleaner.
> [ML] Threading optimisations

- docs/CHANGELOG.asciidoc
- include/api/CAnomalyJob.h
- include/api/CDataProcessor.h
- include/api/CFieldDataTyper.h
- include/api/COutputChainer.h
- include/api/COutputHandler.h
- include/config/CAutoconfigurer.h
- lib/api/CAnomalyJob.cc
- lib/api/CCmdSkeleton.cc
- lib/api/CFieldDataTyper.cc
- lib/api/COutputChainer.cc
- lib/api/COutputHandler.cc
- lib/api/unittest/CAnomalyJobTest.cc
- lib/api/unittest/CAnomalyJobTest.h
- lib/api/unittest/CMockDataProcessor.cc
- lib/api/unittest/CMockDataProcessor.h
- lib/config/CAutoconfigurer.cc
Changed the logic surrounding persistence of both state and quantiles on
graceful shutdown so that persistence only occurs if and only if at
least one input record has been processed or time has been advanced.
closes #393
> [ML] Improve autodetect logic for persistence

- docs/CHANGELOG.asciidoc
- include/api/CAnomalyJob.h
- include/api/CDataProcessor.h
- include/api/CFieldDataTyper.h
- include/api/COutputChainer.h
- include/api/COutputHandler.h
- include/config/CAutoconfigurer.h
- lib/api/CAnomalyJob.cc
- lib/api/CCmdSkeleton.cc
- lib/api/CFieldDataTyper.cc
- lib/api/COutputChainer.cc
- lib/api/COutputHandler.cc
- lib/api/unittest/CAnomalyJobTest.cc
- lib/api/unittest/CAnomalyJobTest.h
- lib/api/unittest/CMockDataProcessor.cc
- lib/api/unittest/CMockDataProcessor.h
- lib/config/CAutoconfigurer.cc
Changed the logic surrounding persistence of both state and quantiles on
graceful shutdown so that persistence only occurs if and only if at
least one input record has been processed or time has been advanced.
Backport #437
> [6.7][ML] Improve autodetect logic for persistence (#437)

- docs/CHANGELOG.asciidoc
- include/api/CAnomalyJob.h
- include/api/CDataProcessor.h
- include/api/CFieldDataTyper.h
- include/api/COutputChainer.h
- include/api/COutputHandler.h
- include/config/CAutoconfigurer.h
- lib/api/CAnomalyJob.cc
- lib/api/CCmdSkeleton.cc
- lib/api/CFieldDataTyper.cc
- lib/api/COutputChainer.cc
- lib/api/COutputHandler.cc
- lib/api/unittest/CAnomalyJobTest.cc
- lib/api/unittest/CAnomalyJobTest.h
- lib/api/unittest/CMockDataProcessor.cc
- lib/api/unittest/CMockDataProcessor.h
- lib/config/CAutoconfigurer.cc
Changed the logic surrounding persistence of both state and quantiles on
graceful shutdown so that persistence only occurs if and only if at
least one input record has been processed or time has been advanced.
Backports #437
> [7.0][ML] Improve autodetect logic for persistence (#437)

- docs/CHANGELOG.asciidoc
- include/api/CAnomalyJob.h
- include/api/CDataProcessor.h
- include/api/CFieldDataTyper.h
- include/api/COutputChainer.h
- include/api/COutputHandler.h
- include/config/CAutoconfigurer.h
- lib/api/CAnomalyJob.cc
- lib/api/CCmdSkeleton.cc
- lib/api/CFieldDataTyper.cc
- lib/api/COutputChainer.cc
- lib/api/COutputHandler.cc
- lib/api/unittest/CAnomalyJobTest.cc
- lib/api/unittest/CAnomalyJobTest.h
- lib/api/unittest/CMockDataProcessor.cc
- lib/api/unittest/CMockDataProcessor.h
- lib/config/CAutoconfigurer.cc
Changed the logic surrounding persistence of both state and quantiles on
graceful shutdown so that persistence only occurs if and only if at
least one input record has been processed or time has been advanced.
Backports #437
> [7.1][ML] Improve autodetect logic for persistence (#437)

- include/maths/COutliers.h
- lib/maths/COutliers.cc
- lib/maths/unittest/COutliersTest.cc
In memory estimation we i) weren't fully accounting for user overrides, ii) double counting points and scorer memory. In memory monitoring we were over counting scorer memory by a factor # partitions - 1.
This also fixes a bug in recover memory when we aren't computing feature influences.
Our upfront estimates are now within 5%.
> [ML] Fix some issues in memory monitoring and estimation

- include/maths/CBoostedTree.h
- include/maths/CDataFrameRegressionModel.h
- include/maths/CDataFrameUtils.h
- lib/maths/CBoostedTree.cc
- lib/maths/CDataFrameRegressionModel.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/Makefile
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/Main.cc
- lib/maths/unittest/Makefile
This implements a boosted regression tree. This is still very much work in progress and largely untested, but it is a first pass implementation of nearly the full train functionality and defines the API for other tasks. As such, I think this represents a point where we can review without the change becoming too large.
The biggest missing piece is hyperparameter optimisation. This will build on some standalone functionality, so I'm leaving it for the time being. I also have some plans for custom treatment of categorical regressors, but this depends on adding a column data type and I'm going to delay this until later.
> [FEATURE][ML] Boosted regression tree (initial commit)

- lib/core/CPackedBitVector.cc
- lib/core/unittest/CPackedBitVectorTest.cc
- lib/core/unittest/CPackedBitVectorTest.h
We were incorrectly inverting the bits of one of the vectors when performing a line scan on our packed bit vector in an edge case. This is a fix and unit test.
> [FEATURE][ML] Fix a bug in bit vector line scan

- docs/CHANGELOG.asciidoc
This PR updates the changelog for 7.0.0-rc1 and removes information about 6.x and 7.1.x.
> [DOCS] Updates changelog for 7.0.0-rc1

- build-setup/linux.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/vagrant/linux/provision.sh
- docs/CHANGELOG.asciidoc
This change adds the stack protector, relro and fortify source
options to the commands used to build the 3rd party libraries
we use on Linux.
(We already used these options when building our own code.)
> [ML] Use hardened compiler options to build 3rd party libraries

- build-setup/linux.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/vagrant/linux/provision.sh
- docs/CHANGELOG.asciidoc
This change adds the stack protector, relro and fortify source
options to the commands used to build the 3rd party libraries
we use on Linux.
(We already used these options when building our own code.)
Backport of #453
> [7.1][ML] Use hardened compiler options to build 3rd party libraries

- include/api/CDataFrameAnalysisSpecification.h
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
This adds `results_field` to the data frame analytics specification.
Results are now written in an object that is named after the value
of this setting.
> [FEATURE][ML] Add results_field to data frame analytics specification

- include/api/CDataFrameAnalysisSpecification.h
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
This adds `results_field` to the data frame analytics specification.
Results are now written in an object that is named after the value
of this setting.
> [7.x][ML] Add results_field to data frame analytics specification (#454)

- include/maths/CBayesianOptimisation.h
- include/maths/CLbfgs.h
- include/maths/CLinearAlgebraEigen.h
- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTree.cc
- lib/maths/Makefile
- lib/maths/unittest/CBayesianOptimisationTest.cc
- lib/maths/unittest/CBayesianOptimisationTest.h
- lib/maths/unittest/CLbfgsTest.cc
- lib/maths/unittest/CLbfgsTest.h
- lib/maths/unittest/Main.cc
- lib/maths/unittest/Makefile
This implements Bayesian optimisation based on a Gaussian Process. We'll use this to optimise most of the hyperparameters for the regression tree implementation. I plan to wire in the use of this in a separate PR to keep this change smaller. Also, although restarts are trivially parallel, I haven't yet threaded this code because I want to do this in the context of end-to-end performance tuning. There are likely to be a few more tweaks down-the-line, but I think this is ready for review.
> [FEATURE][ML] Framework for regression model hyperparameter optimisation

- docs/CHANGELOG.asciidoc
- lib/seccomp/CSystemCallFilter_Linux.cc
This is required with the Oracle Unbreakable
Enterprise Kernel (UEK).  The UEK is not
supported but it's possible some other
supported Linux distro will require the "time"
syscall at some point, so it doesn't hurt to
permit it in our filter.
Fixes elastic/elasticsearch#41101
> [ML] Add the "time" syscall to the syscall filter

- docs/CHANGELOG.asciidoc
- lib/seccomp/CSystemCallFilter_Linux.cc
This is required with the Oracle Unbreakable
Enterprise Kernel (UEK).  The UEK is not
supported but it's possible some other
supported Linux distro will require the "time"
syscall at some point, so it doesn't hurt to
permit it in our filter.
Fixes elastic/elasticsearch#41101
Backport of #459
> [6.7][ML] Add the "time" syscall to the syscall filter

- docs/CHANGELOG.asciidoc
- lib/seccomp/CSystemCallFilter_Linux.cc
This is required with the Oracle Unbreakable
Enterprise Kernel (UEK).  The UEK is not
supported but it's possible some other
supported Linux distro will require the "time"
syscall at some point, so it doesn't hurt to
permit it in our filter.
Fixes elastic/elasticsearch#41101
Backport of #459
> [7.0][ML] Add the "time" syscall to the syscall filter

- docs/CHANGELOG.asciidoc
- lib/seccomp/CSystemCallFilter_Linux.cc
This is required with the Oracle Unbreakable
Enterprise Kernel (UEK).  The UEK is not
supported but it's possible some other
supported Linux distro will require the "time"
syscall at some point, so it doesn't hurt to
permit it in our filter.
Fixes elastic/elasticsearch#41101
Backport of #459
> [7.1][ML] Add the "time" syscall to the syscall filter

- build-setup/linux.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/vagrant/linux/provision.sh
This is a follow on to #453
The stack protector, relro and fortify source options
need to be used when building gcc, because we redistribute
two libraries that are built as part of it, namely
libgcc_s.so.1 and libstdc++.so.6.
> [ML] Use hardening options for gcc 7.3 build

- build-setup/linux.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/vagrant/linux/provision.sh
This is a follow on to #453
The stack protector, relro and fortify source options
need to be used when building gcc, because we redistribute
two libraries that are built as part of it, namely
libgcc_s.so.1 and libstdc++.so.6.
Backport of #470
> [7.1][ML] Use hardening options for gcc 7.3 build

- include/maths/COutliers.h
- lib/maths/COutliers.cc
- lib/maths/unittest/COutliersTest.cc
- lib/maths/unittest/COutliersTest.h
We were hitting issues when the sample of points used for computing nearest neighbours contained only duplicates. In particular, we weren't initialising the local reachability density (lrd) for LOF properly and we weren't computing the cumulative density function (cdf) value for the scores properly when aggregating. This fixes both these problems by using the usual lower bound for lrd and lower bounding the scores' coefficient of variation used to compute the cdf.
> [ML] Improve behaviour of outlier detection with when nearly all points are duplicates

- bin/data_frame_analyzer/Main.cc
- include/api/CDataFrameAnalysisRunner.h
- include/core/CProgramCounters.h
- lib/api/CDataFrameOutliersRunner.cc
- lib/core/unittest/CProgramCountersTest.cc
- lib/core/unittest/CProgramCountersTest.h
- lib/maths/COutliers.cc
This adds some basic performance counters; specifically, (actual and estimated) peak memory usage, run time and the number of partitions used. We will likely add to this over time, but this is a useful first set.
> [ML] Add some instrumentation of outlier detection

- build-setup/linux.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/vagrant/linux/provision.sh
- docs/CHANGELOG.asciidoc
Recent Linux distributions do not install libcrypt as a
system library by default.  We do not use any functionality
from this library, so it is better to build our other
dependencies in such a way that they don't link to libcrypt.
This avoids the need to install extra OS packages before
Elasticsearch.
Closes #478
> [ML] Stop linking to libcrypt on Linux

- build-setup/linux.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/vagrant/linux/provision.sh
- docs/CHANGELOG.asciidoc
Recent Linux distributions do not install libcrypt as a
system library by default.  We do not use any functionality
from this library, so it is better to build our other
dependencies in such a way that they don't link to libcrypt.
This avoids the need to install extra OS packages before
Elasticsearch.
Backport of #480
> [7.2][ML] Stop linking to libcrypt on Linux

- lib/core/unittest/CDataFrameTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/COutliersTest.cc
> [7.2][ML] Switch to use temporary test directory for data frame storage in tests

- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
This receives a delta so should keep the running total itself.
> [ML] Correct outlier peak memory callback and test

- docs/CHANGELOG.asciidoc
- include/model/CResourceMonitor.h
- lib/api/CModelSizeStatsJsonWriter.cc
- lib/api/unittest/CJsonOutputWriterTest.cc
- lib/api/unittest/CModelSnapshotJsonWriterTest.cc
- lib/model/CResourceMonitor.cc
Add the current model memory limit and the number of bytes in
excess of that at the point of the last allocation failure to the model
size stats. These will be used to construct a (hopefully) more
informative hard_limit audit message.
The reported memory usage is also scaled to take into account the byte
limit margin, which is in play in the initial period of a jobs' lifetime
and is used to scale down the high memory limit. This should give a more
accurate representation of how close the memory usage is to the high
limit.
relates https://github.com/elastic/elasticsearch/pull/42086
closes https://github.com/elastic/elasticsearch/issues/38034
> [ML] Improve hard_limit audit message

- docs/CHANGELOG.asciidoc
- include/model/CResourceMonitor.h
- lib/api/CModelSizeStatsJsonWriter.cc
- lib/api/unittest/CJsonOutputWriterTest.cc
- lib/api/unittest/CModelSnapshotJsonWriterTest.cc
- lib/model/CResourceMonitor.cc
relates https://github.com/elastic/elasticsearch/pull/42086
Backports #486
> [7.2][ML] Improve hard_limit audit message (#486)

- docs/CHANGELOG.asciidoc
- lib/maths/COneOfNPrior.cc
- lib/maths/CTimeSeriesModel.cc
- lib/model/unittest/CEventRateModelTest.cc
- lib/model/unittest/CMetricAnomalyDetectorTest.cc
One of our QA sets has shown a regression associated with #468. This was triggered by selecting our Poisson process model in conjunction with a periodic event rate. Including the Poisson process at all in such cases is low value and since we don't properly deal with the change in variance associated with rate changes in this case it has undesirable side effects. This change simply removes it from model selection if we start modelling seasonality (we can revisit this if we do any work to better deal with the variance).
I also increased the parameter introduced in #468 (this means we revert slightly more to our old behaviour). Finally, I've rejigged reinitialisation of the multi-bucket model decay rate, which should have been matching the single bucket model.
> [ML] Fix regression in QA data set

- docs/CHANGELOG.asciidoc
- lib/maths/CTimeSeriesModel.cc
- lib/model/unittest/CEventRateAnomalyDetectorTest.cc
This improves the interaction between multi-bucket feature and the model we maintain attending specifically to periods flagged as anomalous. In particular, we were suppressing updates of this anomaly model if the bucket probability was high but continuing to adjust the overall probability if the multi-bucket feature probability was low. The upshot our scores were inappropriately high.
This change pegs the time used to compute the anomaly duration to the last update time for the anomaly model and also smoothly reduces the impact on our overall result if the bucket value itself is normal.
This should help with #477.
> [ML] Reduce false positives associated with the multi-bucket feature

- docs/CHANGELOG.asciidoc
- include/maths/CModel.h
- lib/maths/CModel.cc
- lib/maths/CTimeSeriesModel.cc
- lib/model/unittest/CEventRateAnomalyDetectorTest.cc
For count/sum functions for sparse data we automatically switch to modelling the count/sum given the bucket is not empty when the proportion of empty buckets becomes too high. In such cases, we account for the chance a bucket is empty, but we applied the correction to both the single and multi-bucket feature probabilities. The upshot was we were accounting for this term twice in the overall bucket probability and non-empty buckets for sparse data were generating false positives.
This is another change aimed at #477.
> [ML] Reduce false positives for sum and count functions on sparse data

- 3rd_party/3rd_party.sh
- 3rd_party/licenses/apr-INFO.csv
- 3rd_party/licenses/apr-NOTICE.txt
- 3rd_party/licenses/apr-iconv-INFO.csv
- 3rd_party/licenses/apr-iconv-NOTICE.txt
- 3rd_party/licenses/apr-util-INFO.csv
- 3rd_party/licenses/apr-util-NOTICE.txt
- 3rd_party/licenses/expat-INFO.csv
- 3rd_party/licenses/expat-LICENSE.txt
- build-setup/linux.md
- build-setup/windows.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/download_windows_deps.ps1
- dev-tools/vagrant/linux/provision.sh
- docs/CHANGELOG.asciidoc
In this change:
- libapr is upgraded to version 1.7.0 from version 1.5.2
- libapriconv is upgraded to version 1.2.2 from version 1.2.1
- libaprutil is upgraded to version 1.6.1 from version 1.5.4
- libexpat is upgraded to version 2.2.6 from the (ancient) version that used to be embedded into libaprutil prior to version 1.6.0
libaprutil no longer embeds libexpat, so it has to be built separately.
> [ML] Upgrade the Apache Portable Runtime libraries

- 3rd_party/3rd_party.sh
- 3rd_party/licenses/apr-INFO.csv
- 3rd_party/licenses/apr-NOTICE.txt
- 3rd_party/licenses/apr-iconv-INFO.csv
- 3rd_party/licenses/apr-iconv-NOTICE.txt
- 3rd_party/licenses/apr-util-INFO.csv
- 3rd_party/licenses/apr-util-NOTICE.txt
- 3rd_party/licenses/expat-INFO.csv
- 3rd_party/licenses/expat-LICENSE.txt
- build-setup/linux.md
- build-setup/windows.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/download_windows_deps.ps1
- dev-tools/vagrant/linux/provision.sh
- docs/CHANGELOG.asciidoc
In this change:
- libapr is upgraded to version 1.7.0 from version 1.5.2
- libapriconv is upgraded to version 1.2.2 from version 1.2.1
- libaprutil is upgraded to version 1.6.1 from version 1.5.4
- libexpat is upgraded to version 2.2.6 from the (ancient) version
that used to be embedded into libaprutil prior to version 1.6.0
libaprutil no longer embeds libexpat, so it has to be built separately.
Backport of #495
> [ML][7.3] Upgrade the Apache Portable Runtime libraries

- docs/CHANGELOG.asciidoc
- include/maths/CPeriodicityHypothesisTests.h
- include/maths/CTimeSeriesDecomposition.h
- include/maths/CTimeSeriesDecompositionDetail.h
- include/maths/CTimeSeriesDecompositionInterface.h
- include/maths/CTimeSeriesDecompositionStub.h
- include/maths/CTimeSeriesModel.h
- lib/api/unittest/CAnomalyJobLimitTest.cc
- lib/maths/CPeriodicityHypothesisTests.cc
- lib/maths/CTimeSeriesDecomposition.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/CTimeSeriesDecompositionStub.cc
- lib/maths/CTimeSeriesModel.cc
- lib/maths/unittest/CForecastTest.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
- lib/model/unittest/CMetricModelTest.cc
Following on from #489, the same data set showed up some improvements we can make to the detection and initialisation of new seasonal components, the seeding of the residual model when new components are detected and instabilities associated with ageing out old data. To that end, this PR makes the following changes:
1. Improve the handling of linear scaling events when testing for new seasonal components and
2. Preprocess the window values to match correctly match the best trend hypothesis from the test,
3. Use a callback to correctly seed the residual model from the test window.
4. Avoid an instability associated with allowing the seasonal component decay rate to become too large with respect to its period.
> [ML] Improve seasonal component lifecycle for time series modelling

- include/maths/CKdTree.h
- include/maths/COutliers.h
- lib/maths/unittest/CKdTreeTest.cc
- lib/maths/unittest/CKdTreeTest.h
- lib/maths/unittest/COutliersTest.cc
- lib/maths/unittest/COutliersTest.h
The special case handling for when the requested number of neighbours *exactly* equals the number of points in the k-d tree was broken: it wasn't returning any points. This could cause an invalid read in outlier detection.
This PR fixes the bug in the k-d tree and makes the outlier code defensive if the neighbour set is ever ~~empty~~ too small.
The code isn't released so marking as a non-issue.
> [ML] Fix a SIGSEGV in outlier detection

- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
It is not guaranteed that the model will use 3 seasonal components in `CTimeSeriesDecompositionTest::testSeasonalOnset`. This test should only check that at least two components have been initialised. This showed up as a sporadic test failure on Windows.
> [ML] Fix occasional test failure

- include/maths/CKdTree.h
- include/maths/COutliers.h
- lib/maths/unittest/CKdTreeTest.cc
- lib/maths/unittest/CKdTreeTest.h
- lib/maths/unittest/COutliersTest.cc
- lib/maths/unittest/COutliersTest.h
> [7.3][ML] Fix a SIGSEGV in outlier detection

- docs/CHANGELOG.asciidoc
- lib/api/CAnomalyJob.cc
Similar to the fix for state and quantiles in #437,
if no input is received and time is not advanced then
there is no need to write model size stats when the
autodetect process exits. Doing this can actually
cause a problem for a job that has never ever seen
any input, as the unnecessary model size stats were
written with a negative timestamp. This change also
adds an extra defensive check to prevent that ever
happening, although the only situation when it is
thought to be possible should be prevented by the
first change.
Fixes #394
> [ML] Do not write model size stats after autodetect no-op

- docs/CHANGELOG.asciidoc
- lib/api/CAnomalyJob.cc
Similar to the fix for state and quantiles in #437,
if no input is received and time is not advanced then
there is no need to write model size stats when the
autodetect process exits. Doing this can actually
cause a problem for a job that has never ever seen
any input, as the unnecessary model size stats were
written with a negative timestamp. This change also
adds an extra defensive check to prevent that ever
happening, although the only situation when it is
thought to be possible should be prevented by the
first change.
Backport of #512
> [7.x][ML] Do not write model size stats after autodetect no-op

- docs/CHANGELOG.asciidoc
- lib/api/CAnomalyJob.cc
Similar to the fix for state and quantiles in #437,
if no input is received and time is not advanced then
there is no need to write model size stats when the
autodetect process exits. Doing this can actually
cause a problem for a job that has never ever seen
any input, as the unnecessary model size stats were
written with a negative timestamp. This change also
adds an extra defensive check to prevent that ever
happening, although the only situation when it is
thought to be possible should be prevented by the
first change.
Backport of #512
> [7.2][ML] Do not write model size stats after autodetect no-op

- docs/CHANGELOG.asciidoc
- lib/api/CAnomalyJob.cc
Similar to the fix for state and quantiles in #437,
if no input is received and time is not advanced then
there is no need to write model size stats when the
autodetect process exits. Doing this can actually
cause a problem for a job that has never ever seen
any input, as the unnecessary model size stats were
written with a negative timestamp. This change also
adds an extra defensive check to prevent that ever
happening, although the only situation when it is
thought to be possible should be prevented by the
first change.
Backport of #512
> [6.8][ML] Do not write model size stats after autodetect no-op

- lib/model/CForecastModelPersist.cc
For some reason, if code is compiled with `-g -O0` using g++ 7.3, then several fields within the const reference to `params` get modified to random values. This problem does not occur when using `boost::bind` or replacing `std::bind` with an equivalent lambda expression.  I could not find any relevant reference to an official bug report in `stdlib`.
> [ML] Workaround a bug with std::bind by changing to lambda

- include/api/CDataFrameOutliersRunner.h
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
Renames outlier detection setting `minimum_score_to_write_feature_influence`
to `feature_influence_threshold`.
> [ML] Rename outlier detection setting to feature_influence_threshold

- docs/CHANGELOG.asciidoc
- lib/api/CAnomalyJob.cc
Persisting state when there has been no input data:
1. Is a waste of time
2. Causes the model snapshot document to embed an invalid
model size stats document which causes an error in Elasticsearch
So we should not do this.
Fixes #519
> [ML] Ignore "persist now" control message if no prior input

- docs/CHANGELOG.asciidoc
- lib/api/CAnomalyJob.cc
Persisting state when there has been no input data:
1. Is a waste of time
2. Causes the model snapshot document to embed an invalid
model size stats document which causes an error in Elasticsearch
So we should not do this.
Backport of #521
> [6.8][ML] Ignore "persist now" control message if no prior input

- docs/CHANGELOG.asciidoc
- lib/api/CAnomalyJob.cc
Persisting state when there has been no input data:
1. Is a waste of time
2. Causes the model snapshot document to embed an invalid
model size stats document which causes an error in Elasticsearch
So we should not do this.
Backport of #521
> [7.2][ML] Ignore "persist now" control message if no prior input

- docs/CHANGELOG.asciidoc
- lib/api/CAnomalyJob.cc
Persisting state when there has been no input data:
1. Is a waste of time
2. Causes the model snapshot document to embed an invalid
model size stats document which causes an error in Elasticsearch
So we should not do this.
Backport of #521
> [7.x][ML] Ignore "persist now" control message if no prior input

- lib/model/CForecastModelPersist.cc
For some reason, if code is compiled with -g -O0 using g++ 7.3, then several fields within the const reference to params get modified to random values. This problem does not occur when using boost::bind or replacing std::bind with an equivalent lambda expression. I could not find any relevant reference to an official bug report in stdlib.
> [7.3][ML] Workaround a bug with std::bind by changing to lambda (#514)

- include/api/CDataFrameAnalysisSpecification.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.h
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
This PR introduces an optional json specification parameter `disk_usage_allowed`, which is `false` by default. This parameter controls whether or not the system can overflow data frame to disk. 
Relates elastic/ml-team#168
> [ML] Introduction disk usage parameter for data frames

- include/api/CDataFrameAnalysisSpecification.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.h
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
This PR introduces an optional json specification parameter disk_usage_allowed, which is false by default. This parameter controls whether or not the system can overflow data frame to disk.
Relates elastic/ml-team#168
> [7.3][ML] Introduction disk usage parameter for data frames (#522)

- lib/maths/CBoostedTree.cc
We only need to visit rows for the child with fewest rows when refreshing leaf statistics after a split and can compute the others from the parent and sibling values.
This gets us around a 10% speed up in the unit tests, but the gain should be significantly larger for large data sets when we've overflowed to disk.
> [FEATURE][ML] Speed up computing node statistics after split during boosted tree training

- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
Whilst investigating #511, I noticed that the data_frame_analyzer will happily run an analysis on a frame with fewer rows than specified in the configuration object. Currently, there is no reason that this should happen and it would indicate a problem with the calling Java code if it did. This change adds a consistency check and fails if the values are inconsistent.
> [ML] Check the data frame row count is consistent with the analysis configuration

- include/api/CDataFrameAnalysisConfigReader.h
- include/api/CDataFrameAnalysisSpecification.h
- lib/api/CDataFrameAnalysisConfigReader.cc
- lib/api/CDataFrameAnalysisSpecification.cc
This PR moves the definitions of the constants for json specification parameter names into the class `CDataFrameAnalysisSpecification`. The type of the constants is changed from `const char* const` to `static const std::string`. This makes them consistent with definitions of other constants elsewhere in the code and adhere to the practices of the modern C++ development.
> [ML] Move json constants to CDataFrameAnalysisSpecification definition

- include/api/CDataFrameAnalysisConfigReader.h
- include/api/CDataFrameAnalysisSpecification.h
- lib/api/CDataFrameAnalysisConfigReader.cc
- lib/api/CDataFrameAnalysisSpecification.cc
This PR moves the definitions of the constants for json specification parameter names into the class `CDataFrameAnalysisSpecification`. The type of the constants is changed from `const char* const` to `static const std::string`. This makes them consistent with definitions of other constants elsewhere in the code and adhere to the practices of the modern C++ development.
> [7.4][ML] Move json constants to CDataFrameAnalysisSpecification definition

- include/api/CDataFrameAnalysisConfigReader.h
- include/api/CDataFrameAnalysisSpecification.h
- include/api/CDataFrameAnalysisSpecificationJsonWriter.h
- lib/api/CDataFrameAnalysisConfigReader.cc
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalysisSpecificationJsonWriter.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/Makefile.first
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.h
- lib/api/unittest/CDataFrameAnalyzerTest.cc
If the json specification parameter `temp_dir` is not set, but `disk_usage_allowed` is `true`, the specification is in inconsistent state. This PR adds an error message informing user about the misconfiguration.
> [ML] Temporary directory must be set if disk usage is allowed

- include/api/CDataFrameAnalysisSpecificationJsonWriter.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalysisSpecificationJsonWriter.cc
- lib/api/Makefile.first
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.h
- lib/api/unittest/CDataFrameAnalyzerTest.cc
If the json specification parameter temp_dir is not set, but disk_usage_allowed is true, the specification is in inconsistent state. This PR adds an error message informing user about the misconfiguration.
> [7.4][ML] Temporary directory must be set if disk usage is allowed (#534)

- include/api/CDataFrameAnalysisConfigReader.h
- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameOutliersRunner.h
- lib/api/CDataFrameAnalysisConfigReader.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.h
Following on from #536, this tidies up the remaining uses of c-style strings in `CDataFrameAnalysisConfigReader` and `CDataFrameAnalysisRunnerFactory`.
> [ML] Fully migrate data frame analysis parameter reader to use std::string

- include/maths/CDataFrameUtils.h
- include/maths/CMic.h
- include/test/CRandomNumbers.h
- lib/core/CDataFrame.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/CMic.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.h
This is helper functionality we'll use for choosing how to encode categorical fields. In particular, it is functionality to 1) compute category frequencies, 2) compute the mean target value for each category, and 3) to compute MICe for hot-one encoded categories and the target variable.
I've split this out to keep the PR smaller.
> [FEATURE][ML] Tools for auto encoding categorical fields

- lib/maths/CDataFrameUtils.cc
Following on from the suggestion of @valeriy42 in #539, this PR implements a generic reduce operation over the results of reading `core::CDataFrame` rows. Although this is slightly more verbose, despite sharing some code, I feel like it does better separate out logical concerns in the functions which use it.
I considered rolling reading the rows into this function and also moving to `core::CDataFrame`. I decided against this for the following reasons:
1. I then have to duplicate the various versions taking different parameters
2. Passing the state from the read to the reduce step via `core::bindRetrievableState` was all then hidden and I felt this made the resulting code more opaque
3. There aren't that many other places in the code which benefit from this yet
I'd be happy to revisit this …
> [FEATURE][ML] Template reducing results read from a data frame

- include/maths/CLinearAlgebraEigen.h
- lib/maths/unittest/CLinearAlgebraTest.cc
[This](https://github.com/elastic/ml-cpp/pull/544/files/64cdffd6576bb0ab40b86555635877824a901337#r303851555) comment intrigued me. It turns out the underlying reason is the Eigen operator<< doesn't behave like one might expect: it works by overwriting the elements from the start of the array representation with the comma separated list supplied. Therefore, as it stood `fromStdVector` wrote all the values into the first element of the vector and left the remaining ones uninitialised.
This change also makes a couple of tweaks to conform to coding standards (public static members first, etc) and makes the to and from std vector methods private for the time being since they're only used by persistence.
> [FEATURE][ML] Fix CDenseVector::fromStdVector

- include/core/CDataFrame.h
- include/maths/CBoostedTree.h
- include/maths/CDataFrameCategoryEncoder.h
- include/maths/CDataFrameUtils.h
- lib/api/CDataFrameAnalyzer.cc
- lib/core/CDataFrame.cc
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/CMic.cc
- lib/maths/Makefile
- lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
- lib/maths/unittest/CDataFrameCategoryEncoderTest.h
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/Main.cc
- lib/maths/unittest/Makefile
This change also provides a data frame row reference wrapper which allows one to access encoded feature values as though they were stored in the data frame.
We use MICe to decide which categories to one-hot encode (which is a lossless scheme) when there are sufficient data, mean target encoding when there are sufficient samples for a category and one catch all indicator variable for rare categories of a categorical column.
All one-hot encoded categories and metrics are chosen together. We have a single parameter which controls whether we prefer choosing distinct metrics and categories from different categorical columns or whether we just consider MICe with the target variable. This accounts for the fact that we typically expect more correlation between errors from distinct categories of …
> [FEATURE][ML] Automatic categorical field encoding

- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
Following on from merging #542, there were some more C-style strings to migrate on this branch. There were also some formatting and test failures to fix.
> [FEATURE][ML] Fix some merge fallout

- lib/core/CNamedPipeFactory.cc
In `CNamedPipeFactory::initPipeHandle` the named pipe file name is stat-ed to check it does not exist. Failure of `lstat` is considered a successful outcome in that the file does not exist and can now be created but `lstat` may fail for a number of reasons. 
The motivation for the change is the following log message spotted in the wild. The message can only occur if `lstat` return a non-zero value and the following called to `mkfifo` failed because the file exists. 
```org.elasticsearch.ElasticsearchException: Unable to create named pipe /tmp/elasticsearch-XXX/normalize_some_ml_job: File exists```
relates to elastic/elasticsearch#43830
> Log if lstat fails for a reason other than missing file

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
This catches the main case we need to care about: that we'll use more resources than were budgeted for. We can't check for equality because the Java currently excludes rows for reasons other than the search filter and these aren't considered when it passes the expected row count.
> [ML] Only check that the supplied rows don't exceed the specified for data frame analyses

- include/core/CPersistUtils.h
- include/maths/CBayesianOptimisation.h
- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBayesianOptimisationTest.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
This PR implements the functionality for persistence and restoration of the boosted trees, e.g. to recover from failure. It also enables a creation of a `CBoostedTree` instance from a serialized string using factory.
As an additional minimal refactoring, I added `rowsPerFeature` to the `CBoostedTreeFactory` since it is present in `Impl` and was missing before here.
> [ML] Persistence for boosted trees

- include/core/CPersistUtils.h
- include/maths/CBayesianOptimisation.h
- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBayesianOptimisationTest.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
This PR implements the functionality for persistence and restoration of the boosted trees, e.g. to recover from failure. It also enables a creation of a CBoostedTree instance from a serialized string using factory.
As an additional minimal refactoring, I added rowsPerFeature to the CBoostedTreeFactory since it is present in Impl and was missing before here.
> [ML] Persistence for boosted trees (#568)

- include/maths/CLbfgs.h
Test failures in the debug build show that a couple
of lambdas in the CLbfgs class were returning Eigen
closure types referencing temporaries that could lead
to invalid memory accesses.
This change makes the lambdas construct self-contained
types before returning to avoid accesses to out-of-scope
temporaries.
(We believe that with optimization enabled the invalid
memory accesses were not occurring as the lambdas were
optimized away.)
> [ML] Fix return type of L-BFGS lambdas

- include/maths/CLbfgs.h
Test failures in the debug build show that a couple
of lambdas in the CLbfgs class were returning Eigen
closure types referencing temporaries that could lead
to invalid memory accesses.
This change makes the lambdas construct self-contained
types before returning to avoid accesses to out-of-scope
temporaries.
(We believe that with optimization enabled the invalid
memory accesses were not occurring as the lambdas were
optimized away.)
Backport of #579
> [7.x][ML] Fix return type of L-BFGS lambdas

- include/core/RestoreMacros.h
- include/core/UnwrapRef.h
- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
Previously, we absorbed any errors emitted restoring boosted tree training state and just returned the bad object. We were also silently swallowing errors in `CBayesianOptimisation` constructor from a state traverser. Finally, we were unnecessarily wrapping individual restore loops in try blocks (this was already done in the `traverseSubLevel` function).
We now ensure all errors are propagated to `CBoostedTreeFactory::constructFromString` where we then propagate errors back to the Java via the usual `HANDLE_FATAL` mechanism. (We need to revisit whether a restore issue should be a fatal error, since we can just resume training from scratch in this case, but I'll defer that decision until it is fully wired in.)
This change also adds some bad state restore unit tests.
> [ML] Some corrections to error handling on fail to restore boosted tree training state

- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
This came up while we were debugging the new Java API: currently the error message is cryptic.
> [ML] Trap the case that no data are sent to data_frame_analyzer explicitly

- bin/data_frame_analyzer/CCmdLineParser.cc
- bin/data_frame_analyzer/CCmdLineParser.h
- bin/data_frame_analyzer/Main.cc
- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameAnalysisSpecification.h
- include/api/CMemoryUsageEstimationResultJsonWriter.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CMemoryUsageEstimationResultJsonWriter.cc
- lib/api/Makefile.first
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.h
- lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc
- lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.h
- lib/api/unittest/Main.cc
- lib/api/unittest/Makefile
Introduce a mode in which data_frame_analyzer binary only outputs memory usage estimations but does not perform any analysis. This mode will be used by the new endpoint in Java server.
Relates https://github.com/elastic/elasticsearch/issues/44699
> Introduce memory usage estimation mode in data_frame_analyzer

- include/api/CDataFrameAnalyzer.h
- lib/api/CDataFrameAnalyzer.cc
- lib/api/CDataFrameBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.h
We must call predict explicitly to ensure that rows missing the dependent variable get predictions after training a regression model.
This also corrects the initialisation of bad data counters and splits out the case that a metric value is missing, i.e. field value is empty, and the case it is non-numeric.
> [ML] Make predictions for rows missing the dependent variable value

- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CChecksum.h
- include/maths/CDataFrameCategoryEncoder.h
- include/maths/CDataFrameUtils.h
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CChecksum.cc
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/Makefile
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
- lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
- lib/maths/unittest/CDataFrameCategoryEncoderTest.h
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.h
This also makes some further refinements to category encoding. In particular, including frequency and target mean encoding explicitly in the feature selection loop. This also requires us to generalise the MICe calculations on `CDataFrameUtils` to support callbacks to define column values.
> [ML] Wire category encoding into random forest training

- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CDataFrameRegressionModel.h
- lib/api/CDataFrameBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CDataFrameRegressionModel.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
> [7.4][ML] Progress monitoring for regression model training

- include/core/CDataFrame.h
- include/maths/CDataFrameCategoryEncoder.h
- lib/api/CDataFrameAnalyzer.cc
- lib/core/CDataFrame.cc
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
- lib/maths/unittest/CDataFrameCategoryEncoderTest.h
- lib/maths/unittest/CDataFrameUtilsTest.cc
Previously, there was no bounds checking when looking up the frequency or target mean so we got undefined behaviour. This issue arises when (for example) predicting rows which don't have a value for the dependent variable and are thus excluded from training.
> [ML] Handle unseen categories in encoding

- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameAnalysisSpecification.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CMemoryUsageEstimationResultJsonWriter.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc
Apply renaming so that C++ code is consistent with Java code change (https://github.com/elastic/elasticsearch/pull/45719):
Rename expected_memory_usage_with_one_partition to expected_memory_without_disk
Rename expected_memory_usage_with_max_partitions to expected_memory_with_disk
Relates https://github.com/elastic/elasticsearch/issues/44699
> Rename memory usage estimation result fields.

- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameAnalysisSpecification.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CMemoryUsageEstimationResultJsonWriter.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc
- Rename expected_memory_usage_with_one_partition to expected_memory_without_disk  (#601)
> [7.x] Rename expected_memory_usage_with_one_partition to expected_memory_without_disk (#601)

- include/core/CDataFrame.h
- include/maths/CDataFrameCategoryEncoder.h
- lib/api/CDataFrameAnalyzer.cc
- lib/core/CDataFrame.cc
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
- lib/maths/unittest/CDataFrameCategoryEncoderTest.h
- lib/maths/unittest/CDataFrameUtilsTest.cc
> [7.4][ML] Handle unseen categories in encoding

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
> [ML] Rename outlier detection method values

- lib/maths/CDataFrameUtils.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.h
> [7.4][ML] Ignore rows which are missing the target value when mean target encoding

- include/maths/CBasicStatistics.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CDataFrameUtils.h
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.h
This change detects if a feature comprises exclusively integers and also computes the feature range on the training set. For integer valued data we should be splitting at `n + 0.5` for `n` integer valued. Also we should never include splits which are less (greater) than the smallest (largest) feature value. This allows us to significantly prune candidate splits in cases where a feature only takes a small number of distinct integer values.
I also improved the exit condition from the loop which adds trees: it was exiting with significant bias on the training set in some cases.
> [ML] Detect feature data types and refine candidate splits in boosted tree training based on type

- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
This also handles the case that we can't improve the loss on the train set with no regularisation. This ought not to be possible, at least for MSE, except for a constant zero target or regressors which we handle as a special case. However, to be safe we force the regularisation parameters to zero in this case, which should be harmless.
Closes #611.
> [ML] Add some missing boosted tree state initialisation

- include/maths/CBayesianOptimisation.h
- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
We're getting stability issues in hyperparameter optimisation. This is shows up because we don't ensure a stable order for the rows in the data frame passed to the data_frame_analyzer command. Seeding Bayesian Optimisation (BO) with several rounds of random search (RS) greatly improves stability (and is in any case considered best practice). We allocate 1/3, 2/3 split between RS and BO.
> [ML] Improve hyperparameter optimisation stability

- bin/data_frame_analyzer/Main.cc
- include/api/CDataFrameBoostedTreeRunner.h
- include/core/CProgramCounters.h
- include/maths/CBayesianOptimisation.h
- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CDataFrameRegressionModel.h
- lib/api/CDataFrameBoostedTreeRunner.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CDataFrameRegressionModel.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
- lib/maths/unittest/COutliersTest.cc
This instruments the regression code to extract peak memory usage and training run time. This enabled me to test memory usage estimation better and I've fixed a bug where we weren't properly accounting for the maximum tree and forest size.
> [ML] Instrument the regression code for memory usage and training run time

- bin/data_frame_analyzer/Main.cc
The stats are only generated once per analysis run and are needed at info to appear in the elasticsearch logs by default.
> [ML] Log stats at info on exit from the data_frame_analyzer command

- lib/api/CDataFrameAnalyzer.cc
CI failures revealed that `analyzing` progress may get stuck at `0`
even though the analysis completed correctly. After investigating
the code, there is a race condition where if the analysis completed
before we started the progress monitoring loop, we might never report
progress. While I could not reproduce to get this confirmed, this seems
the prime suspect at the moment.
This commit addressed this by always reporting progress was completed
after the analysis finishes.
Closes elastic/elasticsearch#46038
> [ML] Ensure DF analytics reports progress after finishing

- lib/api/CDataFrameAnalyzer.cc
CI failures revealed that `analyzing` progress may get stuck at `0`
even though the analysis completed correctly. After investigating
the code, there is a race condition where if the analysis completed
before we started the progress monitoring loop, we might never report
progress. While I could not reproduce to get this confirmed, this seems
the prime suspect at the moment.
This commit addressed this by always reporting progress was completed
after the analysis finishes.
Closes elastic/elasticsearch#46038
Backport of #626
> [7.4][ML] Ensure DF analytics reports progress after finishing (#626)

- lib/api/CDataFrameAnalyzer.cc
CI failures revealed that `analyzing` progress may get stuck at `0`
even though the analysis completed correctly. After investigating
the code, there is a race condition where if the analysis completed
before we started the progress monitoring loop, we might never report
progress. While I could not reproduce to get this confirmed, this seems
the prime suspect at the moment.
This commit addressed this by always reporting progress was completed
after the analysis finishes.
Closes elastic/elasticsearch#46038
Backport of #626
> [7.x][ML] Ensure DF analytics reports progress after finishing (#626)

- docs/CHANGELOG.asciidoc
- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CDataFrameCategoryEncoder.h
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CDataFrameCategoryEncoder.cc
Profiling showed up a couple of performance improvements:
1. We can calculate the node with the fewest rows more efficiently when refreshing derivative statistics
2. We benefit from inlining and a couple of small tweaks in one of the bottleneck functions `addRowDerivatives`
It also showed it is worthwhile threading the calculation of the leaf values which minimise the prediction errors. This required a refactor of `CArgMinLoss` so that we can get a copyable polymorphic type. I've wrapped up its implementation to achieve this.
> [ML] Boosted tree training performance improvements

- lib/maths/CBayesianOptimisation.cc
- lib/maths/unittest/CBoostedTreeTest.cc
We could run into the case that kernel was singular to working precision. This was underflowing the log likelihood calculation, causing us to select a junk kernel.
> [ML] Fix blow up in minus log-likelihood for Bayesian optimisation

- lib/maths/CBayesianOptimisation.cc
- lib/maths/unittest/CBoostedTreeTest.cc
> [7.5][ML] Fix blow up in minus log-likelihood for Bayesian optimisation

- lib/maths/CBayesianOptimisation.cc
- lib/maths/unittest/CBoostedTreeTest.cc
> [7.4][ML] Fix blow up in minus log-likelihood for Bayesian optimisation

- include/maths/CBayesianOptimisation.h
- include/maths/CBoostedTreeImpl.h
- lib/api/CDataFrameBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
The principal bug was that the tree size is defined by number of leaves, i.e. it is allowed to have `maximumTreeSize + 1` leaves. For a binary tree this translates to `2 * maximumTreeSize + 1` nodes in total. We also weren't accounting for the extra columns when reporting estimated memory usage to the logs. Finally, I've added some additional (albeit small) users of memory to the estimation calculation: the validate/train masks, the Bayesian optimisation state, etc. (This was factored out of #625.)
> [ML] Some improvements and a correction to memory estimation for boosted tree training

- lib/maths/CBayesianOptimisation.cc
This PR adds the functionality to persist and restore parameters `RangeScale`, `RangeShift`, and `Restarts` in `BayesianOptimization` class.
> [ML] Add missing bayesopt parameters for persistence/restore

- docs/CHANGELOG.asciidoc
- lib/maths/CTimeSeriesModel.cc
We were missing the initialisation of the return type from updating the trend for multivariate models (this only, potentially, affects results for the lat/long function). This could in rare circumstances cause us to reinitialise the model.
This is a good candidate cause for some sporadic test failures we've seen.
> [ML] Missing variable initialisation causing spurious model reinitialisation for lat/long function

- docs/CHANGELOG.asciidoc
- lib/maths/CTimeSeriesModel.cc
> [7.5][ML] Missing variable initialisation causing spurious model reinitialisation for lat/long function

- docs/CHANGELOG.asciidoc
- lib/maths/CTimeSeriesModel.cc
> [7.4][ML] Missing variable initialisation causing spurious model reinitialisation for lat/long function

- include/maths/CBoostedTreeImpl.h
It is possible that the data isn't separated by any split which is available for a given feature, i.e. imagine we've already decided to split on a binary feature. In this case we were getting an out of bound read in `m_CandidateSplits[i][splitAt]`. I've moved the reading of this inside the loop.
> [ML] Trap out-of-bounds read in search for best split

- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
We weren't properly centring the data when measuring the change in loss. For data where the variance across the training set is small compared to the mean this meant we could significantly over estimate the initial values for `lambda` and `gamma`.
I've also switched to using a single tree to estimate the magnitude of the change in the loss term of the objective. Using a full forest tests underestimates the change per split by roughly a factor of the shrinkage. Finally, rather than using a fixed scaling of `lambda` and `gamma` I scale them by the shrinkage on initialisation to account for the regularisation effect of smaller shrinkage.
This change also closes #631 since it was useful to be able to train a forest of size one for this change.
> [ML] Improve boosted tree training parameter initialisation 

- bin/data_frame_analyzer/CCmdLineParser.cc
- bin/data_frame_analyzer/CCmdLineParser.h
- bin/data_frame_analyzer/Main.cc
- include/api/CDataFrameAnalysisSpecification.h
- include/api/ElasticsearchStateIndex.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
This PR introduces following changes:
- Persister is writing `{"index"...}` and `\0` for every persistence state to comply with requirements for bulk operations
- `JobId` is passed over JSON Specification instead of the command line
- Constants for `ML_STATE` and `REGRESSION_TRAIN_STATE_TYPE` are moved to a dedicated header file
> [ML] Refactoring of the persistence for regression

- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
For outlier detection the estimate is accurate and for regression it is an upper bound.
> [ML] Don't add a margin when checking the memory limit for data frame analyses

- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
> [7.4][ML] Don't add a margin when checking the memory limit for data frame analyses

- build-setup/macos.md
- mk/macosx.mk
Starting with macOS Mojave, Apple has deprecated picking
up system headers from /usr/include.  Instead they should
be picked up from the appropriate SDK directory in the
Xcode app.
> [ML] Pick up headers from the approved place on macOS Mojave

- build-setup/macos.md
- mk/macosx.mk
Starting with macOS Mojave, Apple has deprecated picking
up system headers from /usr/include.  Instead they should
be picked up from the appropriate SDK directory in the
Xcode app.
Backport of #669
> [7.x][ML] Pick up headers from the approved place on macOS Mojave

- build-setup/macos.md
- mk/macosx.mk
Starting with macOS Mojave, Apple has deprecated picking
up system headers from /usr/include.  Instead they should
be picked up from the appropriate SDK directory in the
Xcode app.
Backport of #669
> [7.4][ML] Pick up headers from the approved place on macOS Mojave

- build-setup/macos.md
- mk/macosx.mk
Starting with macOS Mojave, Apple has deprecated picking
up system headers from /usr/include.  Instead they should
be picked up from the appropriate SDK directory in the
Xcode app.
Backport of #669
> [6.8][ML] Pick up headers from the approved place on macOS Mojave

- include/api/CDataFrameAnalysisSpecification.h
- include/api/CDataFrameAnalysisSpecificationJsonWriter.h
- include/api/CDataFrameBoostedTreeRunner.h
- include/api/ElasticsearchStateIndex.h
- include/maths/CBoostedTreeFactory.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalysisSpecificationJsonWriter.cc
- lib/api/CDataFrameBoostedTreeRunner.cc
- lib/api/ElasticsearchStateIndex.cc
- lib/api/Makefile.first
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.h
- lib/maths/CBoostedTreeFactory.cc
This PR implements restoring the Analyzer from a data in named pipe. It also introduces the usage of CStateCompressor and CStateDecompressor for compression and decompression of the state.
As a minor refactoring, memory estimation callback was moved from a lambda function into a dedicated method for symmetry with other callback functions.
> [7.5][ML] Restore regression state from named pipe (#660)

- bin/data_frame_analyzer/Main.cc
- include/api/CDataFrameAnalyzer.h
- lib/api/CDataFrameAnalyzer.cc
This PR fixes the way `restoreSearcherSupplier` is passed from main to the business logic.
> [ML] Remote obsolete reference to restoreSearcherSupplier in Analyzer

- bin/data_frame_analyzer/Main.cc
- include/api/CDataFrameAnalyzer.h
- lib/api/CDataFrameAnalyzer.cc
This PR fixes the way restoreSearcherSupplier is passed from main to the business logic.
Backport to #683
> [7.5][ML] Remote obsolete reference to persisterSupplier in Analyzer (#683)

- docs/CHANGELOG.asciidoc
- lib/model/CForecastModelPersist.cc
A reference to a temporary variable was causing forecast model restoration to fail.
Oddly this was only occurring on Mac builds and even then only with versions of clangd > 10.0.0
The bug was picked up by the `CForecastModelPersistTest::testPersistAndRestore` unit test where it manifested itself in an incorrect bucket length upon model state restoration.
> [ML] Fix dangling reference in CForecastModelPersist

- include/api/CDataFrameAnalyzer.h
Refactors the code by removing an unused reference in `CDataFrameAnalyzer.h`.
> [ML] Remove unused references in CDataFrameAnalyzer

- docs/CHANGELOG.asciidoc
- lib/model/CForecastModelPersist.cc
A reference to a temporary variable was causing forecast model restoration to fail.
Oddly this was only occurring on Mac builds and even then only with versions of clangd > 10.0.0
Backports #688
> [7.5][ML] Fix dangling reference in CForecastModelPersist (#688)

- docs/CHANGELOG.asciidoc
- lib/model/CForecastModelPersist.cc
A reference to a temporary variable was causing forecast model restoration to fail.
Oddly this was only occurring on Mac builds and even then only with versions of clangd > 10.0.0
Backports #688
> [7.4][ML] Fix dangling reference in CForecastModelPersist (#688)

- docs/CHANGELOG.asciidoc
- lib/model/CForecastModelPersist.cc
A reference to a temporary variable was causing forecast model restoration to fail.
Oddly this was only occurring on Mac builds and even then only with versions of clangd > 10.0.0
Backports #688
> [6.8][ML] Fix dangling reference in CForecastModelPersist (#688)

- include/api/CDataFrameAnalyzer.h
Refactors the code by removing an unused reference in CDataFrameAnalyzer.h.
Backport for #685
> [7.5][ML]Remove unused references (#685)

- lib/core/CLoopProgress.cc
The problem is described in
https://stackoverflow.com/questions/7411515/why-does-c-require-a-user-provided-default-constructor-to-default-construct-a
Moving construction of the hasher object into the checksum
method won't matter in practice as the constructor is a
no-op and the object has no data members, so it should get
completely optimised away.
> [ML] Work around compile error in old Xcode

- lib/core/CLoopProgress.cc
The problem is described in
https://stackoverflow.com/questions/7411515/why-does-c-require-a-user-provided-default-constructor-to-default-construct-a
Moving construction of the hasher object into the checksum
method won't matter in practice as the constructor is a
no-op and the object has no data members, so it should get
completely optimised away.
Backport of #699
> [7.x][ML] Work around compile error in old Xcode

- include/core/RestoreMacros.h
- include/maths/CBoostedTree.h
- include/maths/CDataFrameCategoryEncoder.h
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
This PR moves the logic of categorical encoding into a map and replaces online computations in operator[] by a look-up.
Backport to #689
> [7.5][ML] Encapsulate encoding logic (#689)

- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
Debugging intermittent failures in an integration test showed up an out of bounds read when computing the internal node gain and sum curvature if the data is very simple. This was introduced #686 which hasn't been released.
> [ML] Trap out-of-bounds read initialising boosted tree training

- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameAnalysisSpecification.h
- include/api/CDataFrameAnalyzer.h
- include/api/CDataFrameBoostedTreeRunner.h
- include/api/CDataFrameClassificationRunner.h
- include/api/CDataFrameOutliersRunner.h
- include/api/CDataFrameRegressionRunner.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/CDataFrameBoostedTreeRunner.cc
- lib/api/CDataFrameClassificationRunner.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/CDataFrameRegressionRunner.cc
- lib/api/Makefile.first
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.h
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.h
- lib/api/unittest/CDataFrameMockAnalysisRunner.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.h
Make CDataFrameBoostedTreeRunner class abstract and derive two subclasses from it:
1. CDataFrameRegressionRunner
2. CDataFrameClassificationRunner
Relates https://github.com/elastic/elasticsearch/issues/46735
> Introduce classification analysis runner.

- build-setup/clion/using_clion.md
- dev-tools/compiledb.sh
- dev-tools/init_compiledb.sh
The CLion setup instructions used to specify two
different ways of setting up the compilation database,
one of which didn't always work.
This removes the option that was claimed to not always
work so that there is now one recommended way to do the
setup.
It also adds the script that is used into the repo so
that it doesn't have to be created locally by every
user.
> [ML] Simplify CLion setup instructions

- include/core/CContainerPrinter.h
- include/model/CAnomalyDetectorModel.h
- include/model/CCountingModel.h
- include/model/CEventRateModel.h
- include/model/CEventRatePopulationModel.h
- include/model/CMetricModel.h
- include/model/CMetricPopulationModel.h
- lib/core/unittest/CContainerPrinterTest.cc
- lib/model/CAnomalyDetector.cc
- lib/model/CCountingModel.cc
- lib/model/CEventRateModel.cc
- lib/model/CEventRatePopulationModel.cc
- lib/model/CMetricModel.cc
- lib/model/CMetricPopulationModel.cc
- lib/model/unittest/CEventRateModelTest.cc
- lib/model/unittest/CMetricModelTest.cc
- lib/model/unittest/CMetricPopulationModelTest.cc
- lib/model/unittest/Mocks.cc
- lib/model/unittest/Mocks.h
std::auto_ptr has been removed from C++17, so we need
to stop using it before we can upgrade to C++17.
Also corrected the type name of a typedef of a
std::auto_ptr.
> [ML] Replace std::auto_ptr with std::unique_ptr

- include/core/CContainerPrinter.h
- include/model/CAnomalyDetectorModel.h
- include/model/CCountingModel.h
- include/model/CEventRateModel.h
- include/model/CEventRatePopulationModel.h
- include/model/CMetricModel.h
- include/model/CMetricPopulationModel.h
- lib/core/unittest/CContainerPrinterTest.cc
- lib/model/CAnomalyDetector.cc
- lib/model/CCountingModel.cc
- lib/model/CEventRateModel.cc
- lib/model/CEventRatePopulationModel.cc
- lib/model/CMetricModel.cc
- lib/model/CMetricPopulationModel.cc
- lib/model/unittest/CEventRateModelTest.cc
- lib/model/unittest/CMetricModelTest.cc
- lib/model/unittest/CMetricPopulationModelTest.cc
- lib/model/unittest/Mocks.cc
- lib/model/unittest/Mocks.h
std::auto_ptr has been removed from C++17, so we need
to stop using it before we can upgrade to C++17.
Also corrected the type name of a typedef of a
std::auto_ptr.
Backport of #717
> [7.x][ML] Replace std::auto_ptr with std::unique_ptr

- include/api/CDataFrameOutliersRunner.h
- lib/api/CDataFrameOutliersRunner.cc
> [7.x][ML] Rename standardize_columns to standardization_enabled (#716)

- docs/CHANGELOG.asciidoc
- include/maths/CModel.h
- include/model/CAnomalyDetectorModelConfig.h
- include/model/CIndividualModel.h
- include/model/CModelParams.h
- include/model/ModelTypes.h
- lib/maths/CModel.cc
- lib/maths/CPeriodicityHypothesisTests.cc
- lib/maths/CTimeSeriesModel.cc
- lib/maths/unittest/CForecastTest.cc
- lib/maths/unittest/CModelTest.cc
- lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
- lib/model/CAnomalyDetectorModelConfig.cc
- lib/model/CEventRateModel.cc
- lib/model/CEventRatePopulationModel.cc
- lib/model/CIndividualModel.cc
- lib/model/CMetricModel.cc
- lib/model/CMetricPopulationModel.cc
- lib/model/CModelDetailsView.cc
- lib/model/CModelParams.cc
- lib/model/CProbabilityAndInfluenceCalculator.cc
- lib/model/ModelTypes.cc
- lib/model/unittest/CEventRateAnomalyDetectorTest.cc
- lib/model/unittest/CEventRateModelTest.cc
- lib/model/unittest/CModelToolsTest.cc
- lib/model/unittest/CProbabilityAndInfluenceCalculatorTest.cc
This simplifies sparse count and sum modelling and migrates to always updating the time series model, but using a weight which decreases in proportion to the number of empty buckets. This means we simply smoothly transition to modelling non-empty buckets for sparse data.
I've also removed the correction to the probability which accounts for the fraction of non-empty buckets: we have the rare function anyway if this is the primary concern. Finally, I changed periodicity testing so that it approximates the old behaviour, i.e. it tends to ignoring empty buckets as their proportion increases.
Closes #696.
> [ML] Improvements to sparse count modelling

- docs/CHANGELOG.asciidoc
- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CTools.h
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.h
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
This implements binomial logistic regression for the boosted tree. In particular, this targets cross entropy and builds a forest to predict the class log-odds.
We should also have been including sum square leaf weight penalty in the calculation of the optimum tree leaf values, since the splits are chosen targeting the regularised objective. (Note that the regularisation applies to the log-odds for logistic regression, i.e. we'll shrink the log-odds towards zero and so the predicted probabilities towards 0.5.)
I haven't wired this in yet, since that work depends on #701.
> [ML] Logistic regression loss function for boosted tree training

- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/testfiles/error_bayesian_optimisation_state.json
- lib/maths/unittest/testfiles/error_boosted_tree_impl_state.json
- lib/maths/unittest/testfiles/error_no_version_state.json
This PR adds the version number of the current release (7.5) to the format of the training state using for resilience. In the case of the version mismatch, the deserialization of the training state will fail and training will start from scratch.
I also took an opportunity to refactor the test for persistence state error handling to have a more granular control of the reasons for failure.
> [ML] Add state format version for resilience

- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/testfiles/error_bayesian_optimisation_state.json
- lib/maths/unittest/testfiles/error_boosted_tree_impl_state.json
- lib/maths/unittest/testfiles/error_no_version_state.json
This PR adds the version number of the current release (7.5) to the format of the training state using for resilience. In the case of the version mismatch, the deserialization of the training state will fail and training will start from scratch.
I also took an opportunity to refactor the test for persistence state error handling to have a more granular control of the reasons for failure.
> [7.5][ML] Add state format version for resilience (#726)

- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameAnalysisSpecification.h
- include/api/CDataFrameAnalyzer.h
- include/api/CDataFrameBoostedTreeRunner.h
- include/api/CDataFrameClassificationRunner.h
- include/api/CDataFrameOutliersRunner.h
- include/api/CDataFrameRegressionRunner.h
- include/core/CDataFrame.h
- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeFactory.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/CDataFrameBoostedTreeRunner.cc
- lib/api/CDataFrameClassificationRunner.cc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/CDataFrameRegressionRunner.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.h
- lib/api/unittest/CDataFrameMockAnalysisRunner.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.h
- lib/core/CDataFrame.cc
- lib/core/unittest/CDataFrameTest.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
Wires in binomial logistic regression to the data_frame_analyzer command.
This migrates all the state needed to run an analysis and write its results to `core::CDataFrame`. Storing category strings and related data on `api::CDataFrameAnalyzer` was proving a maintenance burden as we kept having to extend the runner interfaces. This has the added advantage of better memory usage estimates.
(Whilst making these changes I spotted a bug in our handling of recovery from failure to restore state. I'll unit test this in a follow on PR.)
> [ML] Wire in binomial logistic regression

- docs/CHANGELOG.asciidoc
- lib/maths/CBoostedTreeImpl.cc
Numeric errors mean that it's possible the sum curvature for a candidate split is identically zero while the gradient is epsilon. This can cause the node gain to appear infinite (when there is no weight regularisation) which in turns causes problems initialising the region we search for optimal hyperparameter values.
Since none of our loss functions should have curvature identically equal to zero, we can safely force the gradient to be zero if detect that the curvature is zero.
\cc @przemekwitek.
> [ML] Fix potential problem for boosted tree training initialisation

- lib/core/unittest/CDataFrameTest.cc
The longer the name of the directory storing the data
frame, the greater the memory usage. This needs to be
taken into account in the expected results, otherwise
the test fails when run in certain CI systems but not
others.
> [ML] On disk data frame memory depends on directory name

- lib/core/unittest/CDataFrameTest.cc
The longer the name of the directory storing the data
frame, the greater the memory usage. This needs to be
taken into account in the expected results, otherwise
the test fails when run in certain CI systems but not
others.
Backport of #741
> [7.x][ML] On disk data frame memory depends on directory name

- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/maths/CBoostedTreeImpl.cc
We should be snapshotting the training state after the final train on the full data set. This incidentally means we can also re-enable the save/restore unit test case we'd disabled when all parameters are supplied by the user.
> [ML] Snapshot boosted tree training state after final train

- bin/data_frame_analyzer/Main.cc
- include/api/CDataFrameBoostedTreeRunner.h
- include/core/CProgramCounters.h
- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CDataFrameCategoryEncoder.h
- include/maths/CDataFrameUtils.h
- include/maths/CSampling.h
- lib/api/CDataFrameBoostedTreeRunner.cc
- lib/api/CDataFrameClassificationRunner.cc
- lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
- lib/api/unittest/CDataFrameAnalyzerTest.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CBoostedTreeTest.h
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.h
This adds two features:
1. Stratifying the sampling we do for each test/train fold for classification.
2. Implementing a reweighting scheme so that each class contributes approximately equal weight to the training loss.
We sample uniformly at random from the training rows for each class in proportion to their frequency in the full train set. We then optionally reweight the loss for each example by the inverse frequency of its category in the training set.
> [ML] Better handling of unbalanced class representation in the training data

- include/api/CInferenceModelDefinition.h
- lib/api/CBoostedTreeInferenceModelBuilder.cc
- lib/api/CInferenceModelDefinition.cc
- lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
- lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.h
This PR fixes an erroneous handling categorical fields that follow the target field. It also adds a unit test to catch similar cases in the future.
closes https://github.com/elastic/ml-cpp/issues/752
> [ML] Fix categorization encoding error

- lib/api/CBoostedTreeInferenceModelBuilder.cc
- lib/api/CInferenceModelDefinition.cc
With the introduction of the `removeUnusedFeatures`, the explicit filtering of the target column has become needless. Indeed, it can cause a memory corruption error. This PR removes this explicitly filtering.
> [ML] Remove explicit filtering of the target column

- include/maths/CDataFrameCategoryEncoder.h
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/unittest/CDataFrameCategoryEncoderTest.cc
- lib/maths/unittest/CDataFrameCategoryEncoderTest.h
We should always just pass back the target variable unmodified in the encoded feature vector.
> [ML] Identity encode the target variable

- include/core/CLogger.h
- lib/core/CLogger.cc
- lib/maths/unittest/CBoostedTreeTest.cc
Following the [discussion](https://github.com/elastic/ml-cpp/pull/726#discussion_r333475371) this PR adds a way to use custom stream in `CLogger`.
> [ML] Refactor CLogger to use custom stream

- lib/api/CInferenceModelDefinition.cc
This is primarily to suppress a warning from clang that it prevents copy elision.
> [ML] No need to explicitly move a temporary

- docs/CHANGELOG.asciidoc
- include/maths/CBoostedTreeImpl.h
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CBoostedTreeImpl.cc
This makes two changes:
1. It calculates the best split in the node statistics constructor, which was calculated as soon as the nodes were pushed to the priority queue (so effectively immediately). The upshot is we don't need to copy the feature bag.
2. Fixes an over counting bug in memory estimation. There are at most number of leaves leaf statistics objects *not* number of nodes, as we were using.
> [ML] Reduce peak memory usage and improve estimation for boosted tree training

- lib/core/unittest/CMemoryUsageTest.cc
- lib/core/unittest/CRapidXmlParserTest.cc
- lib/maths/unittest/CCalendarFeatureTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/CXMeansTest.cc
BOOST_TEST_REQUIRE:
- Clever assertion that looks at LHS/RHS of expression
- Prints LHS/RHS values in any failure message
- Can't cope with logical operators
- Requires LHS/RHS of comparison be printable
BOOST_REQUIRE:
- Simple boolean assertion
- Simple pass/fail diagnostics
- Works with arbitrary expressions that evaluate to a boolean
- No printability constraints
This PR changes the usage of the two macros to reflect their
strengths and weaknesses.
> [ML] Adjust use of BOOST_REQUIRE and BOOST_TEST_REQUIRE

- lib/core/unittest/CMemoryUsageTest.cc
- lib/core/unittest/CRapidXmlParserTest.cc
- lib/maths/unittest/CCalendarFeatureTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/CXMeansTest.cc
BOOST_TEST_REQUIRE:
- Clever assertion that looks at LHS/RHS of expression
- Prints LHS/RHS values in any failure message
- Can't cope with logical operators
- Requires LHS/RHS of comparison be printable
BOOST_REQUIRE:
- Simple boolean assertion
- Simple pass/fail diagnostics
- Works with arbitrary expressions that evaluate to a boolean
- No printability constraints
This PR changes the usage of the two macros to reflect their
strengths and weaknesses.
Backport of #788
> [7.x][ML] Adjust use of BOOST_REQUIRE and BOOST_TEST_REQUIRE

- lib/core/unittest/CNamedPipeFactoryTest.cc
- lib/core/unittest/COsFileFuncsTest.cc
> [7.x][ML] Fix some Windows-specific cases of no assertions in tests

- include/test/CThreadDataReader.h
- include/test/CThreadDataWriter.h
- lib/api/unittest/CIoManagerTest.cc
- lib/core/unittest/CNamedPipeFactoryTest.cc
- lib/seccomp/unittest/CSystemCallFilterTest.cc
- lib/test/CThreadDataReader.cc
- lib/test/CThreadDataWriter.cc
- lib/test/Makefile
Three test suites were all using extremely similar
local classes for reading/writing named pipes in
separate threads.  This change factors out the
common code into classes in the test library.
> [ML] Factor out common test code

- include/test/CThreadDataReader.h
- include/test/CThreadDataWriter.h
- lib/api/unittest/CIoManagerTest.cc
- lib/core/unittest/CNamedPipeFactoryTest.cc
- lib/seccomp/unittest/CSystemCallFilterTest.cc
- lib/test/CThreadDataReader.cc
- lib/test/CThreadDataWriter.cc
- lib/test/Makefile
Three test suites were all using extremely similar
local classes for reading/writing named pipes in
separate threads.  This change factors out the
common code into classes in the test library.
Backport of #796
> [7.x][ML] Factor out common test code

- dev-tools/jenkins_ci.sh
- dev-tools/run_es_tests.sh
This change is to run two suites of ES integration tests
using the C++ artifact built by an ml-cpp PR build:
- The basic (without security) ML YAML tests
- The ML native multi-node tests
The tests are only run on Linux, and only in PR builds.
Any failures will fail the PR build.
Backport of #801
> [7.x][ML] Run ES integration tests on C++ PRs

- dev-tools/jenkins_ci.sh
- dev-tools/run_es_tests.sh
This change is to run two suites of ES integration tests
using the C++ artifact built by an ml-cpp PR build:
- The basic (without security) ML YAML tests
- The ML native multi-node tests
The tests are only run on Linux, and only in PR builds.
Any failures will fail the PR build.
Backport of #801
> [7.5][ML] Run ES integration tests on C++ PRs

- dev-tools/jenkins_ci.sh
- dev-tools/run_es_tests.sh
This change is to run two suites of ES integration tests
using the C++ artifact built by an ml-cpp PR build:
- The basic (without security) ML YAML tests
- The ML native multi-node tests
The tests are only run on Linux, and only in PR builds.
Any failures will fail the PR build.
Backport of #801
> [6.8][ML] Run ES integration tests on C++ PRs

- lib/model/CEventRateModel.cc
- lib/model/CIndividualModel.cc
- lib/model/CMetricModel.cc
This is a bug, but marked as a non-issue since 7.5 is not yet released. (Note that the bounds are expected to change because they used to be scaled by the non-empty bucket frequency.)
Without this fix
With this fix
> [ML] Handle upgrade state to 7.5 to account for sparse count modelling changes

- docs/CHANGELOG.asciidoc
- lib/api/CJsonOutputWriter.cc
- lib/api/unittest/CJsonOutputWriterTest.cc
Adds new geo_point formatted fields for Java side consumption. These are only written if we have actual|typical values that have length of 2, and are using a `lat_long` function.
This is my first PR against this repo, let me know if I missed something. 
Blocked by https://github.com/elastic/elasticsearch/pull/47050
> [ML] add geo point formatting string for actual|typical

- docs/CHANGELOG.asciidoc
- lib/api/CJsonOutputWriter.cc
- lib/api/unittest/CJsonOutputWriterTest.cc
Adds new geo_point formatted fields for Java side consumption. These are only written if we have actual|typical values that have length of 2, and are using a lat_long function.
This is my first PR against this repo, let me know if I missed something.
related elastic/elasticsearch#47050
Backport of #809
> [ML] add geo point formatting string for actual|typical (#809)

- docs/CHANGELOG.asciidoc
- include/maths/CSeasonalTime.h
- lib/maths/CSeasonalTime.cc
- lib/maths/unittest/CSeasonalTimeTest.cc
- lib/maths/unittest/CSeasonalTimeTest.h
- lib/maths/unittest/Main.cc
- lib/maths/unittest/Makefile
Backport #821. Note that this is not a trivial back port because of the test framework change so it is worthwhile reviewing.
> [6.8][ML] Fix restore from checkpoint damaging seasonality modelling for anomaly detection

- docs/CHANGELOG.asciidoc
- include/maths/CSeasonalTime.h
- lib/maths/CSeasonalTime.cc
- lib/maths/unittest/CSeasonalTimeTest.cc
- lib/maths/unittest/Makefile
We weren't persisting and restoring all the state we should have been. This should only affect behaviour after a restore.
Fixes #820.
> [ML] Fix restore from checkpoint damaging seasonality modelling for anomaly detection

- dev-tools/docker/docker_entrypoint.sh
Previously the ML Linux CI workers had 16 CPUs and 14.4GB RAM.
The Jenkins setup has just been changed so that in future they'll
have 16 CPUs and 24GB RAM.
This increase of memory per CPU from 0.9GB to 1.5GB will hopefully
mean that we can utilise all the CPUs on our Linux CI workers
without one of the gcc processes running out of memory.
> [ML] Remove CI parallelism hack

- lib/api/unittest/CPersistenceManagerTest.cc
In the persistence test we trigger background and
foreground persistence manually.  We don't want
the background persistence to trigger based on a
wall clock timer.  This change makes the arbitrary
persistence interval configured by the tests high
enough that it won't trigger if the test runs for
a long time (e.g. on a slow machine when built
without optimisation).
> [ML] Adjust background interval in persistence test

- lib/api/unittest/CPersistenceManagerTest.cc
In the persistence test we trigger background and
foreground persistence manually.  We don't want
the background persistence to trigger based on a
wall clock timer.  This change makes the arbitrary
persistence interval configured by the tests high
enough that it won't trigger if the test runs for
a long time (e.g. on a slow machine when built
without optimisation).
Backport of #830
> [7.x][ML] Adjust background interval in persistence test

- dev-tools/docker/docker_entrypoint.sh
Previously the ML Linux CI workers had 16 CPUs and 14.4GB RAM.
The Jenkins setup has just been changed so that in future they'll
have 16 CPUs and 24GB RAM.
This increase of memory per CPU from 0.9GB to 1.5GB will hopefully
mean that we can utilise all the CPUs on our Linux CI workers
without one of the gcc processes running out of memory.
Backport of #828
> [7.5][ML] Remove CI parallelism hack

- dev-tools/docker/docker_entrypoint.sh
Previously the ML Linux CI workers had 16 CPUs and 14.4GB RAM.
The Jenkins setup has just been changed so that in future they'll
have 16 CPUs and 24GB RAM.
This increase of memory per CPU from 0.9GB to 1.5GB will hopefully
mean that we can utilise all the CPUs on our Linux CI workers
without one of the gcc processes running out of memory.
Backport of #828
> [7.x][ML] Remove CI parallelism hack

- bin/data_frame_analyzer/Main.cc
Remove duplicated code in `bin/data_frame_analyzer/Main.cc`
> Remove duplicated code.

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
- lib/api/unittest/Makefile
Even though the user can request `top_classes` (containing class names and probabilities) to be emitted, it seems reasonable to also include the top class' prediction probability as a field alongside the prediction field.
> Emit prediction_probability field alongside prediction field in ml results.

- include/api/COutputHandler.h
- include/core/CCompressedDictionary.h
- include/core/CHashing.h
- include/core/CStringCache.h
- include/core/CWordDictionary.h
- include/maths/CBasicStatistics.h
- include/maths/CEqualWithTolerance.h
- include/maths/CMathsFuncs.h
- lib/core/CMemoryUsage.cc
- lib/maths/CGammaRateConjugate.cc
- lib/maths/CKMostCorrelated.cc
- lib/maths/CPrior.cc
- lib/maths/unittest/CIntegrationTest.cc
- lib/maths/unittest/TestUtils.cc
- lib/model/CTokenListCategory.cc
C++11 deprecated the unary_function and binary_function base
classes, together with old-style binders like bind1st and not1.
These base classes and functions are completed removed in C++17,
so they need removing from the codebase before we can upgrade.
However, since they are unnecessary in C++11 and above it is
best to remove them in advance of any (master-only) C++17 work
so that the master and 7.x branches can stay more closely
aligned.
> [ML] Remove unary_function/binary_function and old-style binders

- include/api/COutputHandler.h
- include/core/CCompressedDictionary.h
- include/core/CHashing.h
- include/core/CStringCache.h
- include/core/CWordDictionary.h
- include/maths/CBasicStatistics.h
- include/maths/CEqualWithTolerance.h
- include/maths/CMathsFuncs.h
- lib/core/CMemoryUsage.cc
- lib/maths/CGammaRateConjugate.cc
- lib/maths/CKMostCorrelated.cc
- lib/maths/CPrior.cc
- lib/maths/unittest/CIntegrationTest.cc
- lib/maths/unittest/TestUtils.cc
- lib/model/CTokenListCategory.cc
C++11 deprecated the unary_function and binary_function base
classes, together with old-style binders like bind1st and not1.
These base classes and functions are completed removed in C++17,
so they need removing from the codebase before we can upgrade.
However, since they are unnecessary in C++11 and above it is
best to remove them in advance of any (master-only) C++17 work
so that the master and 7.x branches can stay more closely
aligned.
Backport of #840
> [7.x][ML] Remove unary_function/binary_function and old-style binders

- docs/CHANGELOG.asciidoc
- include/maths/CBasicStatistics.h
- include/maths/CTimeSeriesDecomposition.h
- include/maths/ImportExport.h
- include/maths/ProbabilityAggregators.h
- lib/maths/CBjkstUniqueValues.cc
The empty base optimization is not used by default with
multiple inheritance on Windows, but can be enabled using
__declspec(empty_bases).  The investigation in #842 shows
which of our classes would benefit, so this PR adds the
required option to the 5 affected classes.
> [ML] Use empty base optimization with multiple inheritance

- include/api/CCsvOutputWriter.h
- include/api/CJsonOutputWriter.h
Tidied up output writer classes as per `clang-tidy` suggestions
> [ML] Attend to some clang-tidy suggestions

- include/api/CCsvOutputWriter.h
- include/api/CJsonOutputWriter.h
Tidied up output writer classes as per clang-tidy suggestions
Backports #847
> [ML][7.6]  Tidied up output writer classes (#847)

- include/maths/CKdTree.h
- include/maths/CLinearAlgebraEigen.h
This change was driven by problems compiling the previous
code in Visual Studio 2019 in C++17 mode.  However, the
changes should work with other compilers, so it is best
to separate them out of the Visual Studio 2019 upgrade
PR.
There are basically two changes in this PR, but both
relate to the same area of the code:
1. Remove redundant copy constructor definitions from the
Eigen linear algebra wrappers.  Most classes had two
copy constructors, one taking a const argument and the
other non-const.  But since the non-const copy
constructor just forwarded to the const one there was
no need to have two.  This then allows the single const
copy constructor to be specified using = default.
(Visual Studio 2019 warns if both const and non-const
copy constructors are defined, so this silences those …
> [ML] Adjust Eigen linear algebra wrapper constructors

- include/maths/CKdTree.h
- include/maths/CLinearAlgebraEigen.h
This change was driven by problems compiling the previous
code in Visual Studio 2019 in C++17 mode.  However, the
changes should work with other compilers, so it is best
to separate them out of the Visual Studio 2019 upgrade
PR.
There are basically two changes in this PR, but both
relate to the same area of the code:
1. Remove redundant copy constructor definitions from the
Eigen linear algebra wrappers.  Most classes had two
copy constructors, one taking a const argument and the
other non-const.  But since the non-const copy
constructor just forwarded to the const one there was
no need to have two.  This then allows the single const
copy constructor to be specified using = default.
(Visual Studio 2019 warns if both const and non-const
copy constructors are defined, so this silences those …
> [7.x][ML] Adjust Eigen linear algebra wrapper constructors

- docs/CHANGELOG.asciidoc
- include/api/CCsvOutputWriter.h
- include/api/CJsonOutputWriter.h
- lib/maths/CSignal.cc
Also fixes a couple more warnings picked up by clang_tidy
closes #845
> [ML] Fix memory errors picked up by Valgrind

- include/api/CDataFrameTrainBoostedTreeRunner.h
- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeHyperparameters.h
- include/maths/CBoostedTreeImpl.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeHyperparameters.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/Makefile
This PR adds check that user-specified hyperparameters are used as final hyperparameters by the boosted trees. Implementation of the unit test required factoring out classes `CBoostedTreeHyperparameters` and `CBoostedTreeRegularization` from `CBoostedTreeImpl`.
Also I added the setting of some user-specified hyperparameters in `CBoostedTreeFactory.cc` that were missing before.
Fixes #851 
Fixes #849
> [ML] Add unit test checks for new hyperparameters in supervised learning

- docs/CHANGELOG.asciidoc
- include/api/CCsvOutputWriter.h
- include/api/CJsonOutputWriter.h
- lib/maths/CSignal.cc
* Fixes Valgrind errors in `CSignal`
* Also fixes a couple more warnings picked up by clang_tidy
Backports #852
> [ML][7.6] Fix memory errors picked up by Valgrind (#852)

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
- lib/api/unittest/Makefile
- Emit prediction_probability field alongside prediction field in ml results.  (#818)
> [7.x] Emit prediction_probability field alongside prediction field in ml results. (#818)

- STYLEGUIDE.md
> [ML] Updates to STYLEGUIDE.md about explicit "if" statements.

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
- lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
- lib/api/unittest/Makefile
This PR prevents field name clashes in ml results docs on JSON level.
Relates https://github.com/elastic/elasticsearch/issues/48808
> Blacklist a number of prediction field names.

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
- lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
- lib/api/unittest/Makefile
- Blacklist a number of prediction field names.  (#861)
> [7.x] Blacklist a number of prediction field names. (#861)

- docs/CHANGELOG.asciidoc
- include/core/CDataFrame.h
- include/core/CFloatStorage.h
- include/core/CImmutableRadixSet.h
- include/maths/CBoostedTreeHyperparameters.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CBoundingBox.h
- include/maths/CKdTree.h
- include/maths/CQuantileSketch.h
- lib/core/CDataFrame.cc
- lib/core/unittest/CImmutableRadixSetTest.cc
- lib/core/unittest/Makefile
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CQuantileSketch.cc
- lib/maths/CSignal.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
The principal change is to bucket the candidate split points so we only check a subset of the splits when searching for the derivatives to update when computing split statistics. There are also some smaller optimisations which profiling showed up as worthwhile. The impact is largest for the case we have many metric valued features. These are pure runtime optimisations, i.e. the results are unaffected.
> [ML] Assorted runtime optimisations for classification and regression

- include/maths/CBoostedTreeHyperparameters.h
- include/maths/CBoostedTreeImpl.h
CLeafNodeStatistics specified a default move constructor
and move assignment operator.  However, these cannot be
generated because the class has a const reference member.
They were not called anywhere, so this change removes the
= default directives to avoid compiler warnings.
> [ML] Remove impossible move constructor/assignment

- include/core/CCsvLineParser.h
- include/core/CMemory.h
- include/core/CStringSimilarityTester.h
- include/core/CompressUtils.h
- include/model/CBaseTokenListDataCategorizer.h
- include/model/CDataCategorizer.h
- include/model/CResourceMonitor.h
- include/model/CTokenListCategory.h
- include/model/CTokenListDataCategorizer.h
- include/model/CTokenListReverseSearchCreator.h
- include/model/CTokenListReverseSearchCreatorIntf.h
- lib/core/CCsvLineParser.cc
- lib/core/CStringSimilarityTester.cc
- lib/core/CompressUtils.cc
- lib/model/CBaseTokenListDataCategorizer.cc
- lib/model/CDataCategorizer.cc
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListReverseSearchCreator.cc
- lib/model/CTokenListReverseSearchCreatorIntf.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
This is a step towards adding memory instrumentation to
categorization.  On its own this PR has no externally
visible effect, but by splitting out these boilerplate
changes the PR that eventually adds memory instrumentation
to categorization will be smaller.
> [ML] Adding memory usage methods for categorization classes

- include/maths/CBoostedTreeImpl.h
CLeafNodeStatistics specified a default move constructor
and move assignment operator.  However, these cannot be
generated because the class has a const reference member.
They were not called anywhere, so this change removes the
= default directives to avoid compiler warnings.
Backport of #866
> [7.x][ML] Remove impossible move constructor/assignment

- include/core/CCsvLineParser.h
- include/core/CMemory.h
- include/core/CStringSimilarityTester.h
- include/core/CompressUtils.h
- include/model/CBaseTokenListDataCategorizer.h
- include/model/CDataCategorizer.h
- include/model/CResourceMonitor.h
- include/model/CTokenListCategory.h
- include/model/CTokenListDataCategorizer.h
- include/model/CTokenListReverseSearchCreator.h
- include/model/CTokenListReverseSearchCreatorIntf.h
- lib/core/CCsvLineParser.cc
- lib/core/CStringSimilarityTester.cc
- lib/core/CompressUtils.cc
- lib/model/CBaseTokenListDataCategorizer.cc
- lib/model/CDataCategorizer.cc
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListReverseSearchCreator.cc
- lib/model/CTokenListReverseSearchCreatorIntf.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
This is a step towards adding memory instrumentation to
categorization.  On its own this PR has no externally
visible effect, but by splitting out these boilerplate
changes the PR that eventually adds memory instrumentation
to categorization will be smaller.
Backport of #859
> [7.x][ML] Adding memory usage methods for categorization classes

- lib/model/CEventRateBucketGatherer.cc
- lib/model/CMetricBucketGatherer.cc
In C++17 there is a std::apply function that gets chosen in
preference to the apply function in the anonymous namespace
in the metric and event rate bucket gatherers.
This change renames our function so the compiler does not
have to resolve an ambiguity when it's called.
> [ML] Rename anonymous namespace apply function to avoid clash

- lib/model/CEventRateBucketGatherer.cc
- lib/model/CMetricBucketGatherer.cc
In C++17 there is a std::apply function that gets chosen in
preference to the apply function in the anonymous namespace
in the metric and event rate bucket gatherers.
This change renames our function so the compiler does not
have to resolve an ambiguity when it's called.
Backport of #871
> [7.x][ML] Rename anonymous namespace apply function to avoid clash

- 3rd_party/3rd_party.sh
- build-setup/macos.md
- build-setup/macos_cross_compiled.md
- dev-tools/docker/build_macosx_build_image.sh
- dev-tools/docker/macosx_builder/Dockerfile
- dev-tools/docker/macosx_image/Dockerfile
- dev-tools/strip_binaries.sh
- docs/CHANGELOG.asciidoc
- mk/linux_crosscompile_macosx.mk
- mk/macosx.mk
We will build the macOS version 8.x of the ML C++ using
Apple clang 10.1 on High Sierra or cross-compiling using
clang 6.0 on Ubuntu 18.04.  This will eventually facilitate
use of C++17 (after separate PRs to upgrade the Windows and
Linux compilers have also been merged).
> [ML] Upgrade to clang 6.0/Apple clang 10.1 for macOS compilation

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
Currently, classification analysis allows dependent variable of integer or boolean type but in the results field, the prediction field is always emitted as JSON string (so `true` becomes `"true"`, `1` becomes `"1"` etc.).
A solution to that problem is to pass desired `prediction_field_type` from Java to C++ and make C++ emit `bool`, `int` or `string` JSON field depending on the `prediction_field_type` passed.
This PR implements the C++ part of this solution.
Relates https://github.com/elastic/elasticsearch/issues/49796
> Emit predicted category using an appropriate JSON type.

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
- Emit predicted category using an appropriate JSON type.  (#877)
> [7.x] Emit predicted category using an appropriate JSON type. (#877)

- docs/CHANGELOG.asciidoc
- include/core/CImmutableRadixSet.h
- include/core/CPackedBitVector.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeHyperparameters.h
- include/maths/CBoostedTreeImpl.h
- include/test/CDataFrameAnalysisSpecificationFactory.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeHyperparameters.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
We can relatively cheaply (around a 2% overhead) compute predictions for the test rows at the same time as we compute them for the training rows. This means we can cheaply track the validation error as we add additional trees to the forest during training.
The validation error curve is fairly predictable: it decreases quickly (typically exponentially) at the start, hits a minimum and then often increases slightly as the model starts to overfit the training data. This change introduces a very simple exit condition designed to ensure we pay a fixed relative runtime cost for ensuring we don't exit too soon. Specifically, add at least f * "maximum number of trees" trees to the lowest validation error forest and resize the forest to minimise validation error at the end of training. We set f to …
> [ML] Stop early (based on non-decreasing validation error) when adding trees to the forest

- dev-tools/check-style.sh
- Color style-related error messages in console output  (#879)
> [7.x] Color style-related error messages in console output (#879)

- lib/core/Concurrency.cc
This is no longer required after #867
> [ML] Remove old clang workaround

- lib/maths/unittest/CBoostedTreeTest.cc
The older version of clang used on the 7.x El Capitan reference
build server creates an actual value of 0.51796218392671234, so
increase the threshold to 0.52
> [ML] Tweak CBoostedTreeTest.testLogisticRegression test threshold further

- lib/maths/unittest/CBoostedTreeTest.cc
The older version of clang used on the 7.x El Capitan reference
build server creates an actual value of 0.51796218392671234, so
increase the threshold to 0.52
Backport of #887
> [7.x][ML] Tweak CBoostedTreeTest.testLogisticRegression test threshold further

- include/maths/CDataFrameRegressionModel.h
- include/maths/COutliers.h
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/COutliers.cc
We end up needing to subtract memory usage when it's freed so the record memory usage callback needs to allow for the supplied memory being negative. Also, we should never overflow `int64_t` so can just go ahead and cast values where they're supplied to this function.
This PR fixes the function typedef used for outlier detection and regression and tidies up its usage. I'm marking as non-issue since it is non-functional, but this makes the intention much clearer.
Fixes #836.
> [ML] Switch the record memory callback usage to use a signed type for memory

- include/api/CDataFrameAnalysisSpecification.h
- include/api/ElasticsearchStateIndex.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/ElasticsearchStateIndex.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Currently the state document id for regression and classification
analysis both use the suffix `_regression_state`. However, it would
make things clearer to include the analysis name in the doc id as
it gives us the ability to check we are restoring the right state.
This commit makes this change.
> [ML] Use analysis name as suffix for the state doc id

- include/api/CDataFrameAnalysisSpecification.h
- include/api/ElasticsearchStateIndex.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/ElasticsearchStateIndex.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Currently the state document id for regression and classification
analysis both use the suffix `_regression_state`. However, it would
make things clearer to include the analysis name in the doc id as
it gives us the ability to check we are restoring the right state.
This commit makes this change.
Backport of #896
> [7.x][ML] Use analysis name as suffix for the state doc id (#896)

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeRunner.h
- include/maths/CBasicStatistics.h
- include/maths/CBayesianOptimisation.h
- include/maths/CBoostedTreeFactory.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBayesianOptimisationTest.cc
- lib/maths/unittest/CBoostedTreeTest.cc
This migrates to using BO for choosing points at which to evaluate the regularisers in the line searches we perform to find their initial values. Importantly, it also thresholds the minimum expected improvement to bother to continue with the line search to be at least 1% of the current test loss. This saves us *up to* 3 iterations in the loop (since we lower bound the minimum number of iterations we'll use) or around 40% of the cost of the line searches.
> [ML] Early stopping in the line searches to compute initial regulariser values

- build.gradle
- upload.gradle
Gradle 6 gets confused if we try to use its standard dependency
management to convert artifacts with a classifier to an artifact
for the same project without a classifier.
To sidestep this problem this PR changes upload.gradle to use
low level functionality to get the platform-specific artifacts.
> [ML] Adjust platform specific artifact creation and upload

- build.gradle
- upload.gradle
Gradle 6 gets confused if we try to use its standard dependency
management to convert artifacts with a classifier to an artifact
for the same project without a classifier.
To sidestep this problem this PR changes upload.gradle to use
low level functionality to get the platform-specific artifacts.
Backport of #910
> [7.x][ML] Adjust platform specific artifact creation and upload

- docs/CHANGELOG.asciidoc
I add missing doc entry about the new SHAP computation feature.
> [ML] Add CHANGELOG entry for SHAP feature

- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/maths/CDataFrameRegressionModel.cc
This PR renames the prefix for the SHAP value fields form `ml.shap.<field_name>` to `ml.feature_importance.<field_name>`.
> [ML] Rename result shap prefix

- docs/CHANGELOG.asciidoc
- include/api/CPersistenceManager.h
- include/model/CBaseTokenListDataCategorizer.h
- include/model/CDataCategorizer.h
- lib/api/CFieldDataCategorizer.cc
- lib/api/unittest/CPersistenceManagerTest.cc
- lib/model/CBaseTokenListDataCategorizer.cc
All data structures to be persisted need to be copied before a
background persist is started, otherwise inconsistent state could
be persisted as the foreground thread updates the data structures
(or worse, the program could crash).
Fixes #919
> [ML] Copy categorization data structures before background persist

- docs/CHANGELOG.asciidoc
- include/api/CPersistenceManager.h
- include/model/CBaseTokenListDataCategorizer.h
- include/model/CDataCategorizer.h
- lib/api/CFieldDataCategorizer.cc
- lib/api/unittest/CPersistenceManagerTest.cc
- lib/model/CBaseTokenListDataCategorizer.cc
All data structures to be persisted need to be copied before a
background persist is started, otherwise inconsistent state could
be persisted as the foreground thread updates the data structures
(or worse, the program could crash).
Backport of #921
> [7.x][ML] Copy categorization data structures before background persist

- docs/CHANGELOG.asciidoc
- include/api/CBaseTokenListDataTyper.h
- include/api/CDataTyper.h
- lib/api/CBaseTokenListDataTyper.cc
- lib/api/CFieldDataTyper.cc
- lib/api/unittest/CPersistenceManagerTest.cc
- lib/api/unittest/CPersistenceManagerTest.h
All data structures to be persisted need to be copied before a
background persist is started, otherwise inconsistent state could
be persisted as the foreground thread updates the data structures
(or worse, the program could crash).
Backport of #921
> [7.5][ML] Copy categorization data structures before background persist

- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/maths/CBoostedTreeImpl.cc
This PR prevents the return of SHAP values for features if the SHAP value is 0. If the number of non-zero SHAP values was less than `top_shap_values` parameter, this could cause the return of the dependent variable with SHAP 0.0. 
I didn't catch the bug previously, because unit tests were assuming that the dependent variable is the last input field. I adjusted the unit test moving the dependent variable forward and adding assertions.
Fixes #918
> [ML] Fix return of SHAP values for dependent variable issue

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeRunner.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CTreeShapFeatureImportance.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CTreeShapFeatureImportance.cc
This makes two changes:
1. It sets the number of folds to use based on the amount of data available: we ensure each training fold has sufficient data per feature.
2. During hyperparameter optimisation, we use a linear model to predict the cross-validation loss on the remaining folds and stop early if the predicted test loss has a low chance of being less than the best values found so far.
> [ML] Stop cross-validation early if the parameters have high predicted test loss

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeRunner.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CTreeShapFeatureImportance.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CTreeShapFeatureImportance.cc
> [7.6][ML] Stop cross-validation early if the parameters have high predicted test loss

- include/api/CDataFrameTrainBoostedTreeRunner.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/test/CDataFrameAnalysisSpecificationFactory.cc
Renames boosted tree param `top_feature_importance_values` to
`num_top_feature_importance_values`.
> [ML] Rename to num_top_feature_importance_values

- include/api/CDataFrameTrainBoostedTreeRunner.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/test/CDataFrameAnalysisSpecificationFactory.cc
Renames boosted tree param `top_feature_importance_values` to
`num_top_feature_importance_values`.
Backport of #932
> [7.x][ML] Rename to num_top_feature_importance_values (#932)

- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
- include/test/CDataFrameAnalysisSpecificationFactory.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
- lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc
- lib/test/CDataFrameAnalysisSpecificationFactory.cc
We weren't writing out the probabilities for the top classes correctly. This error was introduced by #926. I've marked as a non-issue since that code isn't yet released.
> [ML] Correct the top class probabilities

- lib/maths/unittest/CNaiveBayesTest.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
This was introduced by #859.  A raw pointer with a confusing
typedef name was assumed to be a smart pointer when it wasn't.
Also checked for the same problem in other places, and didn't
find any, but corrected a couple of local typedef names.  (The
wider problem that CMemoryUsage::TMemoryUsagePtr aliases a
raw pointer will have to wait for a bigger PR.)
Relates #922
> [ML] Fix memory leak in tokenization tests

- lib/maths/unittest/CNaiveBayesTest.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
This was introduced by #859.  A raw pointer with a confusing
typedef name was assumed to be a smart pointer when it wasn't.
Also checked for the same problem in other places, and didn't
find any, but corrected a couple of local typedef names.  (The
wider problem that CMemoryUsage::TMemoryUsagePtr aliases a
raw pointer will have to wait for a bigger PR.)
Backport of #940
> [7.x][ML] Fix memory leak in tokenization tests

- lib/maths/unittest/CNaiveBayesTest.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
This was introduced by #859.  A raw pointer with a confusing
typedef name was assumed to be a smart pointer when it wasn't.
Also checked for the same problem in other places, and didn't
find any, but corrected a couple of local typedef names.  (The
wider problem that CMemoryUsage::TMemoryUsagePtr aliases a
raw pointer will have to wait for a bigger PR.)
Backport of #940
> [7.6][ML] Fix memory leak in tokenization tests

- docs/CHANGELOG.asciidoc
- include/model/CTokenListReverseSearchCreator.h
- include/model/CTokenListReverseSearchCreatorIntf.h
- lib/api/unittest/CFieldDataCategorizerTest.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/CTokenListReverseSearchCreator.cc
- lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
When categories include messages with different token orders,
we were not including the tokens whose order varied between
the messages in the terms of the reverse search.  This change
adds these out-of-order tokens that are part of the category
definition back into the reverse search terms.
Fixes the easy part of #949
> [ML] Include out-of-order as well as in-order terms in reverse search

- lib/maths/CBoostedTree.cc
- lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
Avoid the need to reserve the vector before calling the `CBoostedTreeNode::split` function. This rejigs this method to avoid reading member variables after calling `resize` on the supplied vector. Shown up by #922.
> [ML] Fix invalid read in tests

- docs/CHANGELOG.asciidoc
- include/model/CTokenListReverseSearchCreator.h
- include/model/CTokenListReverseSearchCreatorIntf.h
- lib/api/unittest/CFieldDataCategorizerTest.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/CTokenListReverseSearchCreator.cc
- lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
When categories include messages with different token orders,
we were not including the tokens whose order varied between
the messages in the terms of the reverse search.  This change
adds these out-of-order tokens that are part of the category
definition back into the reverse search terms.
Backport of #950
> [7.x][ML] Include out-of-order as well as in-order terms in reverse search

- docs/CHANGELOG.asciidoc
- include/api/CTokenListReverseSearchCreator.h
- include/api/CTokenListReverseSearchCreatorIntf.h
- lib/api/CBaseTokenListDataTyper.cc
- lib/api/CTokenListReverseSearchCreator.cc
- lib/api/unittest/CFieldDataTyperTest.cc
- lib/api/unittest/CFieldDataTyperTest.h
- lib/api/unittest/CTokenListReverseSearchCreatorTest.cc
- lib/api/unittest/CTokenListReverseSearchCreatorTest.h
When categories include messages with different token orders,
we were not including the tokens whose order varied between
the messages in the terms of the reverse search.  This change
adds these out-of-order tokens that are part of the category
definition back into the reverse search terms.
Backport of #950
> [6.8][ML] Include out-of-order as well as in-order terms in reverse search

- docs/CHANGELOG.asciidoc
- include/model/CTokenListReverseSearchCreator.h
- include/model/CTokenListReverseSearchCreatorIntf.h
- lib/api/unittest/CFieldDataCategorizerTest.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/CTokenListReverseSearchCreator.cc
- lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
When categories include messages with different token orders,
we were not including the tokens whose order varied between
the messages in the terms of the reverse search.  This change
adds these out-of-order tokens that are part of the category
definition back into the reverse search terms.
Backport of #950
> [7.6][ML] Include out-of-order as well as in-order terms in reverse search

- lib/api/CDataFrameAnalysisSpecification.cc
#896 introduced undesirable INFO level logging by accident. This downgrades it to trace. The code hasn't been released yet so marking as non-issue.
> [ML] Downgrade noisy logging to trace logging

- docs/CHANGELOG.asciidoc
- include/core/CLoopProgress.h
- include/maths/CBoostedTreeFactory.h
- lib/core/CLoopProgress.cc
- lib/core/unittest/CLoopProgressTest.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/unittest/CBoostedTreeTest.cc
This switches to performing an initial line search over the learn rate and reducing the range we search in the main optimisation loop. This does cost us some run time, but we generally get small wins in both the QoR and the stability of QoR as borne out by the sample results below.
Because we can't estimate the runtime upfront I've extended the progress monitor to allow us to reset the expected total number of steps. This will advance progress if it needs to; we have no mechanism for reducing progress if the expected number steps increase. In this case, we simply get stuck at the current progress. I use a margin in the initial estimates to reduce the chance of this so we get smoother progress monitoring.
Sample regression results:
| data set | master mean R^2 | master sd R^2 | patch mean …
> [ML] Line search for best learn rate

- include/model/CDataCategorizer.h
- include/model/CTokenListCategory.h
- include/model/CTokenListDataCategorizer.h
- include/model/CTokenListDataCategorizerBase.h
- include/model/CTokenListReverseSearchCreator.h
- lib/api/CFieldDataCategorizer.cc
- lib/api/unittest/CRestorePreviousStateTest.cc
- lib/model/CDataCategorizer.cc
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/CTokenListReverseSearchCreator.cc
- lib/model/unittest/CTokenListCategoryTest.cc
- lib/model/unittest/CTokenListDataCategorizerBaseTest.cc
- lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
- lib/model/unittest/Makefile
While working on part 2 of the fix for #949 I noticed that
the categorization code could do with a little modernization,
such as using range based for loops in preference to
iterators where possible.
Additionally there is some dead code left over from the
days of multiple products that used categorization, for
example in our Elasticsearch integration there is never a
need to create a reverse search for a NULL field, so the
method to do that can be removed.
This PR does that modernization and dead code removal
without changing any externally visible functionality.
Then the eventual fix for part 2 of #949 will not be
polluted with lots of irrelevant refactoring.
This PR also adds a couple of low level tests for the
CTokenListCategory class.  One of these highlights the
outstanding problem …
> [ML] Modernize the categorization code

- lib/maths/CBoostedTreeFactory.cc
- lib/maths/unittest/CBoostedTreeTest.cc
We were sometimes using a wrong lower bound for this interval. This regression was introduced in #903 which hasn't been released, so marking as a non-issue.
> [ML] Bug in bounds calculation for the main optimisation hyperparameter search

- include/model/CDataCategorizer.h
- include/model/CTokenListCategory.h
- include/model/CTokenListDataCategorizer.h
- include/model/CTokenListDataCategorizerBase.h
- include/model/CTokenListReverseSearchCreator.h
- lib/api/CFieldDataCategorizer.cc
- lib/api/unittest/CRestorePreviousStateTest.cc
- lib/model/CDataCategorizer.cc
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/CTokenListReverseSearchCreator.cc
- lib/model/unittest/CTokenListCategoryTest.cc
- lib/model/unittest/CTokenListDataCategorizerBaseTest.cc
- lib/model/unittest/CTokenListReverseSearchCreatorTest.cc
- lib/model/unittest/Makefile
While working on part 2 of the fix for #949 I noticed that
the categorization code could do with a little modernization,
such as using range based for loops in preference to
iterators where possible.
Additionally there is some dead code left over from the
days of multiple products that used categorization, for
example in our Elasticsearch integration there is never a
need to create a reverse search for a NULL field, so the
method to do that can be removed.
This PR does that modernization and dead code removal
without changing any externally visible functionality.
Then the eventual fix for part 2 of #949 will not be
polluted with lots of irrelevant refactoring.
This PR also adds a couple of low level tests for the
CTokenListCategory class.  One of these highlights the
outstanding problem …
> [7.x][ML] Modernize the categorization code

- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
The threshold of 0.85 worked in optimised code but
failed (only by a margin of 0.05) when code was
built without optimisation.
> [ML] Adjust test threshold for debug build

- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
The threshold of 0.85 worked in optimised code but
failed (only by a margin of 0.05) when code was
built without optimisation.
Backport of #971
> [7.x][ML] Adjust test threshold for debug build

- docs/CHANGELOG.asciidoc
- include/model/CTokenListCategory.h
- lib/api/unittest/CFieldDataCategorizerTest.cc
- lib/api/unittest/CRestorePreviousStateTest.cc
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/unittest/CTokenListCategoryTest.cc
Previously, when reducing the subset of common tokens that
were in the same order for all messages in a category the
subset matching from the start of the original category
tokens would be used.  This was highly suboptimal in the
case of a message being added to the category that
contained the first token in the original category tokens,
but near the end of the new message rather than near the
beginning.
This PR changes categorization such that the largest
ordered subset is chosen, even if this involves excluding
tokens that occurred near the start of the original category
tokens.
In practice this means that if a category contains messages
of the form "a b c d e" and a message "b c d e a" is
considered close enough to match then the regex chosen that
matches all messages in the category …
> [ML] Use largest ordered subset of categorization tokens for regex

- docs/CHANGELOG.asciidoc
- include/model/CTokenListCategory.h
- lib/api/unittest/CFieldDataCategorizerTest.cc
- lib/api/unittest/CRestorePreviousStateTest.cc
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/unittest/CTokenListCategoryTest.cc
Previously, when reducing the subset of common tokens that
were in the same order for all messages in a category the
subset matching from the start of the original category
tokens would be used.  This was highly suboptimal in the
case of a message being added to the category that
contained the first token in the original category tokens,
but near the end of the new message rather than near the
beginning.
This PR changes categorization such that the largest
ordered subset is chosen, even if this involves excluding
tokens that occurred near the start of the original category
tokens.
In practice this means that if a category contains messages
of the form "a b c d e" and a message "b c d e a" is
considered close enough to match then the regex chosen that
matches all messages in the category …
> [7.x][ML] Use largest ordered subset of categorization tokens for regex

- mk/linux_crosscompile_macosx.mk
- mk/macosx.mk
Clang warns about a bug in C++11, but the compilers
we are using on the master branch do not suffer
from it and we are never likely to downgrade.
Therefore the warning is just an annoyance and
can be silenced.
> [ML] Silence unnecessary clang warning

- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
- include/api/CDataFrameTrainBoostedTreeRunner.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
This is a refractor in anticipation loss functions with multiple parameters. It is non-functional, but I noticed running the unit tests creating the temporaries (even though they're not allocating any memory) actually costs some run time. It will likely make sense to revisit the type choice when I work on updates to the aggregation code. A step towards #982.
> [ML] Rework caching and reading predictions and derivatives in boosted tree training to anticipate multiple values

- include/maths/CBoostedTreeImpl.h
- include/maths/CBoostedTreeLeafNodeStatistics.h
- include/maths/CBoostedTreeUtils.h
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLeafNodeStatistics.cc
- lib/maths/CBoostedTreeUtils.cc
- lib/maths/Makefile
As a precursor to extending `CLeafNodeStatistics` to support multi-parameter loss functions this is a non-functional change to factor it's implementation out of `CBoostedTreeImpl`. This file and class was becoming unwieldy and I also plan to write some standalone unit tests for `CLeafNodeStatistics` as its implementation becomes somewhat more complex.
> [ML] Split up CBoostedTreeImpl

- docs/CHANGELOG.asciidoc
- include/api/CAnomalyJob.h
- include/api/CJsonOutputWriter.h
- include/api/CModelSizeStatsJsonWriter.h
- include/api/CModelSnapshotJsonWriter.h
- include/model/CAnomalyDetector.h
- include/model/CMonitoredResource.h
- include/model/CResourceMonitor.h
- include/model/CTokenListCategory.h
- include/model/CTokenListDataCategorizer.h
- include/model/CTokenListDataCategorizerBase.h
- include/model/ModelTypes.h
- lib/api/CAnomalyJob.cc
- lib/api/CJsonOutputWriter.cc
- lib/api/CModelSizeStatsJsonWriter.cc
- lib/api/unittest/CJsonOutputWriterTest.cc
- lib/api/unittest/CModelSnapshotJsonWriterTest.cc
- lib/model/CAnomalyDetector.cc
- lib/model/CResourceMonitor.cc
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/ModelTypes.cc
- lib/model/unittest/CResourceMonitorTest.cc
- lib/model/unittest/CTokenListDataCategorizerBaseTest.cc
This change adds support for the following new model_size_stats
fields:
- categorized_doc_count
- total_category_count
- frequent_category_count
- rare_category_count
- dead_category_count
- categorization_status
Relates elastic/elasticsearch#50749
> [ML] Add new categorization stats to model_size_stats

- docs/CHANGELOG.asciidoc
- include/api/CAnomalyJob.h
- include/api/CJsonOutputWriter.h
- include/api/CModelSizeStatsJsonWriter.h
- include/api/CModelSnapshotJsonWriter.h
- include/model/CAnomalyDetector.h
- include/model/CMonitoredResource.h
- include/model/CResourceMonitor.h
- include/model/CTokenListCategory.h
- include/model/CTokenListDataCategorizer.h
- include/model/CTokenListDataCategorizerBase.h
- include/model/ModelTypes.h
- lib/api/CAnomalyJob.cc
- lib/api/CJsonOutputWriter.cc
- lib/api/CModelSizeStatsJsonWriter.cc
- lib/api/unittest/CJsonOutputWriterTest.cc
- lib/api/unittest/CModelSnapshotJsonWriterTest.cc
- lib/model/CAnomalyDetector.cc
- lib/model/CResourceMonitor.cc
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/ModelTypes.cc
- lib/model/unittest/CResourceMonitorTest.cc
- lib/model/unittest/CTokenListDataCategorizerBaseTest.cc
This change adds support for the following new model_size_stats
fields:
- categorized_doc_count
- total_category_count
- frequent_category_count
- rare_category_count
- dead_category_count
- categorization_status
Backport of #989
> [7.x][ML] Add new categorization stats to model_size_stats

- dev-tools/jenkins_ci.ps1
When running remotely PowerShell converts output to stderr
as error objects.  These then cause the script to fail.
This change adds a step to convert any such error objects
originating from the main Gradle invocation back to strings.
This is required to get the new CI setup to work on Windows.
> Convert PowerShell error objects from stderr back to strings

- dev-tools/jenkins_ci.ps1
When running remotely PowerShell converts output to stderr
as error objects.  These then cause the script to fail.
This change adds a step to convert any such error objects
originating from the main Gradle invocation back to strings.
This is required to get the new CI setup to work on Windows.
Backport of #997
> [7.x] Convert PowerShell error objects from stderr back to strings

- dev-tools/jenkins_ci.ps1
When running remotely PowerShell converts output to stderr
as error objects.  These then cause the script to fail.
This change adds a step to convert any such error objects
originating from the main Gradle invocation back to strings.
This is required to get the new CI setup to work on Windows.
Backport of #997
> [7.6] Convert PowerShell error objects from stderr back to strings

- dev-tools/jenkins_ci.ps1
When running remotely PowerShell converts output to stderr
as error objects.  These then cause the script to fail.
This change adds a step to convert any such error objects
originating from the main Gradle invocation back to strings.
This is required to get the new CI setup to work on Windows.
Backport of #997
> [6.8] Convert PowerShell error objects from stderr back to strings

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameAnalysisInstrumentation.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CDataFrameAnalysisInstrumentationInterface.h
- include/maths/CDataFramePredictiveModel.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/COutliersTest.cc
We weren't accounting for the data frame's memory usage when reporting peak memory usage for training. Also, we were missing some state when estimating peak memory usage during the line searches to initialise hyperparameters.
I've also taken the opportunity to more fully migrate instrumentation of training to use the new instrumentation object and provide better automatic stubbing.
> [ML] Account for data frame memory in the peak memory usage estimate for classification and regression

- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeLeafNodeStatistics.h
- include/maths/CBoostedTreeUtils.h
- include/maths/CLinearAlgebraEigen.h
- include/maths/CLinearAlgebraShims.h
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLeafNodeStatistics.cc
- lib/maths/CBoostedTreeUtils.cc
- lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/Makefile
This extends computing aggregate derivatives and solving for the highest quadratic gain split to support multi-parameter loss functions.
I experimented with various implementations. This version, which minimises the number of allocations by using memory mapped classes, proved to be much the most efficient.
This is the next step towards #982.
> [ML] Support for multi-parameter loss functions in derivative aggregation and finding best splits

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameAnalysisInstrumentation.h
- include/maths/CDataFrameAnalysisInstrumentationInterface.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.h
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/COutliers.cc
This change fixes a double counting bug for the memory used by the extra columns for classification and regression model training. It also means they only count towards the data frame memory usage: previously they were wrongly being treated as features for memory estimation purposes. 
Incidentally, it also fixes the memory reported by the counter `E_DFOEstimatedPeakMemoryUsage`, which was missing the extra columns' memory usage.
Finally, it tidies up instrumentation of outlier detection, to more fully use the new instrumentation class, and corrects the memory estimates in `testRunOutlierDetectionPartitioned`.
> [ML] Improvements to upfront memory estimation for data frame analyses

- 3rd_party/licenses/gcc-runtime-INFO.csv
This should have been done in #2 but was missed at that time.
> [ML] Correct the gcc version in the third party component info

- 3rd_party/3rd_party.sh
- 3rd_party/licenses/gcc-runtime-INFO.csv
- build-setup/linux.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/vagrant/linux/provision.sh
- docs/CHANGELOG.asciidoc
- mk/linux.mk
- set_env.sh
This change is primarily to upgrade the gcc we use from version 7.3
to version 7.5.
A secondary change is to build a recent version of the binutils
package from source for use in our builds instead of relying on
whatever happened to come with the build machine.
Both changes are driven by the desire to build Tensorflow in the
future.  gcc 7.3 suffers from an internal compiler error when
trying to compile Tensorflow.  The bug is fixed in gcc 7.5.  Also,
the assembler that comes with binutils 2.20 is too old to assemble
the compiler output when building Tensorflow, and version 2.20 is
what CentOS 6 ships with.  Since our build platform for released
product is CentOS 6 we also need to install a newer version of
binutils.
> [ML] Upgrade gcc to version 7.5

- 3rd_party/3rd_party.sh
- 3rd_party/licenses/gcc-runtime-INFO.csv
- build-setup/linux.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/vagrant/linux/provision.sh
- docs/CHANGELOG.asciidoc
- mk/linux.mk
- set_env.sh
This change is primarily to upgrade the gcc we use from version 7.3
to version 7.5.
A secondary change is to build a recent version of the binutils
package from source for use in our builds instead of relying on
whatever happened to come with the build machine.
Both changes are driven by the desire to build Tensorflow in the
future.  gcc 7.3 suffers from an internal compiler error when
trying to compile Tensorflow.  The bug is fixed in gcc 7.5.  Also,
the assembler that comes with binutils 2.20 is too old to assemble
the compiler output when building Tensorflow, and version 2.20 is
what CentOS 6 ships with.  Since our build platform for released
product is CentOS 6 we also need to install a newer version of
binutils.
Backport of #1013
> [7.x][ML] Upgrade gcc to version 7.5

- docs/CHANGELOG.asciidoc
- include/maths/CTreeShapFeatureImportance.h
- lib/maths/CTreeShapFeatureImportance.cc
> [7.7][ML] Feature importance performance optimization 

- build-setup/linux.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/vagrant/linux/provision.sh
The gcc build process makes it hard to set extra linker flags for
the libgcc_s.so.1 library.  We had a [hack](https://github.com/elastic/ml-cpp/blob/07bd27fa66ccacdf6bfe333e3e5dab3335344679/dev-tools/docker/linux_image/Dockerfile#L29) in our build steps that
worked for gcc 7.3, but stopped working in gcc 7.5 with the result
that Debian's lintian tool flags the library as being insecure - see
elastic/elasticsearch#52554.  This change alters the hack to simply
add the required flags directly to the linker command that is used
for libgcc_s.so.1.
Relates elastic/elasticsearch#52554
> [ML] Change the way hardening flags are set for libgcc_s.so.1

- build-setup/linux.md
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/linux_builder/Dockerfile
- dev-tools/docker/linux_image/Dockerfile
- dev-tools/docker/linux_tester/Dockerfile
- dev-tools/vagrant/linux/provision.sh
The gcc build process makes it hard to set extra linker flags for
the libgcc_s.so.1 library.  We had a hack in our build steps that
worked for gcc 7.3, but stopped working in gcc 7.5 with the result
that Debian's lintian tool flags the library as being insecure - see
elastic/elasticsearch#52554.  This change alters the hack to simply
add the required flags directly to the linker command that is used
for libgcc_s.so.1.
Backport of #1019
> [7.x][ML] Change the way hardening flags are set for libgcc_s.so.1

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- include/api/CDataFrameTrainBoostedTreeRunner.h
- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CDataFramePredictiveModel.h
- include/maths/CTreeShapFeatureImportance.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CDataFramePredictiveModel.cc
- lib/maths/CTreeShapFeatureImportance.cc
- lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
This also finishes up multi-parameter loss function support.
Note I don't save and restore `CTreeShapFeatureImportance` because train is always run and so this will always be reinitialised before any SHAP values are computed. For failover we should almost certainly keep track of SHAP values already computed and written, but it might make more sense for the Java to pass this information. I'm therefore deferring this detail to a later PR.
Finally, I've removed multithreading of the SHAP code, because it only gets passed one row at a time now. We should be able to parallelise over trees, but this will require a small tweak to parallel_for_each. Since we don't currently pass number threads from Java, I'll make this change in a follow on PR.
> [ML] Rework computing SHAP to avoid using data frame storage

- docs/CHANGELOG.asciidoc
- include/maths/CBoostedTreeLoss.h
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/unittest/CBoostedTreeTest.cc
This was a bug in the computation of the best leaf weight when predictions for all its training rows are identical. In this case, we should find the weight to *add* to the current prediction which minimises the cross-entropy.
> [ML] Correct logistic loss function

- include/api/CDataFrameAnalysisRunner.h
- include/api/CDataFrameAnalysisSpecification.h
- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- include/core/CDataFrame.h
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/core/CDataFrame.cc
Following on from #1034, we can simplify the handling of missing target field values for classification. Java will supply the missing string value to denote these are missing rather than the empty string.
> [ML] Remove special case handling for missing target field for classification

- include/core/CDataFrame.h
- include/maths/CDataFrameUtils.h
- lib/core/CDataFrame.cc
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
There were some places in the code that assumed categorical features don't have missing values which hadn't been updated as part of #1034. I've also updated the encoding schemes so that missing categories map to missing [1]. Finally, I've also improved unit testing w.r.t. missing values.
Since this is fallout from #1034, which isn't yet released, I'm marking as a non-issue.
Closes #1040.
[1] This may not be the best approach to take, but represents the least effort fix for the SIGSEGV.
> [ML] Correct missing category handling

- lib/api/CDataFrameAnalysisInstrumentation.cc
This seems like the most likely candidate for sporadic integration test failures: they first happened after this was committed.
> [ML] Temporarily disable writing memory usage

- include/api/CDataFrameAnalysisInstrumentation.h
- include/api/CDataFrameAnalysisSpecification.h
- include/api/CDataFrameAnalyzer.h
- include/core/CRapidJsonConcurrentLineWriter.h
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
- lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
This fixes the writing of memory usage and reinstates it.
We were previously sharing a `core::CRapidJsonConcurrentLineWriter` between the main thread and the thread running an analysis. This is not the intended usage: we should have one object per thread managing writing to a shared stream.
I've also taken the opportunity to make sure that the stream is unattached from the runner as soon as it is destroyed. It wasn't being used after this point previously, but this change makes it impossible to use it accidentally.
Finally, I noticed that we weren't actually asserting we were writing memory usage in the unit tests. I've added this check.
I've marked as a non-issue since this code is not released.
> [ML] Start writing memory usage again

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeRunner.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
Adds a new param `max_trees` to replace the existing
`maximum_number_trees` for classification and regression
analyses.
> [ML] Rename maximum_number_trees to max_trees

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeRunner.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
Adds a new param `max_trees` to replace the existing
`maximum_number_trees` for classification and regression
analyses.
Backport of #1047
> [7.x][ML] Rename maximum_number_trees to max_trees (#1047)

- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Adds `num_classes` as a parameter to classification.
The parameter is currently unused but this prepares us to
be able to merge in supplying the parameter from the java side
before it's required.
> [ML] Add classification num_classes param

- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Adds `num_classes` as a parameter to classification.
The parameter is currently unused but this prepares us to
be able to merge in supplying the parameter from the java side
before it's required.
Backport of #1054
> [7.x][ML] Add classification num_classes param (#1054)

- include/api/CBoostedTreeInferenceModelBuilder.h
- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- include/api/CInferenceModelDefinition.h
- include/maths/CBasicStatistics.h
- include/maths/CBoostedTree.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CBoostedTreeLoss.h
- include/maths/CDataFramePredictiveModel.h
- include/maths/CDataFrameUtils.h
- include/maths/CInformationCriteria.h
- include/maths/CKMeans.h
- include/maths/CLinearAlgebra.h
- include/maths/CLinearAlgebraEigen.h
- include/maths/CLinearAlgebraShims.h
- include/test/CDataFrameAnalysisSpecificationFactory.h
- lib/api/CBoostedTreeInferenceModelBuilder.cc
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/CInferenceModelDefinition.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
- lib/maths/CBoostedTree.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLeafNodeStatistics.cc
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/test/CDataFrameAnalysisSpecificationFactory.cc
This wires up multiclass classification so it can be run by the data frame analyzer and also . Marking as a non-issue since the feature was documented in #1037.
I need some more unit testing, so keeping as WIP at the moment, but the code changes are complete. I've also left some TODOs for supporting maximize minimum class recall, which I'll revisit in a later PR.
> [ML] Wire in multiclass classification to the data frame analyzer command

- lib/maths/CBoostedTreeLoss.cc
- lib/maths/unittest/CBoostedTreeLossTest.cc
- lib/maths/unittest/CBoostedTreeTest.cc
This also finishes up the loss function unit testing.
I've also migrated to using exact logs in the loss function. This enables me to test the gradient and curvature functions against numerical derivatives of the loss function, which otherwise suffer large errors. Since these quantities are cached they also aren't a runtime bottleneck.
I've marked this as a non-issue since the code isn't released yet.
> [ML] Fix some bugs in multinomial logistic loss derivatives

- include/maths/CBoostedTreeLeafNodeStatistics.h
- include/maths/CLinearAlgebraEigen.h
- lib/maths/CBoostedTreeLeafNodeStatistics.cc
- lib/maths/unittest/CBoostedTreeTest.cc
This change corrects the logic for dealing with singular (to working precision) Hessians. Before fixing these issues, I noticed that if a split gain is NaN it could be selected. Instead this forces the gain to be negative. Note that I've left TODOs to enable the unit test assertions as I'm still investigating accuracy.
Since this is unreleased code I've marked as a non-issue.
> [ML] Better handling of near singular loss Hessian

- lib/maths/CBoostedTreeImpl.cc
This was broken in #1056, which hasn't been released, so marking as a non-issue.
> [ML] Fix the maximum accuracy objective for binary classification

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameAnalysisInstrumentation.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CDataFrameAnalysisInstrumentationInterface.h
- include/maths/COutliers.h
- include/test/CDataFrameAnalyzerTrainingFactory.h
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
- lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.h
- lib/api/unittest/testfiles/instrumentation/classification_stats.schema.json
- lib/api/unittest/testfiles/instrumentation/memory_usage.schema.json
- lib/api/unittest/testfiles/instrumentation/outlier_detection_stats.schema.json
- lib/api/unittest/testfiles/instrumentation/regression_stats.schema.json
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/COutliers.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/COutliersTest.cc
- lib/test/CDataFrameAnalyzerTrainingFactory.cc
- lib/test/Makefile
This PR enables instrumentation of the supvervised learning jobs. I needed to add maths::CDataFrameTrainBoostedTreeInstrumentationInterface to have an interface for storing validation error results, hyperparameters, and timing.
Since I am passing iteration directly over the new interface, I also refactored nextStep to use an optional string phase as an argument. At the moment, we are not tagging phases, but we intend to in the future. Thus, I added a TODO there.
Finally, I extracted the common routines for generating regression and classification data into CDataFrameAnalyzerTrainingFactory. It is not used for feature importance testing so far, cause the generation procedure there is a little bit different. I intend to unify the code in a follow-up PR.
Backport of #1031
> [7.x][ML] Instrumentation information for boosted tree learning 

- include/maths/CBoostedTreeLoss.h
- include/maths/CLbfgs.h
- include/maths/CTools.h
- include/maths/CToolsDetail.h
- lib/api/CDataFrameAnalysisSpecification.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/unittest/CBoostedTreeLossTest.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CToolsTest.cc
These mainly revolve around reducing the number of new and delete calls from creating temporary vectors. I also adjusted the k-means parameters. The cost of computing leaf values is still dominating (compared to binary case) so this needs more work. This is changing unreleased code so marking as non-issue.
> [ML] Speed ups for multiclass classification

- include/maths/CBoostedTreeLoss.h
- include/maths/CKMeans.h
- include/maths/CKMeansOnline.h
- include/maths/CKdTree.h
- include/maths/CLinearAlgebraShims.h
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CKMeansOnlineTest.cc
- lib/maths/unittest/CKMeansTest.cc
- lib/maths/unittest/CMultivariateMultimodalPriorTest.cc
- lib/maths/unittest/CXMeansOnlineTest.cc
This makes a number of changes to minimise copying vectors when performing streaming k-means. This mainly revolves around moving collections into place where possible. I also made some small tidy ups in the related code and enabled `CBoostedTreeTest/testMultinomialLogisticRegression` which is (just) running fast enough. This mainly affects unreleased code so marking as a non-issue.
> [ML] More speed ups for multiclass classification

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeRunner.h
- include/maths/CTreeShapFeatureImportance.h
- include/test/CDataFrameAnalysisSpecificationFactory.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CTreeShapFeatureImportance.cc
- lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
- lib/test/CDataFrameAnalysisSpecificationFactory.cc
Feature importance is already calculated for multi-class models. This commit adjusts the output sent to ES so that multi-class importance can be explored.
Feature importance objects are now mapped as follows
(logistic) Regression:
```
{
"feature_name": "feature_0",
"importance": -1.3
}
```
Multi-class [class names are `foo`, `bar`, `baz`]
```
{ 
“feature_name”: “feature_0”, 
“importance”: 2.0, // sum(abs()) of class importances
“foo”: 1.0, 
“bar”: 0.5, 
“baz”: -0.5 
},
```
Java side change: https://github.com/elastic/elasticsearch/pull/53803
> [ML] calculate feature importance for multi-class results

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeRunner.h
- include/maths/CTreeShapFeatureImportance.h
- include/test/CDataFrameAnalysisSpecificationFactory.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CTreeShapFeatureImportance.cc
- lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
- lib/test/CDataFrameAnalysisSpecificationFactory.cc
- [ML] calculate feature importance for multi-class results (#1071)
> [7.x] [ML] calculate feature importance for multi-class results (#1071)

- include/maths/CKMeansOnline.h
std::max() takes its arguments by reference, and in older
C++ standards it was not permitted to take the address of
a constant declared and defined on the same line in a class
definition.  Linux still seems to be sticking to this
restriction, although I imagine the standard has changed
because the other two platforms coped with the code.  Also,
even Linux only fails to compile when all optimisation is
disabled presumably because the call to std::max() is
usually optimised away.
The pragmatic fix is to manually optimise away the std::max()
call.
> [ML] Fix non-optimised Linux compilation

- include/maths/CKMeansOnline.h
std::max() takes its arguments by reference, and in older
C++ standards it was not permitted to take the address of
a constant declared and defined on the same line in a class
definition.  Linux still seems to be sticking to this
restriction, although I imagine the standard has changed
because the other two platforms coped with the code.  Also,
even Linux only fails to compile when all optimisation is
disabled presumably because the call to std::max() is
usually optimised away.
The pragmatic fix is to manually optimise away the std::max()
call.
Backport of #1078
> [7.x][ML] Fix non-optimised Linux compilation

- include/maths/CBoostedTreeLoss.h
- include/maths/CSampling.h
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/COutliers.cc
- lib/maths/CSampling.cc
- lib/maths/unittest/CSamplingTest.cc
This change switches to using a weighted random sample of the leaf's training examples to determine the partition with which to approximate the log-loss objective for computing optimal leaf values. (Unfortunately, I couldn't get k-means fast enough for this purpose.)
The sample weights are chosen based on the mean distance between each prediction and the others in the random sample, i.e. they repel one another. This generates a more uniform sampling of the points, which results in lower average radius for the partition subsets. The result is a better approximation to the true loss function than using a uniform random sample.
> [ML] Rework the approximate loss function for choosing leaf values for multiclass classification

- include/maths/CLbfgs.h
- include/maths/CLinearAlgebraEigen.h
- include/maths/CLinearAlgebraShims.h
- include/maths/CTools.h
- include/maths/CToolsDetail.h
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/unittest/CBoostedTreeLossTest.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CToolsTest.cc
Generally, Eigen elides all vector temporaries in vector expressions. The one exception is when we assign to a `CDenseVector`. We use placeholder vectors in various places to avoid additional allocations and we're not getting the full benefits from these as a result.
This gets about 30% improvement in multiclass classification runtime.
> [ML] Avoid temporaries in vector expressions

- .dockerignore
- .gitignore
This mini PR adds hidden directories of Visual Studio Code and clangd into the `.gitignore` file. No functionality is changed.
> [ML] Extend .gitignore to work with VSCode

- lib/api/CDataFrameAnalyzer.cc
This PR adds logging for computing results and writing the output. It aims to tell what's going on, if the job is stuck in the final phase in it takes a while (feature importance computation). I give a log info message at the beginning and at the end of computing results. Also every 20000 rows I produce an intermediate log debug message with timing and progress.
The output will be something like this:
```
2020-03-24 14:41:38,943646 UTC [14831] INFO  CDataFrameAnalyzer.cc@311 Start computing results. For regression and classification with feature importance this may take a while.
2020-03-24 14:41:38,943752 UTC [14831] DEBUG CDataFrameAnalyzer.cc@346 Results computation in progress: 20000/100000. Average time per row in ms: 10 std. dev:  0
2020-03-24 14:41:38,943823 UTC [14831] DEBUG …
```
> [ML] Logging additional information for results

- .dockerignore
- .gitignore
This mini PR adds hidden directories of Visual Studio Code and clangd into the .gitignore and .dockerignore files. No functionality is changed.
Backport of #1089.
> [7.x][ML] Extend .gitignore to work with VSCode 

- include/maths/CBoostedTreeLoss.h
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/unittest/CBoostedTreeLossTest.cc
The optimisation objective is convex so there is no need for restarts. Also, since we're getting unique vectors there is no need to stable sort them. Finally, I increased the size of the approximating partition somewhat because the optimisation is significantly cheaper.
This also truncates lambda to be (small and) positive. This has a couple of benefits: 1) it means we always have a unique minimum (otherwise the normalisation constraint means any {w_j' = k  + w_j} for {w_j} a minimum is also a minimum), 2) it naturally limits weights when all labels are equal so we no longer need to truncate them.
> [ML] Speedup calculating leaf values for multiclass classification

- bin/data_frame_analyzer/Main.cc
- docs/CHANGELOG.asciidoc
This will sandbox the process to a degree in the event
of a security flaw being exploited.
> [ML] Enable system call filter for data_frame_analyzer

- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- include/api/CDataFrameTrainBoostedTreeRunner.h
- include/maths/CBoostedTreeFactory.h
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/unittest/testfiles/instrumentation/classification_stats.schema.json
- lib/api/unittest/testfiles/instrumentation/regression_stats.schema.json
- lib/maths/CBoostedTreeFactory.cc
- lib/test/CDataFrameAnalysisSpecificationFactory.cc
We should the same field names for instrumentation JSON that we do for the analysis configuration, so reported values can just be pasted (unmodified) into a new job config if desired. This cuts over to use the strings defined in the api runner objects and changes some of them in the process.
I think this should ideally released in 7.7 to save renaming after we've released this functionality so I've marked as non-issue.
> [ML] Instrumentation parameter names should match analysis config where applicable

- bin/data_frame_analyzer/Main.cc
- docs/CHANGELOG.asciidoc
This will sandbox the process to a degree in the event
of a security flaw being exploited.
Backport of #1098
> [7.x][ML] Enable system call filter for data_frame_analyzer

- bin/data_frame_analyzer/Main.cc
- docs/CHANGELOG.asciidoc
This will sandbox the process to a degree in the event
of a security flaw being exploited.
Backport of #1098
> [7.7][ML] Enable system call filter for data_frame_analyzer

- bin/autoconfig/Main.cc
- bin/autodetect/Main.cc
- bin/categorize/Main.cc
- bin/data_frame_analyzer/Main.cc
- bin/normalize/Main.cc
- docs/CHANGELOG.asciidoc
- include/core/CProcessPriority.h
- lib/core/CProcessPriority.cc
- lib/core/CProcessPriority_Linux.cc
- lib/core/CProcessPriority_Windows.cc
- lib/core/unittest/CProcessPriorityTest.cc
- lib/core/unittest/CProcessPriorityTest_Linux.cc
When many ML jobs are running at the same time and there is
insufficient CPU it is more important to prioritise the JVM
performance so that search and indexing latency remains
acceptable.
This change is an attempt to do this by increasing the "nice"
setting of the analysis processes (not controller) to reduce
their CPU scheduling priority.
This change should have little or no effect on performance on
machines that are not CPU constrained.
The exact numbers may need to be tweaked in a followup PR.
> [ML] Reduce analysis process priority for CPU scheduling

- bin/autoconfig/Main.cc
- bin/autodetect/Main.cc
- bin/categorize/Main.cc
- bin/data_frame_analyzer/Main.cc
- bin/normalize/Main.cc
- docs/CHANGELOG.asciidoc
- include/core/CProcessPriority.h
- lib/core/CProcessPriority_Linux.cc
- lib/core/CProcessPriority_Windows.cc
- lib/core/unittest/CProcessPriorityTest.cc
- lib/core/unittest/CProcessPriorityTest_Linux.cc
When many ML jobs are running at the same time and there is
insufficient CPU it is more important to prioritise the JVM
performance so that search and indexing latency remains
acceptable.
This change is an attempt to do this by increasing the "nice"
setting of the analysis processes (not controller) to reduce
their CPU scheduling priority.
This change should have little or no effect on performance on
machines that are not CPU constrained.
The exact numbers may need to be tweaked in a followup PR.
Backport of #1109
> [7.x][ML] Reduce analysis process priority for CPU scheduling

- build-setup/linux.md
Although Linux distributions make it easy to install valgrind
using their package manager, this version works best with the
gcc that is installed by the package manager, not the one we
build.  It is better if a valgrind is built by the gcc that
we build.
> [ML] Add instructions for building valgrind

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeRunner.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/maths/unittest/CBoostedTreeTest.cc
This change adjust the memory estimation by taking the parameter `training_percent` into account. 
It is an optional parameter that defaults to `100.0`. The Java side will write out the parameter as it is input by the user.
> [ML] take training_percent into account when estimating memory

- docs/CHANGELOG.asciidoc
- include/maths/CKMeans.h
- include/maths/CKMeansOnline.h
- include/maths/CXMeansOnline.h
- lib/maths/CInformationCriteria.cc
Clustering can be the bottleneck for the `lat_long` function.
This reworks the calculation of the distances to the selected points in k-means++ initialisation. Before we were creating a k-d tree for each point we added and looking up nearest neighbours. This is unnecessary since we can simply update the distances directly, i.e. `distance_i = min(distance_i, distance(selected, x_i))`. The other main speedup comes from the fact that in #1037 I reworked online k-means to remove the points buffer. This saves us memory and we can spend this memory by accumulating more points before we re-cluster.
I also made some tweaks to cutdown the number of allocations (principally by moving various variables into place). Finally, I corrected `CKMeansOnline::split` to copy all the parent clustering …
> [ML] Speed up the lat_long function

- docs/CHANGELOG.asciidoc
- lib/maths/CGammaRateConjugate.cc
- lib/maths/CLogNormalMeanPrecConjugate.cc
- lib/maths/CNormalMeanPrecConjugate.cc
- lib/maths/COneOfNPrior.cc
- lib/maths/CPoissonMeanConjugate.cc
- lib/maths/CPrior.cc
In particular, it more reliably stops non-finite inputs polluting the model.
> [ML] Improve bad input handling in distribution models

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeRunner.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- [ML] take training_percent into account when estimating memory (#1111)
> [7.x] [ML] take training_percent into account when estimating memory (#1111)

- docs/CHANGELOG.asciidoc
- include/api/CFieldDataCategorizer.h
- include/api/CJsonOutputWriter.h
- include/model/CDataCategorizer.h
- include/model/CTokenListCategory.h
- include/model/CTokenListDataCategorizerBase.h
- lib/api/CFieldDataCategorizer.cc
- lib/api/CJsonOutputWriter.cc
- lib/api/unittest/CFieldDataCategorizerTest.cc
- lib/api/unittest/CJsonOutputWriterTest.cc
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
Two new fields added to our category output when they are written back to Java.
* `num_matches` indicates the total number of matches this category has seen
* `preferred_to_categories` indicates that this particular category is matched now instead of the listed categories. 
Java side https://github.com/elastic/elasticsearch/pull/54214
> [ML] Adding num_matches and preferred_to_categories output to categories

- include/model/CTokenListDataCategorizerBase.h
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
The mistake was that m_CategoriesByCount has indices into
m_Categories, not category IDs (which are one more than
the indices so that they start at 1 rather than 0).
Also fixed a couple of edge cases where reference arguments
were not being set despite a function returning success.
Fixes #1121
> [ML] Fix off-by-one error in usurped categories

- lib/seccomp/CSystemCallFilter_Linux.cc
This is to support #1109.
The risk with setpriority is that it can possibly be used on a
different process.  However, it is extremely unlikely that the
user that Elasticsearch is running as in production will have
been granted permission to call it.  Running as root is banned
and it's an extra admin action to grant the privilege to any
other user and there is no good reason for it to have been
granted to the Elasticsearch user.
> [ML] Add getpriority/setpriority to Linux system call whitelist

- include/model/CTokenListDataCategorizerBase.h
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
The mistake was that m_CategoriesByCount has indexes into
m_Categories, not category IDs (which are one more than
the indices so that they start at 1 rather than 0).
Backport of #1122
> [7.x][ML] Fix off-by-one error in usurped categories

- docs/CHANGELOG.asciidoc
- include/maths/CKMeans.h
- include/maths/CKMeansOnline.h
- include/maths/CXMeansOnline.h
- lib/maths/CInformationCriteria.cc
> [7.8][ML] Speed up the lat_long function

- lib/seccomp/CSystemCallFilter_Linux.cc
This is to support #1109.
The risk with setpriority is that it can possibly be used on a
different process.  However, it is extremely unlikely that the
user that Elasticsearch is running as in production will have
been granted permission to call it.  Running as root is banned
and it's an extra admin action to grant the privilege to any
other user and there is no good reason for it to have been
granted to the Elasticsearch user.
Backport of #1117
> [7.x][ML] Add getpriority/setpriority to Linux system call whitelist

- docs/CHANGELOG.asciidoc
- include/maths/CBoostedTreeImpl.h
- include/maths/CDataFrameUtils.h
- include/maths/CTools.h
- include/maths/CToolsDetail.h
- include/test/CDataFrameAnalyzerTrainingFactory.h
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/CToolsTest.cc
- lib/test/CDataFrameAnalyzerTrainingFactory.cc
This implements maximise minimum class recall for multiclass classification when assigning class labels, which is often a better objective when classes are imbalanced in the training data.
> [ML] Multiclass maximise minimum recall

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc
Previously data frame analytics memory estimates were
rounded to the nearest kilobyte, but this results in
excessive precision for large analyses.  This changes
the estimates to always be reported in whole megabytes,
rounded up from the low level estimate.
Closes #1110
Closes elastic/elasticsearch#54506
> [ML] Round up data frame analytics memory estimates to next MB

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc
Previously data frame analytics memory estimates were
rounded to the nearest kilobyte, but this results in
excessive precision for large analyses.  This changes
the estimates to always be reported in whole megabytes,
rounded up from the low level estimate.
Backport of #1126
> [7.x][ML] Round up data frame analytics memory estimates to next MB

- docs/CHANGELOG.asciidoc
- include/maths/CBoostedTreeImpl.h
- include/maths/CDataFrameUtils.h
- include/maths/CTools.h
- include/maths/CToolsDetail.h
- include/test/CDataFrameAnalyzerTrainingFactory.h
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
- lib/maths/unittest/CToolsTest.cc
- lib/test/CDataFrameAnalyzerTrainingFactory.cc
> [7.8][ML] Multiclass maximise minimum recall

- docs/CHANGELOG.asciidoc
- include/core/CIEEE754.h
- include/maths/CBoostedTreeLeafNodeStatistics.h
- include/maths/CLbfgs.h
- include/maths/CTools.h
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/core/CIEEE754.cc
- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLeafNodeStatistics.cc
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/unittest/CBayesianOptimisationTest.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CToolsTest.cc
This addresses some of the underlying causes for variation in regression and classification results for different platforms: `std::log` and `std::exp` don't always agree in the last decimal place and our split order predicate wasn't a total order.
> [ML] Reduce differences in regression and classification results between target platforms

- 3rd_party/3rd_party.sh
- build-setup/linux.md
- lib/maths/unittest/CBasicStatisticsTest.cc
- lib/maths/unittest/CSplineTest.cc
- lib/maths/unittest/CXMeansOnlineTest.cc
- lib/model/unittest/CMetricDataGathererTest.cc
- lib/seccomp/CSystemCallFilter_Linux.cc
- mk/linux.mk
- set_env.sh
This PR adds the ability to compile and unit test the code on
the aarch64 architecture.
It is NOT workable aarch64 support.  That would additionally
require the ability to cross compile for aarch64 from the
x86_64 release manager and CI VMs, and also changes to the
Gradle scripts that assemble the final artifacts.
However, the relative ease of getting the code to compile and
run on aarch64 suggests that supporting this platform is a
realistic goal.
The unit test changes highlight that aarch64 floating point
calculations produce slightly different results to the
equivalent x86_64 calculations.
> [ML] Native compilation and unit test for Linux on aarch64

- 3rd_party/3rd_party.sh
- build-setup/linux.md
- lib/maths/unittest/CBasicStatisticsTest.cc
- lib/maths/unittest/CSplineTest.cc
- lib/maths/unittest/CXMeansOnlineTest.cc
- lib/model/unittest/CMetricDataGathererTest.cc
- lib/seccomp/CSystemCallFilter_Linux.cc
- mk/linux.mk
- set_env.sh
This PR adds the ability to compile and unit test the code on
the aarch64 architecture.
It is NOT workable aarch64 support.  That would additionally
require the ability to cross compile for aarch64 from the
x86_64 release manager and CI VMs, and also changes to the
Gradle scripts that assemble the final artifacts.
However, the relative ease of getting the code to compile and
run on aarch64 suggests that supporting this platform is a
realistic goal.
The unit test changes highlight that aarch64 floating point
calculations produce slightly different results to the
equivalent x86_64 calculations.
Backport of #1132
> [7.x][ML] Native compilation and unit test for Linux on aarch64

- docs/CHANGELOG.asciidoc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/api/unittest/CDataFrameMockAnalysisRunner.h
- lib/maths/CBoostedTreeImpl.cc
This is a simple memory optimisation for regression and classification model training.
Since we limit the maximum tree size, we only need retain statistics for the maximum gain "max tree size" - "current tree size" leaves. Since we add one leaf statistic for each node we add to the tree we only ever need at most "maximum tree size" / 2 node statistics in total.
We use an upper bound for the leaf statistics memory estimates so this also indirectly helps improve our memory estimate accuracy and so helps with #1106. For example, this reduced estimates by around 25% testing.
> [ML] Eagerly discard node statistics for leaves which we will never split

- 3rd_party/3rd_party.sh
- build-setup/linux.md
- build-setup/linux_aarch64_cross_compiled.md
- build.gradle
- dev-tools/docker/build_linux_aarch64_cross_build_image.sh
- dev-tools/docker/build_linux_aarch64_native_build_image.sh
- dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
- dev-tools/docker/linux_aarch64_cross_image/Dockerfile
- dev-tools/docker/linux_aarch64_native_builder/Dockerfile
- dev-tools/docker/linux_aarch64_native_image/Dockerfile
- dev-tools/docker/linux_aarch64_native_tester/Dockerfile
- dev-tools/docker_build.sh
- dev-tools/docker_test.sh
- dev-tools/jenkins_ci.sh
- dev-tools/strip_binaries.sh
- docs/CHANGELOG.asciidoc
- mk/defines.mk
- mk/linux_crosscompile_linux.mk
- set_env.sh
- upload.gradle
Following on from #1132, this change adds:
1. The ability to cross compile a Linux build for aarch64 on
Linux on another hardware architecture
2. A Docker container for x86_64 that is set up for cross
compiling for aarch64
3. A Docker container for aarch64 that can both build and run
unit tests
4. Changes to CI scripts to utilise these Docker containers
where appropriate
> [ML] Add cross compilation support, Docker images and CI for aarch64

- bin/autodetect/Main.cc
- bin/categorize/Main.cc
- docs/CHANGELOG.asciidoc
- include/api/CAnomalyJob.h
- include/api/CFieldDataCategorizer.h
- lib/api/CAnomalyJob.cc
- lib/api/CFieldDataCategorizer.cc
- lib/api/dump_state/Main.cc
- lib/api/unittest/CAnomalyJobLimitTest.cc
- lib/api/unittest/CAnomalyJobTest.cc
- lib/api/unittest/CFieldDataCategorizerTest.cc
- lib/api/unittest/CForecastRunnerTest.cc
- lib/api/unittest/CMultiFileDataAdderTest.cc
- lib/api/unittest/COutputChainerTest.cc
- lib/api/unittest/CPersistenceManagerTest.cc
- lib/api/unittest/CRestorePreviousStateTest.cc
- lib/api/unittest/CSingleStreamDataAdderTest.cc
- lib/api/unittest/CStringStoreTest.cc
- lib/api/unittest/CTestAnomalyJob.cc
- lib/api/unittest/CTestAnomalyJob.h
- lib/api/unittest/CTestFieldDataCategorizer.cc
- lib/api/unittest/CTestFieldDataCategorizer.h
- lib/api/unittest/Makefile
Periodic persistence of categorizer state has not
worked since version 7.4.0.  This change makes it work
again.
Additionally, the persistence manager pointer argument
to the categorizer and anomaly detector classes is no
longer defaulted.  It can still be null, because it's
a major pain for unit tests to have to pass a real
persistence manager, but at least this must be
explicitly specified now, hopefully prompting anyone
who constructs such an object in production code to
pass a non-null persistence manager.
FIxes #1136
> [ML] Fix periodic persistence of categorizer state

- build.gradle
Some versions of Java report amd64 and i386 where most tools
would use x86_64 and x86.  These need to be normalized.
This should have been in #1135.  This PR is master only as for the
backport of #1135 I can incorporate this change before merging.
> [ML] Normalize hardware architecture from Java

- bin/autodetect/Main.cc
- bin/categorize/Main.cc
- docs/CHANGELOG.asciidoc
- include/api/CAnomalyJob.h
- include/api/CFieldDataCategorizer.h
- lib/api/CAnomalyJob.cc
- lib/api/CFieldDataCategorizer.cc
- lib/api/dump_state/Main.cc
- lib/api/unittest/CAnomalyJobLimitTest.cc
- lib/api/unittest/CAnomalyJobTest.cc
- lib/api/unittest/CFieldDataCategorizerTest.cc
- lib/api/unittest/CForecastRunnerTest.cc
- lib/api/unittest/CMultiFileDataAdderTest.cc
- lib/api/unittest/COutputChainerTest.cc
- lib/api/unittest/CPersistenceManagerTest.cc
- lib/api/unittest/CRestorePreviousStateTest.cc
- lib/api/unittest/CSingleStreamDataAdderTest.cc
- lib/api/unittest/CStringStoreTest.cc
- lib/api/unittest/CTestAnomalyJob.cc
- lib/api/unittest/CTestAnomalyJob.h
- lib/api/unittest/CTestFieldDataCategorizer.cc
- lib/api/unittest/CTestFieldDataCategorizer.h
- lib/api/unittest/Makefile
Periodic persistence of categorizer state has not
worked since version 7.4.0.  This change makes it work
again.
Additionally, the persistence manager pointer argument
to the categorizer and anomaly detector classes is no
longer defaulted.  It can still be null, because it's
a major pain for unit tests to have to pass a real
persistence manager, but at least this must be
explicitly specified now, hopefully prompting anyone
who constructs such an object in production code to
pass a non-null persistence manager.
Backport of #1137
> [7.x][ML] Fix periodic persistence of categorizer state

- 3rd_party/3rd_party.sh
- build-setup/linux.md
- build-setup/linux_aarch64_cross_compiled.md
- build.gradle
- dev-tools/docker/build_linux_aarch64_cross_build_image.sh
- dev-tools/docker/build_linux_aarch64_native_build_image.sh
- dev-tools/docker/linux_aarch64_cross_builder/Dockerfile
- dev-tools/docker/linux_aarch64_cross_image/Dockerfile
- dev-tools/docker/linux_aarch64_native_builder/Dockerfile
- dev-tools/docker/linux_aarch64_native_image/Dockerfile
- dev-tools/docker/linux_aarch64_native_tester/Dockerfile
- dev-tools/docker_build.sh
- dev-tools/docker_test.sh
- dev-tools/jenkins_ci.sh
- dev-tools/strip_binaries.sh
- docs/CHANGELOG.asciidoc
- mk/defines.mk
- mk/linux_crosscompile_linux.mk
- set_env.sh
- upload.gradle
Following on from #1134, this change adds:
1. The ability to cross compile a Linux build for aarch64 on
Linux on another hardware architecture
2. A Docker container for x86_64 that is set up for cross
compiling for aarch64
3. A Docker container for aarch64 that can both build and run
unit tests
4. Changes to CI scripts to utilise these Docker containers
where appropriate
Backport of #1135
> [7.x][ML] Add cross compilation support, Docker images and CI for aarch64

- include/maths/COutliers.h
- include/test/CDataFrameAnalyzerTrainingFactory.h
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/config/unittest/CReportWriterTest.cc
- lib/maths/COutliers.cc
- lib/maths/unittest/CMicTest.cc
- lib/maths/unittest/CMultivariateMultimodalPriorTest.cc
- lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
- lib/maths/unittest/CRandomizedPeriodicityTestTest.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
- lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
- lib/maths/unittest/CTrendComponentTest.cc
- lib/model/CResourceMonitor.cc
- lib/model/CRuleCondition.cc
- lib/model/unittest/CEventRatePopulationDataGathererTest.cc
- lib/model/unittest/CEventRatePopulationModelTest.cc
- lib/model/unittest/CSampleQueueTest.cc
This fixes warnings being generated by gcc I noticed while working on #1127. These are harmless and mainly `-Wconversion`.
> [ML] Silence gcc warnings

- docs/CHANGELOG.asciidoc
- lib/seccomp/CSystemCallFilter_MacOSX.cc
Two rules were missing:
1. We were blocking our own SIGIO signals used to wake up blocking
file reads.  (This is quite nasty as this functionality is only
used in edge cases.)
2. We were blocking the setpriority() calls made by nice().
I added the (debug deny) rule so that any blocked calls get logged
to the system console.  This makes it easier to see which rules are
required but missing.
I also changed the code style to match what our current style guide
says.
> [ML] Fix macOS sandbox rules

- lib/seccomp/CSystemCallFilter_MacOSX.cc
Two rules were missing:
1. We were blocking our own SIGIO signals used to wake up blocking
file reads.  (This is quite nasty as this functionality is only
used in edge cases.)
2. We were blocking the setpriority() calls made by nice().
I added the (debug deny) rule so that any blocked calls get logged
to the system console.  This makes it easier to see which rules are
required but missing.
I also changed the code style to match what our current style guide
says.
Backport of #1146
> [7.x][ML] Fix macOS sandbox rules

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
This PR fixes elastic/ml-team#337 which happens when the number of classes in the configuration differs from the number of recognized classes.
> [ML] Fix printing values for multiclass feature importance

- docs/CHANGELOG.asciidoc
- include/core/CIEEE754.h
- include/maths/CBoostedTreeLeafNodeStatistics.h
- include/maths/CLbfgs.h
- include/maths/CTools.h
- include/maths/CToolsDetail.h
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/core/CIEEE754.cc
- lib/maths/CBayesianOptimisation.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLeafNodeStatistics.cc
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/unittest/CBayesianOptimisationTest.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/CToolsTest.cc
> [7.8][ML] Reduce variability in regression and classification results across our target platforms

- include/api/CForecastRunner.h
- include/core/CSmallVector.h
- include/core/Concurrency.h
- include/maths/CDataFrameCategoryEncoder.h
- include/maths/CLinearAlgebraEigen.h
- lib/api/CForecastRunner.cc
- lib/core/CDataFrameRowSlice.cc
- lib/core/CStaticThreadPool.cc
- lib/maths/CDataFrameCategoryEncoder.cc
There are some places where we implement our own move operations which should be marked as `noexcept`. This allows the standard library to better optimise code with strong exception guaranties. There was also another place where we falling into the "can't move from a std::initialization_list" trap. Finally, `CRowRef` move is equivalent to a copy. Since it is 32 bytes we should instead prefer to pass this by constant reference when creating an encoded row.
> [ML] Some move related optimisations

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Fix classification job failures when number of classes in configuration differs from the number of classes present in the training data.
Backport to #1144.
> [7.x][ML] Fix printing values for multiclass feature importance 

- include/maths/CBoostedTreeLeafNodeStatistics.h
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLeafNodeStatistics.cc
- lib/maths/CBoostedTreeLoss.cc
Following on from #1125, we no longer need to recover memory inside `CBoostedTreeLeafNodeStatistics` for splits whose gain is less than zero. Dereferencing a row iterator has a cost and we should minimise the number of times we do it in performance sensitive code. Finally, a small refactor to suppress a variable shadowing warning.
> [ML] Boosted tree tidy ups

- include/core/CMemory.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/core/unittest/CDataFrameTest.cc
- lib/core/unittest/CMemoryUsageTest.cc
#1142 showed up that we weren't accounting for memory used by vector with a custom allocator. This is a pre-existing bug in memory estimation, but the aligned allocator was the first code to expose it. Since this is not released I've marked this as a non-issue.
> [ML] Fix memory usage estimation for vectors with a custom allocator

- docs/CHANGELOG.asciidoc
- lib/model/CEventRateModel.cc
- lib/model/CIndividualModel.cc
- lib/model/CMetricModel.cc
For sparse data with count and sum features (which assign zero values to empty buckets) we smoothly transition to modelling only values in non-empty buckets. This is important so we don't raise anomalies for every non-empty bucket. We also adjust the rate at which we decay out old data so the model isn't based on too little data.
This works fine for the residual distribution model, but the time dependent parts of the model decay out old data on a different schedule and can become unstable as a result. Normally, sparse data doesn't have significant time dependencies. However, this has caused problems when we no longer receive data for a time series. In these cases, it can result in spurious anomalies long after the last "real" data point was received.
This change makes the least intrusive …
> [ML] Improve stability of trend decomposition for very sparse data

- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Changes the way we report progress for data frame analytics
from a plain integer `progress_percent` to an object called
`phase_progress` which contains an integer `progress_percent`
and the `phase` name. In this commit we only have one phase
called `analyzing` but this change allows us to introduce new
phases.
> [ML] Report analytics progress as phase_progress

- build-setup/macos.md
11.3.1 is the highest version of Xcode that will work on Mojave
> Update Xcode version advice

- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Changes the way we report progress for data frame analytics
from a plain integer `progress_percent` to an object called
`phase_progress` which contains an integer `progress_percent`
and the `phase` name. In this commit we only have one phase
called `analyzing` but this change allows us to introduce new
phases.
Backport of #1159
> [7.x][ML] Report analytics progress as phase_progress (#1159)

- docs/CHANGELOG.asciidoc
- include/api/CFieldDataCategorizer.h
- include/model/CDataCategorizer.h
- include/model/CResourceMonitor.h
- include/model/CTokenListDataCategorizerBase.h
- lib/api/CBenchMarker.cc
- lib/api/CFieldDataCategorizer.cc
- lib/api/CModelSizeStatsJsonWriter.cc
- lib/api/unittest/CModelSnapshotJsonWriterTest.cc
- lib/model/CDataCategorizer.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
Anomaly detection jobs have a model_memory_limit setting.  This is
supposed to restrict the amount of memory the job can use, however,
in the past the limit only applied to anomaly detection and not to
categorization.
This change applies memory limiting to categorization as follows:
- When a job is in hard_limit status no new categories will be
created.  The input document that could not be categorized is
discarded as it cannot take part in anomaly detection without a
category.  The failed_category_count statistic is incremented
each time this happens.
- When a job is in soft_limit status, we stop recording examples
for the category.
Fixes #1130
> [ML] Limit categorization memory usage

- docs/CHANGELOG.asciidoc
- include/api/CFieldDataCategorizer.h
- include/model/CDataCategorizer.h
- include/model/CResourceMonitor.h
- include/model/CTokenListDataCategorizerBase.h
- lib/api/CBenchMarker.cc
- lib/api/CFieldDataCategorizer.cc
- lib/api/CModelSizeStatsJsonWriter.cc
- lib/api/unittest/CModelSnapshotJsonWriterTest.cc
- lib/model/CDataCategorizer.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
Anomaly detection jobs have a model_memory_limit setting.  This is
supposed to restrict the amount of memory the job can use, however,
in the past the limit only applied to anomaly detection and not to
categorization.
This change applies memory limiting to categorization as follows:
- When a job is in hard_limit status no new categories will be
created.  The input document that could not be categorized is
discarded as it cannot take part in anomaly detection without a
category.  The failed_category_count statistic is incremented
each time this happens.
- When a job is in soft_limit status, we stop recording examples
for the category.
Backport of #1167
> [7.x][ML] Limit categorization memory usage

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameAnalysisInstrumentation.h
- include/api/CDataFrameAnalyzer.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CDataFrameAnalysisInstrumentationInterface.h
- include/maths/CDataFrameCategoryEncoder.h
- include/maths/COutliers.h
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
- lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/COutliers.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/maths/unittest/COutliersTest.cc
This implements phased progress reporting for data frame analytics. I've extended `CDataFrameAnalysisInstrumentation` to support starting progress monitoring for named tasks. In order to ensure that we always send a phase complete result I also moved the progress writing out of `CDataFrameAnalyzer` into `CDataFrameAnalysisInstrumentation`. (This seems more natural anyway.)
> [ML] Multiphase progress reporting for data frame analyses

- devbin/state_search_splitter/Main.cc
- devbin/state_search_splitter/combine.sh
The version originally committed in #1180 was not the debugged
version.  Doh!
> Fix combine script used with search state splitter program

- devbin/state_search_splitter/Main.cc
- devbin/state_search_splitter/combine.sh
The version originally committed in #1180 was not the debugged
version.
Backport of #1184
> [7.x] Fix combine script used with search state splitter program

- lib/maths/CBoostedTreeImpl.cc
It is expected by Java. This is unreleased and related to #1179 so marking as a non-issue.
> [ML] Output progress for final training even if we don't have this step

- docs/CHANGELOG.asciidoc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/unittest/CBoostedTreeTest.cc
This was being reset when searching for the best learn rate. We were also missing a unit test that user overrides for hyperparameters are respected.
> [ML] Fix override of maximum permitted trees for classification and regression

- docs/CHANGELOG.asciidoc
- include/maths/CPeriodicityHypothesisTests.h
- lib/maths/CPeriodicityHypothesisTests.cc
- lib/maths/CTimeSeriesModel.cc
- lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
While investigating changes in our QA suite from #1158, I noticed, particularly for sparse data, the periodicity test generates false positives.
These turn out to be because of how we account for piecewise scaling of the periodic component. We allow piecewise linear scaling of the periodic component in the time window we test. However, we didn't directly impose a limit on the minimum number of repeats we require per scale. This change requires (as with unscaled periodicity testing) that we have at least three repeats *per* scale selected. I also took the opportunity to slightly rework the combination of soft conditions we check to make it clearer what is happening. 
The downside of detecting periodicity when none is present is that the model is generally less robust to anomalous …
> [ML] Reduce false positives for the periodic component test for anomaly detection

- docs/CHANGELOG.asciidoc
- include/maths/CBoostedTreeImpl.h
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
- lib/maths/CBoostedTreeImpl.cc
We add on a constant weight to "centre" the data. (Strictly speaking this isn't centring the data in the conventional sense, it is finding a single weight which when added to the ensemble prediction minimises the loss.)
Currently, we choose to minimise regularised loss with this weight, i.e. respecting the weight shrinkage. First, there is no need to do this, shrinkage is used to impose a "smoothness" bias, but a constant function is flat. Second, the subsequent trees spend effort updating the mean predictions to be unbiased and means there is an unfortunate interplay between the degree of smoothing we can use (since it will create bias in the unregularised loss) and the centre of the data.
> [ML] Add a constant to the prediction which minimises the unregularised loss for classification and regression

- docs/CHANGELOG.asciidoc
- include/model/CAnomalyDetectorModel.h
- include/model/CResourceMonitor.h
- lib/model/CResourceMonitor.cc
- lib/model/unittest/CResourceMonitorTest.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
We start pruning models when the memory used goes above the
prune threshold, and set the job's memory status to soft
limit at the same time.  If you close and reopen the job and
memory usage is lower than the prune threshold then we don't
prune and the memory limit is ok.  Prior to this change there
was a discrepancy where if you didn't close and reopen the
job but memory usage dropped below the prune threshold then
we continued to prune and left the memory status in soft
limit.
This change makes the case of not closing and reopening the
job more consistent.  If memory usage drops below the prune
threshold and the prune window expands to the default level
then we stop pruning and set the memory status back to ok.
Closes #1131
> [ML] Reset memory status from soft limit to ok below threshold

- lib/maths/unittest/CBoostedTreeTest.cc
The unit test CBoostedTreeTest/testPiecewiseConstant was
failing on Linux only.  This PR adjusts the test threshold
slightly.
(Also fixed a compiler warning.)
> Fix test threshold

- docs/CHANGELOG.asciidoc
- include/model/CAnomalyDetectorModel.h
- include/model/CResourceMonitor.h
- lib/model/CResourceMonitor.cc
- lib/model/unittest/CResourceMonitorTest.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
We start pruning models when the memory used goes above the
prune threshold, and set the job's memory status to soft
limit at the same time.  If you close and reopen the job and
memory usage is lower than the prune threshold then we don't
prune and the memory limit is ok.  Prior to this change there
was a discrepancy where if you didn't close and reopen the
job but memory usage dropped below the prune threshold then
we continued to prune and left the memory status in soft
limit.
This change makes the case of not closing and reopening the
job more consistent.  If memory usage drops below the prune
threshold and the prune window expands to the default level
then we stop pruning and set the memory status back to ok.
Backport of #1193
> [7.x][ML] Reset memory status from soft limit to ok below threshold

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameTrainBoostedTreeRegressionRunner.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CBoostedTreeLoss.h
- include/test/CDataFrameAnalysisSpecificationFactory.h
- include/test/CDataFrameAnalyzerTrainingFactory.h
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLoss.cc
- lib/maths/unittest/CBoostedTreeLossTest.cc
- lib/maths/unittest/CBoostedTreeTest.cc
- lib/test/CDataFrameAnalysisSpecificationFactory.cc
This PR implements Pseudo-Huber loss function and integrates it into the RegressionRunner. Since it has a parameter, I needed to reimplement the persist and restore functionality in order to be able to save the state of the loss functions (the same functionality is useful for MSLE and multiclass classification). I also did some refactoring of unit tests avoid code duplication.
Backport for #1168 and #1195
> [7.x][ML] Pseudo-Huber loss function 

- dev-tools/jenkins_ci.sh
PR builds will now fan out to workers that include an aarch64
worker.  But for old branches we cannot build on this architecture,
so just make such builds a no-op.
> Do nothing on aarch64 workers on old branches

- docs/CHANGELOG.asciidoc
- lib/maths/CPeriodicityHypothesisTests.cc
> [7.9][ML] Only remove discontinuities initialising seasonal components if they were part of the hypothesis we selected

- docs/CHANGELOG.asciidoc
- lib/maths/CPeriodicityHypothesisTests.cc
> [7.8][ML] Only remove discontinuities initialising seasonal components if they were part of the hypothesis we selected

- dev-tools/run_es_tests.sh
- lib/maths/unittest/CBoostedTreeTest.cc
The JDK directories on x86_64 are openjdk11, openjdk14, etc.
On aarch64 they're adoptopenjdk11, adoptopenjdk14, etc.
This change works around the difference.
Backport of #1204
> [7.x] Adjust JDK for running ES integration tests on aarch64

- dev-tools/run_es_tests.sh
- lib/maths/unittest/CBoostedTreeTest.cc
The JDK directories on x86_64 are openjdk11, openjdk14, etc.
On aarch64 they're adoptopenjdk11, adoptopenjdk14, etc.
This change works around the difference.
Backport of #1204
> [7.8] Adjust JDK for running ES integration tests on aarch64

- dev-tools/run_es_tests.sh
> Make ES integration tests work on reused Jenkins workers

- dev-tools/run_es_tests.sh
> [6.8] Make ES integration tests work on reused Jenkins workers

- dev-tools/run_es_tests.sh
> [7.8] Make ES integration tests work on reused Jenkins workers

- dev-tools/run_es_tests.sh
> [7.7] Make ES integration tests work on reused Jenkins workers

- dev-tools/run_es_tests.sh
> [7.x] Make ES integration tests work on reused Jenkins workers

- lib/core/unittest/CAlignmentTest.cc
Prior to gcc 9.3 there is a bug where alignas sometimes wrongly
caps alignment requests of more than 16 bytes at 16 bytes.
The old style alignment attribute does not suffer this problem so
the workaround is to use that instead.
This change will be reverted when we upgrade to gcc 9.3.
> [ML] Work around gcc alignas bug

- lib/core/unittest/CAlignmentTest.cc
Prior to gcc 9.3 there is a bug where alignas wrongly caps alignment
requests of more than 16 bytes at 16 bytes.
The old style alignment attribute does not suffer this problem so
the workaround is to use that instead.
This change will be reverted when we upgrade to gcc 9.3.
Backport of #1220
> [7.x][ML] Work around gcc alignas bug

- lib/core/unittest/CAlignmentTest.cc
Prior to gcc 9.3 there is a bug where alignas wrongly caps alignment
requests of more than 16 bytes at 16 bytes.
The old style alignment attribute does not suffer this problem so
the workaround is to use that instead.
This change will be reverted when we upgrade to gcc 9.3.
Backport of #1220
> [7.8][ML] Work around gcc alignas bug

- include/maths/CBoostedTreeLoss.h
- lib/maths/CBoostedTreeLoss.cc
While adding the additional function parameter in #1168, I wired it in the constructor of the MSLE loss function, but not in the computation of the objective. This PR fixes this, it basically substitutes log(1+x) by log(offset+x) in many different places.
I mark it as a non-issue since the MSLE loss function was not released yet.
Backport of #1200
> [7.x][ML] Add offset in the MSLE computation 

- include/maths/CBoostedTreeLoss.h
- lib/maths/CBoostedTreeLoss.cc
While adding the additional function parameter in #1168, I wired it in the constructor of the MSLE loss function, but not in the computation of the objective. This PR fixes this, it basically substitutes log(1+x) by log(offset+x) in many different places.
I mark it as a non-issue since the MSLE loss function was not released yet.
Backport of #1200
> [7.8][ML] Add offset in the MSLE computation 

- lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
Fix an intermittent test failure.
The concurrent queue doesn't guaranty the order messages are written out so we can only asset that each phase gets a 100% complete message not that it is also the last message.
> [ML] Fix flakey progress monitoring test

- docs/CHANGELOG.asciidoc
- lib/maths/CAdaptiveBucketing.cc
- lib/maths/CCalendarComponentAdaptiveBucketing.cc
- lib/maths/CTimeSeriesDecomposition.cc
Following on from #1114, there are a couple of places where we have code which could in theory generate 0/0. These would be a candidate root cause for #364 along with #1157.
This should generally have no impact on results until we'd actually hit the problem case.
> [ML] Fix possible cause for "Bad variance scale nan" log errors

- include/core/CNamedPipeFactory.h
- lib/core/CLogger.cc
- lib/core/CNamedPipeFactory.cc
- lib/core/CNamedPipeFactory_Windows.cc
The warning if something stops SIGPIPE being ignored has
always been deferred as the signal calls are made before
main() has run.  However, the place the warning was deferred
to could result in it being logged many times because the
deferred logging was in a method that could be called many
times.
This change moves that deferred logging to a dedicated
method that can just be called once.
> [ML] Only log failure to ignore SIGPIPE once

- lib/maths/CDataFrameUtils.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
This is a correction for #1113.
We were computing the objective on the full training set rather than the sampled mask. Normally this is fine, since we use a stratified sample it basically acts like a constant scaling of the objective. However, when there is very little training data we can run into problems (such as a class missing in the sample set which is present in the training set). It also means this code is much slower than intended on very large data sets.
Change #1113 hasn't been released so I've marked this as a non-issue, but it must go out at the same time in 7.8.
> [ML] Fix weights to maximize minimum recall for multiclass classification

- include/core/CNamedPipeFactory.h
- lib/core/CLogger.cc
- lib/core/CNamedPipeFactory.cc
- lib/core/CNamedPipeFactory_Windows.cc
The warning if something stops SIGPIPE being ignored has
always been deferred as the signal calls are made before
main() has run.  However, the place the warning was deferred
to could result in it being logged many times because the
deferred logging was in a method that could be called many
times.
This change moves that deferred logging to a dedicated
method that can just be called once.
Backport of #1221
> [7.x][ML] Only log failure to ignore SIGPIPE once

- include/core/CNamedPipeFactory.h
- lib/core/CLogger.cc
- lib/core/CNamedPipeFactory.cc
- lib/core/CNamedPipeFactory_Windows.cc
The warning if something stops SIGPIPE being ignored has
always been deferred as the signal calls are made before
main() has run.  However, the place the warning was deferred
to could result in it being logged many times because the
deferred logging was in a method that could be called many
times.
This change moves that deferred logging to a dedicated
method that can just be called once.
Backport of #1221
> [7.8][ML] Only log failure to ignore SIGPIPE once

- lib/maths/CDataFrameUtils.cc
- lib/maths/unittest/CDataFrameUtilsTest.cc
> [7.9][ML] Fix weights to maximize minimum recall for multiclass classification

- bin/autodetect/Main.cc
- bin/categorize/Main.cc
- docs/CHANGELOG.asciidoc
- include/api/CAnomalyJob.h
- include/api/CFieldDataCategorizer.h
- lib/api/CAnomalyJob.cc
- lib/api/CFieldDataCategorizer.cc
- lib/api/dump_state/Main.cc
- lib/api/unittest/CAnomalyJobLimitTest.cc
- lib/api/unittest/CAnomalyJobTest.cc
- lib/api/unittest/CFieldDataCategorizerTest.cc
- lib/api/unittest/CForecastRunnerTest.cc
- lib/api/unittest/CMultiFileDataAdderTest.cc
- lib/api/unittest/COutputChainerTest.cc
- lib/api/unittest/CPersistenceManagerTest.cc
- lib/api/unittest/CRestorePreviousStateTest.cc
- lib/api/unittest/CSingleStreamDataAdderTest.cc
- lib/api/unittest/CStringStoreTest.cc
- lib/api/unittest/CTestAnomalyJob.cc
- lib/api/unittest/CTestAnomalyJob.h
- lib/api/unittest/CTestFieldDataCategorizer.cc
- lib/api/unittest/CTestFieldDataCategorizer.h
- lib/api/unittest/Makefile
Periodic persistence of categorizer state has not
worked since version 7.4.0.  This change makes it work
again.
Additionally, the persistence manager pointer argument
to the categorizer and anomaly detector classes is no
longer defaulted.  It can still be null, because it's
a major pain for unit tests to have to pass a real
persistence manager, but at least this must be
explicitly specified now, hopefully prompting anyone
who constructs such an object in production code to
pass a non-null persistence manager.
Backport of #1137
> [7.7][ML] Fix periodic persistence of categorizer state

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
Fix classification job failures when number of classes in configuration differs from the number of classes present in the training data.
Backport to #1144
> [7.7][ML] Fix printing values for multiclass feature importance

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
- lib/core/CTimeUtils.cc
This PR changes the resolution of the timestamps from seconds to milliseconds. This fixes #1234
> [7.8][ML] Fix timestamp issue for instrumentation 

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
- lib/core/CTimeUtils.cc
This PR changes the resolution of the timestamps from seconds to milliseconds. This fixes #1234
> [7.x][ML] Fix timestamp issue for instrumentation

- docs/CHANGELOG.asciidoc
- include/maths/CTimeSeriesDecompositionDetail.h
- lib/maths/CTimeSeriesDecomposition.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/CTimeSeriesModel.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
This would manifest as a `autodetect process stopped unexpectedly: Fatal error: 'terminate called after throwing an instance of 'std::bad_function_call'` error. The issue was introduced in 7.2.
The problem was we were using a callback before it was set. This makes sure that the callback is always set (as a no-op if one isn't provided) and attaches it as the first action in `CTimeSeriesDecomposition::addPoint` and resets it again afterwards. Not reseting it is also a bad idea since it would keep around a reference to a stack variable.
Fixes #1245.
> [ML] Fix bad function call exception in anomaly detection

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
- lib/core/CTimeUtils.cc
This PR changes the resolution of the timestamps from seconds to milliseconds. This fixes #1234
> [7.7][ML] Fix timestamp issue for instrumentation

- lib/maths/CDataFrameUtils.cc
This is a follow on from #1231.
We were still running into problems if the Java doesn't sample a class at all in the training data. This points to a problem with the stratified sampling implementation in Java, but we need to make the weight calculation defensive.
Since this is a correction to change #1113, which hasn't been released, I've marked this as a non-issue, but it must go out at the same time in 7.8.
> [ML] Fix weights to maximize minimum recall for multiclass classification when the training data is missing classes

- include/model/CCountingModelFactory.h
- include/model/CEventRateModelFactory.h
- include/model/CEventRatePopulationModelFactory.h
- include/model/CMetricModelFactory.h
- include/model/CMetricPopulationModelFactory.h
- include/model/CModelFactory.h
- include/model/CSearchKey.h
- lib/api/CAnomalyJob.cc
- lib/model/CAnomalyDetectorModelConfig.cc
- lib/model/CCountingModelFactory.cc
- lib/model/CEventRateModelFactory.cc
- lib/model/CEventRatePopulationModelFactory.cc
- lib/model/CMetricModelFactory.cc
- lib/model/CMetricPopulationModelFactory.cc
- lib/model/CSearchKey.cc
- lib/model/unittest/CEventRateModelTest.cc
- lib/model/unittest/CEventRatePopulationModelTest.cc
- lib/model/unittest/CMetricModelTest.cc
- lib/model/unittest/CMetricPopulationModelTest.cc
- lib/model/unittest/CResourceLimitTest.cc
- Rename identifier to detectorIndex so that the naming is consistent between C++ and Java  (#1251)
> [7.x] Rename identifier to detectorIndex so that the naming is consistent between C++ and Java (#1251)

- dev-tools/run_es_tests.sh
Having the CDS archive enabled on aarch64 was observed to cause an
error in the Gradle used for the ES integration tests:
```
[0.003s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 65536 actual: 4096
```
> [ML] Switch off CDS archive for ES test Gradle on aarch64

- 3rd_party/licenses/boost-INFO.csv
- 3rd_party/licenses/eigen-INFO.csv
- 3rd_party/licenses/gcc-runtime-INFO.csv
- 3rd_party/licenses/libxml2-INFO.csv
- 3rd_party/licenses/moby-INFO.csv
- 3rd_party/licenses/msinttypes-INFO.csv
- 3rd_party/licenses/rapidjson-INFO.csv
- 3rd_party/licenses/rapidxml-INFO.csv
- 3rd_party/licenses/scowl-INFO.csv
- 3rd_party/licenses/strptime-INFO.csv
- 3rd_party/licenses/visualstudio2017-INFO.csv
- 3rd_party/licenses/zlib-INFO.csv
> [ML] Add source URL to 3rd party info when we have to say how to get it

- dev-tools/run_es_tests.sh
Having the CDS archive enabled on aarch64 was observed to cause an
error in the Gradle used for the ES integration tests:
```
[0.003s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 65536 actual: 4096
```
Backport of #1257
> [7.8][ML] Switch off CDS archive for ES test Gradle on aarch64

- 3rd_party/licenses/apr-INFO.csv
- 3rd_party/licenses/apr-iconv-INFO.csv
- 3rd_party/licenses/apr-util-INFO.csv
- 3rd_party/licenses/boost-INFO.csv
- 3rd_party/licenses/eigen-INFO.csv
- 3rd_party/licenses/gcc-runtime-INFO.csv
- 3rd_party/licenses/libxml2-INFO.csv
- 3rd_party/licenses/log4cxx-INFO.csv
- 3rd_party/licenses/moby-INFO.csv
- 3rd_party/licenses/msinttypes-INFO.csv
- 3rd_party/licenses/rapidjson-INFO.csv
- 3rd_party/licenses/rapidxml-INFO.csv
- 3rd_party/licenses/scowl-INFO.csv
- 3rd_party/licenses/strptime-INFO.csv
- 3rd_party/licenses/visualstudio2013express-INFO.csv
- 3rd_party/licenses/zlib-INFO.csv
> [6.8][ML] Add source URL to 3rd party info when we have to say how to get it

- 3rd_party/licenses/boost-INFO.csv
- 3rd_party/licenses/eigen-INFO.csv
- 3rd_party/licenses/gcc-runtime-INFO.csv
- 3rd_party/licenses/libxml2-INFO.csv
- 3rd_party/licenses/moby-INFO.csv
- 3rd_party/licenses/msinttypes-INFO.csv
- 3rd_party/licenses/rapidjson-INFO.csv
- 3rd_party/licenses/rapidxml-INFO.csv
- 3rd_party/licenses/scowl-INFO.csv
- 3rd_party/licenses/strptime-INFO.csv
- 3rd_party/licenses/visualstudio2017-INFO.csv
- 3rd_party/licenses/zlib-INFO.csv
> [7.7][ML] Add source URL to 3rd party info when we have to say how to get it

- 3rd_party/licenses/boost-INFO.csv
- 3rd_party/licenses/eigen-INFO.csv
- 3rd_party/licenses/gcc-runtime-INFO.csv
- 3rd_party/licenses/libxml2-INFO.csv
- 3rd_party/licenses/moby-INFO.csv
- 3rd_party/licenses/msinttypes-INFO.csv
- 3rd_party/licenses/rapidjson-INFO.csv
- 3rd_party/licenses/rapidxml-INFO.csv
- 3rd_party/licenses/scowl-INFO.csv
- 3rd_party/licenses/strptime-INFO.csv
- 3rd_party/licenses/visualstudio2017-INFO.csv
- 3rd_party/licenses/zlib-INFO.csv
> [7.8][ML] Add source URL to 3rd party info when we have to say how to get it

- 3rd_party/licenses/boost-INFO.csv
- 3rd_party/licenses/eigen-INFO.csv
- 3rd_party/licenses/gcc-runtime-INFO.csv
- 3rd_party/licenses/libxml2-INFO.csv
- 3rd_party/licenses/moby-INFO.csv
- 3rd_party/licenses/msinttypes-INFO.csv
- 3rd_party/licenses/rapidjson-INFO.csv
- 3rd_party/licenses/rapidxml-INFO.csv
- 3rd_party/licenses/scowl-INFO.csv
- 3rd_party/licenses/strptime-INFO.csv
- 3rd_party/licenses/visualstudio2017-INFO.csv
- 3rd_party/licenses/zlib-INFO.csv
> [7.x][ML] Add source URL to 3rd party info when we have to say how to get it

- dev-tools/run_es_tests.sh
Having the CDS archive enabled on aarch64 was observed to cause an
error in the Gradle used for the ES integration tests:
```
[0.003s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 65536 actual: 4096
```
Backport of #1257
> [7.x][ML] Switch off CDS archive for ES test Gradle on aarch64

- lib/maths/CSignal.cc
This was returning NaNs before. Given our usage, it was harmless (and so I've marked this as a non-issue), but it's dangerous.
I also adjusted this file to match our current coding style guidelines.
> [ML] Special case handling for autocorrelation of a constant

- include/api/CAnomalyJob.h
- include/model/CAnomalyDetector.h
- include/model/CAnomalyDetectorModel.h
- include/model/CSimpleCountDetector.h
- lib/api/CAnomalyJob.cc
- lib/api/unittest/CAnomalyJobLimitTest.cc
- lib/model/CAnomalyDetector.cc
- lib/model/CAnomalyDetectorModel.cc
- lib/model/CSearchKey.cc
- lib/model/CSimpleCountDetector.cc
- lib/model/unittest/CEventRateAnomalyDetectorTest.cc
- lib/model/unittest/CMetricAnomalyDetectorTest.cc
- lib/model/unittest/CResourceLimitTest.cc
- lib/model/unittest/CResourceMonitorTest.cc
Currently `CAnomalyDetector` gets the `detectorIndex` in the constructor.
It is not necessary though as the detector index can be always obtained by going to `detector.model.gatherer.searchKey.detectorIndex`.
This PR removes `detectorIndex` from the `CAnomalyDetector`'s  constructor parameter list.
> Do not pass detectorIndex to CAnomalyDetector

- include/api/CAnomalyJob.h
- include/model/CAnomalyDetector.h
- include/model/CAnomalyDetectorModel.h
- include/model/CSimpleCountDetector.h
- lib/api/CAnomalyJob.cc
- lib/api/unittest/CAnomalyJobLimitTest.cc
- lib/model/CAnomalyDetector.cc
- lib/model/CAnomalyDetectorModel.cc
- lib/model/CSearchKey.cc
- lib/model/CSimpleCountDetector.cc
- lib/model/unittest/CEventRateAnomalyDetectorTest.cc
- lib/model/unittest/CMetricAnomalyDetectorTest.cc
- lib/model/unittest/CResourceLimitTest.cc
- lib/model/unittest/CResourceMonitorTest.cc
- Do not pass detectorIndex to CAnomalyDetector  (#1259)
> [7.x] Do not pass detectorIndex to CAnomalyDetector (#1259)

- include/maths/CAdaptiveBucketing.h
- include/maths/CLeastSquaresOnlineRegression.h
- include/maths/CLeastSquaresOnlineRegressionDetail.h
- include/maths/CSeasonalComponent.h
- include/maths/CSeasonalComponentAdaptiveBucketing.h
- lib/api/unittest/CAnomalyJobLimitTest.cc
- lib/maths/CAdaptiveBucketing.cc
- lib/maths/CPeriodicityHypothesisTests.cc
- lib/maths/CSeasonalComponent.cc
- lib/maths/CSeasonalComponentAdaptiveBucketing.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/unittest/CCalendarComponentAdaptiveBucketingTest.cc
- lib/maths/unittest/CForecastTest.cc
- lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc
- lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.cc
- lib/maths/unittest/CSeasonalComponentTest.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
- lib/model/unittest/CEventRateModelTest.cc
- lib/model/unittest/CMetricModelTest.cc
This makes a couple of enhancements aimed at #1202.
In particular, we track where anomalies occur for each seasonal component and increase the rate at which we learn from them if there is strong evidence they're occurring periodically. However, we were only doing this for shorter bucket lengths, meaning we could take much longer than intended to adapt for long buckets.
This also reworks mean reversion of seasonal components to be have a continuous parameterisation. Together with how quickly we adjust the position of the local regression model and how quickly we age out old data, this gives us three parameters which control how fast we'll adapt to changes and stability. I did a grid search over these parameters for a range of different QA data sets and chose the values to with the best …
> [ML] Improve time series decomposition adaption

- docs/CHANGELOG.asciidoc
The original release note omitted to mention that the feature
is only implemented for Linux and macOS.
Relates #1109
> [DOCS] Adjust release note for reduced process priority

- docs/CHANGELOG.asciidoc
- include/core/CPersistUtils.h
- include/maths/CChecksum.h
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/core/CStringUtils.cc
- lib/core/unittest/CJsonStatePersistInserterTest.cc
- lib/core/unittest/CPersistUtilsTest.cc
- lib/core/unittest/CRapidXmlStatePersistInserterTest.cc
- lib/core/unittest/CStringUtilsTest.cc
- lib/model/unittest/CAnomalyScoreTest.cc
- lib/model/unittest/CSampleQueueTest.cc
Following on from #1197, this reworks persistence to not lose precision.
Since we chunk and compress state when persisting, using sufficient decimal places to not lose precision doesn't cost us much in terms of model size, and persisting and restoring state is not a performance bottleneck. 
This has the nice property that we can test restore from state produces the same results much more stably, so I simplified and extended `testRunBoostedTreeRegressionTrainingWithStateRecovery` accordingly.
I also took the opportunity to tidy up `CPersistUtils` and in particular fix violations of our coding guidelines.
This affects results for both anomaly detection and data frame analyses, but only after restoring from state.
> [ML] Don't lose precision when persisting state

- docs/CHANGELOG.asciidoc
- include/api/CForecastRunner.h
- include/model/CResourceMonitor.h
- lib/api/CForecastRunner.cc
- lib/api/unittest/CForecastRunnerTest.cc
- lib/model/CResourceMonitor.cc
This commit adds new parameter max_model_memory.
This parameter is defaulted to `20mb` (the previous static setting). 
Some larger forecasts can take a very long time to run. But if a user
has enough memory, they may opt to run more of the forecast in memory
without spooling to disk.
elasticsearch change https://github.com/elastic/elasticsearch/pull/57254
> Adding forecast parameter max_model_memory 

- include/api/CForecastRunner.h
- lib/api/CForecastRunner.cc
The default value is passed to boost::property_tree::ptree::get() as
a reference, which requires taking the address of it.  The new
DEFAULT_MAX_FORECAST_MODEL_MEMORY constant in CForecastRunner was
defined in the class declaration, which means its address cannot be
taken.
This PR moves the definition of DEFAULT_MAX_FORECAST_MODEL_MEMORY
outside of the CForecastRunner class declaration so that its address
can be taken.
We got away with this in optimised builds with the latest compilers
due to inlining and dead code elimination, but in debug builds we
don't.
(I also added a few std:: prefixes to move towards the latest code
style.)
> [ML] Fix debug build

- docs/CHANGELOG.asciidoc
- include/api/CForecastRunner.h
- include/model/CResourceMonitor.h
- lib/api/CForecastRunner.cc
- lib/api/unittest/CForecastRunnerTest.cc
- lib/model/CResourceMonitor.cc
This commit adds new parameter max_model_memory.
This parameter is defaulted to `20mb` (the previous static setting).
Some larger forecasts can take a very long time to run. But if a user
has enough memory, they may opt to run more of the forecast in memory
without spooling to disk.
elasticsearch change https://github.com/elastic/elasticsearch/pull/57254
> [7.x] Adding forecast parameter max_model_memory  (#1238)

- docs/CHANGELOG.asciidoc
- include/core/Concurrency.h
- include/maths/CTreeShapFeatureImportance.h
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CTreeShapFeatureImportance.cc
- lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
We can split the work to compute feature importance up over the trees in the forest since we just sum up the per tree feature importances at the end.
In order to do this, I needed to expose an interface to `parallel_for_each` which takes a list of functions to run on subsets of the iterator range because we use member variables for the algorithm state to avoid reallocating for each training example, which I need to bind to each function upfront.
> [ML] Parallelise the feature importance calculation for classification and regression over trees

- include/core/Concurrency.h
- include/maths/CBoostedTreeLoss.h
- lib/core/unittest/CImmutableRadixSetTest.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
We still have a few gcc warnings mainly about type coercion. This silences those and also corrects a couple of comment typos.
> [ML] Silence some gcc warnings

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameAnalysisInstrumentation.h
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/COutliers.cc
This PR adds memory usage report in two new cases:
1) right after data frame is loaded in the `DataFrameAnalyzer`
2) in the initialization routines on `CBoostedTreeFactory` when memory usage is updated
Closes #1282
> [ML] Report memory usage during DFA job initialization

- include/core/Constants.h
- include/maths/CPeriodicityHypothesisTests.h
- include/maths/CTimeSeriesDecompositionDetail.h
- lib/maths/CPeriodicityHypothesisTests.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/unittest/CTimeSeriesDecompositionTest.cc
There is a short window and a long window to test for "fast" and "slow" seasonal components, respectively. Currently, these are not particularly well parameterised as a function of the job's bucket length: 
1. The parameterisation isn't tuned for very short or long job bucket lengths. This can degrade both the speed with which seasonality is detected and increase error in the components' estimated periods.
2. The window bucket lengths aren't a multiple of the job's bucket length for all the common cases. This causes beating in the assignment of values to buckets which can degrade detection and lead to poor component initialisation. 
3. There is redundancy: the sets of bucket lengths the two windows use "intersect"; this wastes time by running the same tests for both the short and long …
> [ML] Improve seasonal component test parameterisation

- docs/CHANGELOG.asciidoc
- include/core/CPersistUtils.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeImpl.h
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
Searching for initial parameters for boosted tree training is an expensive operation and it is possible to save state to allow this to resume with minimal loss of work. This PR adds checkpointing of sufficient state to resume after failure during this step. It also makes some tweaks to `CPersistUtils`. These include moving values into place where possible and adding some convenience functions to persist pointers.
The basic strategy is to introduce an initialisation stage variable to `CBoostedTreeImpl`. This tracks where initialisation reached at each checkpoint, so that it is possible to resume, skipping stages which have already been performed. It is necessary to additionally persist and restore some factory state.
Closes #1275.
> [ML] Add state checkpoints during coarse parameter search for classification and regression

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameAnalysisInstrumentation.h
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/COutliers.cc
This PR adds memory usage report in two new cases:
right after data frame is loaded in the DataFrameAnalyzer
in the initialization routines on CBoostedTreeFactory when memory usage is updated
Backport to #1294
> [ML] Report memory usage during DFA job initialization (#1294)

- docs/CHANGELOG.asciidoc
- include/maths/CBoostedTreeImpl.h
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CSampling.cc
- lib/maths/unittest/CSamplingTest.cc
The feature derivatives for boosted tree splits are laid out in increasing feature index order, but when we sample a feature bag we don't ensure it is sorted. This means we are getting random access rather than linear scan over the derivatives when computing the best split. This switches to sorting the feature bag after sampling and rejigs the function signatures to avoid allocating a vector for every node.
> [ML] Improve data access pattern computing best splits for classification and regression

- bin/controller/CBlockingCallCancellerThread.cc
- bin/controller/CBlockingCallCancellerThread.h
- bin/controller/Main.cc
- bin/controller/unittest/CBlockingCallCancellerThreadTest.cc
- docs/CHANGELOG.asciidoc
- include/core/CLogger.h
- include/core/CNamedPipeFactory.h
- lib/api/CIoManager.cc
- lib/core/CLogger.cc
- lib/core/CNamedPipeFactory.cc
- lib/core/CNamedPipeFactory_Windows.cc
- lib/core/CThread.cc
- lib/core/unittest/CNamedPipeFactoryTest.cc
- lib/seccomp/unittest/CSystemCallFilterTest.cc
This change fixes two related issues with named pipe connection
when the controller process first starts up:
1. If the ES JVM dies before the controller connects its logging
named pipe then since elastic/elasticsearch#56491 the resulting
errors from the controller process will be seen in the ES
stderr file.  There is a change to the logging to make it
clearer that the controller didn't fail, but exited due to
the ES JVM disappearing.
2. Interrupted system calls while connecting the named pipes
could cause the pipes to unnecessarily fail to connect.  There
is a change to retry the calls on getting an EINTR error unless
the interrupt was caused by the functionality of controller
that kills off the connection attempts if the ES JVM dies (i.e.
the scenario described in point 1).
Backport of …
> [7.x][ML] Better interrupt handling during named pipe connection

- bin/controller/CBlockingCallCancellerThread.cc
- bin/controller/CBlockingCallCancellerThread.h
- bin/controller/Main.cc
- bin/controller/unittest/CBlockingCallCancellerThreadTest.cc
- docs/CHANGELOG.asciidoc
- include/core/CLogger.h
- include/core/CNamedPipeFactory.h
- lib/api/CIoManager.cc
- lib/core/CLogger.cc
- lib/core/CNamedPipeFactory.cc
- lib/core/CNamedPipeFactory_Windows.cc
- lib/core/CThread.cc
- lib/core/unittest/CNamedPipeFactoryTest.cc
- lib/seccomp/Makefile
- lib/seccomp/unittest/CSystemCallFilterTest.cc
This change fixes two related issues with named pipe connection
when the controller process first starts up:
1. If the ES JVM dies before the controller connects its logging
named pipe then since elastic/elasticsearch#56491 the resulting
errors from the controller process will be seen in the ES
stderr file.  There is a change to the logging to make it
clearer that the controller didn't fail, but exited due to
the ES JVM disappearing.
2. Interrupted system calls while connecting the named pipes
could cause the pipes to unnecessarily fail to connect.  There
is a change to retry the calls on getting an EINTR error unless
the interrupt was caused by the functionality of controller
that kills off the connection attempts if the ES JVM dies (i.e.
the scenario described in point 1).
Backport of …
> [6.8][ML] Better interrupt handling during named pipe connection

- bin/controller/CBlockingCallCancellerThread.cc
- bin/controller/CBlockingCallCancellerThread.h
- bin/controller/Main.cc
- bin/controller/unittest/CBlockingCallCancellerThreadTest.cc
- docs/CHANGELOG.asciidoc
- include/core/CLogger.h
- include/core/CNamedPipeFactory.h
- lib/api/CIoManager.cc
- lib/core/CLogger.cc
- lib/core/CNamedPipeFactory.cc
- lib/core/CNamedPipeFactory_Windows.cc
- lib/core/CThread.cc
- lib/core/unittest/CNamedPipeFactoryTest.cc
- lib/seccomp/unittest/CSystemCallFilterTest.cc
This change fixes two related issues with named pipe connection
when the controller process first starts up:
1. If the ES JVM dies before the controller connects its logging
named pipe then since elastic/elasticsearch#56491 the resulting
errors from the controller process will be seen in the ES
stderr file.  There is a change to the logging to make it
clearer that the controller didn't fail, but exited due to
the ES JVM disappearing.
2. Interrupted system calls while connecting the named pipes
could cause the pipes to unnecessarily fail to connect.  There
is a change to retry the calls on getting an EINTR error unless
the interrupt was caused by the functionality of controller
that kills off the connection attempts if the ES JVM dies (i.e.
the scenario described in point 1).
Backport of …
> [7.8][ML] Better interrupt handling during named pipe connection

- docs/CHANGELOG.asciidoc
- include/core/CDataFrame.h
- include/core/CImmutableRadixSet.h
- include/core/CPackedBitVector.h
- include/core/Concurrency.h
- include/maths/CBoostedTreeImpl.h
- include/maths/CBoostedTreeLeafNodeStatistics.h
- include/maths/CBoostedTreeUtils.h
- include/maths/CDataFrameCategoryEncoder.h
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/core/CDataFrame.cc
- lib/core/CPackedBitVector.cc
- lib/core/unittest/CConcurrencyTest.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLeafNodeStatistics.cc
- lib/maths/CBoostedTreeUtils.cc
- lib/maths/CDataFrameCategoryEncoder.cc
- lib/maths/CDataFrameUtils.cc
- lib/maths/unittest/CBoostedTreeTest.cc
Testing showed up we are often I/O bound during boosted tree training on larger data sets. This change introduces a placeholder for the large aggregate derivatives objects which is allocated once upfront at the start of training a forest. This is particularly relevant for running multithreaded because we use one copy of this data per thread. In order to do this it was necessary to change the `CDataFrame` interface to take in a vector of functions to bind to each task so the placeholders can be bound by reference.
We also now pass in information about the minimum gain of a node that we'll keep. This allows us to lazily create storage for these and avoid some work if they aren't needed. 
Testing also showed up degraded performance running multi-threaded when the thread count was set too …
> [ML] Threading speedups for classification and regression

- include/api/CDataFrameAnalysisRunner.h
- include/api/CForecastRunner.h
- include/core/CDualThreadStreamBuf.h
- include/core/CLogger.h
- include/core/CTimeUtils.h
- include/core/CWordDictionary.h
- lib/api/CForecastRunner.cc
- lib/core/CDualThreadStreamBuf.cc
- lib/core/CLogger.cc
- lib/core/CTimeUtils.cc
- lib/core/CWordDictionary.cc
There were a few places in the code where we were inappropriately
using the volatile keyword.  Some of these should have been using
atomics, and others were simply unnecessary.
Additionally, the "magic statics" feature of C++11 finally made it
into Visual Studio 2015.  We were using Visual Studio 2013 in 5.x
and 6.x, so could not use this feature.  However, 7.x is using
Visual Studio 2017, so we can adapt our code to take advantage of
automatic protection of static variable initialisation instead of
having to write custom code for this.
> [ML] Remove volatile and update thread-safe static initialisation

- lib/maths/CMultimodalPrior.cc
Fix the last fallout from #1268 by more aggressively expanding the initial bracket interval: we were running into issues when this was very initialised narrow. Also, I decided to downgrade the error to a warning. It should generate a notification, since it can affect the model plot and exception handling mechanism is expensive, but it doesn't affect anomaly detection quality so I don't think this should be raised at error. As before this is a non-issue since #1268 isn't released.
> [ML] Fix "Unable to compute percentiles: doesn't bracket root..." log errors (part 2)

- 3rd_party/licenses/moby-INFO.csv
The website we got Moby from has been taken down, but it's still
referenced in the internet archive.
> [ML] Adjust 3rd party info for Moby

- include/api/CDataFrameAnalysisRunner.h
- include/api/CForecastRunner.h
- include/core/CDualThreadStreamBuf.h
- include/core/CLogger.h
- include/core/CTimeUtils.h
- include/core/CWordDictionary.h
- lib/api/CForecastRunner.cc
- lib/core/CDualThreadStreamBuf.cc
- lib/core/CLogger.cc
- lib/core/CTimeUtils.cc
- lib/core/CWordDictionary.cc
There were a few places in the code where we were inappropriately
using the volatile keyword.  Some of these should have been using
atomics, and others were simply unnecessary.
Additionally, the "magic statics" feature of C++11 finally made it
into Visual Studio 2015.  We were using Visual Studio 2013 in 5.x
and 6.x, so could not use this feature.  However, 7.x is using
Visual Studio 2017, so we can adapt our code to take advantage of
automatic protection of static variable initialisation instead of
having to write custom code for this.
Backport of #1323
> [7.x][ML] Remove volatile and update thread-safe static initialisation

- 3rd_party/licenses/moby-INFO.csv
The website we got Moby from has been taken down, but it's still
referenced in the internet archive.
Backport of #1331
> [7.x][ML] Adjust 3rd party info for Moby

- 3rd_party/licenses/moby-INFO.csv
The website we got Moby from has been taken down, but it's still
referenced in the internet archive.
Backport of #1331
> [7.8][ML] Adjust 3rd party info for Moby

- 3rd_party/licenses/moby-INFO.csv
The website we got Moby from has been taken down, but it's still
referenced in the internet archive.
Backport of #1331
> [6.8][ML] Adjust 3rd party info for Moby

- include/core/CStringUtils.h
- lib/core/CStringUtils.cc
- lib/core/unittest/CStringUtilsTest.cc
This PR adds a utility to compute the length of a UTF-16 encoded string. This functionality is needed to improve compatibility with Java.
Since it's not a user-facing functionality, I mark it as a non-issue.
> [ML] UTF-16 String length computation

- include/api/CFieldConfig.h
- include/core/CDataFrameRowSlice.h
- include/maths/CAdaptiveBucketing.h
- include/maths/CBjkstUniqueValues.h
- include/maths/CCountMinSketch.h
- include/maths/CDecompositionComponent.h
- include/maths/CKMeansOnline.h
- include/maths/CLassoLogisticRegression.h
- include/maths/CMultinomialConjugate.h
- include/maths/CMultivariatePrior.h
- include/maths/CPrior.h
- include/model/CAnnotatedProbability.h
- include/model/CHierarchicalResults.h
- include/model/CSearchKey.h
- lib/api/CFieldConfig.cc
- lib/core/CDataFrameRowSlice.cc
- lib/maths/CAdaptiveBucketing.cc
- lib/maths/CBjkstUniqueValues.cc
- lib/maths/CCountMinSketch.cc
- lib/maths/CDecompositionComponent.cc
- lib/maths/CLassoLogisticRegression.cc
- lib/maths/CMultinomialConjugate.cc
- lib/maths/CMultivariatePrior.cc
- lib/maths/CPrior.cc
- lib/model/CAnnotatedProbability.cc
- lib/model/CHierarchicalResults.cc
- lib/model/CSearchKey.cc
The standard library can use more efficient algorithms when it
is certain that swap functions, move constructors and move
assignment operators do not throw exceptions.
This change adds noexcept to the majority of such functions that
didn't already have it.
(There are still a few that I didn't add it to, as it was hard
to be sure whether the complicated layers of containers of
Eigen data structures held within them might throw exceptions.)
> [ML] Make swap and move functions noexcept where possible

- include/core/CStringUtils.h
- lib/core/CStringUtils.cc
- lib/core/unittest/CStringUtilsTest.cc
This PR adds a utility to compute the length of a UTF-16 encoded string. This functionality is needed to improve compatibility with Java.
Since it's not a user-facing functionality, I mark it as a non-issue.
Backport of #1338.
> [7.x][ML] UTF-16 String length computation

- include/api/CFieldConfig.h
- include/core/CDataFrameRowSlice.h
- include/maths/CAdaptiveBucketing.h
- include/maths/CBjkstUniqueValues.h
- include/maths/CCountMinSketch.h
- include/maths/CDecompositionComponent.h
- include/maths/CKMeansOnline.h
- include/maths/CLassoLogisticRegression.h
- include/maths/CMultinomialConjugate.h
- include/maths/CMultivariatePrior.h
- include/maths/CPrior.h
- include/model/CAnnotatedProbability.h
- include/model/CHierarchicalResults.h
- include/model/CSearchKey.h
- lib/api/CFieldConfig.cc
- lib/core/CDataFrameRowSlice.cc
- lib/maths/CAdaptiveBucketing.cc
- lib/maths/CBjkstUniqueValues.cc
- lib/maths/CCountMinSketch.cc
- lib/maths/CDecompositionComponent.cc
- lib/maths/CLassoLogisticRegression.cc
- lib/maths/CMultinomialConjugate.cc
- lib/maths/CMultivariatePrior.cc
- lib/maths/CPrior.cc
- lib/model/CAnnotatedProbability.cc
- lib/model/CHierarchicalResults.cc
- lib/model/CSearchKey.cc
The standard library can use more efficient algorithms when it
is certain that swap functions, move constructors and move
assignment operators do no throw exceptions.
This change adds noexcept to the majority of such functions that
didn't already have it.
(There are still a few that I didn't add it to, as it was hard
to be sure whether the complicated layers of containers of
Eigen data structures held within them might throw exceptions.)
Backport of #1339
> [7.x][ML] Make swap and move functions noexcept where possible

- include/api/CInferenceModelDefinition.h
- lib/api/CInferenceModelDefinition.cc
- lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
- lib/api/unittest/testfiles/model_size_info/model_size_info.schema.json
This PR adds the ability to generate model_size_info objects used in Java to estimate the heap size for the inference models. I added a slim subclass CSizeInfo to all relevant classes which contains reference to the definition objects and generates Json with the necessary information when called.
We do a double work for counting nodes and leaves of the tree when computing numOperations and generating JSON. I did it to avoid memory overhead.
I am not writing the model_size_info in the results yet, I intend to do it in a subsequent PR. Hence this PR is marked as a non-issue.
Backport of #1316.
> [7.x][ML] Generate memory size info for compressed model definition

- include/maths/CBoostedTreeLeafNodeStatistics.h
- lib/maths/CBoostedTreeLeafNodeStatistics.cc
Following on from #1317, we can delay computing the bitwise or of the different thread row masks until we know we can split the leaf. This operation is serial and can be expensive for many threads and rows.
I've decided not to document this separately from #1317, since it is a natural optimisation I missed in that change; so I've marked it as a non-issue.
> [ML] Only compute boosted tree leaf row masks if they are needed

- docs/CHANGELOG.asciidoc
- include/maths/CIntegerTools.h
- lib/maths/CIntegerTools.cc
We need to be defensive against the case that we've been asked to floor to a multiple of 0. We shouldn't be calling the function in this way at present, but it is a candidate for #1348. In this case it is natural to return the supplied integer value and certainly better than aborting.
> [ML] Trap potential cause of SIGFPE

- include/core/CTimeUtils.h
- lib/core/CTimeUtils.cc
- lib/core/unittest/CTimeUtilsTest.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
This PR makes time period used in model change annotation formatted using newly introduced `CTimeUtils::durationToString`.
The goal is to make the annotation text human-readable.
Relates https://github.com/elastic/elasticsearch/issues/55781
> Format time period in model change annotation using CTimeUtils::durationToString

- include/core/CTimeUtils.h
- lib/core/CTimeUtils.cc
- lib/core/unittest/CTimeUtilsTest.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- Format time period in model change annotation using CTimeUtils::durationToString  (#1358)
> [7.x] Format time period in model change annotation using CTimeUtils::durationToString (#1358)

- include/maths/CModel.h
- include/maths/CTimeSeriesDecomposition.h
- include/maths/CTimeSeriesDecompositionDetail.h
- include/maths/CTimeSeriesDecompositionInterface.h
- include/maths/MathsTypes.h
- lib/maths/CTimeSeriesDecompositionDetail.cc
- lib/maths/CTimeSeriesModel.cc
- lib/model/CEventRateModel.cc
- lib/model/CEventRatePopulationModel.cc
- lib/model/CMetricModel.cc
- lib/model/CMetricPopulationModel.cc
All annotations can use the start time of the bucket in which they are added. This means that it is not necessary to pass in a time when adding an annotation it can be captured in the lambda.
This is important because there are places we may want to generate annotations, such as when the residual distribution model changes, where time is unavailable. It will be undesirable to have to make it available just for annotations.
I also made a small tweak to the way the callback is passed to `std::function`. The size of this object means it won't be able to take advantage of the small object optimisation. This triggers an allocation on every single bucket and time series update which we try to avoid. By passing the callback by reference we avoid this.
> [ML] Don't require time is supplied when adding an annotation

- docs/CHANGELOG.asciidoc
- include/core/CPackedBitVector.h
- include/maths/CBoostedTreeFactory.h
- include/maths/CBoostedTreeLeafNodeStatistics.h
- include/maths/CBoostedTreeUtils.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/core/CPackedBitVector.cc
- lib/core/unittest/CPackedBitVectorTest.cc
- lib/maths/CBoostedTreeFactory.cc
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/CBoostedTreeLeafNodeStatistics.cc
- lib/maths/unittest/CBoostedTreeTest.cc
We use run length encoding for the bit masks we use to cache the rows for each leaf of the boosted tree. The scheme we were previously using was to use a fixed 1 byte to encode each run length. Long runs were then represented by "run length" / 256 bytes. This scheme works well while the expected run length < 256, but becomes highly suboptimal when the expected run length >> 256.
As we grow a tree we are partitioning rows between leaves, so naturally induce sparseness into the bit masks which corresponds to longer expected run lengths (of zero bits). For roughly balanced splits, our current scheme works well until the tree depth is 8 and then performance tails off for deeper trees. And in particular, the worst case for both memory usage and run time, many deep trees, are when the encoding …
> [ML] Improve bit vector encoding efficiency for sparse vectors

- docs/CHANGELOG.asciidoc
- include/api/CDataFrameAnalysisInstrumentation.h
- include/api/CInferenceModelDefinition.h
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/api/unittest/testfiles/instrumentation/memory_usage.schema.json
This PR adds `status` field to the `analytics_memory_usage` instrumentation object for DGA. The status can be "ok" and "hard-limit". Additionally I added the field `advised_limit_bytes` containing new recommended memory limit for simple usage, e.g. by UI.
Since this is closely related to #1298, I don't document this separately and mark as non-issue.
Closes #1310.
> [ML] Add memory_status to memory_stats

- include/api/CDataFrameAnalysisInstrumentation.h
- include/api/CInferenceModelDefinition.h
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/api/unittest/testfiles/instrumentation/memory_usage.schema.json
This PR adds status field to the analytics_memory_usage instrumentation object for DGA. The status can be "ok" and "hard-limit". Additionally I added the field advised_limit_bytes containing new recommended memory limit for simple usage, e.g. by UI.
Since this is closely related to #1298, I don't document this separately and mark as non-issue.
Backport of #1345.
> [7.x][ML] Add memory_status to memory_stats

- include/api/CDataFrameAnalyzer.h
- lib/api/CDataFrameAnalyzer.cc
This PR changes the sequence of writing results outputting inference model definition before prediction results.
Closes #1280
> [ML] Return inference model definition before writing prediction results

- include/maths/CPeriodicityHypothesisTests.h
- lib/maths/CPeriodicityHypothesisTests.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
This PR appends the description field to the annotation text generated when periodicity is detected.
This way annotations do not show up as duplicates as the texts are now different.
Closes https://github.com/elastic/elasticsearch/issues/58589
> Add description (e.g.: "daily", "weekend weekly") to the annotation text

- include/api/CInferenceModelDefinition.h
- include/core/CRapidJsonConcurrentLineWriter.h
- lib/api/CDataFrameAnalyzer.cc
- lib/api/CInferenceModelDefinition.cc
- lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
To reduce memory consumption, the inference model definition is now written directly into a stream using core::CRapidJsonLineWriter<rapidjson::OStreamWrapper> instead of core::CRapidJsonConcurrentLineWriter used before. Therefore, to distinguish the two kinds of creating json format, we now have two internfaces:
CSerializableToJsonDocument with the function addToJsonDocument uses provided CRapidJsonConcurrentLineWriter to create a rapidjson object and then write it into the result stream directly.
CSerializableToJsonStream with the function addToJsonStream uses CRapidJsonLineWriter to write in a stream without keeping a complete json object in memory.
Memory size info classes still implement CSerializableToJsonDocument since the memory overhead there is minimal and this way they can use …
> [7.x][ML] Avoid instantiating string for writing model definition

- include/maths/CPeriodicityHypothesisTests.h
- lib/maths/CPeriodicityHypothesisTests.cc
- lib/maths/CTimeSeriesDecompositionDetail.cc
- Add description (e.g.: "daily", "weekend weekly") to the annotation text  (#1373)
> [7.x] Add description (e.g.: "daily", "weekend weekly") to the annotation text (#1373)

- include/maths/CBoostedTreeImpl.h
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
There was an error in how we were computing the correction coefficient which led to wrong scaling. This PR fixes the issues and adds a unit test to check the values.
Since memory correction is not released yet I am marking this as a non-issue.
> [ML] Memory correction coefficient fixed

- include/maths/CBoostedTreeImpl.h
- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
There was an error in how we were computing the correction coefficient which led to wrong scaling. This PR fixes the issues and adds a unit test to check the values.
Since memory correction is not released yet I am marking this as a non-issue.
Backport of  #1377.
> [7.x][ML] Memory correction coefficient fixed

- docs/CHANGELOG.asciidoc
- include/api/CBoostedTreeInferenceModelBuilder.h
- include/api/CInferenceModelDefinition.h
- include/maths/CBoostedTree.h
- lib/api/CBoostedTreeInferenceModelBuilder.cc
- lib/api/CInferenceModelDefinition.cc
- lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
- lib/maths/CBoostedTreeImpl.cc
This PR adds exponent aggregator required for the regression models trained with MSLE objective function.
Closes #1372
> [ML] Adds exponent aggregator to the inference model definition

- docs/CHANGELOG.asciidoc
- include/core/CDataFrame.h
- include/maths/CBoostedTreeImpl.h
- lib/core/CDataFrame.cc
- lib/core/unittest/CDataFrameTest.cc
- lib/maths/CBoostedTreeFactory.cc
We weren't accounting for the padding we include since we memory aligned columns, #1142, in `CBoostedTreeFactory` when computing the number of extra columns. This meant we were using presenting extra columns to feature selection (which would nearly always ignore them) and occasionally changing the initialisation of the learn rate.
The problem we hit which caused the SIGSEGV was when there was only one feature which itself carried no information, i.e. it was a constant. We could then erroneously select an extra column as a feature.
> [ML] Fix cause of SIGSEGV for classification and regression

- docs/CHANGELOG.asciidoc
- include/api/CBoostedTreeInferenceModelBuilder.h
- include/api/CInferenceModelDefinition.h
- include/maths/CBoostedTree.h
- lib/api/CBoostedTreeInferenceModelBuilder.cc
- lib/api/CInferenceModelDefinition.cc
- lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
- lib/maths/CBoostedTreeImpl.cc
This PR adds exponent aggregator required for the regression models trained with MSLE objective function.
Backport of #1375.
> [7.x][ML] Adds exponent aggregator to the inference model definition 

- docs/CHANGELOG.asciidoc
- lib/maths/CDecompositionComponent.cc
- lib/maths/CTimeSeriesDecomposition.cc
- lib/maths/CTrendComponent.cc
- lib/maths/unittest/CForecastTest.cc
This addresses the potential causes for empty forecast confidence intervals.
In particular, we weren't ensuring that the smoothing we perform where we join the predictions of models for distinct time intervals doesn't invert the confidence interval bounds (although this should be very unlikely, it is theoretically possible). It also reworks the handling of heteroskedasticity so we scale the forecasted seasonal confidence interval. By construction, this transform will never invert the confidence interval bounds.
Closes #1357.
> [ML] Trap potential causes of inverted forecast bounds

- docs/CHANGELOG.asciidoc
- include/maths/CTimeSeriesChangeDetector.h
- lib/maths/CTimeSeriesChangeDetector.cc
The change detector would crash during restoration if seasonal
components existed at the time it was originally created, but
had been discarded by the time it was persisted.
This change ensures that the change models within the change
detector reflect the status of seasonality at the time of
restoration from state.
> [ML] Fix change detector restore

- docs/CHANGELOG.asciidoc
- include/maths/CTimeSeriesChangeDetector.h
- lib/maths/CTimeSeriesChangeDetector.cc
The change detector would crash during restoration if seasonal
components existed at the time it was originally created, but
had been discarded by the time it was persisted.
This change ensures that the change models within the change
detector reflect the status of seasonality at the time of
restoration from state.
Backport of #1391
> [6.8][ML] Fix change detector restore

- docs/CHANGELOG.asciidoc
- include/maths/CTimeSeriesChangeDetector.h
- lib/maths/CTimeSeriesChangeDetector.cc
The change detector would crash during restoration if seasonal
components existed at the time it was originally created, but
had been discarded by the time it was persisted.
This change ensures that the change models within the change
detector reflect the status of seasonality at the time of
restoration from state.
Backport of #1391
> [7.x][ML] Fix change detector restore

- docs/CHANGELOG.asciidoc
- include/maths/CTimeSeriesChangeDetector.h
- lib/maths/CTimeSeriesChangeDetector.cc
The change detector would crash during restoration if seasonal
components existed at the time it was originally created, but
had been discarded by the time it was persisted.
This change ensures that the change models within the change
detector reflect the status of seasonality at the time of
restoration from state.
Backport of #1391
> [7.8][ML] Fix change detector restore

- lib/api/CDataFrameAnalysisInstrumentation.cc
This tiny PR updates the instructions for the user stating explicitly that the analysis job has to be force-stop before the memory setting can be updated.
> [ML] Update user instructions for memory limit surpass

- lib/api/CDataFrameAnalysisInstrumentation.cc
This message is new to 7.9 so I've marked this PR as a non-issue.
> [ML] Fix a race in writing the memory usage message after circuit breaking

- lib/api/CDataFrameAnalysisInstrumentation.cc
This tiny PR updates the instructions for the user stating explicitly that the analysis job has to be force-stop before the memory setting can be updated.
Backport of  #1397.
> [7.x][ML] Update user instructions for memory limit surpass

- docs/CHANGELOG.asciidoc
- lib/model/CAnomalyDetector.cc
It is possible that a model which hasn't received any recent updates is removed. In this case, when forecasting we'd hit a null pointer dereference. This moves the offending code under the check that the model still exists.
Fixes #1401.
> [ML] Fix for SIGSEGV forecasting

- docs/CHANGELOG.asciidoc
- lib/model/CAnomalyDetector.cc
> [7.8][ML] Fix for SIGSEGV forecasting

- docs/CHANGELOG.asciidoc
- include/model/CTokenListCategory.h
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
The max matching string length in a category definition is supposed
to stop a category created from a message with very few tokens from
matching messages with many more tokens that happen to include the
few tokens.  However, the 10% tolerance that was added to the length
when considering a match could cause the category to match slightly
longer messages over and over again until the max matching length
was an order of magnitude greater than it started off.
This change caps the increase in the max matching length to a
multiple of the length of the original message that caused the
category to be created.  The multiple is 2 for categories that have
few tokens, and progressively bigger as the number of tokens that
define the category increases (as the more tokens the category has
the less …
> [ML] Restrict growth of max matching string length for categories

- docs/CHANGELOG.asciidoc
- include/model/CTokenListCategory.h
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
The max matching string length in a category definition is supposed
to stop a category created from a message with very few tokens from
matching messages with many more tokens that happen to include the
few tokens.  However, the 10% tolerance that was added to the length
when considering a match could cause the category to match slightly
longer messages over and over again until the max matching length
was an order of magnitude greater than it started off.
This change caps the increase in the max matching length to a
multiple of the length of the original message that caused the
category to be created.  The multiple is 2 for categories that have
few tokens, and progressively bigger as the number of tokens that
define the category increases (as the more tokens the category has
the less …
> [7.x][ML] Restrict growth of max matching string length for categories

- lib/maths/CBoostedTreeImpl.cc
- lib/maths/unittest/CBoostedTreeTest.cc
This PR changes the memory correction strategy to enforce the strongly monotonic behavior of the corrected values. Previously, the correction could leave to the situation where memory estimations could be swapped (bigger job could have a smaller memory estimation), this is not possible now.
> [ML] New memory estimation correction function

- docs/CHANGELOG.asciidoc
- include/model/CTokenListCategory.h
- lib/model/CTokenListCategory.cc
- lib/model/CTokenListDataCategorizerBase.cc
- lib/model/unittest/CTokenListDataCategorizerTest.cc
The max matching string length in a category definition is supposed
to stop a category created from a message with very few tokens from
matching messages with many more tokens that happen to include the
few tokens.  However, the 10% tolerance that was added to the length
when considering a match could cause the category to match slightly
longer messages over and over again until the max matching length
was an order of magnitude greater than it started off.
This change caps the increase in the max matching length to a
multiple of the length of the original message that caused the
category to be created.  The multiple is 2 for categories that have
few tokens, and progressively bigger as the number of tokens that
define the category increases (as the more tokens the category has
the less …
> [7.9][ML] Restrict growth of max matching string length for categories

- lib/maths/CTimeSeriesChangeDetector.cc
Change #1391 introduced a subtle error: when computing the likelihood of no change we should use a reference to the current time series trend model, not the copy of the model which assumes a change is occurring. This has not yet been released so I've marked this as a non-issue.
> [ML] Testing for no change should not use the change trend model

- lib/maths/CTimeSeriesChangeDetector.cc
Change #1391 introduced a subtle error: when computing the likelihood of no change
we should use a reference to the current time series trend model, not the copy of the
model which assumes a change is occurring.
Backport #1415.
> [7.8][ML] Testing for no change should not use the change trend model

- lib/maths/CTimeSeriesChangeDetector.cc
Change #1391 introduced a subtle error: when computing the likelihood of no change
we should use a reference to the current time series trend model, not the copy of the
model which assumes a change is occurring.
Backport #1415.
> [7.10][ML] Testing for no change should not use the change trend model

- include/api/CDataFrameTrainBoostedTreeRunner.h
- include/api/CInferenceModelDefinition.h
- include/test/CDataFrameAnalysisSpecificationFactory.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/CInferenceModelDefinition.cc
- lib/test/CDataFrameAnalysisSpecificationFactory.cc
`IsEmpty` can only be called on an `rapidjson::Array` object. This fixes some fallout from #1408 by checking types first and migrating to an optional `rapidjson::Document` on `CDataFrameAnalysisSpecificationFactory`. Since the code hasn't been released I've marked this as a non-issue.
> [ML] Fix undefined behaviour

- lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
These tests expect the custom processors to be an array, which
is what the test document gets parsed as.  Interpreting it as
an object trips an assertion if they are enabled, though works
by pure luck as the array and object are both just pointers
and are members of a union so you get the same address even
after calling the wrong method.
> [ML] Fix custom processor tests

- lib/maths/CTimeSeriesChangeDetector.cc
Change #1391 introduced a subtle error: when computing the likelihood of no change
we should use a reference to the current time series trend model, not the copy of the
model which assumes a change is occurring.
Backport #1415.
> [7.9][ML] Testing for no change should not use the change trend model

- lib/maths/CTimeSeriesChangeDetector.cc
Change #1391 introduced a subtle error: when computing the likelihood of no change
we should use a reference to the current time series trend model, not the copy of the
model which assumes a change is occurring.
Backport #1415.
> [6.8][ML] Testing for no change should not use the change trend model

- lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
These tests expect the custom processors to be an array, which
is what the test document gets parsed as.  Interpreting it as
an object trips an assertion if they are enabled, though works
by pure luck as the array and object are both just pointers
and are members of a union so you get the same address even
after calling the wrong method.
Backport of #1424
> [7.x][ML] Fix custom processor tests

- include/api/CCsvOutputWriter.h
- include/api/CNdJsonOutputWriter.h
- include/api/CSimpleOutputWriter.h
- lib/api/CCsvOutputWriter.cc
- lib/api/CNdJsonOutputWriter.cc
- lib/api/CSimpleOutputWriter.cc
- lib/api/unittest/CCsvOutputWriterTest.cc
- lib/api/unittest/CNdJsonOutputWriterTest.cc
- The "messages" functionality in the CSV output writer was
obsolete (related to the old Prelert app for Splunk)
- The optional time passed to the output methods was never used
- Unit tests could be simplified using modern syntax, and taking
advantage of the fact that Boost.Test automatically prints
what was compared when assertions fail
- The sleeps in destructors related to some dodgy behaviour with
Python and named pipes on Solaris - no longer relevant
> [ML] Remove dead code in simple output writers

- build.gradle
- buildSrc/build.gradle
- gradle.properties
- upload.gradle
This PR fixes some deprecated gradle api usages in the gradle build. It also enforces the failure of the build from now on if a deprecated api is used. That makes it easy to keep the build clean and not let deprecations sneak into the build over time. 
This PR is related to a discussion with the elasticsearch infra team at https://elastic.slack.com/archives/C8UUBNASY/p1595288611366200 after a failure in a 7.8.1 BC
> Fix deprecated Gradle API usage

- build.gradle
- buildSrc/build.gradle
- gradle.properties
- upload.gradle
- enforce build failing on deprecated api usage
Backport of #1427
> [7.x] Fix deprecated Gradle API usage

- build.gradle
- buildSrc/build.gradle
- gradle.properties
- upload.gradle
- enforce build failing on deprecated api usage
Backport of #1427
> [7.9] Fix deprecated Gradle API usage

- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/core/CRapidJsonConcurrentLineWriter.cc
When the job is failing due to the memory limit exceeding, the job fails to emit the final memory_status message. This PR fixes this.
There was a type in the "hard_limit" tag which I fixed. Also I tweaked the parameters of the unit test CDataFrameAnalyzerTrainingTest.testMemoryLimitHandling to reduce runtime.
Additionally I took the new messaging from #1428 and added it here to avoid merge conflicts.
Backport of #1432
> [7.9][ML] Fixing memory_status output on fatal error

- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
- lib/core/CRapidJsonConcurrentLineWriter.cc
When the job is failing due to the memory limit exceeding, the job fails to emit the final memory_status message. This PR fixes this.
There was a type in the "hard_limit" tag which I fixed. Also I tweaked the parameters of the unit test CDataFrameAnalyzerTrainingTest.testMemoryLimitHandling to reduce runtime.
Additionally I took the new messaging from #1428 and added it here to avoid merge conflicts.
Backport of #1432
> [7.x][ML] Fixing memory_status output on fatal error 

- 3rd_party/3rd_party.sh
- build-setup/macos.md
- build-setup/macos_cross_compiled.md
- dev-tools/docker/build_macosx_build_image.sh
- dev-tools/docker/macosx_builder/Dockerfile
- dev-tools/docker/macosx_image/Dockerfile
- dev-tools/strip_binaries.sh
- docs/CHANGELOG.asciidoc
- mk/linux_crosscompile_macosx.mk
Upgrade to build the macOS version 8.x of the ML C++
using Apple clang 11.3.1 on Mojave or cross-compiling
using clang 8 on Ubuntu 20.04.
> [ML] Upgrade to clang 8/Apple clang 11.3.1 for macOS compilation

- dev-tools/run_es_tests.sh
Due to refactoring of the Elasticsearch build system we need
to use different task names when we run integration tests for
PRs.
> [ML] Alter ES integration test tasks

- set_env.sh
> [ML] Adding /usr/local/bin to the Linux PATH for FOSSA

- dev-tools/run_es_tests.sh
Due to refactoring of the Elasticsearch build system we need
to use different task names when we run integration tests for
PRs.
Backport of #1442
> [7.x][ML] Alter ES integration test tasks

- lib/core/CPackedBitVector.cc
- lib/core/unittest/CPackedBitVectorTest.cc
`Valgrind`'s `memcheck` tool  was run over the unit test suite. The tool picked up
an error related to unit test code only and another in production code
itself. Labelling as a non-issue because of the relatively minor nature of the problems identified.
> [ML] Fixed errors identified by valgrind memcheck

- set_env.sh
> [6.8][ML] Adding /usr/local/bin to the Linux PATH for FOSSA

- set_env.sh
> [7.8][ML] Adding /usr/local/bin to the Linux PATH for FOSSA

- set_env.sh
> [7.9][ML] Adding /usr/local/bin to the Linux PATH for FOSSA

- set_env.sh
> [7.x][ML] Adding /usr/local/bin to the Linux PATH for FOSSA

- lib/core/CPackedBitVector.cc
- lib/core/unittest/CPackedBitVectorTest.cc
Valgrind memcheck was run over the unit test suite. The tool picked up
an error related to unit test code only and another in production code
itself.
Backport of #1445
> [7.x][ML] Fixed errors identified by valgrind memcheck

- docs/CHANGELOG.asciidoc
- include/maths/CBoostedTreeImpl.h
- lib/maths/CBoostedTreeImpl.cc
> [7.10][ML] Fix progress on resume after final training has completed for classification and regression

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameAnalyzer.cc
- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
Activate the output of the model metadata and the corresponding unit tests for total feature importance. 
The implementation itself was introduced in #1387 however, I need to fix the documentation, it was originally attributed to v7.10. Hence, I mark this PR as enhancement to rectify the docs.
> [ML] Activate model metadata output

- include/api/CDataFrameTrainBoostedTreeClassifierRunner.h
- include/api/CInferenceModelMetadata.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/CInferenceModelMetadata.cc
This commit addresses two bugs:
- For individual class feature importance values, we now resolve the predicted class type name. e.g. we will now write JSON boolean `true` instead of `"1"`.
- For total feature importance, the predicted class type is now resolved as well.
> [ML] Resolves the predicted class type when writing feature importance values

- include/api/CInferenceModelMetadata.h
- lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc
- lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc
- lib/api/CInferenceModelMetadata.cc
- [ML] Resolves the predicted class type when writing feature importance values (#1463)
> [7.x] [ML] Resolves the predicted class type when writing feature importance values (#1463)

- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
From the management side, we allow users to update configured memory limits after the analytics configuration has started.
To help users with their workflow, we should allow analytics processes to attempt to run even if the configured memory limit is lower than our memory estimate. 
related to: https://github.com/elastic/elasticsearch/pull/61505
> [ML] do not fail to start analytics process if memory estimate is lower than predicted memory usage

- lib/api/CDataFrameAnalysisRunner.cc
- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- [ML] do not fail to start analytics process if memory estimate is lower than predicted memory usage (#1465)
> [7.x] [ML] do not fail to start analytics process if memory estimate is lower than predicted memory usage (#1465)

- dev-tools/run_es_tests.sh
This PR https://github.com/elastic/elasticsearch/pull/60630 changed the task for running our native integration tests.
This commit changes from using `integTest` to `javaRestTest`
> [ML] fix integration test command with es

- dev-tools/run_es_tests.sh
- [ML] fix integration test command with es (#1470)
> [7.x] [ML] fix integration test command with es (#1470)

- include/api/CAnomalyJob.h
- lib/api/CAnomalyJob.cc
- lib/api/unittest/CPersistenceManagerTest.cc
Refactor foreground persistence to allow for using supplied descriptors when snapshotting model state.
This paves the way for upgrading model state.
Backports #1473
> [7.x][ML] Refactor foreground persistence (#1473)

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameOutliersRunner.cc
- lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc
This changes the format of `feature_influence` for outlier detection so
that the feature name is not part of the field name. This helps reduce
field explosion in the results index.
Feature influence is now an array with nested objects. Each of them contains
the `feature_name` and the `influence` value.
> [ML] Change outlier detection feature influence format to nested object

- dev-tools/run_es_tests.sh
- include/maths/CBasicStatistics.h
- include/maths/CSignal.h
- include/maths/CTimeSeriesTestForSeasonality.h
- lib/maths/CSignal.cc
- lib/maths/CTimeSeriesTestForSeasonality.cc
- lib/maths/unittest/CForecastTest.cc
- lib/maths/unittest/CTimeSeriesModelTest.cc
Testing on our full QA suite showed up some edge cases, mainly around numerics, which were generating log errors.
We had some cases of 0/0 in the test statistics. Also we weren't checking the denominator degrees freedom for the F distribution was > 4 before getting variance (for which it is undefined). Finally, I've improved handling of the case that almost all values are either missing or constant in the test window.
Follow on from #1451.
> [ML] Fix some edge cases in new seasonal decomposition

- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
In the memory stats we reported the current memory usage instead of the peak memory usage. This PR fixes this.
Furthermore, we now check if the memory usage exceeds memory limit every time memory usage is updated instead of ca. once every second like it was before.
Backport of #1468
> [7.9][ML] Fix peak memory usage reporting

- dev-tools/run_es_tests.sh
- docs/CHANGELOG.asciidoc
- lib/api/CDataFrameAnalysisInstrumentation.cc
- lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
- lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
In the memory stats we reported the current memory usage instead of the peak memory usage. This PR fixes this.
Furthermore, we now check if the memory usage exceeds memory limit every time memory usage is updated instead of ca. once every second like it was before.
Backport of #1468
> [7.x][ML] Fix peak memory usage reporting

- include/api/CAnomalyJob.h
- include/api/CPersistenceManager.h
- lib/api/CAnomalyJob.cc
- lib/api/CPersistenceManager.cc
- lib/api/unittest/CAnomalyJobTest.cc
Parse and validate optional arguments to the 'persist' control message.
If present these arguments are used to perform foreground persistence,
else background persistence is requested.
As further work is still required to compose and send such a message from a suitable API, labelling this PR as a non-issue.
> [ML] Parse enhanced persist control message

- include/api/CAnomalyJob.h
- include/api/CPersistenceManager.h
- lib/api/CAnomalyJob.cc
- lib/api/CPersistenceManager.cc
- lib/api/unittest/CAnomalyJobTest.cc
Parse and validate optional arguments to the 'persist' control message.
If present these arguments are used to perform foreground persistence,
else background persistence is requested.
Backports #1488
> [7.x][ML] Parse enhanced persist control message (#1488)

- include/api/CSingleStreamSearcher.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/CSingleStreamSearcher.cc
Data frame analytics state may spread over multiple
documents. But unlike autodetect, where state is accompanied
by a model snapshot that allows us to know exactly how many
docs it comprises of, or categorizer, where we don't have
a snapshot equivalent but state can only grow, DFA state
may spread less docs than the previous one for a job.
This means that when the state is restored and streamed
into the c++ process, we might get more documents than
just the necessary ones.
We correctly restore state as we detect the `eos` marker.
However, we also need to consume the stream to its end
so that the thread writing to the stream may complete.
> [ML] Consume restore state stream to end

- include/api/CSingleStreamSearcher.h
- lib/api/CDataFrameTrainBoostedTreeRunner.cc
- lib/api/CSingleStreamSearcher.cc
Data frame analytics state may spread over multiple
documents. But unlike autodetect, where state is accompanied
by a model snapshot that allows us to know exactly how many
docs it comprises of, or categorizer, where we don't have
a snapshot equivalent but state can only grow, DFA state
may spread less docs than the previous one for a job.
This means that when the state is restored and streamed
into the c++ process, we might get more documents than
just the necessary ones.
We correctly restore state as we detect the `eos` marker.
However, we also need to consume the stream to its end
so that the thread writing to the stream may complete.
Backport of #1498
> [7.x][ML] Consume restore state stream to end (#1498)

- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/maths/COutliers.cc
- lib/maths/unittest/COutliersTest.cc
In order to estimate the memory requirement we now use the maximum number of nearest neighbors instead of the expected average of the neighbors. This makes the new model memory estimation more robust.
I also adjusted the unit test assertions since now the estimated memory is higher.
> [ML] Fix memory estimation for outlier detections

- lib/api/unittest/CDataFrameAnalysisRunnerTest.cc
- lib/maths/COutliers.cc
- lib/maths/unittest/COutliersTest.cc
In order to estimate the memory requirement we now use the maximum number of nearest neighbors instead of the expected average of the neighbors. This makes the new model memory estimation more robust.
I also adjusted the unit test assertions since now the estimated memory is higher.
Backport of #1502.
> [7.x][ML] Fix memory estimation for outlier detections 

- lib/model/unittest/CCountingModelTest.cc
- lib/model/unittest/CEventRateModelTest.cc
- lib/model/unittest/CEventRatePopulationModelTest.cc
- lib/model/unittest/CMetricModelTest.cc
- lib/model/unittest/CMetricPopulationModelTest.cc
- lib/model/unittest/CModelTestFixtureBase.h
Rework a number of model library unit tests to factor out:
* A commonly used resource monitor instance
* Many multiply defined types 
These will now reside in a newly defined test fixture base class.
This is the initial stage of work of that discussed in #1477
> [ML] Refactor model lib unit tests

- lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
This PR instruments the unit tests that occasionally fail. Next time the test suppose to fail because an actual feature importance variable is 0, the test will dump the result json into the log so I can investigate the causes of failure.
I will remove this instrumentation once I've found the root cause of failure.
> [ML] Investigate total importance CI failure

- dev-tools/docker/build_check_style_image.sh
- dev-tools/docker/build_linux_aarch64_cross_build_image.sh
- dev-tools/docker/build_linux_aarch64_native_build_image.sh
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/build_macosx_build_image.sh
The host to push our Docker images to is changing from
push.docker.elastic.co to simply docker.elastic.co.
This change adjusts our scripts to reflect this.
> [ML] Change Docker push target

- dev-tools/docker/build_check_style_image.sh
- dev-tools/docker/build_linux_aarch64_cross_build_image.sh
- dev-tools/docker/build_linux_aarch64_native_build_image.sh
- dev-tools/docker/build_linux_build_image.sh
- dev-tools/docker/build_macosx_build_image.sh
The host to push our Docker images to is changing from
push.docker.elastic.co to simply docker.elastic.co.
This change adjusts our scripts to reflect this.
Backport of #1507
> [7.x][ML] Change Docker push target

- docs/CHANGELOG.asciidoc
- lib/maths/CBoostedTreeImpl.cc
Since we downsample the rows when computing candidate splits it's possible that a feature with non-zero probability of being selected ends up with no non-missing feature values when we compute candidate splits. This is harmless and we can happily initialise the candidate splits to an empty set in this case. However, it was generating log spam when trying to compute quantiles. In particular, we'd get repeated errors and warnings during training of the form:
```
[CBoostedTreeImpl.cc@737] Failed to compute quantile 86.7027: ignoring split
[CQuantileSketch.cc@295] No values added to quantile sketch
```
This change simply checks that there are values before trying to compute quantiles.
> [ML] Avoid log spam when we only have missing values for a feature computing candidate splits for regression and classification
