elastic/ml-cpp

dev-tools/check-style.sh
This change ensures all our C++ code has the correct copyright header.
=> [ML] Check copyright headers in check-style script

include/maths/CBasicStatistics.h, include/maths/CTimeSeriesChangeDetector.h, include/maths/CTimeSeriesDecompositionDetail.h, lib/maths/CAdaptiveBucketing.cc, lib/maths/CBasicStatistics.cc, lib/maths/CModel.cc, lib/maths/CPeriodicityHypothesisTests.cc, lib/maths/CTimeSeriesChangeDetector.cc, lib/maths/CTimeSeriesDecomposition.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CBasicStatisticsTest.cc, lib/maths/unittest/CBasicStatisticsTest.h, lib/maths/unittest/CTimeSeriesChangeDetectorTest.cc, lib/maths/unittest/CTimeSeriesChangeDetectorTest.h, lib/maths/unittest/CTimeSeriesModelTest.cc
=> [6.x][ML] Improve change point detection for long bucket lengths

CONTRIBUTING.md
see https://github.com/elastic/ml-cpp/pull/105
=> [6.4][ML] Backport PR guidelines (#105)

lib/seccomp/CSystemCallFilter_Linux.cc
=> [6.4][ML] Add clock_gettime to seccomp filter (#116)

docs/CHANGELOG.asciidoc, include/maths/CTools.h, lib/maths/CTools.cc, lib/maths/CXMeansOnline1d.cc, lib/maths/unittest/CToolsTest.cc, lib/maths/unittest/CToolsTest.h
=> [6.4][ML] Fix #51 - fix lgamma calculation for x-means clustering

include/core/CRapidJsonWriterBase.h, include/maths/CMathsFuncs.h, include/maths/CMultivariateNormalConjugate.h, include/maths/CTools.h, lib/maths/CCategoricalTools.cc, lib/maths/CGammaRateConjugate.cc, lib/maths/CLogNormalMeanPrecConjugate.cc, lib/maths/CMathsFuncs.cc, lib/maths/CMultinomialConjugate.cc, lib/maths/CNormalMeanPrecConjugate.cc, lib/maths/CPoissonMeanConjugate.cc, lib/maths/CRadialBasisFunction.cc, lib/maths/CStatisticalTests.cc, lib/maths/CTools.cc, lib/maths/ProbabilityAggregators.cc, lib/maths/unittest/CIntegerToolsTest.cc, lib/maths/unittest/CProbabilityAggregatorsTest.cc, lib/maths/unittest/CSamplingTest.cc, lib/maths/unittest/CToolsTest.cc
=> [6.4][ML] Refactor code to use std::lgamma instead of boost::math::lgamma

docs/CHANGELOG.asciidoc, include/maths/CAdaptiveBucketing.h, include/maths/CBasicStatistics.h, include/maths/CBasicStatisticsPersist.h, include/maths/CCalendarComponentAdaptiveBucketing.h, include/maths/CSeasonalComponent.h, include/maths/CSeasonalComponentAdaptiveBucketing.h, include/maths/CTools.h, include/maths/CTrendComponent.h, lib/maths/CAdaptiveBucketing.cc, lib/maths/CCalendarComponentAdaptiveBucketing.cc, lib/maths/CSeasonalComponent.cc, lib/maths/CSeasonalComponentAdaptiveBucketing.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTools.cc, lib/maths/CTrendComponent.cc, lib/maths/unittest/CBasicStatisticsTest.cc, lib/maths/unittest/CForecastTest.cc, lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.cc, lib/maths/unittest/CTimeSeriesDecompositionTest.cc
=> [6.4][ML] Improve adaption of the modelling of cyclic components to very localised features

docs/CHANGELOG.asciidoc, include/core/CStateMachine.h, lib/core/CStateMachine.cc, lib/core/unittest/CStateMachineTest.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/unittest/CTimeSeriesDecompositionTest.cc
=> [6.4][ML] Fix issues upgrading state leading to possible abort of the autodetect process

docs/CHANGELOG.asciidoc, include/core/CStateMachine.h, lib/core/CStateMachine.cc, lib/core/unittest/CStateMachineTest.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/unittest/CTimeSeriesDecompositionTest.cc
=> [6.3][ML] Fix issues upgrading state leading to possible abort of the autodetect process

lib/model/CProbabilityAndInfluenceCalculator.cc
=> [6.4][ML] skip calculation of influencer probabilities if no influences specified

docs/CHANGELOG.asciidoc, lib/model/CMetricPopulationModel.cc, lib/model/CProbabilityAndInfluenceCalculator.cc, lib/model/unittest/CMetricPopulationModelTest.cc
=> [6.4][ML] Fix influencer count and influence calculation

include/maths/CAdaptiveBucketing.h, include/maths/CCalendarComponentAdaptiveBucketing.h, include/maths/CSeasonalComponentAdaptiveBucketing.h, lib/maths/CAdaptiveBucketing.cc, lib/maths/CCalendarComponentAdaptiveBucketing.cc, lib/maths/CSeasonalComponentAdaptiveBucketing.cc, lib/maths/unittest/CCalendarComponentAdaptiveBucketingTest.cc, lib/maths/unittest/CCalendarComponentAdaptiveBucketingTest.h, lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.cc, lib/maths/unittest/CSeasonalComponentAdaptiveBucketingTest.h
=> [6.4][ML]improve error message for splitting failure (#152)

docs/CHANGELOG.asciidoc, include/maths/CGammaRateConjugate.h, include/maths/CLogNormalMeanPrecConjugate.h, include/maths/CNaturalBreaksClassifier.h, include/maths/CNormalMeanPrecConjugate.h, include/maths/CPoissonMeanConjugate.h, include/maths/CXMeansOnline.h, include/maths/CXMeansOnline1d.h, include/maths/MathsTypes.h, lib/maths/CGammaRateConjugate.cc, lib/maths/CLogNormalMeanPrecConjugate.cc, lib/maths/CNaturalBreaksClassifier.cc, lib/maths/CNormalMeanPrecConjugate.cc, lib/maths/CPoissonMeanConjugate.cc, lib/maths/CXMeansOnline1d.cc, lib/maths/unittest/CMultimodalPriorTest.cc, lib/maths/unittest/CNormalMeanPrecConjugateTest.cc, lib/maths/unittest/COneOfNPriorTest.cc, lib/maths/unittest/CPoissonMeanConjugateTest.cc, lib/maths/unittest/CPriorTest.cc, lib/maths/unittest/CTimeSeriesModelTest.cc, lib/maths/unittest/CXMeansOnline1dTest.cc, lib/model/unittest/CMetricModelTest.cc
=> [6.4][ML] Decrease the memory used by distribution models (#146)

include/maths/CExpandingWindow.h, include/maths/CTimeSeriesDecompositionDetail.h, lib/maths/CExpandingWindow.cc, lib/maths/CTimeSeriesDecomposition.cc, lib/maths/CTimeSeriesDecompositionDetail.cc
=> [6.4][ML] Improve times series decomposition after detecting time shifts

docs/CHANGELOG.asciidoc, include/maths/CTimeSeriesModel.h, lib/maths/CMultimodalPrior.cc, lib/maths/CMultivariateOneOfNPrior.cc, lib/maths/CTimeSeriesModel.cc, lib/model/unittest/CEventRateModelTest.cc
=> [6.5][ML] Fixes potentials for SIGSEGV in multivariate probability calculation

docs/CHANGELOG.asciidoc, include/maths/CTimeSeriesModel.h, lib/maths/CMultimodalPrior.cc, lib/maths/CMultivariateOneOfNPrior.cc, lib/maths/CTimeSeriesModel.cc, lib/model/unittest/CEventRateModelTest.cc
=> [6.4][ML] Fixes potentials for SIGSEGV in multivariate probability calculation

docs/CHANGELOG.asciidoc, include/maths/CMultimodalPriorUtils.h, lib/maths/unittest/CMultimodalPriorTest.cc
=> [6.5][ML] Correct the multimodal prior confidence interval calculation

include/maths/CModel.h, include/maths/CTimeSeriesMultibucketFeatures.h, lib/maths/CModel.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CTimeSeriesMultibucketFeaturesTest.cc, lib/model/CEventRatePopulationModel.cc, lib/model/CMetricPopulationModel.cc, lib/model/unittest/CEventRateAnomalyDetectorTest.cc, lib/model/unittest/CMetricAnomalyDetectorTest.cc
=> [ML] Improvements to address QA regressions associated with multi-bucket

lib/api/CAnomalyJob.cc
Backport of #203
Ensure that normalizers (and hence quantile state) are persisted only
once, when time is advanced
=> [ML] Optimization to quantile persistence (#203)

docs/CHANGELOG.asciidoc, include/maths/CNaiveBayes.h, lib/maths/CNaiveBayes.cc, lib/maths/unittest/CNaiveBayesTest.cc, lib/maths/unittest/CNaiveBayesTest.h
=> [6.5][ML] Trap case triggering "Bad density value..." log errors whilst forecasting

docs/CHANGELOG.asciidoc, include/maths/CExpandingWindow.h, include/maths/CTimeSeriesDecomposition.h, include/maths/CTimeSeriesDecompositionDetail.h, include/maths/CTimeSeriesDecompositionInterface.h, include/maths/CTimeSeriesDecompositionStub.h, include/maths/CTimeSeriesModel.h, lib/maths/CExpandingWindow.cc, lib/maths/CTimeSeriesDecomposition.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesDecompositionStub.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CTimeSeriesModelTest.cc
=> [6.5][ML] Improve initialisation of the residual model after detecting new  decomposition components

docs/CHANGELOG.asciidoc, include/model/CBucketGatherer.h, include/model/CEventRateBucketGatherer.h, include/model/CMetricBucketGatherer.h, lib/model/CBucketGatherer.cc, lib/model/CEventRateBucketGatherer.cc, lib/model/CMetricBucketGatherer.cc, lib/model/unittest/CEventRateDataGathererTest.cc, lib/model/unittest/CEventRateModelTest.cc
=> [6.5][ML] Fix incorrectly missing anomaly influences for empty buckets

dev-tools/jenkins_ci.ps1, dev-tools/jenkins_ci.sh
Powershell script was modelled on
https://github.com/elastic/beats/pull/8268, and should prevent silent
failures such as https://elasticsearch-ci.elastic.co/job/elastic+machine-learning+master+windows/4/console
=> [ci] Add a couple of `jenkins-ci` helper scripts for Linux and Widnows testing.

docs/CHANGELOG.asciidoc, include/model/CResourceMonitor.h, lib/api/unittest/CAnomalyJobLimitTest.cc, lib/model/CResourceMonitor.cc
Changed the calculation to decrease the byte limit margin to take into account
bucket spans greater than 1 day
Backports #243
=> [6.5][ML] hard_limit memory error fix (#243)

lib/model/CProbabilityAndInfluenceCalculator.cc
Labelled as non-issue as relates to as-yet unreleased feature
=> [ML] Round multi_bucket_impact to 2dp

lib/model/CProbabilityAndInfluenceCalculator.cc
non-issue as relates to as-yet unreleased feature
Backports #257
=> [6.5][ML] Round multi_bucket_impact to 2dp (#257)

docs/CHANGELOG.asciidoc, include/model/CResourceMonitor.h, lib/api/unittest/CAnomalyJobLimitTest.cc, lib/model/CResourceMonitor.cc
Changed the calculation to decrease the byte limit margin to take into account
bucket spans greater than 1 day
Backports #243
=> [6.4][ML] hard_limit memory error fix (#243)

include/maths/CTimeSeriesDecomposition.h, include/maths/CTimeSeriesDecompositionDetail.h, include/maths/CTimeSeriesDecompositionInterface.h, include/maths/CTimeSeriesDecompositionStub.h, include/maths/CTimeSeriesModel.h, lib/maths/CTimeSeriesDecomposition.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesDecompositionStub.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CTimeSeriesModelTest.cc
=> [6.5][ML] Account for step discontinuities when reinitialising the residual model after a detecting a change or new decomposition components

lib/seccomp/unittest/CSystemCallFilterTest.cc
The seccomp tests were getting a temporary directory after
installing the syscall filter.  This causes the user-specific
temp directory functionality to fail, and the fallback option
of using /tmp to be selected.  But using /tmp is not ideal
because it may contain files of the names the test wants to
used but owned by a different user (which was why we switched
to user-specific temp directories for the tests in the first
place).
This change caches the name of the user-specific temp directory
before any tests run, and also cleans up a couple of compiler
warnings.
Backport of #276
=> [ML][6.6] Call CTestTmpDir::tmpDir() before installing syscall filter

lib/seccomp/unittest/CSystemCallFilterTest.cc
The seccomp tests were getting a temporary directory after
installing the syscall filter.  This causes the user-specific
temp directory functionality to fail, and the fallback option
of using /tmp to be selected.  But using /tmp is not ideal
because it may contain files of the names the test wants to
used but owned by a different user (which was why we switched
to user-specific temp directories for the tests in the first
place).
This change caches the name of the user-specific temp directory
before any tests run, and also cleans up a couple of compiler
warnings.
Backport of #276
=> [ML][6.5] Call CTestTmpDir::tmpDir() before installing syscall filter

docs/CHANGELOG.asciidoc, include/maths/CTimeSeriesDecomposition.h, include/maths/CTimeSeriesDecompositionDetail.h, include/maths/CTimeSeriesDecompositionInterface.h, include/maths/CTimeSeriesDecompositionStub.h, lib/maths/CTimeSeriesDecomposition.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesDecompositionStub.cc, lib/maths/CTimeSeriesModel.cc
=> [6.6][ML] Prevent trend detection during a change in a time series creating a poorly reinitialised model

docs/CHANGELOG.asciidoc, include/maths/CTimeSeriesDecomposition.h, include/maths/CTimeSeriesDecompositionDetail.h, include/maths/CTimeSeriesDecompositionInterface.h, include/maths/CTimeSeriesDecompositionStub.h, lib/maths/CTimeSeriesDecomposition.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesDecompositionStub.cc, lib/maths/CTimeSeriesModel.cc
=> [6.5][ML] Prevent trend detection during a change in a time series creating a poorly reinitialised model

CONTRIBUTING.md, README.md, bin/autodetect/Main.cc, bin/categorize/Main.cc, include/api/CForecastRunner.h, lib/api/CForecastRunner.cc, mk/make_rc_defines.sh
ML is now a feature of the Elastic Stack
=> [ML] Deemphasizing X-Pack

CONTRIBUTING.md, README.md, bin/autodetect/Main.cc, bin/categorize/Main.cc, include/api/CForecastRunner.h, lib/api/CForecastRunner.cc, mk/make_rc_defines.sh
ML is now a feature of the Elastic Stack
Backports #312
=> [ML][6.6] Deemphasizing X-Pack

CONTRIBUTING.md, README.md, bin/autodetect/Main.cc, bin/categorize/Main.cc, include/api/CForecastRunner.h, lib/api/CForecastRunner.cc, mk/make_rc_defines.sh
ML is now a feature of the Elastic Stack
Backports #312
=> [ML][6.5] Deemphasizing X-Pack

docs/CHANGELOG.asciidoc, include/api/CForecastRunner.h, include/model/CForecastDataSink.h, lib/api/CForecastRunner.cc, lib/model/CForecastDataSink.cc, lib/model/CModelDetailsView.cc
=> [ML] Correct query times for model plot and forecast

docs/CHANGELOG.asciidoc, include/api/CForecastRunner.h, include/model/CForecastDataSink.h, lib/api/CForecastRunner.cc, lib/model/CForecastDataSink.cc, lib/model/CModelDetailsView.cc
=> [ML] Correct query times for model plot and forecast (#327)

bin/data_frame_analyzer/Main.cc, include/api/CDataFrameAnalyzer.h, lib/api/CDataFrameAnalyzer.cc, lib/core/CJsonOutputStreamWrapper.cc
This fixes a couple of issues and adds writing of fake results
which allows us to test the java side before wiring in outlier
detection.
=> [FEATURE][ML] Prepare data frame analytics results writing

lib/model/CForecastDataSink.cc
=> [ML] Write out forecasts predictions at "bucket time" rather than the actual times they are made in the time buckets

docs/CHANGELOG.asciidoc, lib/maths/CPoissonMeanConjugate.cc, lib/maths/unittest/CPoissonMeanConjugateTest.cc, lib/maths/unittest/CPoissonMeanConjugateTest.h, lib/maths/unittest/testfiles/log4cxx.properties, lib/maths/unittest/testfiles/testLogErrorsLog4cxx.properties
Fix for "sample out of bounds" error generated from
CPoissonMeanConjugate
Backports #335
=> [6.6][ML] Fix for CPoissonMeanConjugate sampling error. (#335)

docs/CHANGELOG.asciidoc, include/api/CForecastRunner.h, include/model/CForecastDataSink.h, lib/api/CForecastRunner.cc, lib/model/CForecastDataSink.cc, lib/model/CModelDetailsView.cc
=> [6.5][ML] Correct query times for model plot and forecast

lib/model/CForecastDataSink.cc
=> [6.5][ML] Write out forecasts predictions at "bucket time" rather than the actual times they are made in the time buckets

doxygen/cplusplus.Doxyfile, gradle.properties
Raising this now so it's ready for 6.6 feature freeze,
although it shouldn't be merged until feature freeze
is confirmed.
=> [ML] Bumped version to 6.7.0

lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc
This is to match the java side configuration name.
=> [FEATURE][ML] Rename analysis outliers to outlier_detection

include/maths/CAnnotatedVector.h
Tidy up in preparation for merge
=> [FEATURE][ML] This todo can now be done

lib/core/CDataFrameRowSlice.cc
=> [7.1][ML] Fix the debug build

lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
=> [7.1][ML] Fix race condition in test assertion

include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameOutliersRunner.h, include/maths/CKdTree.h, include/maths/COutliers.h, include/maths/CSampling.h, include/test/CDataFrameTestUtils.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h, lib/core/unittest/CDataFrameTest.cc, lib/maths/COutliers.cc, lib/maths/unittest/COutliersTest.cc
=> [7.1][ML] Enhancements to the outlier detection ensemble

include/api/CDataFrameAnalyzer.h, lib/api/CDataFrameAnalyzer.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc
This commit implements progress reporting for the analysis.
We poll the runner for progress and we output progress as
a result type.
=> [ML] Output data frame analytics progress

include/api/CDataFrameAnalyzer.h, lib/api/CDataFrameAnalyzer.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc
This commit implements progress reporting for the analysis.
We poll the runner for progress and we output progress as
a result type.
=> [7.1][ML] Output data frame analytics progress (#389)

include/core/CDataFrame.h, include/core/CDataFrameRowSlice.h, include/maths/CDataFrameUtils.h, include/maths/COutliers.h, include/test/CDataFrameTestUtils.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.h, lib/core/CDataFrame.cc, lib/core/CDataFrameRowSlice.cc, lib/core/unittest/CDataFrameTest.cc, lib/core/unittest/CDataFrameTest.h, lib/maths/COutliers.cc, lib/maths/unittest/COutliersTest.cc
=> [7.1][ML] Out-of-core outlier detection

lib/core/Concurrency.cc
=> [7.1][ML] Prevent potential invalid read if worker throws an exception in parallel_for_each

lib/core/unittest/CConcurrentWrapperTest.cc
=> [7.1][ML] Fix race to assert and process all messages

include/maths/CKdTree.h, include/maths/COrderings.h, lib/api/CDataFrameAnalysisSpecification.cc, lib/maths/unittest/COutliersTest.cc
=> [7.1][ML] Improve performance of k-d tree nearest neighbour search

include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalyzer.h, include/api/CDataFrameOutliersRunner.h, include/maths/CLinearAlgebraShims.h, include/maths/COutliers.h, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h, lib/maths/COutliers.cc, lib/maths/unittest/COutliersTest.cc, lib/maths/unittest/COutliersTest.h
=> [7.1][ML] Features influencing outliers

include/api/CDataFrameAnalysisConfigReader.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameOutliersRunner.h, include/maths/CDataFrameUtils.h, include/maths/COutliers.h, lib/api/CDataFrameAnalysisConfigReader.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/Makefile.first, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.h, lib/maths/COutliers.cc, lib/maths/unittest/COutliersTest.cc
=> [7.1][ML] Rework user overrides for data frame analytics plus support overriding additional parameters for outlier detection

include/api/CDataFrameOutliersRunner.h, include/maths/CAnnotatedVector.h, include/maths/CKdTree.h, include/maths/COutliers.h, lib/api/CDataFrameOutliersRunner.cc, lib/maths/COutliers.cc, lib/maths/unittest/COutliersTest.cc, lib/maths/unittest/COutliersTest.h
=> [7.1][ML] Outlier memory monitoring plus improvements to memory estimation

include/core/CConcurrentQueue.h, include/core/CDataFrame.h, include/core/CStaticThreadPool.h, include/core/Concurrency.h, lib/core/CDataFrame.cc, lib/core/CStaticThreadPool.cc, lib/core/Concurrency.cc, lib/core/unittest/CStaticThreadPoolTest.cc
=> [7.1][ML] Threading optimisations

include/maths/CDataFrameUtils.h, lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CDataFrameUtilsTest.cc, lib/maths/unittest/CDataFrameUtilsTest.h
Adds the capability to compute approximate column(/feature) quantile values for a data frame. (This is a useful building block for certain types of regression model.)
=> [FEATURE][ML] Data frame column value quantile estimates

include/maths/COutliers.h, lib/maths/COutliers.cc, lib/maths/unittest/COutliersTest.cc
=> [7.1][ML] Fix some issues in memory monitoring and estimation for outlier detection

include/maths/CBayesianOptimisation.h, include/maths/CBoostedTree.h, include/maths/CDataFrameRegressionModel.h, lib/maths/CBoostedTree.cc, lib/maths/unittest/CBoostedTreeTest.cc
This is a first pass wiring hyperparameter tuning for the principle regularisation parameters of the regression tree.
=> [FEATURE][ML] Boosted tree hyperparameter tuning

include/maths/COutliers.h, lib/maths/COutliers.cc, lib/maths/unittest/COutliersTest.cc, lib/maths/unittest/COutliersTest.h
=> [ML] Improve behaviour of outlier detection with when nearly all points are duplicates

bin/data_frame_analyzer/Main.cc, include/api/CDataFrameAnalysisRunner.h, include/core/CProgramCounters.h, lib/api/CDataFrameOutliersRunner.cc, lib/core/unittest/CProgramCountersTest.cc, lib/core/unittest/CProgramCountersTest.h, lib/maths/COutliers.cc
=> [7.1][ML] Add some instrumentation of outlier detection

include/maths/CBoostedTree.h, include/maths/CDataFrameRegressionModel.h, lib/maths/CBoostedTree.cc, lib/maths/CQuantileSketch.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h
This improves various parameter initialisations. It also improves weight shrinkage. Finally, it switches to consider both the mean loss and its variation across the folds when choosing the best hyperparameter values. I've also done a lot more work on unit testing. Although there is still some more to do I think this represents a reasonable point to review.
=> [FEATURE][ML] Boosted tree improvements plus more unit testing

docs/CHANGELOG.asciidoc, lib/maths/COneOfNPrior.cc, lib/maths/CTimeSeriesModel.cc, lib/model/unittest/CEventRateModelTest.cc, lib/model/unittest/CMetricAnomalyDetectorTest.cc
=> [7.3][ML] Fix regression in QA data set

docs/CHANGELOG.asciidoc, lib/maths/CTimeSeriesModel.cc, lib/model/unittest/CEventRateAnomalyDetectorTest.cc
=> [ML] Reduce false positives associated with the multi-bucket feature

docs/CHANGELOG.asciidoc, include/maths/CPeriodicityHypothesisTests.h, include/maths/CTimeSeriesDecomposition.h, include/maths/CTimeSeriesDecompositionDetail.h, include/maths/CTimeSeriesDecompositionInterface.h, include/maths/CTimeSeriesDecompositionStub.h, include/maths/CTimeSeriesModel.h, lib/api/unittest/CAnomalyJobLimitTest.cc, lib/maths/CPeriodicityHypothesisTests.cc, lib/maths/CTimeSeriesDecomposition.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesDecompositionStub.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CForecastTest.cc, lib/maths/unittest/CTimeSeriesDecompositionTest.cc, lib/maths/unittest/CTimeSeriesModelTest.cc, lib/model/unittest/CMetricModelTest.cc
=> [7.3][ML] Improve seasonal component lifecycle for time series modelling

docs/CHANGELOG.asciidoc, include/maths/CModel.h, lib/maths/CModel.cc, lib/maths/CTimeSeriesModel.cc, lib/model/unittest/CEventRateAnomalyDetectorTest.cc
=> [7.3][ML] Reduce false positives for sum and count functions on sparse data

include/maths/COutliers.h
This fixes an oob read causing `COutliersTest::testFewPoints` to fail in a debug build.
=> [ML] Fix out-of-bounds read

lib/maths/unittest/CTimeSeriesDecompositionTest.cc
=> [7.3][ML] Fix occasional test failure

include/maths/COutliers.h
=> [7.3][ML] Fix out-of-bounds read

include/api/CDataFrameAnalyzer.h, include/core/CDataFrame.h, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.h, lib/core/CDataFrame.cc, lib/maths/CBoostedTree.cc
Proper encoding will happen later.
=> [FEATURE][ML] Read and store categorical fields

lib/api/CDataFrameAnalyzer.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc
=> [7.3][ML] Check the data frame row count is consistent with the analysis configuration

include/maths/CBoostedTree.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/maths/CBoostedTree.cc
Upfront memory estimation for boosted regression trees.
Closes elastic/ml-team#127
=> [ML] Boosted tree memory estimation

include/api/CDataFrameAnalysisConfigReader.h, include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameOutliersRunner.h, lib/api/CDataFrameAnalysisConfigReader.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h
=> [7.4][ML] Fully migrate data frame analysis parameter reader to use std::string

docs/CHANGELOG.asciidoc
This PR adds descriptions for the following PRs in the changelog:
* https://github.com/elastic/ml-cpp/pull/527
* https://github.com/elastic/ml-cpp/pull/516
https://github.com/elastic/ml-cpp/pull/489
=> Updates changelog for 7.2.1

docs/CHANGELOG.asciidoc
=> Updates changelog for 7.3

docs/CHANGELOG.asciidoc, lib/api/CDataFrameAnalyzer.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc
=> [7.4][ML] Only check that the supplied row count doesn't exceed the specified for data frame analyses

docs/CHANGELOG.asciidoc, lib/api/CDataFrameAnalyzer.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc
=> [7.3.1][ML] Only check that the supplied row count doesn't exceed the specified for data frame analyses

lib/maths/unittest/CBoostedTreeTest.cc
This is a quick win speed up for some long running boosted tree QoR unit tests. We now only check that results are equivalent between in memory and on disk data frames for one data set for each test rather than all of them. The upshot is close to a 50% speed up.
=> [ML] Slow tests speed up

include/maths/CBayesianOptimisation.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBayesianOptimisationTest.cc, lib/maths/unittest/CBayesianOptimisationTest.h, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.4][ML] Improve initialisation of boosted tree hyperparameter optimisation

lib/maths/unittest/CBoostedTreeTest.cc
=> [7.4][ML] Slow test speed ups

include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameBoostedTreeRunner.h, include/api/CDataFrameOutliersRunner.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.4][ML] Pass dependent variable for regression by name rather than column index

include/core/RestoreMacros.h, include/core/UnwrapRef.h, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h
=> [7.4][ML] Some corrections to error handling on fail to restore boosted tree training state

lib/api/CDataFrameAnalyzer.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc
=> [7.4][ML] Trap the case that no data are sent to data_frame_analyzer explicitly

include/api/CDataFrameBoostedTreeRunner.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc
=> [ML] Allow configuration of prediction column name in data_frame_analyzer

bin/data_frame_analyzer/CCmdLineParser.cc, bin/data_frame_analyzer/CCmdLineParser.h, bin/data_frame_analyzer/Main.cc, include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CMemoryUsageEstimationResultJsonWriter.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CMemoryUsageEstimationResultJsonWriter.cc, lib/api/Makefile.first, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/api/unittest/CDataFrameAnalysisRunnerTest.h, lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.cc, lib/api/unittest/CMemoryUsageEstimationResultJsonWriterTest.h, lib/api/unittest/Main.cc, lib/api/unittest/Makefile
- Introduce memory usage estimation mode in data_frame_analyzer  (#584)
=> [7.x] Introduce memory usage estimation mode in data_frame_analyzer (#584)

include/api/CDataFrameBoostedTreeRunner.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc
=> [7.4][ML] Allow configuration of prediction column name in data_frame_analyzer

include/maths/CDataFrameCategoryEncoder.h, include/maths/CDataFrameUtils.h, lib/core/CDataFrame.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.h, lib/maths/unittest/CDataFrameUtilsTest.cc
=> [7.4][ML] Consider redundancy as well as relevancy when selecting features

include/api/CDataFrameAnalyzer.h, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.h
=> [7.4][ML] Make predictions for rows missing the dependent variable value

include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CChecksum.h, include/maths/CDataFrameCategoryEncoder.h, include/maths/CDataFrameUtils.h, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CChecksum.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/CDataFrameUtils.cc, lib/maths/Makefile, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h, lib/maths/unittest/CDataFrameCategoryEncoderTest.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.h, lib/maths/unittest/CDataFrameUtilsTest.cc, lib/maths/unittest/CDataFrameUtilsTest.h
=> [7.4][ML] Wire category encoding into boosted tree training

docs/CHANGELOG.asciidoc, lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc
=> [7.x][ML] Rename outlier detection method values (#598)

lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.4][ML] Add some missing boosted tree state initialisation

include/maths/CBasicStatistics.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameUtils.h, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h, lib/maths/unittest/CDataFrameUtilsTest.cc, lib/maths/unittest/CDataFrameUtilsTest.h
=> [7.4][ML] Detect feature data types and refine candidate splits in boosted tree training based on type

include/maths/CBayesianOptimisation.h, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.4][ML] Improve hyperparameter optimisation stability

include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
This gives us a 30-50% speedup for MSE objective based on the testing I've done.
=> [ML] Check whether the splits will change before recomputing in loop building the regression forest

include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameRegressionModel.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc
I also took the opportunity to finish some comments.
=> [ML] Tag results which were used for training

include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameRegressionModel.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc
This tags regression results with `<results_field>.is_training` to
clarifies which data frame rows were used for training.
=> [7.x][ML] Tag results which were used for training (#617)

include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.4][ML] Check whether the splits will change before recomputing in loop building the regression forest

bin/data_frame_analyzer/Main.cc, include/api/CDataFrameBoostedTreeRunner.h, include/core/CProgramCounters.h, include/maths/CBayesianOptimisation.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameRegressionModel.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameRegressionModel.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h, lib/maths/unittest/COutliersTest.cc
=> [7.4][ML] Instrument the regression code for memory usage and training run time

bin/data_frame_analyzer/Main.cc
=> [7.4][ML] Log run stats at info on exit

docs/CHANGELOG.asciidoc, include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameCategoryEncoder.h, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameCategoryEncoder.cc
=> [7.5][ML] Boosted tree training performance improvements

include/maths/CBayesianOptimisation.h, include/maths/CBoostedTreeImpl.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.4][ML] Some improvements and a correction to memory estimation for boosted tree training 

include/maths/CBayesianOptimisation.h, include/maths/CBoostedTreeImpl.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.5][ML] Some improvements and a correction to memory estimation for boosted tree training

lib/maths/CBayesianOptimisation.cc
If the function evaluates to NaN then we will never initialise `xmax` in `CBayesianOptimisation::maximumExpectedImprovement` and we get undefined behaviour. With this change we instead fallback to random search.
=> [ML] Fallback to random search from maximum expected improvement search if function is NaN

include/maths/CBoostedTreeImpl.h
=> [7.5][ML] Trap out-of-bounds read in the search for the best split

include/maths/CBoostedTreeImpl.h
=> [7.4][ML] Trap out-of-bounds read in the search for the best split

lib/maths/CBayesianOptimisation.cc
=> [7.5][ML] Fallback to random search from maximum expected improvement search if function is NaN

lib/maths/CBayesianOptimisation.cc
=> [7.4][ML] Fallback to random search from maximum expected improvement search if function is NaN

lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h
=> [7.5][ML] Improve boosted tree training hyperparameter search initialisation

lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h
=> [ML] Improve boosted tree training hyperparameter search initialisation

bin/data_frame_analyzer/CCmdLineParser.cc, bin/data_frame_analyzer/CCmdLineParser.h, bin/data_frame_analyzer/Main.cc, include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameAnalyzer.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameRegressionModel.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.h, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameRegressionModel.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.5][ML] Exporting regression training state (#623)

include/maths/CBayesianOptimisation.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameCategoryEncoder.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.h, lib/maths/unittest/CDataFrameUtilsTest.cc
=> [7.5][ML] Exclude features which are unlikely to be selected during training

bin/data_frame_analyzer/CCmdLineParser.cc, bin/data_frame_analyzer/CCmdLineParser.h, bin/data_frame_analyzer/Main.cc, include/api/CDataFrameAnalysisSpecification.h, include/api/ElasticsearchStateIndex.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc
=> [7.5][ML] Refactoring of the persistence for regression (#658)

include/maths/CBayesianOptimisation.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameCategoryEncoder.h, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.h, lib/maths/unittest/CDataFrameUtilsTest.cc
=> [7.4][ML] Exclude features which are unlikely to be selected during training

lib/api/CDataFrameAnalysisSpecification.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
=> [7.x][ML] Add job id to spec reader 7x

lib/maths/unittest/CXMeansOnline1dTest.cc
Plugged a `TODO` in the clustering unit tests
=> Added unit test to CXMeansOnline1dTest.cc

include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameAnalysisSpecificationJsonWriter.h, include/api/CDataFrameBoostedTreeRunner.h, include/api/ElasticsearchStateIndex.h, include/maths/CBoostedTreeFactory.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalysisSpecificationJsonWriter.cc, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/ElasticsearchStateIndex.cc, lib/api/Makefile.first, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.h, lib/maths/CBoostedTreeFactory.cc
Same as #660 with fixed error in calling default callback functions.
=> [ML] Restore regression state from named pipe

include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameAnalysisSpecificationJsonWriter.h, include/api/CDataFrameBoostedTreeRunner.h, include/api/ElasticsearchStateIndex.h, include/maths/CBoostedTreeFactory.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalysisSpecificationJsonWriter.cc, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/ElasticsearchStateIndex.cc, lib/api/Makefile.first, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.h, lib/maths/CBoostedTreeFactory.cc
=> [7.5][ML] Restore regression state from named pipe (#677)

docs/CHANGELOG.asciidoc, include/api/CDataFrameBoostedTreeRunner.h, include/core/CLoopProgress.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.h, lib/core/CLoopProgress.cc, lib/core/unittest/CLoopProgressTest.cc, lib/core/unittest/CLoopProgressTest.h, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.5][ML] Improve boosted tree training initialisation

lib/core/CResourceLocator.cc
Fixes a bug introduced in #593
=> [ML] Fix relative location to load resources from

include/core/CMemory.h, include/model/CEventRateModel.h, include/model/CEventRatePopulationModel.h, include/model/CMetricModel.h, include/model/CMetricPopulationModel.h, lib/api/CJsonOutputWriter.cc, lib/config/CPolledDataPenalty.cc, lib/maths/CCalendarFeature.cc, lib/maths/CMultivariateOneOfNPrior.cc, lib/model/CAnnotatedProbability.cc, lib/model/CBucketGatherer.cc, lib/model/CEventRateModel.cc, lib/model/CEventRatePopulationModel.cc, lib/model/CHierarchicalResults.cc, lib/model/CMetricModel.cc, lib/model/CMetricPopulationModel.cc, lib/model/unittest/CMetricAnomalyDetectorTest.cc
Attended to a handful of warnings thrown up by `make analyze` on the library code.
Nothing too serious was thrown up - mainly uninitialised / unused variables and a few missing checks for `nullptr`
=> [ML] Fix problems found by static code analysis

include/core/CMemory.h, include/model/CEventRateModel.h, include/model/CEventRatePopulationModel.h, include/model/CMetricModel.h, include/model/CMetricPopulationModel.h, lib/api/CJsonOutputWriter.cc, lib/config/CPolledDataPenalty.cc, lib/maths/CCalendarFeature.cc, lib/maths/CMultivariateOneOfNPrior.cc, lib/model/CAnnotatedProbability.cc, lib/model/CBucketGatherer.cc, lib/model/CEventRateModel.cc, lib/model/CEventRatePopulationModel.cc, lib/model/CHierarchicalResults.cc, lib/model/CMetricModel.cc, lib/model/CMetricPopulationModel.cc, lib/model/unittest/CMetricAnomalyDetectorTest.cc
Attended to static code analysis warnings
Backports #695
=> [7.5][ML] Fix problems found by static code analysis (#695)

include/core/CMemory.h, include/model/CEventRateModel.h, include/model/CEventRatePopulationModel.h, include/model/CMetricModel.h, include/model/CMetricPopulationModel.h, lib/api/CJsonOutputWriter.cc, lib/config/CPolledDataPenalty.cc, lib/maths/CCalendarFeature.cc, lib/maths/CMultivariateOneOfNPrior.cc, lib/model/CAnnotatedProbability.cc, lib/model/CBucketGatherer.cc, lib/model/CEventRateModel.cc, lib/model/CEventRatePopulationModel.cc, lib/model/CHierarchicalResults.cc, lib/model/CMetricModel.cc, lib/model/CMetricPopulationModel.cc, lib/model/unittest/CMetricAnomalyDetectorTest.cc
Attended to static code analysis warnings
Backports #695
=> [7.4][ML] Fix problems found by static code analysis (#695)

include/core/CMemory.h, include/model/CEventRateModel.h, include/model/CEventRatePopulationModel.h, include/model/CMetricModel.h, include/model/CMetricPopulationModel.h, lib/api/CJsonOutputWriter.cc, lib/config/CPolledDataPenalty.cc, lib/maths/CCalendarFeature.cc, lib/maths/CMultivariateOneOfNPrior.cc, lib/model/CAnnotatedProbability.cc, lib/model/CBucketGatherer.cc, lib/model/CEventRateModel.cc, lib/model/CEventRatePopulationModel.cc, lib/model/CHierarchicalResults.cc, lib/model/CMetricModel.cc, lib/model/CMetricPopulationModel.cc, lib/model/unittest/CMetricAnomalyDetectorTest.cc
Attended to static code analysis warnings
Backports #695
=> [6.8][ML] Fix problems found by static code analysis (#695)

docs/CHANGELOG.asciidoc, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameCategoryEncoder.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h
=> [7.5][ML] Depth based regularisation for boosted tree training

lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h
=> [7.5][ML] Trap out-of-bounds read initialising boosted tree training

include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameAnalyzer.h, include/api/CDataFrameBoostedTreeRunner.h, include/api/CDataFrameClassificationRunner.h, include/api/CDataFrameOutliersRunner.h, include/api/CDataFrameRegressionRunner.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/CDataFrameClassificationRunner.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/CDataFrameRegressionRunner.cc, lib/api/Makefile.first, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/api/unittest/CDataFrameAnalysisRunnerTest.h, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.h, lib/api/unittest/CDataFrameMockAnalysisRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h
- Introduce classification analysis runner.  (#701)
=> [7.x] Introduce classification analysis runner. (#701)

docs/CHANGELOG.asciidoc, include/maths/CModel.h, include/model/CAnomalyDetectorModelConfig.h, include/model/CIndividualModel.h, include/model/CModelParams.h, include/model/ModelTypes.h, lib/maths/CModel.cc, lib/maths/CPeriodicityHypothesisTests.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CForecastTest.cc, lib/maths/unittest/CModelTest.cc, lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc, lib/maths/unittest/CTimeSeriesModelTest.cc, lib/model/CAnomalyDetectorModelConfig.cc, lib/model/CEventRateModel.cc, lib/model/CEventRatePopulationModel.cc, lib/model/CIndividualModel.cc, lib/model/CMetricModel.cc, lib/model/CMetricPopulationModel.cc, lib/model/CModelDetailsView.cc, lib/model/CModelParams.cc, lib/model/CProbabilityAndInfluenceCalculator.cc, lib/model/ModelTypes.cc, lib/model/unittest/CEventRateAnomalyDetectorTest.cc, lib/model/unittest/CEventRateModelTest.cc, lib/model/unittest/CModelToolsTest.cc, lib/model/unittest/CProbabilityAndInfluenceCalculatorTest.cc
=> [7.5][ML] Improvements to sparse count modelling

docs/CHANGELOG.asciidoc, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CTools.h, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.h, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h
=> [7.5][ML] Logistic regression loss function for boosted tree training

include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameAnalyzer.h, include/api/CDataFrameBoostedTreeRunner.h, include/api/CDataFrameClassificationRunner.h, include/api/CDataFrameOutliersRunner.h, include/api/CDataFrameRegressionRunner.h, include/core/CDataFrame.h, include/maths/CBoostedTreeFactory.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/CDataFrameClassificationRunner.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/CDataFrameRegressionRunner.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.h, lib/api/unittest/CDataFrameMockAnalysisRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h, lib/core/CDataFrame.cc, lib/core/unittest/CDataFrameTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.cc, lib/maths/unittest/CDataFrameUtilsTest.cc
=> [7.5][ML] Wire in binomial logistic regression

lib/maths/CBoostedTreeImpl.cc
Add the description of #732 as an inline comment for posterity.
=> [ML] Add comment for fixing numeric

include/maths/CBoostedTree.h, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h
Properly handle numeric errors in the calculation of logistic loss related functions.
=> [ML] Improve logistic regression numerics

docs/CHANGELOG.asciidoc, lib/maths/CBoostedTreeImpl.cc
=> [7.5][ML] Add comment for fixing numeric

include/maths/CBoostedTree.h, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h
=> [7.5][ML] Improve logistic regression numerics

include/api/CBoostedTreeRegressionInferenceModelBuilder.h, include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameAnalyzer.h, include/api/CDataFrameBoostedTreeRunner.h, include/api/CInferenceModelDefinition.h, include/core/CRapidJsonLineWriter.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameCategoryEncoder.h, lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/CInferenceModelDefinition.cc, lib/api/Makefile.first, lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.cc, lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.h, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/Main.cc, lib/api/unittest/Makefile, lib/api/unittest/testfiles/inference_json_schema/definition.schema.combined.json, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/unittest/CBoostedTreeTest.cc
Re-attempt to merge #694
Waiting for changes on the Java side.
=> [ML]Merge inference definition

include/api/CBoostedTreeRegressionInferenceModelBuilder.h, include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameAnalyzer.h, include/api/CDataFrameBoostedTreeRunner.h, include/api/CInferenceModelDefinition.h, include/core/CRapidJsonLineWriter.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameCategoryEncoder.h, lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/CInferenceModelDefinition.cc, lib/api/Makefile.first, lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.cc, lib/api/unittest/CBoostedTreeRegressionInferenceModelBuilderTest.h, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/api/unittest/Main.cc, lib/api/unittest/Makefile, lib/api/unittest/testfiles/inference_json_schema/definition.schema.combined.json, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.6][ML] Merge inference definition

lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBoostedTreeImpl.cc
=> [7.6][ML] Snapshot boosted tree training state after final train

lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBoostedTreeImpl.cc
=> [7.5][ML] Snapshot boosted tree training state after final train

include/api/CBoostedTreeInferenceModelBuilder.h, include/api/CInferenceModelDefinition.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/api/CBoostedTreeRegressionInferenceModelBuilder.cc, lib/api/CInferenceModelDefinition.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
=> [7.6][ML] Fix categorization bug (#748)

include/api/CInferenceModelDefinition.h, include/core/CRapidJsonLineWriter.h, lib/api/CInferenceModelDefinition.cc
=> [7.6][ML] Fix VS linking problem

bin/data_frame_analyzer/Main.cc, include/api/CDataFrameBoostedTreeRunner.h, include/core/CProgramCounters.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameCategoryEncoder.h, include/maths/CDataFrameUtils.h, include/maths/CSampling.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/CDataFrameClassificationRunner.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h, lib/maths/unittest/CDataFrameUtilsTest.cc, lib/maths/unittest/CDataFrameUtilsTest.h
=> [7.6][ML] Better handling of unbalanced class representation in the training data

bin/data_frame_analyzer/Main.cc, include/api/CDataFrameBoostedTreeRunner.h, include/core/CProgramCounters.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameCategoryEncoder.h, include/maths/CDataFrameUtils.h, include/maths/CSampling.h, lib/api/CDataFrameBoostedTreeRunner.cc, lib/api/CDataFrameClassificationRunner.cc, lib/api/unittest/CDataFrameAnalyzerTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CBoostedTreeTest.h, lib/maths/unittest/CDataFrameUtilsTest.cc, lib/maths/unittest/CDataFrameUtilsTest.h
=> [7.5][ML] Better handling of unbalanced class representation in the training data

include/api/CInferenceModelDefinition.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/api/CInferenceModelDefinition.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.h
=> [7.6][ML] Fix categorization encoding error

lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/api/CInferenceModelDefinition.cc
=> [7.6][ML] Remove explicit filtering of the target column 

include/maths/CDataFrameCategoryEncoder.h, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.h
=> [7.5][ML] Always identity encode the target variable

include/maths/CDataFrameCategoryEncoder.h, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.cc, lib/maths/unittest/CDataFrameCategoryEncoderTest.h
=> [7.6][ML] Always identity encode the target variable

lib/api/CDataFrameClassificationRunner.cc, lib/api/CDataFrameRegressionRunner.cc, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/api/unittest/CDataFrameAnalysisRunnerTest.h, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
=> [7.5][ML] Better error handling for data frame train model

lib/api/CDataFrameClassificationRunner.cc, lib/api/CDataFrameRegressionRunner.cc, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/api/unittest/CDataFrameAnalysisRunnerTest.h, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
=> [7.6][ML] Better error handling for data frame train model

include/core/CLogger.h, lib/core/CLogger.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.6][ML] Refactor CLogger to use custom stream 

lib/api/CInferenceModelDefinition.cc
=> [7.6][ML] No need to explicitly move a temporary

docs/CHANGELOG.asciidoc, include/maths/CBoostedTreeImpl.h, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTreeImpl.cc
=> [ML] Reduce peak memory usage and improve estimation for boosted tree training

lib/maths/unittest/CXMeansOnline1dTest.cc
Plugged a `TODO` in the clustering unit tests
Backport of #673
=> [7.x] Added unit test to CXMeansOnline1dTest.cc

docs/CHANGELOG.asciidoc, include/maths/CBoostedTreeFactory.h, include/maths/CDataFrameUtils.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CDataFrameUtilsTest.cc
=> [7.6][ML] Stratified cross validation for regression

lib/core/unittest/CNamedPipeFactoryTest.cc, lib/core/unittest/COsFileFuncsTest.cc
=> [ML] Fix some Windows-specific cases of no assertions in tests

include/api/CBoostedTreeInferenceModelBuilder.h, include/api/CInferenceModelDefinition.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CInferenceModelDefinition.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
This PR adds information about `classification_labels` to the inference definition for classifiers.
Closes #785
=> [ML] Add classification labels for classification definition

include/api/CBoostedTreeInferenceModelBuilder.h, include/api/CInferenceModelDefinition.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CInferenceModelDefinition.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc
This PR adds information about classification_labels to the inference definition for classifiers.
Backport to #793
=> [ML] Add classification labels for classification definition (#793)

lib/model/CEventRateModel.cc, lib/model/CIndividualModel.cc, lib/model/CMetricModel.cc
=> [7.6][ML] Handle upgrade state to 7.5 to account for sparse count modelling changes

lib/model/CEventRateModel.cc, lib/model/CIndividualModel.cc, lib/model/CMetricModel.cc
=> [7.5][ML] Handle upgrade state to 7.5 to account for sparse count modelling changes

docs/CHANGELOG.asciidoc, include/maths/CSeasonalTime.h, lib/maths/CSeasonalTime.cc, lib/maths/unittest/CSeasonalTimeTest.cc, lib/maths/unittest/Makefile
=> [7.6][ML] Fix restore from checkpoint damaging seasonality modelling for anomaly detection

docs/CHANGELOG.asciidoc, include/maths/CSeasonalTime.h, lib/maths/CSeasonalTime.cc, lib/maths/unittest/CSeasonalTimeTest.cc, lib/maths/unittest/CSeasonalTimeTest.h, lib/maths/unittest/Main.cc, lib/maths/unittest/Makefile
=> [7.5][ML] Fix restore from checkpoint damaging seasonality modelling for anomaly detection

bin/data_frame_analyzer/Main.cc
- Remove duplicated code  (#799)
=> [7.x] Remove duplicated code (#799)

README.md, build-setup/macos.md
=> [ML]Documented developing, building and running the `ml-cpp` project

include/api/CDataFrameOutliersRunner.h, include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/api/CDataFrameTrainBoostedTreeRegressionRunner.h, include/api/CDataFrameTrainBoostedTreeRunner.h, include/test/CDataFrameAnalysisSpecificationFactory.h, lib/api/CDataFrameAnalysisSpecificationJsonWriter.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc
=> [7.6][ML] Tidy up test analysis specification writing

docs/CHANGELOG.asciidoc, include/api/CDataFrameTrainBoostedTreeRunner.h, include/core/CLoopProgress.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameRegressionModel.h, include/maths/CDataFrameUtils.h, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/core/CLoopProgress.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CDataFrameUtilsTest.cc
=> [7.6][ML] Stochastic derivatives for boosted tree training

include/api/CDataFrameTrainBoostedTreeRunner.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeHyperparameters.h, include/maths/CBoostedTreeImpl.h, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeHyperparameters.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/Makefile
=> [7.6][ML] Add unit test checks for new hyperparameters in supervised learning

lib/maths/CBoostedTreeImpl.cc
=> [7.6][ML] Log best hyperparameters and runtime summary (#864)

docs/CHANGELOG.asciidoc, include/core/CDataFrame.h, include/core/CFloatStorage.h, include/core/CImmutableRadixSet.h, include/maths/CBoostedTreeHyperparameters.h, include/maths/CBoostedTreeImpl.h, include/maths/CBoundingBox.h, include/maths/CKdTree.h, include/maths/CQuantileSketch.h, lib/core/CDataFrame.cc, lib/core/unittest/CImmutableRadixSetTest.cc, lib/core/unittest/Makefile, lib/maths/CBoostedTreeImpl.cc, lib/maths/CQuantileSketch.cc, lib/maths/CSignal.cc, lib/maths/CTimeSeriesDecompositionDetail.cc
=> [7.6][ML] Assorted runtime optimisations for classification and regression

docs/CHANGELOG.asciidoc, include/core/CImmutableRadixSet.h, include/core/CPackedBitVector.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeHyperparameters.h, include/maths/CBoostedTreeImpl.h, include/test/CDataFrameAnalysisSpecificationFactory.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeHyperparameters.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.6][ML] Stop early (based on non-decreasing validation error) when adding trees to the regression/classification forest

dev-tools/check-style.sh, lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc
This PR makes style-related error messages colored in red making them stand out in the console out.
=> Color style-related error messages in console output

lib/maths/unittest/CBoostedTreeTest.cc
Fixes unit test failures on mac CI builds.
=> [ML] Adjusts thresholds in CBoostedTreeTest

lib/maths/unittest/CBoostedTreeTest.cc
[ML][7.6]Fixes unit test failures on mac CI builds.
Backports #884
=> [ML] Adjusts thresholds in CBoostedTreeTest (#884)

include/api/CDataFrameTrainBoostedTreeRunner.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameCategoryEncoder.h, include/maths/CDataFrameRegressionModel.h, include/maths/CTreeShapFeatureImportance.h, include/test/CDataFrameAnalysisSpecificationFactory.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/api/unittest/Makefile, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/CDataFrameRegressionModel.cc, lib/maths/CTreeShapFeatureImportance.cc, lib/maths/Makefile, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc, lib/maths/unittest/Makefile, lib/test/CDataFrameAnalysisSpecificationFactory.cc
=> [7.6][ML] Compute SHAP values for supervised learning (#857)

lib/maths/CBoostedTreeImpl.cc
The stopwatch lap function returns the accumulated time to date. Note, this code hasn't been released.
=> [ML] Fix the train model per loop run time estimate

include/maths/CDataFrameRegressionModel.h, include/maths/COutliers.h, lib/maths/CBoostedTreeImpl.cc, lib/maths/COutliers.cc
=> [7.6][ML] Switch the record memory callback to use a signed type for memory

lib/maths/CBoostedTreeImpl.cc
=> [7.6][ML] Fix the train model per loop run time estimate

docs/CHANGELOG.asciidoc, include/api/CDataFrameTrainBoostedTreeRunner.h, include/core/CFloatStorage.h, include/maths/CBoostedTree.h, include/maths/CPRNG.h, include/maths/CQuantileSketch.h, include/maths/CTreeShapFeatureImportance.h, lib/maths/CBoostedTreeImpl.cc, lib/maths/CPRNG.cc, lib/maths/CQuantileSketch.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CCalendarCyclicTestTest.cc, lib/maths/unittest/CQuantileSketchTest.cc
=> [7.6][ML] Faster quantile estimation

include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameRegressionModel.h, include/maths/CTreeShapFeatureImportance.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CTreeShapFeatureImportance.cc, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
=> [7.6][ML] Cleaning-up SHAP estimation

include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameRegressionModel.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTree.cc, lib/maths/unittest/CBoostedTreeTest.cc
This adds in unit testing for the case that some of the feature values are missing. I also tidied up the interface to get the prediction column.
=> [ML] Test missing feature values when training a regression model

docs/CHANGELOG.asciidoc, include/api/CDataFrameTrainBoostedTreeRunner.h, include/maths/CBasicStatistics.h, include/maths/CBayesianOptimisation.h, include/maths/CBoostedTreeFactory.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBayesianOptimisationTest.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.6][ML] Early stopping in the line searches to compute initial regulariser values

include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameRegressionModel.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTree.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.6][ML] Test missing feature values when training a regression model

docs/CHANGELOG.asciidoc
=> [7.6][ML] Add CHANGELOG entry for SHAP feature 

lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/maths/CDataFrameRegressionModel.cc
=> [7.6][ML] Rename result shap prefix

lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/maths/CBoostedTreeImpl.cc
=> [7.6][ML] Fix return of SHAP values for dependent variable issue 

lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
Recent changes in #920 caused `CDataFrameAnalyzerFeatureImportanceTest/testRunBoostedTreeRegressionFeatureImportanceNoImportance` to segfault, since it was trying to access non-existing json members in the result. This PR fixes this.
=> [ML] Fix unit test segfault

lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
=> [7.6][ML] Fix unit test segfault 

docs/CHANGELOG.asciidoc, include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFramePredictiveModel.h, include/maths/CDataFrameUtils.h, include/maths/CSolvers.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFramePredictiveModel.cc, lib/maths/CDataFrameUtils.cc, lib/maths/Makefile, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.6][ML] Set the class assignment probability threshold to maximise minimum recall

include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/api/CDataFrameTrainBoostedTreeRegressionRunner.h, include/test/CDataFrameAnalysisSpecificationFactory.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc, lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc
=> [7.7][ML] Correct top class probabilities

include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/api/CDataFrameTrainBoostedTreeRegressionRunner.h, include/test/CDataFrameAnalysisSpecificationFactory.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc, lib/api/unittest/CDataFrameTrainBoostedTreeRegressionRunnerTest.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc
=> [7.6][ML] Correct top class probabilities

include/maths/CBoostedTreeHyperparameters.h
=> [ML] Default initialise the best hyperparameters

lib/maths/CBoostedTree.cc, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
=> [7.7][ML] Fix invalid read in tests

lib/maths/CBoostedTree.cc, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
=> [7.6][ML] Fix invalid read in tests

lib/api/CDataFrameAnalysisSpecification.cc
=> [7.7][ML] Downgrade noisy logging to trace

lib/api/CDataFrameAnalysisSpecification.cc
=> [7.6][ML] Downgrade noisy logging to trace

docs/CHANGELOG.asciidoc, include/core/CLoopProgress.h, include/maths/CBoostedTreeFactory.h, lib/core/CLoopProgress.cc, lib/core/unittest/CLoopProgressTest.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.7][ML] Line search for best learn rate

lib/maths/CBoostedTreeFactory.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.7][ML] Bug in bounds calculation for the main hyperparameter optimisation search

lib/maths/CBoostedTreeFactory.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.6][ML] Bug in bounds calculation for the main hyperparameter optimisation search

include/api/CInferenceModelDefinition.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/api/CInferenceModelDefinition.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc, lib/api/unittest/testfiles/inference_json_schema/model_definition.schema.json
Following changes of @benwtrent in the inference model definition, this PR updates the definition file in the corresponding unit test.
=> [ML] Update the inference schema model definition unit test

include/api/CInferenceModelDefinition.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/api/CInferenceModelDefinition.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc, lib/api/unittest/testfiles/inference_json_schema/model_definition.schema.json
=> [ML] Update the inference schema model definition unit test 

include/api/CDataFrameAnalysisInstrumentation.h, include/maths/CBoostedTree.h, include/maths/CDataFrameAnalysisInstrumentationInterface.h, include/maths/COutliers.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
This anticipates wanting to support loss functions with multiple parameters, i.e. multinomial logistic regression. I'm making these non-functional changes upfront since we're considering adding other loss functions in the 7.7 timeframe and they need to conform to the new interfaces.
=> [ML] Interface changes to support multi-parameter loss functions

include/api/CDataFrameAnalysisInstrumentation.h, include/maths/CBoostedTree.h, include/maths/CDataFrameAnalysisInstrumentationInterface.h, include/maths/COutliers.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.7][ML] Interface changes to support multi-parameter loss functions

include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/api/CDataFrameTrainBoostedTreeRegressionRunner.h, include/api/CDataFrameTrainBoostedTreeRunner.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.7][ML] Rework caching and reading predictions and derivatives in boosted tree training to anticipate multiple values

include/maths/CBoostedTreeImpl.h, include/maths/CBoostedTreeLeafNodeStatistics.h, include/maths/CBoostedTreeUtils.h, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLeafNodeStatistics.cc, lib/maths/CBoostedTreeUtils.cc, lib/maths/Makefile
=> [7.7][ML] Split up CBoostedTreeImpl

docs/CHANGELOG.asciidoc, include/api/CDataFrameAnalysisInstrumentation.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameAnalysisInstrumentationInterface.h, include/maths/CDataFramePredictiveModel.h, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/COutliersTest.cc
=> [7.7][ML] Account for data frame memory in the peak memory usage estimate for classification and regression

include/maths/CBoostedTree.h, include/maths/CBoostedTreeLeafNodeStatistics.h, include/maths/CBoostedTreeUtils.h, include/maths/CLinearAlgebraEigen.h, include/maths/CLinearAlgebraShims.h, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLeafNodeStatistics.cc, lib/maths/CBoostedTreeUtils.cc, lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/Makefile
=> [7.7][ML] Support for multi-parameter loss functions in derivative aggregation and finding best splits

lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
#991 together with #993 are causing test failures on Windows.
=> [ML] Test threshold fix

lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
=> [7.7][ML] Test threshold fix

lib/maths/CBoostedTreeFactory.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.7][ML] Fix a bug with progress reporting during model training

docs/CHANGELOG.asciidoc, include/api/CDataFrameAnalysisInstrumentation.h, include/maths/CDataFrameAnalysisInstrumentationInterface.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h, lib/maths/CBoostedTreeImpl.cc, lib/maths/COutliers.cc
=> [7.7][ML] Improvements to upfront memory estimation for data frame analyses

include/api/CBoostedTreeInferenceModelBuilder.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, include/maths/CLinearAlgebraEigen.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CTreeShapFeatureImportance.cc, lib/maths/unittest/CLinearAlgebraTest.cc, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
This leaves open the tasks of updating the inference model definition and tree SHAP for which I've left TODOs.
This is the next step towards #982.
=> [ML] Extend boosted tree node to support multiple values

include/api/CInferenceModelDefinition.h, include/maths/CDataFrameCategoryEncoder.h, include/maths/CLinearAlgebraEigen.h, include/maths/CTreeShapFeatureImportance.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/api/CInferenceModelDefinition.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc, lib/api/unittest/testfiles/inference_json_schema/model_definition.schema.json, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/CTreeShapFeatureImportance.cc, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
Also, some more groundwork for SHAP.
Another step towards #982.
=> [ML] Extend inference model serialisation to support multivalued leaves

include/api/CBoostedTreeInferenceModelBuilder.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, include/maths/CLinearAlgebraEigen.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CTreeShapFeatureImportance.cc, lib/maths/unittest/CLinearAlgebraTest.cc, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
=> [7.7][ML] Extend boosted tree node to support multiple values

include/api/CInferenceModelDefinition.h, include/maths/CDataFrameCategoryEncoder.h, include/maths/CLinearAlgebraEigen.h, include/maths/CTreeShapFeatureImportance.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/api/CInferenceModelDefinition.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc, lib/api/unittest/testfiles/inference_json_schema/model_definition.schema.json, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/CTreeShapFeatureImportance.cc, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
=> [7.7][ML] Extend inference model serialisation to support multivalued leaves

docs/CHANGELOG.asciidoc, include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/api/CDataFrameTrainBoostedTreeRunner.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFramePredictiveModel.h, include/maths/CTreeShapFeatureImportance.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFramePredictiveModel.cc, lib/maths/CTreeShapFeatureImportance.cc, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
=> [7.7][ML] Rework computing SHAP to avoid using data frame storage

docs/CHANGELOG.asciidoc, include/maths/CBoostedTreeLoss.h, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLoss.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.7][ML] Correct logistic loss function

docs/CHANGELOG.asciidoc, include/api/CDataFrameAnalysisInstrumentation.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h, lib/api/unittest/Makefile
=> [7.7][ML] Format memory instrumentation output

lib/maths/CBoostedTreeLoss.cc
Since I've factored out the unit tests in #1037 I'll add a test for this case after that is merged. I've marked this as a non-issue because the problem was introduced in #993 which isn't released.
=> [ML] Error in handling of precision loss in logistic loss gradient and curvature

lib/maths/CBoostedTreeLoss.cc
=> [7.7][ML] Fix handling of numerical precision loss in logistic loss gradient and curvature

lib/api/CDataFrameAnalysisInstrumentation.cc
=> [7.7][ML] Don't write memory usage

include/core/CDataFrame.h, include/maths/CDataFrameUtils.h, lib/core/CDataFrame.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CDataFrameUtilsTest.cc
=> [7.7][ML] Correct missing category handling

include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/core/CDataFrame.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/core/CDataFrame.cc
=> [7.7][ML] Remove special case handling for missing target field

include/api/CDataFrameAnalysisInstrumentation.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameAnalyzer.h, include/core/CRapidJsonConcurrentLineWriter.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc
=> [7.7][ML] Start writing memory usage again

docs/CHANGELOG.asciidoc, include/maths/CBoostedTreeLoss.h, include/maths/CKMeans.h, include/maths/CKMeansOnline.h, include/maths/CLinearAlgebraEigen.h, include/maths/CLinearAlgebraShims.h, include/maths/CTools.h, include/maths/CToolsDetail.h, include/maths/CXMeansOnline.h, include/maths/Constants.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLoss.cc, lib/maths/unittest/CBoostedTreeLossTest.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CDataFrameUtilsTest.cc, lib/maths/unittest/CKMeansOnlineTest.cc, lib/maths/unittest/CMultivariateMultimodalPriorTest.cc, lib/maths/unittest/CXMeansOnlineTest.cc, lib/maths/unittest/Makefile
=> [7.7][ML] Multinomial logistic regression

include/api/CDataFrameTrainBoostedTreeRunner.h, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc
=> [7.x][ML] Remove deprecated maximum_number_trees (#1051)

include/api/CBoostedTreeInferenceModelBuilder.h, include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/api/CInferenceModelDefinition.h, include/maths/CBasicStatistics.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeImpl.h, include/maths/CBoostedTreeLoss.h, include/maths/CDataFramePredictiveModel.h, include/maths/CDataFrameUtils.h, include/maths/CInformationCriteria.h, include/maths/CKMeans.h, include/maths/CLinearAlgebra.h, include/maths/CLinearAlgebraEigen.h, include/maths/CLinearAlgebraShims.h, include/test/CDataFrameAnalysisSpecificationFactory.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/CInferenceModelDefinition.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLeafNodeStatistics.cc, lib/maths/CBoostedTreeLoss.cc, lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc
=> [7.7][ML] Wire in multiclass classification to the data frame analyzer command

docs/CHANGELOG.asciidoc, include/maths/CBoostedTree.h, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.6][ML] Correct logistic loss function

lib/maths/CBoostedTreeLoss.cc, lib/maths/unittest/CBoostedTreeLossTest.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.7][ML] Fix some bugs in multinomial logistic loss derivatives

include/maths/CBoostedTreeLeafNodeStatistics.h, include/maths/CLinearAlgebraEigen.h, lib/maths/CBoostedTreeLeafNodeStatistics.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.7][ML] Better handling of near singular loss Hessian

lib/maths/CBoostedTreeImpl.cc
=> [7.7][ML] Fix the maximum accuracy objective for binary classification

include/maths/CBoostedTreeLoss.h, include/maths/CLbfgs.h, include/maths/CTools.h, include/maths/CToolsDetail.h, lib/api/CDataFrameAnalysisSpecification.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLoss.cc, lib/maths/unittest/CBoostedTreeLossTest.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CToolsTest.cc
=> [7.7][ML] Speed ups for multiclass classification

docs/CHANGELOG.asciidoc, include/api/CDataFrameAnalysisInstrumentation.h, include/maths/CDataFrameAnalysisInstrumentationInterface.h, include/maths/COutliers.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc, lib/api/unittest/testfiles/instrumentation/outlier_detection_stats.schema.json, lib/maths/COutliers.cc
This PR implements the initial instrumentation of the outlier detection code. Instrumentation information is posted only once on completion of the outlier score computation.
Closes #976
=> [ML] Instrumentation for outlier detection

docs/CHANGELOG.asciidoc, include/api/CDataFrameAnalysisInstrumentation.h, include/maths/CDataFrameAnalysisInstrumentationInterface.h, include/maths/COutliers.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc, lib/api/unittest/testfiles/instrumentation/outlier_detection_stats.schema.json, lib/maths/COutliers.cc
This PR implements the initial instrumentation of the outlier detection code. Instrumentation information is posted only once on completion of the outlier score computation.
Backport of #1068.
=> [7.x][ML] Instrumentation for outlier detection

include/maths/CBoostedTreeLoss.h, include/maths/CKMeans.h, include/maths/CKMeansOnline.h, include/maths/CKdTree.h, include/maths/CLinearAlgebraShims.h, lib/maths/CBoostedTreeLoss.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CKMeansOnlineTest.cc, lib/maths/unittest/CKMeansTest.cc, lib/maths/unittest/CMultivariateMultimodalPriorTest.cc, lib/maths/unittest/CXMeansOnlineTest.cc
=> [7.7][ML] More speed ups for multiclass classification

lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
Activates instrumentation output and corresponding unit tests.
=> [ML] Activate instrumentation output

lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc
Activates instrumentation output and corresponding unit tests.
Backport of #1076.
=> [7.x][ML] Activate instrumentation output

include/maths/CBoostedTreeLoss.h, include/maths/CSampling.h, lib/maths/CBoostedTreeLoss.cc, lib/maths/CDataFrameUtils.cc, lib/maths/COutliers.cc, lib/maths/CSampling.cc, lib/maths/unittest/CSamplingTest.cc
=> [7.8][ML] Rework the approximate loss function for choosing leaf values for multiclass classification

include/maths/CBoostedTreeLoss.h, include/maths/CSampling.h, lib/maths/CBoostedTreeLoss.cc, lib/maths/CDataFrameUtils.cc, lib/maths/COutliers.cc, lib/maths/CSampling.cc, lib/maths/unittest/CSamplingTest.cc
=> [7.7][ML] Rework the approximate loss function for choosing leaf values for multiclass classification

include/maths/CLbfgs.h, include/maths/CLinearAlgebraEigen.h, include/maths/CTools.h, include/maths/CToolsDetail.h, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTreeLoss.cc, lib/maths/unittest/CBoostedTreeLossTest.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CToolsTest.cc
=> [7.8][ML] Avoid temporaries in vector expressions

include/maths/CLbfgs.h, include/maths/CLinearAlgebraEigen.h, include/maths/CTools.h, include/maths/CToolsDetail.h, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/maths/CBayesianOptimisation.cc, lib/maths/CBoostedTreeLoss.cc, lib/maths/unittest/CBoostedTreeLossTest.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CToolsTest.cc
=> [7.7][ML] Avoid temporaries in vector expressions

include/api/CDataFrameAnalysisInstrumentation.h, include/maths/CSampling.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
Note also that the default case generates a compiler warning for me because all enums are explicitly handled.
The error is in test code only and also isn't released so I've marked as a non-issue.
=> [ML] Fix out-of-bounds read in multiclass feature importance unit test

include/api/CDataFrameAnalysisInstrumentation.h, include/maths/CSampling.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
=> [7.8][ML] Fix out-of-bounds read in multiclass feature importance unit test

include/api/CDataFrameAnalysisInstrumentation.h, include/maths/CSampling.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
=> [7.7][ML] Fix out-of-bounds read in multiclass feature importance unit test

lib/api/CDataFrameAnalyzer.cc
This PR adds logging for computing results and writing the output. It aims to tell what's going on, if the job is stuck in the final phase in it takes a while (feature importance computation). I give a log info message at the beginning and at the end of computing results. Also every 20000 rows I produce an intermediate log debug message with timing and progress.
Backport of #1079
=> [7.7][ML] Logging additional information for results

lib/api/CDataFrameAnalyzer.cc
This PR adds logging for computing results and writing the output. It aims to tell what's going on, if the job is stuck in the final phase in it takes a while (feature importance computation). I give a log info message at the beginning and at the end of computing results. Also every 20000 rows I produce an intermediate log debug message with timing and progress.
Backport of #1079
=> [7.x][ML] Logging additional information for results (#1079)

include/maths/CBoostedTreeLoss.h, lib/maths/CBoostedTreeLoss.cc, lib/maths/unittest/CBoostedTreeLossTest.cc
=> [7.7][ML] Speedup calculating leaf values for multiclass classification

include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/api/CDataFrameTrainBoostedTreeRunner.h, include/maths/CBoostedTreeFactory.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/testfiles/instrumentation/classification_stats.schema.json, lib/api/unittest/testfiles/instrumentation/regression_stats.schema.json, lib/maths/CBoostedTreeFactory.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc
=> [7.8][ML] Instrumentation parameter names should match analysis config where applicable

include/maths/CBoostedTreeLoss.h, lib/maths/CBoostedTreeLoss.cc, lib/maths/unittest/CBoostedTreeLossTest.cc
=> [7.8][ML] Speedup calculating leaf values for multiclass classification

include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/api/CDataFrameTrainBoostedTreeRunner.h, include/maths/CBoostedTreeFactory.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/testfiles/instrumentation/classification_stats.schema.json, lib/api/unittest/testfiles/instrumentation/regression_stats.schema.json, lib/maths/CBoostedTreeFactory.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc
=> [7.7][ML] Instrumentation parameter names should match analysis config where applicable

docs/CHANGELOG.asciidoc, include/api/CFieldDataCategorizer.h, include/api/CJsonOutputWriter.h, include/model/CDataCategorizer.h, include/model/CTokenListCategory.h, include/model/CTokenListDataCategorizerBase.h, lib/api/CFieldDataCategorizer.cc, lib/api/CJsonOutputWriter.cc, lib/api/unittest/CFieldDataCategorizerTest.cc, lib/api/unittest/CJsonOutputWriterTest.cc, lib/model/CTokenListCategory.cc, lib/model/CTokenListDataCategorizerBase.cc, lib/model/unittest/CTokenListDataCategorizerTest.cc
- [ML] Adding num_matches and preferred_to_categories output to categories (#1062)
=> [7.x] [ML] Adding num_matches and preferred_to_categories output to categories (#1062)

docs/CHANGELOG.asciidoc, lib/maths/CGammaRateConjugate.cc, lib/maths/CLogNormalMeanPrecConjugate.cc, lib/maths/CNormalMeanPrecConjugate.cc, lib/maths/COneOfNPrior.cc, lib/maths/CPoissonMeanConjugate.cc, lib/maths/CPrior.cc
=> [7.8][ML] Improve bad input handling in distribution models

docs/CHANGELOG.asciidoc, include/api/CDataFrameTrainBoostedTreeRegressionRunner.h, include/maths/CBoostedTreeLoss.h, include/test/CDataFrameAnalysisSpecificationFactory.h, include/test/CDataFrameAnalyzerTrainingFactory.h, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLoss.cc, lib/maths/unittest/CBoostedTreeLossTest.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc, lib/test/CDataFrameAnalyzerTrainingFactory.cc
This PR implements mean squared logarithmic error loss function for regression. It also adds CLoss::isRegression() function to distinguish between regression and classification loss functions.
Backport to #1101.
=> [7.x][ML] Implement MSLE loss function for regression 

docs/CHANGELOG.asciidoc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h, lib/maths/CBoostedTreeImpl.cc
=> [7.8][ML] Eagerly discard node statistics for leaves which we will never split

include/maths/COutliers.h, include/test/CDataFrameAnalyzerTrainingFactory.h, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/config/unittest/CReportWriterTest.cc, lib/maths/COutliers.cc, lib/maths/unittest/CMicTest.cc, lib/maths/unittest/CMultivariateMultimodalPriorTest.cc, lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc, lib/maths/unittest/CRandomizedPeriodicityTestTest.cc, lib/maths/unittest/CTimeSeriesDecompositionTest.cc, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc, lib/maths/unittest/CTrendComponentTest.cc, lib/model/CResourceMonitor.cc, lib/model/CRuleCondition.cc, lib/model/unittest/CEventRatePopulationDataGathererTest.cc, lib/model/unittest/CEventRatePopulationModelTest.cc, lib/model/unittest/CSampleQueueTest.cc
=> [7.8][ML] Silence gcc warnings

include/api/CForecastRunner.h, include/core/CSmallVector.h, include/core/Concurrency.h, include/maths/CDataFrameCategoryEncoder.h, include/maths/CLinearAlgebraEigen.h, lib/api/CForecastRunner.cc, lib/core/CDataFrameRowSlice.cc, lib/core/CStaticThreadPool.cc, lib/maths/CDataFrameCategoryEncoder.cc
=> [7.8][ML] Some move related optimisations

docs/CHANGELOG.asciidoc, include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameOutliersRunner.h, include/api/CDataFrameTrainBoostedTreeRunner.h, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h
This relates to elastic/elasticsearch#55593.
=> [ML] Trap and fail if no regressors are provided to classification or regression

include/core/CMemory.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/core/unittest/CDataFrameTest.cc, lib/core/unittest/CMemoryUsageTest.cc
=> [7.8][ML] Fix memory usage estimation for vectors with a custom allocator

include/maths/CBoostedTreeLeafNodeStatistics.h, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLeafNodeStatistics.cc, lib/maths/CBoostedTreeLoss.cc
=> [7.8][ML] Boosted tree tidy ups

docs/CHANGELOG.asciidoc, lib/model/CEventRateModel.cc, lib/model/CIndividualModel.cc, lib/model/CMetricModel.cc
=> [7.8][ML] Improve stability of trend decomposition for very sparse data

docs/CHANGELOG.asciidoc, include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalysisSpecification.h, include/api/CDataFrameOutliersRunner.h, include/api/CDataFrameTrainBoostedTreeRunner.h, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h
=> [7.8][ML] Trap and fail if no regressors are provided to classification or regression

devbin/model_extractor/.gitignore, devbin/model_extractor/Main.cc, devbin/state_search_splitter/.gitignore, devbin/state_search_splitter/Main.cc, devbin/state_search_splitter/Makefile, devbin/state_search_splitter/combine.sh
This is an internal tool that helps with debugging model state
restoration problems.
=> [ML] Add a helper program for splitting searches of .ml-state

devbin/model_extractor/.gitignore, devbin/model_extractor/Main.cc, devbin/state_search_splitter/.gitignore, devbin/state_search_splitter/Main.cc, devbin/state_search_splitter/Makefile, devbin/state_search_splitter/combine.sh
This is an internal tool that helps with debugging model state
restoration problems.
Backport of #1180
=> [7.x][ML] Add a helper program for splitting searches of .ml-state

docs/CHANGELOG.asciidoc, include/api/CDataFrameAnalysisInstrumentation.h, include/api/CDataFrameAnalyzer.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFrameAnalysisInstrumentationInterface.h, include/maths/CDataFrameCategoryEncoder.h, include/maths/COutliers.h, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc, lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/COutliers.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/COutliersTest.cc
=> [7.8][ML] Multiphase progress reporting for data frame analyses

lib/maths/CBoostedTreeImpl.cc
=> [7.8][ML] Output progress for final training even if we don't have this step

docs/CHANGELOG.asciidoc, include/maths/CPeriodicityHypothesisTests.h, lib/maths/CPeriodicityHypothesisTests.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CPeriodicityHypothesisTestsTest.cc, lib/maths/unittest/CTimeSeriesDecompositionTest.cc
=> [7.8][ML] Reduce false positives for the periodic component test for anomaly detection

docs/CHANGELOG.asciidoc, lib/maths/CBoostedTreeFactory.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.8][ML] Fix override of maximum permitted trees for classification and regression

docs/CHANGELOG.asciidoc, include/maths/CBoostedTreeImpl.h, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/maths/CBoostedTreeImpl.cc
=> [7.8][ML] Add a constant to the prediction which minimises the unregularised loss for classification and regression

docs/CHANGELOG.asciidoc, lib/maths/CAdaptiveBucketing.cc, lib/maths/CCalendarComponentAdaptiveBucketing.cc, lib/maths/CTimeSeriesDecomposition.cc
=> [7.9][ML] Fix possible cause for "Bad variance scale nan" log errors

docs/CHANGELOG.asciidoc, lib/maths/CAdaptiveBucketing.cc, lib/maths/CCalendarComponentAdaptiveBucketing.cc, lib/maths/CTimeSeriesDecomposition.cc
=> [7.8][ML] Fix possible cause for "Bad variance scale nan" log errors

lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
=> [7.9][ML] Fix flakey progress monitoring test

lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc
=> [7.8][ML] Fix flakey progress monitoring test

lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CDataFrameUtilsTest.cc
=> [7.8][ML] Fix weights to maximize minimum recall for multiclass classification

docs/CHANGELOG.asciidoc, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc, lib/core/CTimeUtils.cc
This PR changes the resolution of the timestamps from seconds to milliseconds. This fixes #1234
=> [ML] Fix timestamp issue for instrumentation

docs/CHANGELOG.asciidoc, include/maths/CTimeSeriesDecompositionDetail.h, lib/maths/CTimeSeriesDecomposition.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CTimeSeriesDecompositionTest.cc
=> [7.8][ML] Fix bad function call exception in anomaly detection

docs/CHANGELOG.asciidoc, include/maths/CTimeSeriesDecompositionDetail.h, lib/maths/CTimeSeriesDecomposition.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CTimeSeriesDecompositionTest.cc
=> [7.9][ML] Fix bad function call exception in anomaly detection

docs/CHANGELOG.asciidoc, lib/maths/CAdaptiveBucketing.cc, lib/maths/CCalendarComponentAdaptiveBucketing.cc, lib/maths/CTimeSeriesDecomposition.cc
=> [7.7][ML] Fix possible cause for "Bad variance scale nan" log errors

lib/maths/CDataFrameUtils.cc
=> [7.9][ML] Fix weights to maximize minimum recall for multiclass classification when the training data is missing classes 

lib/maths/CDataFrameUtils.cc
=> [7.8][ML] Fix weights to maximize minimum recall for multiclass classification when the training data is missing classes

lib/maths/CSignal.cc
=> [7.9][ML] Special case handling for autocorrelation of a constant

docs/CHANGELOG.asciidoc, include/core/CPersistUtils.h, include/maths/CChecksum.h, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/core/CStringUtils.cc, lib/core/unittest/CJsonStatePersistInserterTest.cc, lib/core/unittest/CPersistUtilsTest.cc, lib/core/unittest/CRapidXmlStatePersistInserterTest.cc, lib/core/unittest/CStringUtilsTest.cc, lib/model/unittest/CAnomalyScoreTest.cc, lib/model/unittest/CSampleQueueTest.cc
=> [7.9][ML] Don't lose precision when persisting state

docs/CHANGELOG.asciidoc, include/core/Concurrency.h, include/maths/CTreeShapFeatureImportance.h, lib/maths/CBoostedTreeImpl.cc, lib/maths/CTreeShapFeatureImportance.cc, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
=> [7.9][ML] Parallelise the feature importance calculation for classification and regression over trees

docs/CHANGELOG.asciidoc, include/core/CPersistUtils.h, include/core/Concurrency.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CBoostedTreeLoss.h, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/core/unittest/CImmutableRadixSetTest.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CTimeSeriesModelTest.cc
=> [7.9][ML] Add state checkpoints during coarse parameter search for classification and regression

lib/maths/CMultimodalPrior.cc
After #1268, we were occasionally getting `Unable to compute percentiles: doesn't bracket root...` log errors, due to floating point precision issues. This PR adds a fallback to exponentially grow the interval we solve on if it doesn't bracket the percentile point.
There was also an error in the treatment of variance scale, although most of the time this was unobservable because we were able to solve for the correct value.
I've marked this as a non-issue since #1268 isn't released.
=> [ML] Fix "Unable to compute percentiles: doesn't bracket root..." log errors

lib/maths/CMultimodalPrior.cc
=> [7.9][ML] Fix "Unable to compute percentiles: doesn't bracket root..." log errors

include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameOutliersRunner.h, include/api/CDataFrameTrainBoostedTreeRunner.h, include/core/CDataFrame.h, include/core/Concurrency.h, include/maths/CBoostedTreeLoss.h, lib/api/CDataFrameAnalysisSpecification.cc, lib/api/CDataFrameOutliersRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.cc, lib/api/unittest/CDataFrameMockAnalysisRunner.h, lib/core/CDataFrame.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLoss.cc
=> [7.9][ML] Tailor the data frame slice size per analysis type

docs/CHANGELOG.asciidoc, include/maths/CBoostedTreeImpl.h, lib/maths/CBoostedTreeImpl.cc, lib/maths/CSampling.cc, lib/maths/unittest/CSamplingTest.cc
=> [7.9][ML] Improve data access pattern computing best splits for classification and regression

docs/CHANGELOG.asciidoc, include/core/CDataFrame.h, include/core/CImmutableRadixSet.h, include/core/CPackedBitVector.h, include/core/Concurrency.h, include/maths/CBoostedTreeImpl.h, include/maths/CBoostedTreeLeafNodeStatistics.h, include/maths/CBoostedTreeUtils.h, include/maths/CDataFrameCategoryEncoder.h, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/core/CDataFrame.cc, lib/core/CPackedBitVector.cc, lib/core/unittest/CConcurrencyTest.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLeafNodeStatistics.cc, lib/maths/CBoostedTreeUtils.cc, lib/maths/CDataFrameCategoryEncoder.cc, lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.9][ML] Threading speedups for classification and regression

lib/maths/CMultimodalPrior.cc
=> [7.9][ML] Fix "Unable to compute percentiles: doesn't bracket root..." log errors (part 2)

include/maths/CBoostedTreeLeafNodeStatistics.h, lib/maths/CBoostedTreeLeafNodeStatistics.cc
=> [7.9][ML] Only compute boosted tree leaf row masks if they are needed

docs/CHANGELOG.asciidoc, include/maths/CIntegerTools.h, lib/maths/CIntegerTools.cc
=> [6.8][ML] Trap potential cause of SIGFPE

docs/CHANGELOG.asciidoc, include/maths/CIntegerTools.h, lib/maths/CIntegerTools.cc
=> [7.8][ML] Trap potential cause of SIGFPE

docs/CHANGELOG.asciidoc, include/maths/CIntegerTools.h, lib/maths/CIntegerTools.cc
=> [7.9][ML] Trap potential cause of SIGFPE

include/maths/CModel.h, include/maths/CTimeSeriesDecomposition.h, include/maths/CTimeSeriesDecompositionDetail.h, include/maths/CTimeSeriesDecompositionInterface.h, include/maths/MathsTypes.h, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesModel.cc, lib/model/CEventRateModel.cc, lib/model/CEventRatePopulationModel.cc, lib/model/CMetricModel.cc, lib/model/CMetricPopulationModel.cc
=> [7.9][ML] Don't require time is supplied when adding an annotation

docs/CHANGELOG.asciidoc, include/core/CPackedBitVector.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeLeafNodeStatistics.h, include/maths/CBoostedTreeUtils.h, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/core/CPackedBitVector.cc, lib/core/unittest/CPackedBitVectorTest.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLeafNodeStatistics.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.9][ML] Improve bit vector encoding efficiency for sparse vectors

lib/api/CForecastRunner.cc
This is to help debug elastic/elasticsearch#58806
=> [ML] Add more logging to forecasting disk space check

docs/CHANGELOG.asciidoc, include/core/CDataFrame.h, include/maths/CBoostedTreeImpl.h, lib/core/CDataFrame.cc, lib/core/unittest/CDataFrameTest.cc, lib/maths/CBoostedTreeFactory.cc
=> [7.9][ML] Fix cause of SIGSEGV for classification and regression

docs/CHANGELOG.asciidoc, include/core/CDataFrame.h, include/maths/CBoostedTreeImpl.h, lib/core/CDataFrame.cc, lib/core/unittest/CDataFrameTest.cc, lib/maths/CBoostedTreeFactory.cc
=> [7.8][ML] Fix cause of SIGSEGV for classification and regression

docs/CHANGELOG.asciidoc, lib/maths/CDecompositionComponent.cc, lib/maths/CTimeSeriesDecomposition.cc, lib/maths/CTrendComponent.cc, lib/maths/unittest/CForecastTest.cc
=> [7.9][ML] Trap potential causes of inverted forecast bounds

lib/api/CDataFrameAnalysisInstrumentation.cc
=> [7.9][ML] Fix a race in writing the memory usage message after circuit breaking

docs/CHANGELOG.asciidoc, lib/model/CAnomalyDetector.cc
=> [7.9][ML] Fix for SIGSEGV forecasting

lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
This PR changes the memory correction strategy to enforce the strongly monotonic behavior of the corrected values. Previously, the correction could leave to the situation where memory estimations could be swapped (bigger job could have a smaller memory estimation), this is not possible now.
Backport of #1407
=> [7.x][ML] New memory estimation correction function 

lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
This PR changes the memory correction strategy to enforce the strongly monotonic behavior of the corrected values. Previously, the correction could leave to the situation where memory estimations could be swapped (bigger job could have a smaller memory estimation), this is not possible now.
Backport of #1407
=> [7.9][ML] New memory estimation correction function

include/api/CBoostedTreeInferenceModelBuilder.h, include/api/CDataFrameTrainBoostedTreeRunner.h, include/api/CInferenceModelDefinition.h, include/test/CDataFrameAnalysisSpecificationFactory.h, lib/api/CBoostedTreeInferenceModelBuilder.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/CInferenceModelDefinition.cc, lib/api/unittest/CBoostedTreeInferenceModelBuilderTest.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc
- [ML] handles new optional analysis parameter `feature_processors` (#1408)
=> [7.x] [ML] handles new optional analysis parameter `feature_processors` (#1408)

include/api/CDataFrameTrainBoostedTreeRunner.h, include/api/CInferenceModelDefinition.h, include/test/CDataFrameAnalysisSpecificationFactory.h, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/CInferenceModelDefinition.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc
=> [7.10][ML] Fix undefined behaviour

docs/CHANGELOG.asciidoc, include/maths/CBoostedTreeImpl.h, lib/maths/CBoostedTreeImpl.cc
We previously showed progress stuck at zero for the final training step.
=> [ML] Fix progress on resume after final training has completed for classification and regression

docs/CHANGELOG.asciidoc, include/api/CDataFrameAnalysisRunner.h, include/api/CDataFrameAnalyzer.h, include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/api/CDataFrameTrainBoostedTreeRegressionRunner.h, include/api/CInferenceModelMetadata.h, include/maths/CBasicStatistics.h, include/maths/CTreeShapFeatureImportance.h, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CDataFrameAnalyzer.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/CInferenceModelMetadata.cc, lib/api/Makefile.first, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/maths/CTreeShapFeatureImportance.cc
This PR add computation of the total feature importance values.
Backport of #1387.
=> [7.x][ML] Return total SHAP per feature as a new result type 

build-setup/clion/using_clion.md
Mention the pitfalls of using a Makefile project to import the ml-cpp repo.
=> [ML] Update CLion instructions for version 2020.2

lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc
This PR instruments the unit tests that occasionally fail. Next time the test suppose to fail because an actual feature importance variable is 0, the test will dump the result json into the log so I can investigate the causes of failure.
I will remove this instrumentation once I've found the root cause of failure.
Backport of #1506
=> [7.x][ML] Investigate total importance CI failure 

lib/model/unittest/CCountingModelTest.cc, lib/model/unittest/CEventRateModelTest.cc, lib/model/unittest/CEventRatePopulationModelTest.cc, lib/model/unittest/CMetricModelTest.cc, lib/model/unittest/CMetricPopulationModelTest.cc
* Use initializer lists to populate containers
* Remove unnecessarily included header files
Backports #1509
=> [7.x][ML] Modernize and tidy model test code where possible (#1509)

docs/CHANGELOG.asciidoc, lib/maths/CBoostedTreeImpl.cc
=> [7.10][ML] Avoid log spam when we only have missing values for a feature computing candidate splits for regression and classification

include/api/CInferenceModelMetadata.h, include/maths/CTreeShapFeatureImportance.h, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRegressionRunner.cc, lib/api/CInferenceModelMetadata.cc, lib/api/unittest/CDataFrameAnalyzerFeatureImportanceTest.cc, lib/maths/CTreeShapFeatureImportance.cc
=> [7.10][ML] Store feature importance baselines in model metadata (#1522)

include/maths/CSignal.h, lib/maths/CSignal.cc, lib/maths/CTimeSeriesTestForSeasonality.cc, lib/maths/unittest/CSignalTest.cc
This removes some unused functionality.
=> [ML] Remove some dead code

docs/CHANGELOG.asciidoc, lib/maths/CSeasonalComponentAdaptiveBucketing.cc
=> [7.11][ML] Short circuit seasonal component gradient calculation (#1549)

include/core/CDataFrame.h, include/core/CPackedBitVector.h, include/maths/CLinearAlgebraEigen.h, lib/maths/CBjkstUniqueValues.cc
=> [7.11][ML] Migrate away from inheriting from std::iterator

docs/CHANGELOG.asciidoc, lib/maths/CNaturalBreaksClassifier.cc, lib/maths/CXMeansOnline1d.cc
=> [7.11][ML] Trap potential cause of log errors from CXMeansOnline1d

docs/CHANGELOG.asciidoc, include/core/CLogger.h, include/core/CLoggerThrottler.h, include/core/LogMacros.h, lib/core/CLogger.cc, lib/core/CLoggerThrottler.cc, lib/core/Makefile, lib/core/unittest/CLoggerTest.cc, lib/core/unittest/CLoggerThrottlerTest.cc, lib/core/unittest/Makefile
=> [7.11][ML] Warn and error level log throttling

include/maths/CTimeSeriesTestForSeasonality.h, lib/maths/CTimeSeriesTestForSeasonality.cc, lib/maths/unittest/CTimeSeriesDecompositionTest.cc
=> [7.11][ML] Improve test to decide whether to drop seasonal components

include/core/Constants.h, include/test/CDataFrameAnalyzerTrainingFactory.h, lib/api/CAnomalyJobConfig.cc, lib/api/CDataFrameAnalysisInstrumentation.cc, lib/api/CDataFrameAnalysisRunner.cc, lib/api/CInferenceModelDefinition.cc, lib/api/CSingleStreamDataAdder.cc, lib/api/unittest/CAnomalyJobLimitTest.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc, lib/api/unittest/CDataFrameAnalysisRunnerTest.cc, lib/core/CDataFrame.cc, lib/core/CStringUtils.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/model/CResourceMonitor.cc, lib/model/unittest/CResourceMonitorTest.cc
=> [7.12][ML] Switch to using global memory constants

docs/CHANGELOG.asciidoc, lib/maths/CSignal.cc
=> [7.12][ML] Fix edge case in start up behaviour for non-diurnal seasonality

include/maths/CTimeSeriesTestForChange.h, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesTestForChange.cc, lib/maths/unittest/CTimeSeriesModelTest.cc
=> [7.11][ML] Avoid applying scale change points when the scale can't be accurately estimated

include/maths/CTimeSeriesTestForChange.h, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesTestForChange.cc, lib/maths/unittest/CTimeSeriesModelTest.cc
=> [7.12][ML] Avoid applying scale change points when the scale can't be accurately estimated

lib/api/CAnomalyJobConfig.cc
Fix assertion failures shown up in debug builds of test cases.
Relates #1253
=> [ML] Fix rapidjson assertion failures

lib/api/CAnomalyJobConfig.cc
Fix assertion failures shown up in debug builds of test cases.
Relate #1253
Backports #1670
=> [7.x][ML] Fix rapidjson assertion failures (#1670)

docs/CHANGELOG.asciidoc, include/maths/CDecayRateController.h, include/maths/CPRNG.h, lib/maths/CDecayRateController.cc, lib/maths/CPRNG.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CDecayRateControllerTest.cc
=> [7.11][ML] Fix bug persisting and restoring time series model decay rate controller

docs/CHANGELOG.asciidoc, include/maths/CDecayRateController.h, include/maths/CPRNG.h, lib/maths/CDecayRateController.cc, lib/maths/CPRNG.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CDecayRateControllerTest.cc, lib/maths/unittest/CDecayRateControllerTest.h
=> [6.8][ML] Fix bug persisting and restoring time series model decay rate controller

docs/CHANGELOG.asciidoc, include/maths/CTimeSeriesModel.h, lib/maths/CTimeSeriesModel.cc, lib/maths/unittest/CTimeSeriesModelTest.cc
=> [7.12][ML] Fix a bug in upgrade from pre 6.3 state for the lat_long function

lib/api/CDataFrameAnalysisInstrumentation.cc
=> [7.12][ML] Tidy up data frame analysis progress monitoring

include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.12][ML] Provide the ability to override eta growth rate hyperparameter

lib/api/CDataFrameTrainBoostedTreeRunner.cc
This completes the work done in #1690
=> [ML] Read eta_growth_rate_per_tree param

lib/api/CDataFrameTrainBoostedTreeRunner.cc
This completes the work done in #1690
Backport of #1706
=> [7.x][ML] Read eta_growth_rate_per_tree param (#1706)

docs/CHANGELOG.asciidoc, include/maths/CCalendarComponent.h, include/maths/CCalendarFeature.h, include/maths/CSeasonalComponent.h, include/maths/CSeasonalComponentAdaptiveBucketing.h, include/maths/CSeasonalTime.h, include/maths/CTimeSeriesDecompositionDetail.h, include/maths/CTimeSeriesModel.h, lib/maths/CCalendarComponent.cc, lib/maths/CCalendarComponentAdaptiveBucketing.cc, lib/maths/CCalendarFeature.cc, lib/maths/CDecayRateController.cc, lib/maths/CSeasonalComponent.cc, lib/maths/CSeasonalComponentAdaptiveBucketing.cc, lib/maths/CSeasonalTime.cc, lib/maths/CTimeSeriesDecomposition.cc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesModel.cc, lib/maths/CTimeSeriesTestForSeasonality.cc, lib/maths/unittest/CDecayRateControllerTest.cc, lib/maths/unittest/CForecastTest.cc, lib/maths/unittest/CSeasonalComponentTest.cc, lib/maths/unittest/CTimeSeriesDecompositionTest.cc, lib/maths/unittest/CTimeSeriesModelTest.cc, lib/maths/unittest/CTimeSeriesTestForSeasonalityTest.cc, lib/model/unittest/CEventRateModelTest.cc, lib/model/unittest/CMetricModelTest.cc
=> [7.12][ML] Assorted time series modelling stability fixes

docs/CHANGELOG.asciidoc, lib/maths/CTimeSeriesDecompositionDetail.cc, lib/maths/CTimeSeriesTestForChange.cc, lib/maths/CTimeSeriesTestForSeasonality.cc, lib/maths/unittest/CTimeSeriesDecompositionTest.cc, lib/maths/unittest/CTimeSeriesModelTest.cc
=> [7.12][ML] Make sure we remove seasonality modelling when data flatlines

include/core/RestoreMacros.h, include/maths/CBoostedTreeImpl.h, lib/maths/CBoostedTreeImpl.cc
Following on from #1717, there are some more invariants we should be checking in `CBoostedTreeImpl`.
=> [ML] Invariants for boosted tree training restore

include/core/RestoreMacros.h, include/maths/CBoostedTreeImpl.h, lib/maths/CBoostedTreeImpl.cc
=> [7.12][ML] Check invariants after restoring a boosted tree

include/api/CDataFrameAnalysisConfigReader.h, include/api/CDataFrameTrainBoostedTreeClassifierRunner.h, include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CDataFramePredictiveModel.h, include/test/CDataFrameAnalysisSpecificationFactory.h, lib/api/CDataFrameAnalysisConfigReader.cc, lib/api/CDataFrameTrainBoostedTreeClassifierRunner.cc, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc, lib/test/CDataFrameAnalyzerTrainingFactory.cc
=> [7.12][ML] Allow a user to override weights for assigning labels to classes

include/maths/CBayesianOptimisation.h, lib/maths/CBayesianOptimisation.cc
=> [ML] Some extra invariants which we should check for BO on restore

include/maths/CBayesianOptimisation.h, lib/maths/CBayesianOptimisation.cc
=> [7.12][ML] Some extra invariants which we should check for BO on restore

bin/pytorch_inference/.gitignore, bin/pytorch_inference/evaluate.py
Running the `evaluate.py` smoketest script leaves files behind that can be cleaned up.
The diff makes this change look much bigger than it is, I wrapped the code in a `try.. finally` statement and indented it. The only non-whitespace changes are the try keyword and finally section.
=> [ML] Delete temp files created by evaluate.py

docs/CHANGELOG.asciidoc, include/maths/CBoostedTree.h, include/maths/CBoostedTreeHyperparameters.h, include/maths/CBoostedTreeImpl.h, include/maths/CBoostedTreeLeafNodeStatistics.h, include/maths/CDataFramePredictiveModel.h, lib/maths/CBoostedTree.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLeafNodeStatistics.cc, lib/maths/unittest/CBoostedTreeLeafNodeStatisticsTest.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.12][ML] Use a per tree feature bag for boosted tree training

docs/CHANGELOG.asciidoc, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.13][ML] Line search feature bag fraction for classification and regression model training

dev-tools/jenkins_ci.ps1, dev-tools/jenkins_ci.sh
=> [6.8][ML] Retry getting AWS credentials in CI builds

devbin/model_extractor/CCmdLineParser.cc, devbin/model_extractor/CCmdLineParser.h, devbin/model_extractor/Main.cc
Small modifications required to bring the model_extractor code
up-to-date with recent ml-cpp library changes.
=> [ML] Ensure model_extractor compiles

build-setup/vscode/using_vscode.md
Commits shamelessly copied from #1771
=> [ML] VSCode setup instructions

build-setup/vscode/using_vscode.md
- [ML] VSCode setup instructions (#1787)
=> [7.x] [ML] VSCode setup instructions (#1787)

include/maths/CBoostedTree.h, include/maths/CBoostedTreeFactory.h, include/maths/CBoostedTreeImpl.h, include/maths/CBoostedTreeLoss.h, include/maths/CBoostedTreeUtils.h, include/maths/CDataFrameCategoryEncoder.h, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLoss.cc, lib/maths/CBoostedTreeUtils.cc, lib/maths/unittest/CBoostedTreeLossTest.cc, lib/maths/unittest/CBoostedTreeTest.cc
This adds a new adjusted MSE loss function to penalise changing predictions from the tree being retrained.
=> [ML] MSE loss function for incremental training

bin/autodetect/CCmdLineParser.cc, devbin/state_search_splitter/Main.cc
=> [7.12][ML] Some command line improvements

bin/autodetect/CCmdLineParser.cc, devbin/state_search_splitter/Main.cc
=> [7.13][ML] Some command line improvements

bin/pytorch_inference/Main.cc
This commit changes the way the pytorch_inference process writes
results so they fit the format java expects.
=> [ML] PyTorch results should be written as an array

dev-tools/jenkins_ci.sh
The changes of #1835 introduced a separate script for
cross compiling in Jenkins builds.  However, at that
time cross compiles still had to be done in the original
CI script too because Jenkins was not running the
dedicated script.
Now Jenkins _is_ running the dedicated script, and we
are in the situation where cross compiles are being done
twice for each build.  This PR tidies that up by making
jenkins_ci.sh dedicated to native compilation.
This should improve end-to-end build times.
Backport of #1844
=> [7.12][ML] Cross compile solely in dedicated script

docs/CHANGELOG.asciidoc, include/maths/CBoostedTreeImpl.h, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.13][ML] Scale regularisers for final train

docs/CHANGELOG.asciidoc, lib/maths/CDataFrameUtils.cc, lib/maths/unittest/CBoostedTreeTest.cc
=> [7.13][ML] Gracefully handle insufficient training data for classification and regression model training

include/core/CDataFrame.h, include/test/CDataFrameAnalyzerTrainingFactory.h, lib/api/CDataFrameAnalyzer.cc, lib/api/unittest/CDataFrameAnalysisInstrumentationTest.cc, lib/api/unittest/CDataFrameAnalyzerOutlierTest.cc, lib/api/unittest/CDataFrameAnalyzerTrainingTest.cc, lib/api/unittest/CDataFrameTrainBoostedTreeClassifierRunnerTest.cc, lib/core/unittest/CDataFrameTest.cc, lib/maths/CBoostedTreeFactory.cc, lib/maths/CBoostedTreeImpl.cc, lib/maths/CBoostedTreeLeafNodeStatistics.cc, lib/maths/CDataFrameUtils.cc, lib/maths/COutliers.cc, lib/maths/CTreeShapFeatureImportance.cc, lib/maths/unittest/CBoostedTreeTest.cc, lib/maths/unittest/CDataFrameUtilsTest.cc, lib/maths/unittest/COutliersTest.cc, lib/maths/unittest/CTreeShapFeatureImportanceTest.cc
=> [7.14][ML] Pass row iterators by constant reference to data frame callbacks

docs/CHANGELOG.asciidoc, include/maths/CMultivariateMultimodalPrior.h, lib/maths/CMultimodalPrior.cc
=> [7.14][ML] Fail gracefully on encountering unexpected state

docs/CHANGELOG.asciidoc, include/maths/CMultivariateMultimodalPrior.h, lib/maths/CMultimodalPrior.cc
=> [7.13][ML] Fail gracefully on encountering unexpected state

docs/CHANGELOG.asciidoc, include/api/CFieldDataCategorizer.h, include/core/CWordDictionary.h, include/model/CTokenListDataCategorizer.h, include/model/CTokenListDataCategorizerBase.h, lib/api/unittest/CAnomalyJobConfigTest.cc, lib/core/unittest/CStringSimilarityTesterTest.cc, lib/model/CTokenListCategory.cc, lib/model/CTokenListDataCategorizerBase.cc, lib/model/unittest/CTokenListDataCategorizerTest.cc
In an effort to categorise the most important parts of a message, give a boost to the weighting when 3 or more dictionary words in the message are adjacent one another.
Relates to #1724
=> [ML] Boost weighting for multiple adjacent words.

docs/CHANGELOG.asciidoc, include/api/CFieldDataCategorizer.h, include/core/CWordDictionary.h, include/model/CTokenListDataCategorizer.h, include/model/CTokenListDataCategorizerBase.h, lib/api/unittest/CAnomalyJobConfigTest.cc, lib/core/unittest/CStringSimilarityTesterTest.cc, lib/model/CTokenListCategory.cc, lib/model/CTokenListDataCategorizerBase.cc, lib/model/unittest/CTokenListDataCategorizerTest.cc
In an effort to categorise the most important parts of a message,
give a boost to the weighting of 3 of more adjacent dictionary words in the message.
Relates to #1724
Backports #1903
=> [7.x][ML] Boost weighting for multiple adjacent words. (#1903)

include/maths/CBoostedTreeLoss.h, lib/maths/CBoostedTreeLoss.cc, lib/maths/unittest/BoostedTreeTestData.cc, lib/maths/unittest/BoostedTreeTestData.h, lib/maths/unittest/CBoostedTreeLossTest.cc, lib/maths/unittest/CBoostedTreeUtilsTest.cc
This implements the incremental version of the binomial logistic loss. We add on a penalty which is the cross-entropy of the old and new tree predictions on the original training data.
=> [ML] Incremental binomial logistic loss

jupyter/notebooks/utils/misc.py
This PR adds a check if the job succeeded or failed using exit codes. It is more robust than parsing strings with line numbers and will work on different platforms.
=> [ML] Use exit codes in jupyter notebooks

README.md
=> [6.8]Update README.md (#1915)

README.md
=> [7.0] Update README.md (#1915)

README.md
=> [7.1] Update README.md (#1915)

README.md
=> [7.2] Update README.md (#1915)

README.md
=> [7.3] Update README.md

README.md
=> [7.4] Update README.md (#1915)

README.md
=> [7.5] Update README.md (#1915)

README.md
=> [7.6] Update README.md (#1915)

README.md
=> [7.7] Update README.md (#1915)

README.md
=> [7.8] Update README.md (#1915)

README.md
=> [7.9] Update README.md (#1915)

README.md
=> [7.10] Update README.md (#1915)

README.md
=> [7.11] Update README.md (#1915)

README.md
=> [7.12] Update README.md (#1915)

README.md
=> [7.13] Update README.md (#1915)

README.md
=> [7.x] Update README.md (#1915)

jupyter/notebooks/configs/dga_data_ngrams.json, jupyter/notebooks/utils/misc.py
I added `\0` as a placeholder for missing data in `pandas`. This is the behavior expected by the C++ backend.
I also added the config file `dga_data_ngrams.json` to the repository.
=> [ML] Correct handling missing data in Python

NOTICE.txt
=> [ML] Update year in NOTICE file

jupyter/src/incremental_learning/job.py, jupyter/tests/incremental_learning/test_regression.py
After merging the `main` branch into the feature branch, some python unit tests started failing. This PR fixes them.
=> [ML] Fix python unit tests

jupyter/scripts/incremental_learning/README.md
=> [ML] Add readme for submitting jobs

lib/maths/CBoostedTreeImpl.cc
=> [7.x][ML] Add logging so we know which round we exited hyperparameter tuning

docs/CHANGELOG.asciidoc, lib/maths/CBoostedTreeLeafNodeStatistics.cc
=> [7.x][ML] Fix potential undefined behaviour in classification and regression training

docs/CHANGELOG.asciidoc, lib/maths/CBoostedTreeLeafNodeStatistics.cc
=> [7.15][ML] Fix potential undefined behaviour in classification and regression training

build-setup/linux.md, build-setup/macos.md, build-setup/windows.md, dev-tools/docker/linux_aarch64_native_image/Dockerfile, dev-tools/docker/linux_image/Dockerfile
=> [ML] Update boost download URL

bin/pytorch_inference/Main.cc
The log messages were added when resolving #2007
=> [ML][PYTORCH] Remove debug logging of inference requests 

jupyter/src/incremental_learning/transforms.py, lib/maths/CBoostedTreeImpl.cc
Since we incrementally train to get the range to use for the tree topology change penalty, we need to reinitialise the predictions before computing the loss for the original model.
=> [ML] Reinitialise predictions before estimating initial loss

lib/model/unittest/CMetricModelTest.cc, lib/model/unittest/CMetricPopulationModelTest.cc
Updates the reason the tests fail to the current issue
=> [ML] Update issue link

lib/model/unittest/CMetricModelTest.cc, lib/model/unittest/CMetricPopulationModelTest.cc
=> [ML] Update linked for muted tests

docs/CHANGELOG.asciidoc, lib/maths/CBoostedTreeImpl.cc
=> [7.x][ML] Capture best hyperparameters after restoring for final train 

include/api/CDataFrameAnalysisConfigReader.h, include/maths/analytics/CBoostedTreeFactory.h, include/maths/analytics/CBoostedTreeHyperparameters.h, include/test/CDataFrameAnalyzerTrainingFactory.h, lib/api/CDataFrameTrainBoostedTreeRunner.cc, lib/api/unittest/CDataFrameAnalysisSpecificationTest.cc, lib/maths/analytics/CBoostedTreeFactory.cc, lib/maths/analytics/CBoostedTreeImpl.cc, lib/maths/analytics/unittest/CBoostedTreeHyperparametersTest.cc, lib/maths/analytics/unittest/CBoostedTreeTest.cc, lib/test/CDataFrameAnalysisSpecificationFactory.cc
For train by query it is useful to be able to control hyperparameter ranges for each iteration from the coordinating process.
=> [ML] Support supplying hyperparameter ranges

include/maths/common/CLinearAlgebra.h
=> [7.16][ML] Better vector and matrix checksum implementation

include/maths/common/CLinearAlgebra.h
=> [8.0][ML] Better vector and matrix checksum implementation

lib/maths/analytics/CBoostedTreeLoss.cc
=> [7.16][ML] Fix divide by zero in MSLE and Huber loss functions

lib/maths/analytics/CBoostedTreeLoss.cc
=> [8.0][ML] Fix divide by zero in MSLE and Huber loss functions

docs/CHANGELOG.asciidoc, include/maths/time_series/CExpandingWindow.h, include/maths/time_series/CTimeSeriesDecompositionDetail.h, include/maths/time_series/CTimeSeriesTestForSeasonality.h, lib/maths/time_series/CExpandingWindow.cc, lib/maths/time_series/CTimeSeriesDecompositionDetail.cc, lib/maths/time_series/CTimeSeriesTestForSeasonality.cc, lib/maths/time_series/unittest/CTimeSeriesDecompositionTest.cc, lib/maths/time_series/unittest/CTimeSeriesTestForSeasonalityTest.cc
=> [7.17][ML] Ensure we have sufficient resolution when we reinitialise component models

jupyter/scripts/multi_step_learning/origin/experiment_driver.py, jupyter/src/.bumpversion.cfg, jupyter/src/incremental_learning/__init__.py, jupyter/src/incremental_learning/job.py, jupyter/src/setup.py
This change adds recent changes of using hyperparameter overrides to the original multistep learning experiment driver.
I also add functionality to store input files if `data_frame_analyzer`   fails. This will facilitate debugging.
=> [ML] Minor update of experiment driver

jupyter/requirements.txt, jupyter/src/incremental_learning/config.py
The new way to check the OS name is by calling `distro.name()` mini PR uses the new api to fix deprecation warning.
=> [ML] Fix python api deprecation

docs/CHANGELOG.asciidoc, include/maths/common/CMathsFuncs.h, include/maths/common/CMathsFuncsForMatrixAndVectorTypes.h, include/maths/common/CSolvers.h, lib/maths/common/CConstantPrior.cc, lib/maths/common/CGammaRateConjugate.cc, lib/maths/common/CLogNormalMeanPrecConjugate.cc, lib/maths/common/CLogTDistribution.cc, lib/maths/common/CMultimodalPrior.cc, lib/maths/common/CMultinomialConjugate.cc, lib/maths/common/CMultivariatePrior.cc, lib/maths/common/CNormalMeanPrecConjugate.cc, lib/maths/common/COneOfNPrior.cc, lib/maths/common/CPoissonMeanConjugate.cc, lib/maths/common/unittest/CGammaRateConjugateTest.cc, lib/maths/common/unittest/CLogNormalMeanPrecConjugateTest.cc, lib/maths/common/unittest/CNormalMeanPrecConjugateTest.cc, lib/maths/common/unittest/COneOfNPriorTest.cc, lib/maths/common/unittest/CPoissonMeanConjugateTest.cc, lib/maths/common/unittest/CSolversTest.cc, lib/maths/common/unittest/CToolsTest.cc, lib/maths/time_series/CTimeSeriesDecomposition.cc
=> [8.1][ML] Address potential causes of "x = NaN, distribution = N5boost4math23students_t_distribution" log errors

docs/CHANGELOG.asciidoc, include/maths/common/CMathsFuncs.h, include/maths/common/CMathsFuncsForMatrixAndVectorTypes.h, include/maths/common/CSolvers.h, lib/maths/common/CConstantPrior.cc, lib/maths/common/CGammaRateConjugate.cc, lib/maths/common/CLogNormalMeanPrecConjugate.cc, lib/maths/common/CLogTDistribution.cc, lib/maths/common/CMultimodalPrior.cc, lib/maths/common/CMultinomialConjugate.cc, lib/maths/common/CMultivariatePrior.cc, lib/maths/common/CNormalMeanPrecConjugate.cc, lib/maths/common/COneOfNPrior.cc, lib/maths/common/CPoissonMeanConjugate.cc, lib/maths/common/unittest/CGammaRateConjugateTest.cc, lib/maths/common/unittest/CLogNormalMeanPrecConjugateTest.cc, lib/maths/common/unittest/CNormalMeanPrecConjugateTest.cc, lib/maths/common/unittest/COneOfNPriorTest.cc, lib/maths/common/unittest/CPoissonMeanConjugateTest.cc, lib/maths/common/unittest/CSolversTest.cc, lib/maths/common/unittest/CToolsTest.cc, lib/maths/time_series/CTimeSeriesDecomposition.cc
=> [7.17][ML] Address potential causes of "x = NaN, distribution = N5boost4math23students_t_distribution" log errors

docs/CHANGELOG.asciidoc, lib/model/CEventRateBucketGatherer.cc
=> [7.17][ML] Fix bug restoring data gatherer state for time of day/week and anomaly detection

include/model/CAnomalyDetectorModel.h, include/model/CAnomalyDetectorModelConfig.h, include/model/FunctionTypes.h, include/model/ModelTypes.h, lib/model/CAnomalyDetectorModelConfig.cc, lib/model/CDataGatherer.cc, lib/model/CEventRateBucketGatherer.cc, lib/model/FunctionTypes.cc, lib/model/ModelTypes.cc
This removes some dead code relating to a feature we're unlikely to resume work on.
=> [ML] Remove dead code from anomaly detection

docs/CHANGELOG.asciidoc, lib/maths/time_series/CTimeSeriesTestForSeasonality.cc
=> [7.17][ML] Correct initialisation of the trend model after detecting seasonality for edge case

docs/CHANGELOG.asciidoc, lib/maths/common/CGammaRateConjugate.cc, lib/maths/common/CNaturalBreaksClassifier.cc, lib/maths/common/CSampling.cc, lib/maths/common/CTools.cc, lib/maths/common/unittest/CToolsTest.cc
=> [7.17][ML] Fix a source of "Discarding sample = nan, weights = ..." log errors

docs/CHANGELOG.asciidoc, lib/maths/common/CGammaRateConjugate.cc, lib/maths/common/CNaturalBreaksClassifier.cc, lib/maths/common/CSampling.cc, lib/maths/common/CTools.cc, lib/maths/common/unittest/CToolsTest.cc
=> [ML] Fix a source of "Discarding sample = nan, weights = ..." log errors

docs/CHANGELOG.asciidoc, lib/maths/common/CGammaRateConjugate.cc, lib/maths/common/CNaturalBreaksClassifier.cc, lib/maths/common/CSampling.cc, lib/maths/common/CTools.cc, lib/maths/common/unittest/CToolsTest.cc
=> [8.3][ML] Fix a source of "Discarding sample = nan, weights = ..." log errors

docs/CHANGELOG.asciidoc, include/model/CAnomalyScore.h, lib/api/unittest/CResultNormalizerTest.cc, lib/model/CAnomalyScore.cc, lib/model/unittest/CAnomalyScoreTest.cc, lib/model/unittest/CHierarchicalResultsTest.cc
=> [8.3][ML] Improve normalisation of anomaly detection results for short bucket lengths

jupyter/docker/Dockerfile, lib/api/CMakeLists.txt, lib/api/unittest/CMakeLists.txt, lib/maths/analytics/CMakeLists.txt, lib/maths/analytics/unittest/CMakeLists.txt
Adding new, incremental_training source files to CMakeLists.txt files.
=> [ML] Add additional incremental_training files

build.gradle, cmake/clang-format.cmake, set_env.bat
Set up the minimal environment variables to allow for building from a
native windows command prompt.
=> [ML] Alter build.gradle to allow for native windows builds

3rd_party/dependency_report.cmake, build.gradle
Replace dependency_report.sh bash script with cmake script equivalent
=> [ML] Platform independent dependency report script

bin/pytorch_inference/Main.cc, include/core/Concurrency.h
Non issue as this fixes a bug in unreleased code
=> [ML] Size pytorch_inference thread pool properly

include/core/CLoggerTrace.h, include/core/LogMacros.h, include/maths/common/CBasicStatistics.h, include/maths/common/CXMeansOnline.h, include/model/CMetricMultivariateStatistic.h, lib/model/unittest/CSampleQueueTest.cc
Some followups to #2363 to make it possible to build with
trace logging enabled.
=> [ML] Fix debug builds

docs/CHANGELOG.asciidoc, lib/maths/analytics/CBoostedTreeImpl.cc
=> [8.4][ML] Fix potential out-of-bounds read

docs/CHANGELOG.asciidoc, lib/maths/analytics/CBoostedTreeImpl.cc
=> [7.17][ML] Fix potential out-of-bounds read

lib/maths/common/unittest/CQuantileSketchTest.cc
Remove a call to a protected method called in TRACE logging
=> [ML] Remove the source of CI debug build failures

include/maths/common/CSampling.h, include/maths/time_series/CTimeSeriesDecompositionDetail.h, lib/maths/analytics/CBoostedTreeFactory.cc, lib/maths/analytics/CBoostedTreeLoss.cc, lib/maths/analytics/unittest/CBoostedTreeTest.cc, lib/maths/common/unittest/CSamplingTest.cc
=> [ML] Fix failure computing leaf values with multithreading for multi-class classification

lib/maths/time_series/CTimeSeriesModel.cc
This PR effectively reverts #2413.
=> [ML] Reanable confidence bounds computation

.buildkite/pull-requests.json
=> Typo in pull-request.json

.buildkite/scripts/steps/create_dra.sh
Upload platform specific artifacts to S3 and GCS along with the "all platform" bundles.
=> [ML] Upload platform specific artifacts to S3 & GCS

.buildkite/scripts/steps/create_dra.sh
Upload platform specific artifacts to S3 and GCS along with the "all platform" bundles.
Backports #2458
=> [8.7][ML]  upload all artifacts to S3 and GCS

.buildkite/scripts/steps/create_dra.sh
Account for naming convention differences between v8 and v7
=> [ML] Include debug artifacts in DRA uploads

.buildkite/scripts/common/aws_creds_from_vault.sh, buildSrc/src/main/groovy/org/elastic/gradle/UploadS3Task.groovy
Take advantage of the new AWS secret engine now available in CI Vault
backports #2474
=> [8.8][ML] Make use of CI Vault's AWS secrets engine (#2474)

.buildkite/scripts/common/aws_creds_from_vault.sh, buildSrc/src/main/groovy/org/elastic/gradle/UploadS3Task.groovy
Take advantage of the new AWS secret engine now available in CI Vault
Backports #2474
=> [8.7][ML] Make use of CI Vault's AWS secrets engine (#2474)

.buildkite/scripts/common/aws_creds_from_vault.sh, buildSrc/src/main/groovy/org/elastic/gradle/UploadS3Task.groovy
Take advantage of the new AWS secret engine now available in CI Vault
Backport #2474
=> [7.17][ML] Make use of CI Vault's AWS secrets engine (#2474)

buildSrc/build.gradle, dev-tools/docker_build.sh, dev-tools/docker_test.sh, dev-tools/jenkins_cross_compile.sh
Our Gradle build uses the AWS SDK. We should upgrade to the latest version.
=> [ML] Upgrade to latest AWS SDK version

.buildkite/pipelines/upload_dra_to_gcs.yml.sh, .buildkite/pull-requests.json, build.gradle, dev-tools/jenkins_ci.ps1, dev-tools/jenkins_ci.sh, dev-tools/jenkins_combine_artifacts.sh
* Disable uploading from Jenkins
* Enable uploading from BuildKite
=> [ML] Perform artifact uploads from BuildKite only

.buildkite/pipelines/upload_dra_to_gcs.yml.sh, .buildkite/pull-requests.json, build.gradle, dev-tools/jenkins_ci.ps1, dev-tools/jenkins_ci.sh, dev-tools/jenkins_combine_artifacts.sh
This reverts commit 9283e0dcfb25e7307802f60507e49576974e7312.
=> Revert "[ML] Perform artifact uploads from BuildKite only (#2503)"

.buildkite/pipelines/upload_dra_to_gcs.yml.sh, build.gradle, dev-tools/jenkins_ci.ps1, dev-tools/jenkins_ci.sh, dev-tools/jenkins_combine_artifacts.sh
For the snapshot and staging builds:
* Disable uploading from Jenkins
* Enable uploading from BuildKite
Backports #2511
=> [8.8][ML] Upload build artifacts from BuildKite (#2511)

.buildkite/pipelines/upload_dra_to_gcs.yml.sh, build.gradle, dev-tools/jenkins_ci.ps1, dev-tools/jenkins_ci.sh, dev-tools/jenkins_combine_artifacts.sh
For the snapshot and staging builds:
* Disable uploading from Jenkins
* Enable uploading from BuildKite
Backports #2511
=> [7.17][ML] Upload build artifacts from BuildKite (#2511)

.buildkite/pipelines/build_linux.json.py, .buildkite/pipelines/build_macos.json.py, .buildkite/pipelines/build_windows.json.py
Allow for lengthy debug builds
=> [ML] Increase build timeouts to 4 hours

.buildkite/pipelines/build_linux.json.py, .buildkite/pipelines/build_macos.json.py, .buildkite/pipelines/build_windows.json.py
Allow for lengthy debug builds
Backports #2528
=> [7.17][ML] Increase build timeouts to 4 hours (#2528)

include/model/CResourceMonitor.h, lib/model/CResourceMonitor.cc, lib/model/unittest/CResourceMonitorTest.cc
Fixes #2524
Mark it as a non-issue since it is not customer-facing.
=> [ML] Replace CResourceMonitor::m_AllocationFailures to reduce the memory footprint

catalog-info.yaml, gradle.properties
- Bump version on `main` branch
- Set up branch builds for the new `8.9` branch
=> [ML] Preparing for 8.9 feature freeze

catalog-info.yaml, gradle.properties
- Bump version on `main` branch
- Set up branch builds for the new `8.10` branch
=> [ML] Preparing for 8.10 feature freeze

docs/CHANGELOG.asciidoc, include/core/CCompressedLfuCache.h
=> [ML] Call readvalue even if cache write fails 

catalog-info.yaml, gradle.properties
- Bump version on `main` branch
- Set up branch builds for the new `8.11` branch
=> [ML] Preparing for 8.11 feature freeze

include/core/CCompressedLfuCache.h
=> [ML] Remove inaccurate log message (#2582)

jupyter/requirements.txt
=> [ML] Python module version updates

build-setup/macos.md
The versions of Java and Xcode mentioned were ancient, so bring these up to date.
=> [ML] Modernise the macOS build setup instructions

include/core/CBoostJsonWriterBase.h
Use json::serialize to perform escaping of special characters.
Closes #2626
=> [ML] Escape special characters in keys as well as string values

catalog-info.yaml, gradle.properties
- Bump version on main branch
- Set up branch builds for new 8.14 branch
=> [ML] Preparing for 8.14 feature freeze

.buildkite/branch.json.py
Add the now required architecture flags to the dynamic pipeline step generator
=> [ML] Pass the required build architecture args to the pipeline steps

.buildkite/pipelines/create_dra.yml.sh, dev-tools/docker/docker_entrypoint.sh
Update the name of a Buildkite step in a dependency list.
=> [ML] Fix Buildkite step dependencies

.buildkite/pipelines/run_pytorch_tests.yml.sh
* Remove comment about triggered pipeline name
* Set the QAF_TESTS_TO_RUN environment variable appropriately
=> [ML] Tidy the PyTorch tests Buildkite pipeline

catalog-info.yaml
Ensure that code changes that are merged to active branches are automatically incorporated into a build.
Backports #2717
=> [8.16][ML] Trigger a "staging" build on merge to branch (#2717)

catalog-info.yaml
Ensure that code changes that are merged to active branches are automatically incorporated into a build.
Backports #2717
=> [8.15][ML] Trigger a "staging" build on merge to branch (#2717)

include/core/CFlatPrefixTree.h, include/core/CPatternSet.h, include/model/CAnomalyDetectorModel.h, include/model/CDetectionRule.h, include/model/CPopulationModel.h, include/model/CRuleCondition.h, include/model/CRuleScope.h, lib/core/CFlatPrefixTree.cc, lib/core/CPatternSet.cc, lib/model/CAnomalyDetectorModel.cc, lib/model/CCountingModel.cc, lib/model/CDetectionRule.cc, lib/model/CIndividualModel.cc, lib/model/CPopulationModel.cc, lib/model/CRuleCondition.cc, lib/model/CRuleScope.cc, lib/model/unittest/CCountingModelTest.cc, lib/model/unittest/CDetectionRuleTest.cc
=> [ML] Persist callback detection rules in the detector model state

lib/model/CDetectionRule.cc, lib/model/unittest/CDetectionRuleTest.cc
This reverts commit a0ff8a4866f8daf8245e56b15ecb73939bf3ff73.
=> Revert "[ML] Change time shift sign for intuitive configuration (#2737)"

lib/model/CDetectionRule.cc, lib/model/unittest/CDetectionRuleTest.cc
This reverts commit 0bc01ba0e12e9bc8c634d096e79f740df621bf80.
=> Revert-2743

dev-tools/docker/ubuntu_devbox/Dockerfile, dev-tools/docker/ubuntu_devbox/Dockerfile.8.11
This PR adds two Dockerfiles that can automatically generate development environments based on the Ubuntu 22.04 image.
=> [ML] Add Dockerfile for Ubuntu devbox

catalog-info.yaml
Adjust build configurations to include version 8.17 and update daily SNAPSHOT build messages accordingly.
=> Update build configurations for version 8.17 and SNAPSHOT messages

catalog-info.yaml, gradle.properties
Update the Elasticsearch version to 8.18.0
=> [ML] Bump version to 8.18.0

catalog-info.yaml
=> [ML] Fix typos in catalog-info.yaml

.buildkite/pipelines/build_windows.json.py
Remove duplicate `image` entry
=> [ML] Fix merge error in windows pipeline

.buildkite/branch.json.py, .buildkite/job-build-test-all-debug.json.py
Remove reference to macOS x86_64 builds from all buildkite pipelines
=> [ML] Remove macOS x86_64 builds from _all_ pipelines

lib/maths/time_series/unittest/CTimeSeriesMultibucketFeaturesTest.cc
Fix a TRACE statement which causes the debug build compilation to fail
=> [ML] Fix compilation issue in debug build

gradle.properties
Update the Elasticsearch version to 8.19.0
=> [ML] Bump version to 8.19.0

catalog-info.yaml
Adjust build configurations to include version 8.18 and update daily SNAPSHOT build messages accordingly.
=> Update build configurations for version 8.18

bin/normalize/Main.cc, docs/CHANGELOG.asciidoc, include/api/CAnomalyJob.h, include/api/CResultNormalizer.h, include/model/CHierarchicalResultsAggregator.h, include/model/CHierarchicalResultsLevelSet.h, include/model/CHierarchicalResultsNormalizer.h, include/model/CResourceMonitor.h, lib/api/CAnomalyJob.cc, lib/api/CResultNormalizer.cc, lib/api/unittest/CAnomalyJobTest.cc, lib/api/unittest/CJsonOutputWriterTest.cc, lib/api/unittest/CRestorePreviousStateTest.cc, lib/api/unittest/CResultNormalizerTest.cc, lib/api/unittest/CTestAnomalyJob.h, lib/model/CHierarchicalResultsAggregator.cc, lib/model/CHierarchicalResultsNormalizer.cc, lib/model/unittest/CHierarchicalResultsLevelSetTest.cc, lib/model/unittest/CHierarchicalResultsTest.cc, lib/model/unittest/CMakeLists.txt
=> [ML] Track memory usage in  CHierarchicalResultsNormalizer (#2831)
